// eEventFlags
    // huge buffer of flags
    // bit position is reversed for continuity

        enum_start 0xe0 // 0x1C
    enum EVENT_1C7
    enum EVENT_1C6
    enum EVENT_1C5
    enum EVENT_1C4
    enum EVENT_1C3
    enum EVENT_1C2
    enum EVENT_1C1
    enum EVENT_1C0

        enum_start 0xf0 // 0x1E
    enum EVENT_1E7
    enum EVENT_1E6
    enum EVENT_1E5
    enum EVENT_1E4
    enum EVENT_1E3
    enum EVENT_1E2
    enum EVENT_1E1
    enum EVENT_1E0

        enum_start 0x160 // 0x2C
    enum EVENT_2C7
    enum EVENT_2C6
    enum EVENT_2C5
    enum EVENT_2C4
    enum EVENT_2C3
    enum EVENT_2C2
    enum EVENT_2C1
    enum EVENT_2C0

        enum_start 0x5e0 // 0xBC
    enum EVENT_BC7
    enum EVENT_BC6
    enum EVENT_BC5
    enum EVENT_BC4
    enum EVENT_BC3
    enum EVENT_BC2
    enum EVENT_BC1
    enum EVENT_BC0

        enum_start 0x5f0 // 0xBE
    enum EVENT_BE7
    enum EVENT_BE6
    enum EVENT_BE5
    enum EVENT_BE4
    enum EVENT_BE3
    enum EVENT_BE2
    enum EVENT_BE1
    enum EVENT_BE0

        enum_start 0x5f8 // 0x0BF
    enum EVENT_0BF7
    enum EVENT_0BF6
    enum EVENT_0BF5
    enum EVENT_0BF4 
    enum EVENT_0BF3
    enum EVENT_0BF2
    enum EVENT_0BF1
    enum EVENT_0BF0

        enum_start 0x1700 // 0x2E0
    enum EVENT_2E07
    enum EVENT_2E06
    enum EVENT_2E05
    enum EVENT_2E04
    enum EVENT_2E03
    enum EVENT_2E02
    enum EVENT_2E01
    enum EVENT_2E00

        enum_start 0x1708 // 0x2E1
    enum EVENT_2E17
    enum EVENT_2E16
    enum EVENT_2E15
    enum EVENT_2E14
    enum EVENT_2E13
    enum EVENT_2E12
    enum EVENT_2E11
    enum EVENT_2E10

        enum_start 0x1710 // 0x2E2
    enum EVENT_2E27
    enum EVENT_2E26
    enum EVENT_2E25
    enum EVENT_2E24
    enum EVENT_2E23
    enum EVENT_2E22
    enum EVENT_2E21
    enum EVENT_2E20

        enum_start 0x1718 // 0x2E3
    // activates when pressing L, jacking in,
    // and talking to objects (but not NPCs?)
    // otherwise constantly cleared
    enum EVENT_2E37
    enum EVENT_2E36
    enum EVENT_2E35
    enum EVENT_2E34
    enum EVENT_2E33
    // MegaMan disappears from PET, HP becomes 0/0
    enum EVENT_PET_NAVI_ACTIVE
    enum EVENT_2E31
    enum EVENT_2E30

        enum_start 0x1720 // 0x2E4
    enum EVENT_2E47
    enum EVENT_2E46
    enum EVENT_2E45
    enum EVENT_2E44
    enum EVENT_2E43
    enum EVENT_2E42
    enum EVENT_2E41
    enum EVENT_2E40

    // applies on map update (like after closing a submenu)
        enum_start 0x1728 // 0x2E5
    enum EVENT_L_MESSAGE_ACTIVE
    // when enabled, Lan's sprite is replaced with MegaMan
    enum EVENT_COPYBOT_ACTIVE
    enum EVENT_2E55
    enum EVENT_2E54
    enum EVENT_2E53
    enum EVENT_2E52
    enum EVENT_2E51
    enum EVENT_2E50

        enum_start 0x1730 // 0x2E6
    enum EVENT_2E67
    enum EVENT_2E66
    enum EVENT_2E65
    enum EVENT_2E64
    enum EVENT_2E63
    enum EVENT_2E62
    enum EVENT_2E61
    enum EVENT_2E60

        enum_start 0x1738 // 0x2E7
    enum EVENT_2E77
    enum EVENT_2E76
    enum EVENT_2E75
    enum EVENT_2E74
    enum EVENT_2E73
    enum EVENT_2E72
    enum EVENT_2E71
    enum EVENT_2E70

        enum_start 0x1740 // 0x2E8
    enum EVENT_2E87
    enum EVENT_2E86
    enum EVENT_2E85
    enum EVENT_2E84
    enum EVENT_2E83
    enum EVENT_2E82
    enum EVENT_2E81
    enum EVENT_2E80



// eFlags2009F38
