// eEventFlags
    // huge buffer of flags
    // bit position is reversed for continuity

        enum_start 0xe0 // 0x1C
    enum EVENT_1C_FLAG7
    enum EVENT_1C_FLAG6
    enum EVENT_1C_FLAG5
    enum EVENT_1C_FLAG4
    enum EVENT_1C_FLAG3
    enum EVENT_1C_FLAG2
    enum EVENT_1C_FLAG1
    enum EVENT_1C_FLAG0

        enum_start 0xf0 // 0x1E
    enum EVENT_1E_FLAG7
    enum EVENT_1E_FLAG6
    enum EVENT_1E_FLAG5
    enum EVENT_1E_FLAG4
    enum EVENT_1E_FLAG3
    enum EVENT_1E_FLAG2
    enum EVENT_1E_FLAG1
    enum EVENT_1E_FLAG0

        enum_start 0x160 // 0x2C
    enum EVENT_2C_FLAG7
    enum EVENT_2C_FLAG6
    enum EVENT_2C_FLAG5
    enum EVENT_2C_FLAG4
    enum EVENT_2C_FLAG3
    enum EVENT_2C_FLAG2
    enum EVENT_2C_FLAG1
    enum EVENT_2C_FLAG0

        enum_start 0x5e0 // 0xBC
    enum EVENT_BC_FLAG7
    enum EVENT_BC_FLAG6
    enum EVENT_BC_FLAG5
    enum EVENT_BC_FLAG4
    enum EVENT_BC_FLAG3
    enum EVENT_BC_FLAG2
    enum EVENT_BC_FLAG1
    enum EVENT_BC_FLAG0

        enum_start 0x5f0 // 0xBE
    enum EVENT_BE_FLAG7
    enum EVENT_BE_FLAG6
    enum EVENT_BE_FLAG5
    enum EVENT_BE_FLAG4
    enum EVENT_BE_FLAG3
    enum EVENT_BE_FLAG2
    enum EVENT_BE_FLAG1
    enum EVENT_BE_FLAG0

        enum_start 0x5f8 // 0x0BF
    enum EVENT_0BF_FLAG7
    enum EVENT_0BF_FLAG6
    enum EVENT_0BF_FLAG5
    enum EVENT_0BF_FLAG4
    enum EVENT_0BF_FLAG3
    enum EVENT_0BF_FLAG2
    enum EVENT_0BF_FLAG1
    enum EVENT_0BF_FLAG0

        enum_start 0x1700 // 0x2E0
    enum EVENT_2E0_FLAG7
    enum EVENT_2E0_FLAG6
    enum EVENT_2E0_FLAG5
    enum EVENT_2E0_FLAG4
    enum EVENT_2E0_FLAG3
    enum EVENT_2E0_FLAG2
    enum EVENT_2E0_FLAG1
    enum EVENT_2E0_FLAG0

        enum_start 0x1708 // 0x2E1
    enum EVENT_2E1_FLAG7
    enum EVENT_2E1_FLAG6
    enum EVENT_2E1_FLAG5
    enum EVENT_2E1_FLAG4
    enum EVENT_2E1_FLAG3
    enum EVENT_2E1_FLAG2
    enum EVENT_2E1_FLAG1
    enum EVENT_2E1_FLAG0

        enum_start 0x1710 // 0x2E2
    enum EVENT_2E2_FLAG7
    enum EVENT_2E2_FLAG6
    enum EVENT_2E2_FLAG5
    enum EVENT_2E2_FLAG4
    enum EVENT_2E2_FLAG3
    enum EVENT_2E2_FLAG2
    enum EVENT_2E2_FLAG1
    enum EVENT_2E2_FLAG0

        enum_start 0x1718 // 0x2E3
    // activates when pressing L, jacking in,
    // and talking to objects (but not NPCs?)
    // otherwise constantly cleared
    enum EVENT_2E3_FLAG7
    enum EVENT_2E3_FLAG6
    enum EVENT_2E3_FLAG5
    enum EVENT_2E3_FLAG4
    enum EVENT_2E3_FLAG3
    // MegaMan disappears from PET, HP becomes 0/0
    enum EVENT_PET_NAVI_ACTIVE
    enum EVENT_2E3_FLAG1
    enum EVENT_2E3_FLAG0

        enum_start 0x1720 // 0x2E4
    enum EVENT_2E4_FLAG7
    enum EVENT_2E4_FLAG6
    enum EVENT_2E4_FLAG5
    enum EVENT_2E4_FLAG4
    enum EVENT_2E4_FLAG3
    enum EVENT_2E4_FLAG2
    enum EVENT_2E4_FLAG1
    enum EVENT_2E4_FLAG0

    // applies on map update (like after closing a submenu)
        enum_start 0x1728 // 0x2E5
    enum EVENT_L_MESSAGE_ACTIVE
    // when enabled, Lan's sprite is replaced with MegaMan
    enum EVENT_COPYBOT_ACTIVE
    enum EVENT_2E5_FLAG5
    enum EVENT_2E5_FLAG4
    enum EVENT_2E5_FLAG3
    enum EVENT_2E5_FLAG2
    enum EVENT_2E5_FLAG1
    enum EVENT_2E5_FLAG0

        enum_start 0x1730 // 0x2E6
    enum EVENT_2E6_FLAG7
    enum EVENT_2E6_FLAG6
    enum EVENT_2E6_FLAG5
    enum EVENT_2E6_FLAG4
    enum EVENT_2E6_FLAG3
    enum EVENT_2E6_FLAG2
    enum EVENT_2E6_FLAG1
    enum EVENT_2E6_FLAG0

        enum_start 0x1738 // 0x2E7
    enum EVENT_2E7_FLAG7
    enum EVENT_2E7_FLAG6
    enum EVENT_2E7_FLAG5
    enum EVENT_2E7_FLAG4
    enum EVENT_2E7_FLAG3
    enum EVENT_2E7_FLAG2
    enum EVENT_2E7_FLAG1
    enum EVENT_2E7_FLAG0

        enum_start 0x1740 // 0x2E8
    enum EVENT_2E8_FLAG7
    enum EVENT_2E8_FLAG6
    enum EVENT_2E8_FLAG5
    enum EVENT_2E8_FLAG4
    enum EVENT_2E8_FLAG3
    enum EVENT_2E8_FLAG2
    enum EVENT_2E8_FLAG1
    enum EVENT_2E8_FLAG0



// eFlags2009F38
