
    // enum Song
    enum_start 0x00
    enum SONG_NO_MUSIC // 0x00
    enum SONG_TITLE_SCREEN // 0x01
    enum SONG_WWW_THEME // 0x02
    enum SONG_CYBER_CITY // 0x03
    enum SONG_INDOORS // 0x04
    enum SONG_SCHOOL // 0x05
    enum SONG_SEASIDE_TOWN // 0x06
    enum SONG_SKY_TOWN // 0x07
    enum SONG_GREEN_TOWN // 0x08
    enum SONG_GRAVEYARD_AREA // 0x09
    enum SONG_MR_WEATHER_COMP // 0x0A
    enum SONG_EVENT_OCCURANCE // 0x0B
    enum SONG_CRISES // 0x0C
    enum SONG_SAD // 0x0D
    enum SONG_HAPPY // 0x0E
    enum SONG_TRANSMISSION // 0x0F
    enum SONG_ROBO_CONTROL_COMP // 0x10
    enum SONG_AQUARIUM_COMP // 0x11
    enum SONG_JUDGE_TREE_COMP // 0x12
    enum SONG_NETWORK // 0x13
    enum SONG_UNDERNET // 0x14
    enum SONG_VIRUS_BATTLE // 0x15
    enum SONG_BOSS_BATTLE // 0x16
    enum SONG_FINAL_BATTLE // 0x17
    enum SONG_PAVILION // 0x18
    enum SONG_WINNER_0 // 0x19
    enum SONG_LOSER // 0x1A
    enum SONG_GAME_OVER // 0x1B
    enum SONG_BOSS_PRELUDE // 0x1C
    enum SONG_CREDITS // 0x1D
    enum SONG_NAVI_CUSTOMIZER // 0x1E
    enum SONG_WINNER_1 // 0x1F
    enum SONG_PAVILION_COMP // 0x20
    enum SONG_CYBERBEASTS // 0x21
    enum SONG_CROSSOVER_BATTLE // 0x22
    enum SONG_SHARK_CHASE // 0x23
    enum SONG_ACDC_TOWN // 0x24
    enum SONG_EXPO // 0x25

    // enum SoundEffect
    enum_start 0x64
    enum SOUND_BEEP_64 // 0x64
    enum SOUND_TYPE // 0x65
    enum SOUND_UNK_66 // 0x66
    enum SOUND_SELECT_67 // 0x67
    enum SOUND_UNSELECT_68 // 0x68
    enum SOUND_CANT_JACK_IN // 0x69
    enum SOUND_BUSTER_6A // 0x6A
    enum SOUND_HIT_6B // 0x6B
    enum SOUND_DELETED // 0x6C
    enum SOUND_HIT_6D // 0x6D
    enum SOUND_HIT_6E // 0x6E
    enum SOUND_HIT_BOMB_0 // 0x6F
    enum SOUND_HIT_BOMB_1 // 0x70
    enum SOUND_BUSTER_CHARGE // 0x71
    enum SOUND_UNK_72 // 0x72
    enum SOUND_UNK_73 // 0x73
    enum SOUND_UNK_74 // 0x74
    enum SOUND_BEEP_75 // 0x75
    enum SOUND_LOG_OUT_76 // 0x76
    enum SOUND_LOG_IN_77 // 0x77
    enum SOUND_BATTLE_START // 0x78
    enum SOUND_SELECT_79 // 0x79
    enum SOUND_SELECT_7A // 0x7A
    enum SOUND_UNSELECT_7B // 0x7B
    enum SOUND_UNSELECT_7C // 0x7C
    enum SOUND_UNK_7D // 0x7D
    enum SOUND_UNK_7E // 0x7E
    enum SOUND_MENU_CUR_MOVE // 0x7F
    enum SOUND_CUR_MOVE_80 // 0x80
    enum SOUND_MENU_SELECT // 0x81
    enum SOUND_SELECT_82 // 0x82
    enum SOUND_EXIT_SUBMENU // 0x83
    enum SOUND_LOW_HP // 0x84
    enum SOUND_UNK_85 // 0x85
    enum SOUND_SELECT_86 // 0x86
    enum SOUND_HIT_87 // 0x87
    enum SOUND_UNK_88 // 0x88
    enum SOUND_UNK_89 // 0x89
    enum SOUND_UNK_8A // 0x8A
    enum SOUND_OK_8B // 0x8B
    enum SOUND_UNK_8C // 0x8C
    enum SOUND_UNK_8D // 0x8D
    enum SOUND_FADE_8E // 0x8E
    enum SOUND_UNK_8F // 0x8F
    enum SOUND_UNK_90 // 0x90
    enum SOUND_ERR_SELECT_91 // 0x91
    // goes on to FD



