	.ifndef INC_DATA_DAT04
	.equ INC_DATA_DAT04, 0

/* Public Symbols */
	.global byte_804E74C
	.global byte_804E87C
	.global dword_804E8D0
	.global dword_804E8D4
	.global byte_804E8D8
	.global off_804E92C
	.global off_804E940
	.global off_804E954
	.global off_804E968
	.global off_804E9CC
	.global byte_804EA08
	.global byte_804EA0D
	.global byte_804EA12
	.global byte_804EA1C
	.global byte_8050102
	.global byte_8050202
	.global byte_8050302
	.global byte_805083F
	.global byte_8051002
	.global byte_8051007
	.global byte_8051009
	.global byte_805150D
	.global off_8052244
	.global off_8052480
	.global off_80524C0
	.global byte_80524E8
	.global byte_8052510
	.global byte_8052538
	.global byte_8052560
	.global byte_80525C0
	.global byte_80525DC


/* External Symbols */
	.include "asm/asm00_2.inc"
// .global loc_8011508

	.include "asm/asm03_0.inc"
// .global off_8030908
// .global loc_803150A

	.include "data/dat13.inc"
// .global byte_807150F

	.include "data/dat20.inc"
// .global byte_8080501

	.include "data/dat21.inc"
// .global byte_8081C84
// .global byte_8083C03
// .global byte_8083F01
// .global byte_8083F07
// .global byte_8084A28

	.include "data/dat22.inc"
// .global byte_8087874
// .global byte_8088268

	.include "data/dat23.inc"
// .global byte_808AC74
// .global byte_808B6F0

	.include "data/dat24.inc"
// .global byte_808DC88
// .global byte_808DEF8

	.include "data/dat25.inc"
// .global byte_80905BC
// .global byte_80908CC
// .global byte_8090AA8
// .global byte_8091374

	.include "data/dat26.inc"
// .global byte_8093A64
// .global byte_8093B60

	.include "data/dat27.inc"
// .global byte_8098BB8

	.include "asm/asm28_0.inc"
// .global byte_8098C78
// .global byte_8098DDC
// .global byte_8099CEC

	.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global byte_809F6EC
// .global byte_809F71C

	.include "asm/asm31.inc"
// .global loc_8100314

	.include "data/dat37.inc"
// .global byte_817B826

	.include "data/dat38_31.inc"
// .global byte_8340901

	.include "data/dat38_33.inc"
// .global byte_83C0716
// .global byte_83C0A10
// .global byte_83C0F08
// .global byte_83C1310
// .global byte_83C1808
// .global byte_83C21DC
// .global byte_83CC02A
// .global byte_83F0016
// .global byte_83F0116
// .global byte_83F0208
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0608
// .global byte_83F0716
// .global byte_83F0808
// .global byte_83F0908
// .global byte_83F0A08
// .global byte_83F1B16

	.include "data/dat38_59.inc"
// .global byte_8519F0C
// .global byte_851AD50
// .global byte_851AD70
// .global byte_851AD90
// .global byte_851AF58
// .global byte_851AF78
// .global byte_851AF98
// .global byte_851EBA8
// .global byte_851EBC8
// .global byte_85235AC
// .global byte_85235CC
// .global byte_85235EC
// .global byte_8526A5C
// .global byte_8527AC4
// .global byte_8527AE4
// .global byte_8527B04
// .global byte_8527B28
// .global byte_8527B48
// .global byte_8527B68
// .global byte_852B784


/* Undeclared Symbols */
// .equ unk_2011EA4, 0x2011EA4
// .equ byte_3001960, 0x3001960
// .equ unk_3001AA0, 0x3001AA0
	.equ byte_82C0804, 0x82C0804
	.equ byte_8310133, 0x8310133

	.endif // INC_DATA_DAT04
