.ifndef INC_DATA_DAT07
.equ INC_DATA_DAT07, 0

/* Public Symbols */
.global unk_805E01C
.global byte_805E084
.global byte_805E09C
.global byte_805E118
.global byte_805E158
.global off_805E15C
.global off_805E170
.global off_805E184
.global off_805E198
.global off_805E1FC
.global byte_805E238
.global byte_805E23D
.global byte_805E242
.global byte_805FF01
.global off_8060184
.global byte_806020A
.global off_8060284
.global byte_80602A4
.global byte_80602CC
.global byte_80602FC
.global byte_806032C


/* External Symbols */
.include "data/dat04.inc"
// .global byte_8050102

.include "data/dat23.inc"
// .global byte_808A6C8

.include "asm/asm24.inc"
// .global byte_808C248

.include "asm/asm28_0.inc"
// .global byte_80990DC
// .global byte_8099CEC

.include "asm/asm31.inc"
// .global off_80E0408

.include "data/dat38_59.inc"
// .global byte_856E826

.include "data/dat38_60.inc"
// .global byte_861FF05

.include "data/dat38_85.inc"
// .global byte_86DFF03

.include "data/dat38_87.inc"
// .global dword_878FA4C


/* Undeclared Symbols */
// .equ unk_3001A20, 0x3001A20

.endif // INC_DATA_DAT07
