.ifndef INC_DATA_DAT05
.equ INC_DATA_DAT05, 0

/* Public Symbols */
.global dword_8052834
.global dword_80529B4
.global dword_8052A6C
.global dword_8052B24
.global dword_8052BDC
.global dword_8052BE0
.global dword_8052BE4
.global dword_8052C10
.global dword_8052D54
.global dword_8052D80
.global dword_8052D84
.global off_8052D88
.global off_8052DB4
.global off_8052DE0
.global off_8052E0C
.global off_8052EE8
.global byte_8052F6C
.global byte_8052F77
.global byte_8052F82
.global off_8059294
.global off_8059378
.global unk_80593B8
.global unk_80593F8
.global unk_8059438
.global unk_8059468
.global unk_80594A8
.global unk_80594E8
.global unk_8059528
.global unk_8059558
.global unk_8059588


/* External Symbols */
.include "asm/asm00_2.inc"
// .global loc_8011508
// .global loc_8013308

.include "data/dat01.inc"
// .global byte_802083F

.include "asm/asm03_0.inc"
// .global sub_8030808
// .global loc_803150A

.include "data/spritePointers_8031CC4.inc"
// .global off_8032108

.include "asm/chatbox.inc"
// .global byte_804033B

.include "data/dat04.inc"
// .global byte_8050102
// .global unk_8051002
// .global unk_805150D
// .global unk_8052560

.include "data/dat08.inc"
// .global unk_806083F

.include "data/dat13.inc"
// .global byte_8070102
// .global byte_8070202
// .global byte_807083F
// .global byte_8070A02
// .global byte_8071503
// .global byte_807150F

.include "data/dat20.inc"
// .global byte_8080115
// .global byte_8080315
// .global byte_808054A
// .global byte_808054F
// .global byte_808058D
// .global unk_8080715
// .global byte_80809F6
// .global byte_80809F8

.include "data/dat21.inc"
// .global byte_8083C01
// .global byte_8083C03
// .global byte_8083C07
// .global byte_8083F03
// .global byte_8083F07
// .global unk_8084554

.include "data/dat23.inc"
// .global byte_808A220

.include "data/dat27.inc"
// .global byte_8094BD0
// .global unk_8094CC8
// .global byte_8098BB8

.include "asm/asm28_0.inc"
// .global byte_80990B8
// .global unk_8099CEC
// .global unk_809BFB0

.include "asm/asm28_1.inc"
// .global dword_809F6B8
// .global byte_809F6CC
// .global byte_809F6EC
// .global byte_809F71C
// .global byte_809F8A5
// .global byte_809F8CA

.include "data/dat28.inc"
// .global unk_80A2713

.include "data/BattleSettings.inc"
// .global byte_80B083F

.include "asm/asm31.inc"
// .global byte_80E083F

.include "data/dat37.inc"
// .global unk_81D083F

.include "data/dat38_32.inc"
// .global byte_835083F

.include "data/dat38_33.inc"
// .global byte_83C0716
// .global byte_83C081D
// .global byte_83C0A10
// .global byte_83C1B16
// .global byte_83C1C16
// .global byte_83C21DC
// .global byte_83F0000
// .global byte_83F0016
// .global byte_83F0116
// .global byte_83F0208
// .global byte_83F0216
// .global byte_83F0216
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0608
// .global byte_83F0616
// .global byte_83F0716
// .global byte_83F0805
// .global byte_83F0808
// .global byte_83F0811
// .global byte_83F081D
// .global byte_83F0908
// .global byte_83F0A08
// .global byte_83F0A10
// .global byte_83F0C08
// .global byte_83F1308
// .global byte_83F1508
// .global byte_83F1608
// .global byte_83F1916
// .global byte_83F1A08
// .global byte_83F1B03
// .global byte_83F1B07
// .global byte_83F1B16
// .global byte_83F1C16
// .global byte_83F2008
// .global byte_83F2300
// .global byte_83F2B16
// .global byte_83F2D16
// .global byte_83F3C10
// .global byte_83F8108
// .global byte_83FC02A

.include "data/dat38_34.inc"
// .global byte_840100F

.include "data/dat38_59.inc"
// .global byte_8535284
// .global byte_85352A4
// .global byte_85352C4
// .global byte_85352E4
// .global byte_8535304
// .global byte_8535324
// .global byte_8535344
// .global byte_8535364
// .global byte_8535384
// .global byte_85353A4
// .global byte_85353C4
// .global byte_85353E4
// .global byte_8535408
// .global byte_8535428
// .global byte_8535448
// .global byte_8535468
// .global byte_853A478
// .global byte_853A498
// .global byte_853A4B8
// .global byte_853A4D8
// .global byte_853A4F8
// .global byte_853A518
// .global byte_853A538
// .global byte_853A558
// .global byte_853A578
// .global byte_853A598
// .global byte_853A5B8
// .global byte_853A5D8
// .global byte_853FF14
// .global byte_853FF34
// .global byte_853FF54
// .global byte_853FF74
// .global byte_853FF94
// .global byte_853FFB4
// .global byte_8545408
// .global byte_8545428
// .global byte_8545448
// .global byte_85494B4
// .global byte_85494D4
// .global byte_85494F4
// .global byte_8549514
// .global byte_8549534
// .global byte_8549554
// .global byte_8549574
// .global byte_8549594

.include "data/dat38_60.inc"
// .global unk_860100F

.include "data/dat38_73.inc"
// .global unk_86D0508

.include "data/dat38_86.inc"
// .global byte_86F6002
// .global byte_86FFF05

.include "data/dat38_87.inc"
// .global byte_8761026


/* Undeclared Symbols */
// .equ unk_3001A80, 0x3001A80
// .global sprite_82F9CCC
.equ byte_8310133, 0x8310133

.endif // INC_DATA_DAT05
