.ifndef INC_DATA_DAT09
.equ INC_DATA_DAT09, 0

/* Public Symbols */
.global byte_8062BFC
.global byte_8062DA4
.global byte_8062DE4
.global byte_8062E88
.global byte_8062EB4
.global byte_8062F1C
.global off_8062F48
.global off_8062F60
.global off_8062F78
.global off_8062F90
.global off_8063008
.global byte_8063050
.global byte_8063056
.global off_8066020
.global off_8066048
.global byte_80662B8
.global byte_80662E8
.global byte_8066328
.global byte_8066368
.global byte_80663A8


/* External Symbols */
.include "data/dat04.inc"
// .global byte_805150D

.include "data/dat08.inc"
// .global byte_8062938

.include "data/dat13.inc"
// .global byte_807150F

.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global sub_809F904

.include "data/dat28.inc"
// .global byte_80A083F

.include "asm/asm29.inc"
// .global sub_80AA104

.include "data/dat38_33.inc"
// .global byte_83C21DC
// .global byte_83F0116
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0716

.include "data/dat38_60.inc"
// .global dword_8610F08
// .global byte_862623B


.endif // INC_DATA_DAT09
