.ifndef INC_DATA_DAT08
.equ INC_DATA_DAT08, 0

/* Public Symbols */
.global dword_8060474
.global dword_80604A0
.global dword_80605E4
.global dword_80605E8
.global off_806063C
.global off_806064C
.global off_806065C
.global off_806066C
.global off_80606BC
.global byte_80606EC
.global byte_80606F0
.global byte_80606F4
.global byte_806083F
.global byte_8061416
.global byte_8061622
.global off_8062728
.global byte_8062860
.global byte_80628A0
.global byte_80628E0
.global byte_8062908
.global byte_8062938
.global byte_8062958
.global byte_80629C0
.global byte_80629F0
.global byte_8062A30
.global byte_8062A70


/* External Symbols */
.include "data/dat21.inc"
// .global byte_8083C07

.include "data/dat24.inc"
// .global byte_808DD60

.include "asm/asm28_1.inc"
// .global sub_809F904

.include "data/dat38_33.inc"
// .global byte_83C0809
// .global byte_83CC02A
// .global byte_83F0016
// .global byte_83F0116
// .global byte_83F0208
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0608
// .global byte_83F0716
// .global byte_83F0A08


.endif // INC_DATA_DAT08
