.ifndef INC_DATA_DAT06
.equ INC_DATA_DAT06, 0

/* Public Symbols */
.global unk_80596F4
.global byte_805975C
.global byte_8059A58
.global byte_8059C00
.global byte_8059D30
.global off_8059D48
.global off_8059D5C
.global off_8059D70
.global off_8059D84
.global off_8059DE8
.global byte_8059E24
.global byte_8059E29
.global byte_8059E2E
.global byte_805D1DC
.global off_805DD24
.global off_805DE28
.global byte_805DE50
.global byte_805DE78
.global byte_805DEA8
.global byte_805DED8


/* External Symbols */
.include "data/dat04.inc"
// .global byte_8050302

.include "data/dat21.inc"
// .global byte_8084F10
// .global byte_80855AC
// .global byte_808580C
// .global byte_80858C4
// .global byte_80865AC

.include "asm/asm28_0.inc"
// .global byte_80990B8
// .global byte_8099CEC

.include "asm/asm28_1.inc"
// .global byte_809F6B8
// .global byte_809F6CC
// .global byte_809F71C
// .global byte_809F7E4

.include "data/dat38_33.inc"
// .global byte_83C21DC
// .global byte_83F0208
// .global byte_83F0716
// .global byte_83F1208

.include "data/dat38_59.inc"
// .global byte_8522C26
// .global byte_856E826

.include "data/dat38_60.inc"
// .global byte_865AC26


/* Undeclared Symbols */
// .equ unk_3001AA0, 0x3001AA0

.endif // INC_DATA_DAT06
