.ifndef INC_DATA_DAT03
.equ INC_DATA_DAT03, 0

/* Public Symbols */
.global unk_804CFBC
.global byte_804CFD4
.global byte_804D08C
.global byte_804D090
.global byte_804D094
.global byte_804D098
.global byte_804D09C
.global byte_804D0A0
.global off_804D0A4
.global off_804D0AC
.global off_804D0B4
.global off_804D0BC
.global off_804D0E4
.global byte_804D0FC
.global byte_804D0FE
.global byte_804D100
.global off_804E38C
.global off_804E450
.global off_804E478
.global off_804E4A0
.global byte_804E5D4
.global byte_804E604


/* External Symbols */
.include "asm/asm03_0.inc"
// .global sub_8030808

.include "data/dat04.inc"
// .global byte_805150D

.include "data/dat21.inc"
// .global byte_8083F07

.include "data/dat25.inc"
// .global byte_80911A0

.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global byte_809F71C

.include "data/dat38_31.inc"
// .global byte_8340031

.include "data/dat38_33.inc"
// .global byte_83C0710
// .global byte_83C0A10
// .global byte_83F0116
// .global byte_83F0216
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0608
// .global byte_83F0716
// .global byte_83F0808
// .global byte_83F0B08
// .global byte_83F0C08
// .global byte_83F0D08
// .global byte_83F1916
// .global byte_83F1C16

.include "data/dat38_59.inc"
// .global byte_850CF74
// .global byte_850CF94
// .global byte_850CFB4
// .global byte_850CFD4
// .global byte_850CFF4
// .global byte_850D014
// .global dword_850D034
// .global byte_8510CF4
// .global byte_8510D14
// .global byte_8510D34
// .global byte_8516280
// .global byte_85162A0
// .global byte_85162C0


/* Undeclared Symbols */
// .equ byte_3000001, 0x3000001
// .equ unk_3001A60, 0x3001A60
// .equ unk_3001A80, 0x3001A80

.endif // INC_DATA_DAT03
