	.ifndef INC_DATA_DAT00
	.equ INC_DATA_DAT00, 0

/* Public Symbols */
	.global off_801ECB4
	.global word_801ED6C
	.global word_801EDB4
	.global byte_801EDFC
	.global word_801EE14
	.global word_801EE58
	.global byte_801EE78
	.global byte_801EE98
	.global byte_801EF10
	.global off_801EF30
	.global off_801EF4C
	.global off_801EF68
	.global pt_801EF84
	.global pt_801EFD4
	.global word_801F374
	.global byte_801F376
	.global word_801F554
	.global byte_801F556
	.global off_801FD64
	.global off_801FD90
	.global byte_801FDC0


/* External Symbols */
	.include "data/dat38_60.inc"
// .global dword_86B7AC0
// .global dword_86B7BA0
// .global dword_86BA120

	.include "data/dat38_85.inc"
// .global dword_86E1638
// .global dword_86E1938
// .global dword_86E1978
// .global dword_86E19B8
// .global dword_86E19F8
// .global dword_86E1A38
// .global dword_86E1A78
// .global dword_86E1AB8
// .global dword_86E1AF8
// .global dword_86E1B38
// .global dword_86E1B78
// .global dword_86E1BF8
// .global dword_86E1C78
// .global dword_86E1D38
// .global byte_86E2E18
// .global byte_86E58FC
// .global dword_86E609C
// .global byte_86E79CC
// .global dword_86E7DCC
// .global dword_86F1340
// .global dword_86F1380
// .global byte_86F13C0
// .global dword_86F1400
// .global dword_86F1440
// .global byte_86F1480
// .global byte_86F14C0
// .global byte_86F1500
// .global byte_86F1540
// .global byte_86F1580
// .global dword_86F15C0
// .global dword_86F1600
// .global byte_86F1640
// .global byte_86F1680
// .global byte_86F16C0
// .global dword_86F1700
// .global dword_86F1780
// .global dword_86F17C0
// .global dword_86F1800
// .global dword_86F1840
// .global byte_86F18C0
// .global byte_86F1900
// .global dword_86F1940
// .global dword_86F19C0
// .global dword_86F1A00
// .global dword_86F1A40
// .global dword_86F1A80
// .global dword_86F1AC0
// .global byte_86F1B00
// .global byte_86F1B40
// .global byte_86F1B80
// .global byte_86F1BC0
// .global byte_86F1C00
// .global byte_86F1C40
// .global byte_86F1C80
// .global byte_86F1CC0
// .global byte_86F1D00
// .global dword_86F1D40
// .global dword_86F1D80
// .global dword_86F1DC0
// .global dword_86F1E00
// .global dword_86F1E40
// .global dword_86F1E80
// .global dword_86F1EC0
// .global dword_86F1F00
// .global dword_86F1F40
// .global dword_86F1F80
// .global dword_86F1FC0
// .global dword_86F2000
// .global dword_86F2040
// .global dword_86F2240
// .global dword_86F2500
// .global dword_86F26C0
// .global byte_86F2900

	.include "data/dat38_86.inc"
// .global byte_872CFB4
// .global byte_872CFD4
// .global byte_872CFF4


/* Undeclared Symbols */
// .equ byte_3001690, 0x3001690
// .equ byte_3001710, 0x3001710
// .equ unk_3001AA0, 0x3001AA0
// .equ unk_3001AC0, 0x3001AC0
// .equ unk_3001AE0, 0x3001AE0
// .equ byte_3001B00, 0x3001B00
// .equ unk_3001B20, 0x3001B20

	.endif // INC_DATA_DAT00
