.ifndef INC_DATA_DAT12
.equ INC_DATA_DAT12, 0

/* Public Symbols */
.global dword_806DD2C
.global dword_806DD44
.global dword_806DD84
.global dword_806DD9C
.global dword_806DDB4
.global dword_806DDCC
.global dword_806DDE4
.global dword_806DDFC
.global dword_806DE3C
.global dword_806DE54
.global dword_806DE80
.global dword_806DEC0
.global dword_806DEEC
.global dword_806DF18
.global dword_806DF44
.global dword_806DF70
.global off_806DFB0
.global off_806DFF0
.global off_806E030
.global off_806E070
.global byte_806E1B0
.global off_806FA98


/* External Symbols */
.include "asm/asm28_0.inc"
// .global byte_8098CA2
// .global byte_80990B8
// .global byte_8099CEC

.include "data/dat38_33.inc"
// .global byte_83F0716


.endif // INC_DATA_DAT12
