.ifndef INC_DATA_DAT18
.equ INC_DATA_DAT18, 0

/* Public Symbols */
.global unk_807AAFC
.global byte_807AC18
.global byte_807ACA8
.global off_807ADEC
.global off_807ADF8
.global off_807AE04
.global off_807AE10
.global byte_807AE4C
.global off_807C82C
.global off_807C94C
.global off_807C974
.global byte_807CA04
.global byte_807CA54
.global byte_807CAA4
.global byte_807CACC
.global byte_807CB1C
.global byte_807CB6C
.global byte_807CBBC
.global byte_807CC0C
.global byte_807CC34
.global byte_807CC5C
.global byte_807CCAC
.global byte_807CCFC
.global byte_807CD4C
.global byte_807CD9C


/* External Symbols */
.include "data/dat13.inc"
// .global byte_8071402

.include "asm/asm28_0.inc"
// .global byte_80990DC

.include "asm/asm28_1.inc"
// .global byte_809F6EC

.include "data/dat38_60.inc"
// .global byte_8605ACC
// .global byte_8605AEC
// .global byte_8605B0C
// .global byte_8605B2C
// .global byte_8605B4C
// .global byte_8605CD0
// .global byte_8605CF0
// .global byte_8605D10
// .global byte_8605D30
// .global byte_8605D50
// .global byte_8605ED4
// .global byte_8605EF4
// .global byte_8605F14
// .global byte_8605F38
// .global byte_8605F58
// .global byte_8605F78
// .global dword_8605F98
// .global dword_8605FB8
// .global byte_8605FD8
// .global byte_860D228
// .global byte_860D248
// .global byte_860D268
// .global byte_860D288
// .global byte_860D2A8
// .global byte_860D42C
// .global byte_860D44C
// .global byte_860D46C
// .global byte_860D490
// .global dword_860D4B0
// .global dword_860D4D0
// .global dword_860D4F0
// .global dword_860D510
// .global byte_860D534
// .global dword_860D554
// .global dword_860D574
// .global dword_860D594
// .global dword_860D5B4
// .global byte_860D5D8
// .global dword_860D5F8
// .global dword_860D618
// .global dword_860D638
// .global dword_860D658
// .global dword_86190F4


.endif // INC_DATA_DAT18
