.ifndef INC_DATA_DAT15
.equ INC_DATA_DAT15, 0

/* Public Symbols */
.global dword_8075614
.global dword_8075708
.global dword_807575C
.global off_80758A0
.global off_80758AC
.global off_80758B8
.global off_80758C4
.global byte_8075900
.global byte_8075903
.global off_8077618
.global off_8077720


/* External Symbols */
.include "data/dat13.inc"
// .global byte_807150F

.include "asm/asm28_0.inc"
// .global byte_8099CEC

.include "asm/asm28_1.inc"
// .global byte_809F6CC

.include "data/dat38_60.inc"
// .global byte_85DB0C0
// .global byte_85DB0E0
// .global byte_85DB100
// .global byte_85DB120
// .global byte_85DB140
// .global byte_85EAA3C
// .global byte_85EAA5C
// .global byte_85EAA7C
// .global byte_85EAA9C
// .global byte_85EAAC0
// .global dword_85EAAE0
// .global dword_85EAB00
// .global dword_85EAB20
// .global dword_85EAB40
// .global byte_85EAB64
// .global byte_85EAB84
// .global byte_85EABA4
// .global byte_85EABC4
// .global byte_85EABE4
// .global byte_85EAC08
// .global byte_85EAC28
// .global byte_85EAC48
// .global byte_85EAC68
// .global byte_85EAC88
// .global byte_85EACAC
// .global byte_85EACCC
// .global byte_85EACEC
// .global byte_85EAD0C
// .global byte_85EE224
// .global byte_85EE244
// .global byte_85EE264
// .global byte_85EE284
// .global dword_8617488


.endif // INC_DATA_DAT15
