	.ifndef INC_DATA_DAT14
	.equ INC_DATA_DAT14, 0

/* Public Symbols */
	.global off_8072C10
	.global byte_8072C3C
	.global off_807360C
	.global off_8073650
	.global off_8073F1C
	.global off_8074F30
	.global byte_8074FDC
	.global byte_807500C
	.global off_807505C
	.global byte_807534C
	.global byte_807537C
	.global byte_80753CC
	.global byte_80753FC


/* External Symbols */
	.include "data/dat04.inc"
// .global byte_805083F

	.include "data/dat13.inc"
// .global byte_8071503
// .global byte_807150F
// .global byte_807153F

	.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global byte_809F6EC
// .global byte_809F71C
// .global byte_809F7E4
// .global byte_809F880
// .global sub_809F904

	.include "data/dat38_33.inc"
// .global byte_83F0016
// .global byte_83F0208
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0508
// .global byte_83F0716
// .global byte_83F0908
// .global byte_83F0B08
// .global byte_83F0F08
// .global byte_83F1516
// .global byte_83F2608
// .global byte_83F2C16

	.include "data/dat38_60.inc"
// .global byte_85DB0C0
// .global byte_85DB0E0
// .global byte_85DB100
// .global byte_85DB120
// .global byte_85DB140
// .global byte_85E2E6C
// .global byte_85E2E8C
// .global byte_85E2EAC
// .global byte_85E2ECC
// .global byte_85E2EF0
// .global dword_85E2F10
// .global dword_85E2F30
// .global dword_85E2F50
// .global dword_85E2F70
// .global byte_85E511C
// .global byte_85E513C
// .global byte_85E515C
// .global byte_85E517C
// .global dword_8617488


	.endif // INC_DATA_DAT14
