.ifndef INC_DATA_DAT19
.equ INC_DATA_DAT19, 0

/* Public Symbols */
.global byte_807D024
.global byte_807D0B4
.global byte_807D1A8
.global byte_807D210
.global off_807D2F0
.global off_807D300
.global off_807D310
.global off_807D320
.global byte_807D370
.global off_807EA6C
.global off_807EB18
.global byte_807EB68
.global byte_807EBB8
.global byte_807EC08
.global off_807EC58
.global off_807ECA8


/* External Symbols */
.include "data/dat13.inc"
// .global byte_807150F

.include "asm/asm28_1.inc"
// .global byte_809F6CC

.include "data/dat38_33.inc"
// .global byte_83F0016
// .global byte_83F0316
// .global byte_83F0408
// .global byte_83F0516
// .global byte_83F0608
// .global byte_83F0708
// .global byte_83F0716
// .global byte_83F09C0
// .global byte_83F0A08
// .global byte_83F2C16
// .global byte_83F2D16

.include "data/dat38_60.inc"
// .global dword_860D820
// .global byte_860D840
// .global byte_860D860
// .global byte_860D880
// .global byte_860D8A0
// .global dword_860DA24
// .global byte_860DA44
// .global byte_860DA64
// .global byte_860DA84
// .global byte_860DAA4
// .global byte_860DC28
// .global byte_860DC48
// .global byte_860DC68
// .global dword_860DC8C
// .global dword_860DCAC
// .global dword_860DCCC
// .global dword_860DCEC
// .global dword_860DD0C
// .global byte_860DD30
// .global dword_860DD50
// .global dword_860DD70
// .global dword_860DD90
// .global dword_860DDB0
// .global byte_8619630
// .global byte_8619650
// .global byte_8619670
// .global byte_8619690
// .global byte_86196B0
// .global byte_86196D0
// .global byte_86196F0
// .global byte_8619710


/* Undeclared Symbols */
// .equ byte_3001960, 0x3001960
// .equ unk_3001A20, 0x3001A20
// .equ unk_3001A80, 0x3001A80

.endif // INC_DATA_DAT19
