.ifndef INC_DATA_DAT16
.equ INC_DATA_DAT16, 0

/* Public Symbols */
.global unk_8077EA4
.global byte_8077EF8
.global off_8078104
.global off_807810C
.global off_8078114
.global off_807811C
.global byte_8078144
.global off_80790A4
.global off_80790EC
.global byte_8079114
.global byte_8079164
.global byte_80791B4
.global byte_8079204
.global byte_8079254
.global byte_80792A4
.global byte_80792F4


/* External Symbols */
.include "data/dat38_60.inc"
// .global byte_85F1678
// .global byte_85F1698
// .global byte_85F16B8
// .global byte_85F16D8
// .global byte_85F16F8
// .global byte_85F187C
// .global byte_85F189C
// .global byte_85F18BC
// .global byte_85F18DC
// .global byte_85F18FC
// .global byte_85F1A80
// .global byte_85F1AA0
// .global byte_85F1AC0
// .global byte_85F1AE0
// .global byte_85F1B00
// .global byte_85F4D24
// .global byte_85F4D44
// .global byte_85F4D64
// .global dword_86190F4


.endif // INC_DATA_DAT16
