.ifndef INC_DATA_DAT12
.equ INC_DATA_DAT12, 0

/* Public Symbols */
.global byte_806DD2C
.global byte_806DD44
.global byte_806DD84
.global byte_806DD9C
.global byte_806DDB4
.global byte_806DDCC
.global byte_806DDE4
.global byte_806DDFC
.global byte_806DE3C
.global byte_806DE54
.global byte_806DE80
.global byte_806DEC0
.global byte_806DEEC
.global byte_806DF18
.global byte_806DF44
.global byte_806DF70
.global off_806DFB0
.global off_806DFF0
.global off_806E030
.global off_806E070
.global byte_806E1B0
.global off_806FA98


/* External Symbols */
.include "asm/asm28_0.inc"
// .global byte_8098CA2
// .global byte_80990B8
// .global byte_8099CEC

.include "data/dat38_33.inc"
// .global byte_83F0716


.endif // INC_DATA_DAT12
