.ifndef INC_DATA_DAT19
.equ INC_DATA_DAT19, 0

/* Public Symbols */
.global dword_807D024
.global dword_807D0B4
.global dword_807D1A8
.global dword_807D210
.global off_807D2F0
.global off_807D300
.global off_807D310
.global off_807D320
.global byte_807D370
.global off_807EA6C
.global off_807EB18
.global dword_807EB68
.global dword_807EBB8
.global off_807EC58
.global off_807ECA8


/* External Symbols */
.include "data/dat38_60.inc"
// .global dword_860D840
// .global dword_860DA24
// .global dword_860DA44
// .global dword_860DC28
// .global dword_860DC28
// .global dword_860DC8C
// .global dword_860DD50
// .global dword_860DD70
// .global dword_860DD90


/* Undeclared Symbols */
// .equ word_3001960, 0x3001960
// .equ unk_3001A20, 0x3001A20
// .equ unk_3001A80, 0x3001A80

.endif // INC_DATA_DAT19
