	.ifndef INC_DATA_DAT13
	.equ INC_DATA_DAT13, 0

/* Public Symbols */
	.global byte_8070034
	.global byte_8070074
	.global byte_80700B4
	.global byte_80700CC
	.global byte_80700E4
	.global byte_80700FC
	.global byte_8070102
	.global byte_8070114
	.global byte_807012C
	.global byte_8070144
	.global byte_8070184
	.global byte_807019C
	.global byte_80701B4
	.global byte_80701CC
	.global byte_80701E4
	.global byte_80701FC
	.global byte_8070202
	.global byte_8070214
	.global off_807022C
	.global off_807026C
	.global off_80702AC
	.global off_80702EC
	.global byte_807042C
	.global byte_8070605
	.global byte_807083F
	.global byte_8070A02
	.global byte_8071402
	.global byte_8071503
	.global byte_807150F
	.global byte_8071510
	.global off_8071584
	.global off_8071680
	.global byte_8071970
	.global byte_80719C0
	.global byte_8071A10
	.global byte_8071A60
	.global byte_8071AB0
	.global byte_8071B00


/* External Symbols */
	.include "asm/asm28_0.inc"
// .global byte_8099CEC

	.include "data/dat38_60.inc"
// .global byte_85DAF78
// .global dword_85DAF98
// .global dword_85DAFB8
// .global dword_85DAFD8
// .global dword_85DAFF8
// .global byte_85DB01C
// .global byte_85DB03C
// .global byte_85DB05C
// .global byte_85DB07C
// .global byte_85DB09C
// .global byte_85DB0C0
// .global byte_85DB0E0
// .global byte_85DB100
// .global byte_85DB120
// .global byte_85DB140
// .global byte_85DDAD4
// .global byte_85DDAF4
// .global byte_85DDB14
// .global byte_85DDB34
// .global byte_85DDB54
// .global byte_85E0530
// .global byte_85E0550
// .global byte_85E0570
// .global byte_85E0590
// .global byte_85E05B0
// .global byte_85E05D0
// .global byte_85E05F0
// .global byte_85E0610
// .global byte_85E0630
// .global byte_85E0650
// .global dword_8617488


/* Undeclared Symbols */
// .equ byte_3000190, 0x3000190

	.endif // INC_DATA_DAT13
