	.ifndef INC_DATA_DAT17
	.equ INC_DATA_DAT17, 0

/* Public Symbols */
	.global byte_80794AC
	.global byte_80794EC
	.global off_807952C
	.global off_8079534
	.global off_807953C
	.global off_8079544
	.global byte_807956C
	.global byte_807956E
	.global off_8079F74
	.global off_807A080
	.global byte_807A370
	.global byte_807A3C0
	.global byte_807A410
	.global byte_807A460
	.global byte_807A4B0
	.global off_807A4E0
	.global byte_807A7D0
	.global byte_807A800
	.global byte_807A850


/* External Symbols */
	.include "data/dat38_60.inc"
// .global byte_85DB0C0
// .global byte_85DB0E0
// .global byte_85DB100
// .global byte_85DB120
// .global byte_85DB140
// .global byte_85F7BB8
// .global byte_85F7BD8
// .global byte_85F7BF8
// .global byte_85F7C18
// .global byte_85F7C38
// .global byte_85FB5DC
// .global byte_85FB5FC
// .global byte_85FB61C
// .global byte_85FB63C
// .global byte_85FB65C
// .global byte_85FB680
// .global byte_85FB6A0
// .global byte_85FB6C0
// .global byte_85FB6E0
// .global byte_85FB700
// .global byte_85FB724
// .global dword_85FB744
// .global dword_85FB764
// .global dword_85FB784
// .global dword_85FB7A4
// .global byte_85FB7C8
// .global byte_85FB7E8
// .global byte_85FB808
// .global byte_85FB828
// .global byte_85FEDE4
// .global byte_85FEE04
// .global byte_85FEE24
// .global byte_85FEE44
// .global byte_85FEE68
// .global byte_85FEE88
// .global byte_85FEEA8
// .global byte_85FEEC8
// .global byte_85FEEE8
// .global dword_8617488


	.endif // INC_DATA_DAT17
