.ifndef INC_DATA_DAT20
.equ INC_DATA_DAT20, 0

/* Public Symbols */
.global unk_807EEB8
.global byte_807EFD4
.global byte_807F1E0
.global byte_807F1F8
.global byte_807F204
.global byte_807F210
.global off_807F21C
.global byte_807F268
.global off_807F690
.global off_807F900
.global off_807FAC0
.global off_807FB98
.global off_807FE88
.global byte_8080115
.global off_8080178
.global off_80802A8
.global off_8080314
.global byte_8080404
.global byte_8080501
.global byte_808054A
.global byte_808054F
.global byte_8080550
.global byte_808058D
.global off_8080598
.global off_80805C0
.global byte_808060A
.global off_8080684
.global byte_8080689
.global byte_808068A
.global byte_808068B
.global byte_80806B3
.global byte_8080715
.global off_80808B0
.global off_80808D8
.global byte_80809F8
.global off_8080AA0
.global byte_8080C0C


/* External Symbols */
.include "asm/asm28_0.inc"
// .global byte_8099CEC

.include "asm/asm28_1.inc"
// .global byte_809F79C

.include "data/dat38_60.inc"
// .global dword_8610F08
// .global dword_8611B68
// .global dword_8613028
// .global dword_8613DDC
// .global dword_8616904
// .global dword_8617488
// .global dword_86190F4


.endif // INC_DATA_DAT20
