.ifndef INC_DATA_DAT24
.equ INC_DATA_DAT24, 0

/* Public Symbols */
.global byte_808DC88
.global byte_808DD60
.global byte_808DEF8
.global off_808F5D4
.global byte_808F668
.global byte_808F67C
.global byte_808F690
.global byte_808F6EC
.global byte_808F728
.global byte_808F748
.global byte_808F788


/* External Symbols */
.include "asm/asm03_1.inc"
// .global sub_80355DE


/* Undeclared Symbols */
// .equ unk_2000310, 0x2000310

.endif // INC_DATA_DAT24
