.ifndef INC_DATA_DAT22
.equ INC_DATA_DAT22, 0

/* Public Symbols */
.global unk_80871D8
.global sub_80871F4
.global sub_8087238
.global byte_8087874
.global byte_8088268
.global byte_8088514
.global byte_8088708


/* External Symbols */
.include "data/dat21.inc"
// .global off_8086D18
// .global off_8086D1C

.include "asm/reqBBS.inc"
// .global reqBBS_setFlag_e17b0f7_8140A00


/* Undeclared Symbols */
// .equ byte_2000EC0, 0x2000EC0
// .equ byte_2000EC1, 0x2000EC1
// .equ byte_2000EC2, 0x2000EC2
// .equ byte_2000EC3, 0x2000EC3
// .equ byte_2000EC4, 0x2000EC4
// .equ byte_2000EC5, 0x2000EC5
// .equ byte_2000EC6, 0x2000EC6
// .equ byte_2000EC7, 0x2000EC7
// .equ byte_2000EC8, 0x2000EC8
// .equ byte_2000EC9, 0x2000EC9

.endif // INC_DATA_DAT22
