	.ifndef INC_DATA_DAT25
	.equ INC_DATA_DAT25, 0

/* Public Symbols */
	.global byte_8090508
	.global byte_80905BC
	.global byte_809083F
	.global byte_80908CC
	.global byte_8090AA8
	.global byte_80911A0
	.global byte_8091374


/* External Symbols */
	.include "asm/asm03_1.inc"
// .global off_80348FC
// .global off_8034938


/* Undeclared Symbols */
	.equ LCDControl, 0x4000000

	.endif // INC_DATA_DAT25
