.ifndef INC_DATA_DAT33
.equ INC_DATA_DAT33, 0

/* Public Symbols */
.global byte_812C258
.global byte_812C268
.global byte_812C278
.global byte_812C280
.global byte_812C288
.global sub_812C2C0


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sound_play // () -> void
// .global ZeroFillByWord // (void *memBlock, int size) -> void
// .global ZeroFillByEightWords // (int a1, int a2) -> void
// .global decompAndCopyData // (u32 *initRefs) -> void
// .global sub_80015FC
// .global zeroFillVRAM
// .global sub_80017E0
// .global sub_800183C

.include "asm/asm00_1.inc"
// .global engine_setScreeneffect // (int a1, int a2) -> void
// .global engine_isScreeneffectAnimating // () -> zf

.include "asm/asm02.inc"
// .global dword_8021AEC
// .global sub_8021B92 // (int idx, int searchItem, int off) -> void*

.include "asm/asm03_1.inc"
// .global sub_803C59C
// .global sub_803DD60
// .global sub_803E8E4
// .global sub_803E8F8
// .global sub_803EA50
// .global sub_803EA58
// .global sub_803EA60
// .global sub_803EA70
// .global sub_803EAE4
// .global sub_803EBAC
// .global sub_803EBF4
// .global sub_803EF74
// .global sub_803F798

.include "asm/chatbox.inc"
// .global chatbox_8040818
// .global chatbox_8045F3C

.include "asm/asm03_2.inc"
// .global sub_80465A0 // (void *a1) -> void
// .global sub_80465BC
// .global sub_80465F8 // () -> void
// .global sub_8046664 // () -> void

.include "asm/asm32.inc"
// .global sub_8119854
// .global sub_811A914
// .global sub_811A940
// .global sub_811A968
// .global sub_811F7EC
// .global sub_811FA0C
// .global sub_811FA22
// .global sub_8120AB8
// .global sub_8120CC8

.include "asm/asm33.inc"
// .global byte_8129150
// .global dword_8129180
// .global sub_8129248
// .global sub_812AC14
// .global sub_812AF3C
// .global sub_812AF78
// .global sub_812AF84
// .global sub_812AFC8
// .global sub_812B530

.include "asm/asm34.inc"
// .global sub_812D378
// .global sub_812D3A8
// .global sub_812D3E4
// .global sub_812D4FC
// .global sub_812D528
// .global sub_812D5A0
// .global sub_812D5D0
// .global sub_812D690
// .global sub_812D6F8
// .global sub_812D748
// .global sub_812D778
// .global sub_812D78C
// .global sub_812D854
// .global sub_812D880
// .global sub_812D8C8
// .global sub_812D91C
// .global loc_812D922
// .global sub_812D934
// .global sub_812D954
// .global sub_812D99C
// .global sub_812DA3C
// .global sub_812DA4C
// .global sub_812DA60

.include "asm/asm36.inc"
// .global sub_8132280
// .global sub_81323B0
// .global sub_8132430
// .global sub_81324A8
// .global sub_81325C0
// .global sub_81325CC
// .global sub_8132614

.include "asm/libs.inc"
// .global sub_8149568
// .global sub_8149644

.include "data/dat38_70.inc"
// .global byte_86C9D6C


/* Undeclared Symbols */
// .equ unk_20251A0, 0x20251A0

.endif // INC_DATA_DAT33
