	.ifndef INC_DATA_DAT38_17
	.equ INC_DATA_DAT38_17, 0

/* Public Symbols */
	.global byte_8411E90
	.global byte_8415A90
	.global byte_8419440
	.global byte_841C9C4
	.global byte_8420000
	.global byte_84201AC
	.global byte_8424C78
	.global byte_842A630
	.global byte_842DAC0
	.global byte_8430534


/* External Symbols */

/* Undeclared Symbols */
	.equ LCDControl, 0x4000000

	.endif // INC_DATA_DAT38_17
