	.ifndef INC_DATA_DAT30
	.equ INC_DATA_DAT30, 0

/* Public Symbols */
	.global off_80B1B7C
	.global off_80B1ED8
	.global off_80B23C8
	.global off_80B29CC
	.global off_80B2EDC
	.global off_80B36BC
	.global off_80B3970
	.global off_80B41E4
	.global off_80B4AB8
	.global off_80B4AF8
	.global off_80B4B38
	.global off_80B5A0C
	.global off_80B5A4C
	.global off_80B62F8
	.global off_80B66A8
	.global off_80B6C20
	.global off_80B71D4
	.global off_80B79C0


/* External Symbols */

	.endif // INC_DATA_DAT30
