.ifndef INC_DATA_DAT36
.equ INC_DATA_DAT36, 0

/* Public Symbols */
.global unk_8138944
.global byte_8138B90
.global off_8138C04
.global off_8138DBC
.global off_8138F10
.global off_81390A0
.global off_81391EC
.global off_813925C
.global off_81392A0
.global off_81393E8
.global StructArr_813944C
.global byte_813B1EC
.global byte_813B2CD
.global byte_813B3AE
.global byte_813B522


/* External Symbols */
.include "data/dat04.inc"
// .global byte_8051007
// .global byte_8051009
// .global byte_805150D

.include "data/dat13.inc"
// .global byte_807150F

.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global byte_809F878

.include "data/dat38_59.inc"
// .global unk_850100F

.include "data/dat38_60.inc"
// .global byte_85A100F

.include "data/dat38_85.inc"
// .global unk_86E101C


.endif // INC_DATA_DAT36
