.ifndef INC_DATA_DAT38_70
.equ INC_DATA_DAT38_70, 0

/* Public Symbols */
.global byte_86C9D6C
.global byte_86C9D8C
.global byte_86C9DAC
.global byte_86C9DCC
.global dword_86CA10C
.global PET_Gfx_tileRefs
.global TileRefs_86CB21C
.global TileRefs_86CB240
.global TileRefs_86CB264
.global TileRefs_86CB288
.global TileRefs_86CB2AC
.global TileRefs_86CB2D0
.global TileRefs_86CB2F4
.global TileRefs_86CB318
.global TileRefs_86CB33C
.global byte_86CB360
.global sprite_86CBB7C
.global sprite_86CC13C
.global sprite_86CD410
.global dword_86CD7C4
.global dword_86CD924
.global dword_86CDBC4
.global dword_86CDBE4


/* External Symbols */

.endif // INC_DATA_DAT38_70
