	.ifndef INC_DATA_DAT38_92
	.equ INC_DATA_DAT38_92, 0

/* Public Symbols */
	.global sprite_87E6E20
	.global dword_87E74F4
	.global dword_87E7514
	.global dword_87E7534
	.global dword_87E7554
	.global dword_87E7574
	.global dword_87E76B8
	.global dword_87E771C
	.global dword_87E7780
	.global dword_87E77E4
	.global dword_87E7848
	.global byte_87E78A8
	.global byte_87E7B30
	.global byte_87E9320
	.global byte_87E9578
	.global byte_87EA788
	.global byte_87EA9F4
	.global byte_87EBAB8
	.global byte_87EBDDC
	.global byte_87ECF34
	.global byte_87ED240
	.global dword_87EE1AC
	.global dword_87EE2F0
	.global dword_87EE5B0
	.global dword_87EF5A4
	.global byte_87EF824
	.global byte_87EFBA4
	.global reqBBS_textualShades
	.global byte_87EFE14


/* External Symbols */

	.endif // INC_DATA_DAT38_92
