	.ifndef INC_DATA_DAT38_18
	.equ INC_DATA_DAT38_18, 0

/* Public Symbols */
	.global byte_843C234
	.global byte_8442164
	.global byte_8445E00
	.global byte_844BF80
	.global unk_8451508
	.global byte_8453D90
	.global byte_8456ABC
	.global byte_845F138
	.global dword_8468940
	.global byte_846FD50
	.global byte_8477574
	.global byte_8481548
	.global byte_848334C
	.global byte_8485F74
	.global byte_848FCEC


/* External Symbols */

/* Undeclared Symbols */
// .equ timer_2000000, 0x2000000
	.equ LCDControl, 0x4000000

	.endif // INC_DATA_DAT38_18
