.ifndef INC_DATA_DAT38_37
.equ INC_DATA_DAT38_37, 0

/* Public Symbols */
.global npcSpriteProtoMan
.global npcSpriteProgman
.global npcSpriteGreenNavi
.global npcSpriteEvilNavi
.global byte_8451508
.global npcSpriteGirlNavi
.global npcSpriteSpoutMan
.global npcSpriteHawkMan
.global sprite_8468940
.global npcSpriteDrillMan
.global sprite_8477574
.global sprite_8481548
.global sprite_848334C
.global npcSpriteColonel
.global sprite_848FCEC


/* External Symbols */

.endif // INC_DATA_DAT38_37
