.ifndef INC_DATA_DAT37
.equ INC_DATA_DAT37, 0

/* Public Symbols */
.global byte_814FE90
.global byte_814FE94
.global off_8158278
.global off_815827C
.global byte_8158280
.global word_8158282
.global sound_MusicTable
.global byte_817B826
.global byte_819DD01
.global byte_819ED15
.global byte_81A081B
.global byte_81AA901
.global byte_81AB915
.global byte_81B8101
.global off_81B9114
.global byte_81C03AC
.global byte_81C03D8
.global LibInfoText_FU_MBOOT
.global LibInfoText_aNintendosio32i
.global off_81C0418
.global byte_81C04A8
.global byte_81C055A
.global byte_81C055B
.global byte_81C055C
.global byte_81C058C
.global byte_81C05A4
.global byte_81C05A5
.global byte_81C0626
.global byte_81C0627
.global byte_81C0628
.global byte_81C0640
.global byte_81C067B
.global byte_81C067C
.global byte_81C068C
.global off_81C06C0
.global off_81C241C
.global byte_81C7000
.global byte_81D081E
.global byte_81D083F
.global unk_81D4314


/* External Symbols */
.include "asm/libs.inc"
// .global sub_814D8CC
// .global sub_814D8F0
// .global sub_814D994
// .global sub_814D9C4
// .global byte_814E02D
// .global sub_814E044
// .global sub_814E064
// .global sub_814E0DC
// .global sub_814E0FC
// .global sub_814E118
// .global sub_814E12C
// .global sub_814E15C
// .global sub_814E168
// .global sub_814E17C
// .global sub_814E190
// .global sub_814E1C0
// .global sub_814E1D4
// .global sub_814E1E8
// .global sub_814E1FC
// .global sub_814E210
// .global sub_814E21C
// .global sub_814E234
// .global sub_814E248
// .global sub_814E4DC
// .global sub_814E758
// .global sub_814E7CC
// .global sub_814E7E0
// .global sub_814EDC0
// .global sub_814F228
// .global sub_814F2F0
// .global sub_814FD74
// .global sub_814FD88
// .global sub_814FDD0
// .global sub_814FDE4
// .global sub_814FDF8
// .global sub_814FE0C
// .global sub_814FE20
// .global sub_814FE34
// .global sub_814FE40
// .global sub_814FE4C
// .global sub_814FE60


/* Undeclared Symbols */
// .equ timer_2000000, 0x2000000
// .equ unk_2000200, 0x2000200
// .equ unk_2006E08, 0x2006E08
// .equ unk_2006EF8, 0x2006EF8
// .equ unk_2010000, 0x2010000
// .equ unk_2010690, 0x2010690
// .equ unk_201FAF8, 0x201FAF8
// .equ unk_2020200, 0x2020200
.equ LCDControl, 0x4000000

.endif // INC_DATA_DAT37
