	.ifndef INC_DATA_DAT38_96
	.equ INC_DATA_DAT38_96, 0

/* Public Symbols */
	.global dword_87F25B4
	.global TextScriptNetworkEnterFolderName1
	.global TextScriptNetworkEnterFolderName0
	.global dword_87F28DC
	.global TextScriptNetworkRequestConnection87F2A1C
	.global TextScriptNaviNames0
	.global TextScriptNaviNames1
	.global TextScriptCommError873B9E0
	.global TextScriptDustManUndernetTut


/* External Symbols */

	.endif // INC_DATA_DAT38_96
