.ifndef INC_DATA_DAT32
.equ INC_DATA_DAT32, 0

/* Public Symbols */
.global dword_8121270
.global dword_812127C
.global dword_8121288
.global dword_812129C
.global dword_81212B0
.global dword_81212CC
.global dword_81212E8
.global dword_812130C
.global dword_8121330
.global dword_8121354
.global dword_8121388
.global dword_81213BC
.global dword_81213F0
.global dword_8121424
.global dword_8121458
.global off_812148C
.global off_8121748
.global off_8121A2C
.global off_8121C40
.global off_8121EA4
.global off_81220F8
.global off_8122334
.global off_8122618
.global off_812291C
.global off_8122BF8
.global off_8122EBC


/* External Symbols */

.endif // INC_DATA_DAT32
