	.ifndef INC_DATA_SPRITEPOINTERS_8031CC4
	.equ INC_DATA_SPRITEPOINTERS_8031CC4, 0

/* Public Symbols */
	.global SpritePointersList
	.global off_8032108
	.global mugshotSpritePtrs
	.global guiSpritePtrs
	.global off_80329A8
	.global off_80329C4
	.global off_8032F6C
	.global off_8032F88
	.global pt_8033530
	.global pt_803354C


/* External Symbols */
	.include "asm/asm03_0.inc"
// .global sub_8030628
// .global sub_8030808
// .global sub_803086C

	.include "asm/asm03_1.inc"
// .global off_8033764

	.include "data/dat38_30.inc"
// .global sprite_8336320
// .global sprite_8336D54

	.include "data/dat38_31.inc"
// .global sprite_8338F18
// .global sprite_833BE68
// .global sprite_833F3A0
// .global sprite_8342AC4
// .global sprite_8345C50
// .global sprite_8348E80
// .global sprite_83497CC
// .global sprite_834A108
// .global sprite_834A580
// .global sprite_834AE94
// .global sprite_834B2D0
// .global sprite_834B6A4
// .global sprite_834BBF0
// .global sprite_834BEB8
// .global sprite_834C6F0

	.include "data/dat38_32.inc"
// .global sprite_8350628
// .global sprite_8350888
// .global sprite_8351FA8
// .global sprite_8352360
// .global sprite_83536BC
// .global sprite_83547A4
// .global sprite_8354D0C
// .global sprite_8354EF0
// .global sprite_8355D50
// .global sprite_835613C
// .global sprite_83566F4
// .global sprite_8357308
// .global sprite_8357B10
// .global sprite_8359644
// .global sprite_835AD9C
// .global sprite_835B938
// .global sprite_835C4B0
// .global sprite_835C794
// .global sprite_835CA2C
// .global sprite_835E264
// .global sprite_835F424
// .global sprite_83607D0
// .global sprite_83611FC
// .global sprite_8367848
// .global sprite_8368F54
// .global sprite_836B6A8
// .global sprite_836B818
// .global sprite_836C668
// .global sprite_836E034
// .global sprite_836EA90
// .global sprite_836EDB8
// .global sprite_8370D6C
// .global sprite_8371274
// .global sprite_8371C50
// .global sprite_8372410
// .global sprite_8372F34
// .global sprite_83732AC
// .global sprite_8373AFC
// .global sprite_8373D70
// .global sprite_8376364
// .global sprite_8376A24
// .global sprite_8377834
// .global sprite_8377AF4
// .global sprite_8379D44
// .global sprite_837D8E0
// .global sprite_837EB4C
// .global sprite_837F2E0
// .global sprite_837FD98
// .global sprite_83805D4
// .global sprite_8381340
// .global sprite_83822F0
// .global sprite_8382928
// .global sprite_8383698
// .global sprite_8385354
// .global sprite_8385648
// .global sprite_83864F4
// .global sprite_8387244
// .global sprite_8387E4C
// .global sprite_838849C
// .global sprite_838A9A8

	.include "data/dat38_33.inc"
// .global sprite_838B930
// .global sprite_838C3C8
// .global sprite_838C864
// .global sprite_838E194
// .global sprite_838E74C
// .global sprite_838EC00
// .global sprite_83908A4
// .global sprite_8390F44
// .global sprite_8390FC4
// .global sprite_8391E40
// .global sprite_839247C
// .global sprite_83930E0
// .global sprite_8395034
// .global sprite_8395660
// .global sprite_8396650
// .global byte_83971C0
// .global byte_8398048
// .global sprite_8399578
// .global sprite_839AAB8
// .global sprite_839B9C0
// .global sprite_839CCDC
// .global sprite_83A000C
// .global sprite_83A0DA8
// .global sprite_83A5E30
// .global sprite_83A67AC
// .global sprite_83A9190
// .global sprite_83AC1A8
// .global sprite_83AC430
// .global sprite_83ACF48
// .global sprite_83AD870
// .global sprite_83AE2B4
// .global sprite_83AF658
// .global sprite_83B00F8
// .global sprite_83B0A90
// .global sprite_83B2494
// .global sprite_83B3BF4
// .global sprite_83B440C
// .global sprite_83B4AE4
// .global sprite_83B5F44
// .global sprite_83B92B4
// .global sprite_83BA940
// .global sprite_83BB440
// .global sprite_83BC3B0
// .global sprite_83BCC70
// .global sprite_83BD228
// .global sprite_83BE6B0
// .global npcSpriteLan
// .global npcSpriteMayl
// .global npcSpriteDex
// .global npcSpriteYai
// .global npcSpriteChaud
// .global npcSpriteDad
// .global npcSpriteMom
// .global sprite_83E0108
// .global sprite_83E1EEC
// .global sprite_83E2B48
// .global sprite_83E55F8
// .global sprite_83E7F4C
// .global sprite_83EB980
// .global sprite_83EEF14
// .global sprite_83F37C4
// .global sprite_83F6824
// .global sprite_83FA130

	.include "data/dat38_34.inc"
// .global sprite_83FEC68
// .global sprite_8402FA0
// .global sprite_8406044
// .global sprite_84069EC
// .global sprite_8408360
// .global sprite_8408DB4

	.include "data/dat38_35.inc"
// .global sprite_840B3A4

	.include "data/dat38_36.inc"
// .global sprite_8411E90
// .global sprite_8415A90
// .global sprite_8419440
// .global sprite_841C9C4
// .global sprite_84201AC
// .global sprite_8424C78
// .global sprite_842A630
// .global sprite_842DAC0
// .global npcSpriteMegaMan

	.include "data/dat38_37.inc"
// .global npcSpriteProtoMan
// .global npcSpriteProgman
// .global npcSpriteGreenNavi
// .global npcSpriteEvilNavi
// .global npcSpriteGirlNavi
// .global npcSpriteSpoutMan
// .global npcSpriteHawkMan
// .global sprite_8468940
// .global npcSpriteDrillMan
// .global sprite_8477574
// .global sprite_8481548
// .global sprite_848334C
// .global npcSpriteColonel
// .global sprite_848FCEC

	.include "data/dat38_38.inc"
// .global sprite_8495B88
// .global sprite_8497CF8

	.include "data/dat38_39.inc"
// .global sprite_849B424
// .global sprite_849BA28
// .global sprite_849D164
// .global objSpriteSkullBarrier
// .global sprite_849FBC0

	.include "data/dat38_40.inc"
// .global sprite_84A3048

	.include "data/dat38_41.inc"
// .global sprite_84A53C4
// .global sprite_84A599C

	.include "data/dat38_42.inc"
// .global sprite_84A8AC0

	.include "data/dat38_43.inc"
// .global sprite_84A97A8

	.include "data/dat38_44.inc"
// .global sprite_84AB2D0
// .global sprite_84AB680
// .global sprite_84ADD6C

	.include "data/dat38_45.inc"
// .global sprite_84AF710
// .global sprite_84B1BA0

	.include "data/dat38_46.inc"
// .global sprite_84B4838
// .global sprite_84B5238

	.include "data/dat38_47.inc"
// .global sprite_84B5C18
// .global sprite_84B62AC

	.include "data/dat38_48.inc"
// .global sprite_84B7414
// .global sprite_84B8BB4
// .global sprite_84BA414
// .global sprite_84BA7A8

	.include "data/dat38_49.inc"
// .global sprite_84BC0C8

	.include "data/dat38_50.inc"
// .global sprite_84BC854

	.include "data/dat38_51.inc"
// .global sprite_84BDDD4

	.include "data/dat38_52.inc"
// .global sprite_84BF6F8

	.include "data/dat38_53.inc"
// .global sprite_84C0298
// .global sprite_84C2D34

	.include "data/dat38_54.inc"
// .global sprite_84C5194
// .global sprite_84C832C

	.include "data/dat38_55.inc"
// .global sprite_84C90B4

	.include "data/dat38_56.inc"
// .global sprite_84CDF74

	.include "data/dat38_57.inc"
// .global sprite_84D3DBC

	.include "data/dat38_58.inc"
// .global sprite_84DF96C

	.include "data/dat38_59.inc"
// .global mugshotLan
// .global mugshotMayl
// .global mugshotDex
// .global mugshotYai
// .global mugshotChaud
// .global mugshotDad
// .global mugshotMom
// .global sprite_84E3E80
// .global sprite_84E44CC
// .global sprite_84E4AAC
// .global sprite_84E4FC8
// .global sprite_84E55C8
// .global sprite_84E5C4C
// .global sprite_84E6244
// .global sprite_84E6804
// .global sprite_84E6EA4
// .global sprite_84E74E0
// .global sprite_84E7B00
// .global sprite_84E8120
// .global sprite_84E8800
// .global sprite_84E8E60
// .global sprite_84E9460
// .global sprite_84E9A18
// .global sprite_84EA01C
// .global sprite_84EA61C
// .global sprite_84EACDC
// .global sprite_84EB328
// .global mugshotMrFamous
// .global mugshotDrWily
// .global mugshotShuko
// .global sprite_84ECD24
// .global sprite_84ED4B4
// .global sprite_84EDA70
// .global sprite_84EE048
// .global sprite_84EE7FC
// .global sprite_84EEFDC
// .global sprite_84EF69C
// .global sprite_84EFB78
// .global sprite_84F0094
// .global sprite_84F070C
// .global sprite_84F0CC4
// .global sprite_84F13D0
// .global mugshotMegaMan
// .global sprite_84F223C
// .global sprite_84F2908
// .global sprite_84F3100
// .global sprite_84F362C
// .global sprite_84F3B08
// .global sprite_84F4324
// .global sprite_84F4868
// .global sprite_84F4DD4
// .global sprite_84F5340
// .global sprite_84F57A4
// .global sprite_84F5CE0
// .global sprite_84F6354
// .global sprite_84F68C0
// .global sprite_84F6F84
// .global sprite_84F75A8
// .global sprite_84F7C44
// .global sprite_84F81B0
// .global sprite_84F8754
// .global sprite_84F8E10
// .global sprite_84F9534
// .global sprite_84F9978
// .global sprite_84F9E48
// .global sprite_84FA28C
// .global sprite_84FA744
// .global mugshotBlack
// .global byte_84FAFCC
// .global byte_84FF308
// .global byte_84FF4AC
// .global dword_8500F1C
// .global byte_8503098
// .global byte_850323C
// .global byte_8503C90
// .global byte_85077F8
// .global byte_850799C
// .global byte_8509354
// .global byte_850C2C0
// .global byte_850C464
// .global byte_850E134
// .global byte_85105CC
// .global byte_8510770
// .global byte_8510D54
// .global byte_8511C40
// .global byte_8511DE4
// .global byte_85120AC
// .global byte_8515394
// .global byte_8515538
// .global byte_85162E0
// .global byte_8519D64
// .global byte_851A0AC
// .global byte_851ADB0
// .global byte_851AFB8
// .global byte_851BC60
// .global byte_851D8D4
// .global byte_851DA78
// .global byte_851EC08
// .global byte_851EDAC
// .global byte_852213C
// .global byte_85222E0
// .global byte_852360C
// .global byte_8526938
// .global byte_8526ADC
// .global byte_8527B88
// .global byte_852B5DC
// .global byte_852B924
// .global byte_852C560
// .global byte_852E5DC
// .global byte_852E780
// .global byte_852EFA0
// .global byte_852F144
// .global byte_85330DC
// .global byte_8533280
// .global byte_8535488
// .global byte_85387FC
// .global byte_85389A0
// .global byte_853A5F8
// .global byte_853DEC4
// .global byte_853E068
// .global byte_853FFD4
// .global byte_8542FC8
// .global byte_854316C
// .global byte_8545468
// .global byte_8547C24
// .global byte_8547DC8
// .global byte_85495B4
// .global byte_854D26C
// .global byte_854D410
// .global byte_8550B90
// .global byte_8552F78
// .global byte_855311C
// .global byte_8554160
// .global byte_8557210
// .global byte_85573B4
// .global byte_8558498
// .global byte_8559ECC
// .global byte_855A070
// .global byte_855B17C
// .global byte_855DBC0
// .global byte_855DD64
// .global byte_855EE14
// .global byte_85621EC
// .global byte_8562390
// .global byte_8564358
// .global byte_8566F74
// .global byte_8567118
// .global byte_8569DFC
// .global byte_856D0FC
// .global byte_856D2A0
// .global byte_856E4F8
// .global byte_8570BBC
// .global byte_8570D60
// .global byte_8572DEC
// .global byte_8576500
// .global byte_85766A4
// .global byte_8579340
// .global byte_857B5E4
// .global byte_857B788

	.include "data/dat38_60.inc"
// .global byte_857D8D0
// .global byte_8580D64
// .global dword_8580F08
// .global byte_8582308
// .global byte_8585ED0
// .global byte_8586074
// .global byte_85878F4
// .global byte_858AAE0
// .global byte_858AC84
// .global byte_858CDA4
// .global byte_858E380
// .global byte_858E524
// .global dword_858F110
// .global off_8592304
// .global dword_85924A8
// .global dword_8594D80
// .global dword_8598328
// .global byte_859B428
// .global byte_859B5CC
// .global dword_859E9D0
// .global byte_85A2198
// .global byte_85A5590
// .global byte_85A8B04
// .global byte_85A8CA8
// .global byte_85ABE34
// .global dword_85AEFA8
// .global dword_85B22DC
// .global off_85B5D28
// .global dword_85B5ECC
// .global dword_85B86C8
// .global dword_85BB3D0
// .global byte_85BE350
// .global dword_85C18E0
// .global byte_85C4750
// .global dword_85C7AA0
// .global dword_85CB0A8
// .global off_85CD6B4
// .global dword_85CD858
// .global off_85D0894
// .global off_85D183C
// .global dword_85D19E0
// .global off_85D2850
// .global off_85D29F4
// .global off_85D2B98
// .global off_85D2D3C
// .global off_85D2EE0
// .global off_85D35B8
// .global dword_85D375C
// .global off_85D430C
// .global dword_85D44B0
// .global dword_85D4E48
// .global off_85D895C
// .global dword_85D8B00
// .global dword_85DB160
// .global off_85DDB74
// .global dword_85DDD18
// .global off_85E0670
// .global dword_85E0814
// .global dword_85E2F90
// .global dword_85E519C
// .global off_85E79D0
// .global dword_85E7B74
// .global off_85EAD2C
// .global dword_85EAED0
// .global off_85EE2A4
// .global dword_85EE448
// .global dword_85F1B20
// .global off_85F4D84
// .global dword_85F4F28
// .global dword_85F7C58
// .global off_85FB848
// .global dword_85FB9EC
// .global dword_85FEF08
// .global off_8602590
// .global dword_8602734
// .global dword_8606438
// .global dword_8609770
// .global off_860D678
// .global dword_860DDD0
// .global byte_8619BD0
// .global byte_861AD84
// .global byte_861B31C
// .global byte_861B338
// .global byte_861C770
// .global byte_861CC50
// .global byte_861CEE8
// .global byte_861D05C
// .global byte_861D4D8
// .global dword_861E06C
// .global dword_861E6D4
// .global dword_861F710
// .global dword_8620350
// .global dword_8620A9C
// .global dword_8620E58
// .global byte_8622CFC
// .global byte_86246F0
// .global byte_8625B10
// .global byte_8627DF8
// .global byte_8628968
// .global byte_862AB08
// .global dword_862B6E0
// .global dword_862C160
// .global dword_862C978
// .global dword_862D0A0
// .global dword_862E15C
// .global dword_863168C
// .global dword_8632288
// .global dword_8633084
// .global dword_8634E64
// .global dword_8635EB4
// .global dword_8636A7C
// .global dword_86376B4
// .global dword_8638E70
// .global dword_863951C
// .global dword_863B234
// .global dword_863D1A4
// .global dword_863F830
// .global dword_8642B34
// .global dword_86460FC
// .global dword_86475CC
// .global dword_8648BA8
// .global dword_864A484
// .global dword_864D860
// .global dword_8651B2C
// .global dword_8656C0C
// .global dword_865A08C
// .global dword_865B77C
// .global dword_8660604
// .global byte_866296C
// .global byte_866446C
// .global dword_8664988
// .global dword_8664F04
// .global dword_8665548
// .global dword_8667820
// .global dword_866B038
// .global byte_866D090
// .global byte_8671A74
// .global byte_8673418
// .global byte_8675094
// .global byte_8678F4C
// .global byte_867D85C
// .global byte_8680690
// .global byte_868316C
// .global byte_8687DCC
// .global byte_868CB78
// .global byte_868EBA0
// .global byte_8691154
// .global byte_8694FB4

	.include "data/dat38_70.inc"
// .global sprite_86CBB7C
// .global sprite_86CC13C
// .global sprite_86CD410

	.include "data/dat38_87.inc"
// .global sprite_87DC190
// .global sprite_87DC5F0
// .global byte_87DD248
// .global sprite_87DDB7C
// .global sprite_87E069C
// .global sprite_87E0854
// .global sprite_87E0E44
// .global sprite_87E1894
// .global sprite_87E1AD4
// .global sprite_87E1D84
// .global sprite_87E24F4
// .global sprite_87E2860

	.include "data/dat38_92.inc"
// .global sprite_87E6E20


/* Undeclared Symbols */
// .global battleSpriteMegaMan
// .global battleSpriteFlameCross
// .global battleSpriteElecCross
// .global battleSpriteSlashCross
// .global battleSprite_81FA9E8
// .global battleSprite_8204108
// .global battleSprite_820CD4C
// .global battleSprite_8214808
// .global battleSprite_821C354
// .global battleSprite_8223C48
// .global battleSprite_822CC50
// .global battleSprite_8233728
// .global battleSprite_823B768
// .global compVirusBattleSpriteMetteur
// .global compVirusBattleSprite_8242E94
// .global virusBattleSprite_8244164
// .global compVirusBattleSprite_82455B0
// .global virusBattleSprite_8246A24
// .global compVirusBattleSprite_82489C8
// .global compVirusBattleSprite_82492FC
// .global compVirusBattleSprite_8249C7C
// .global virusBattleSprite_824AC94
// .global virusBattleSprite_824B254
// .global compVirusBattleSprite_824D23C
// .global compVirusBattleSprite_824DC7C
// .global virusBattleSprite_824EAF4
// .global compVirusBattleSprite_8252558
// .global sprite_82533F4
// .global sprite_8253F88
// .global comp_8257994
// .global comp_825859C
// .global comp_8258FF8
// .global comp_825A0D8
// .global comp_825AD90
// .global comp_825B860
// .global comp_825BFC4
// .global sprite_825C9AC
// .global comp_825DFB4
// .global sprite_825F2C8
// .global sprite_8260F88
// .global comp_8262CEC
// .global comp_8263484
// .global comp_82647E4
// .global battleSpriteFlameMan
// .global battleSpriteElecMan
// .global battleSpriteSlashMan
// .global sprite_828324C
// .global sprite_828F18C
// .global battleSpriteSpoutMan
// .global sprite_829D818
// .global sprite_82A5AF0
// .global sprite_82B0690
// .global sprite_82BA7BC
// .global battleSpriteProtoMan
// .global comp_82CED74
// .global comp_82D2AC8
// .global comp_82D6FE4
// .global compSprite_82DABC8
// .global comp_82DD9A8
// .global compBattleSprite_Colonel
// .global comp_82E4050
// .global comp_82E8470
// .global sprite_82EFE48
// .global sprite_82F39C0
// .global sprite_82F569C
// .global sprite_82F6ECC
// .global sprite_82F9CCC
// .global comp_82FCA14
// .global sprite_82FE378
// .global sprite_82FE704
// .global sprite_82FF95C
// .global sprite_8300CFC
// .global sprite_8300F70
// .global sprite_8303A34
// .global sprite_830451C
// .global sprite_8304700
// .global sprite_8308700
// .global sprite_830902C
// .global sprite_830A308
// .global sprite_830D494
// .global sprite_830E44C
// .global sprite_830F144
// .global sprite_8311288
// .global sprite_83124E8
// .global sprite_8312FB4
// .global sprite_83138C4
// .global sprite_831530C
// .global sprite_831661C
// .global sprite_8317340
// .global sprite_8318920
// .global sprite_83195F0
// .global sprite_8319B5C
// .global sprite_831C8A4
// .global sprite_831CAF8
// .global sprite_831E67C
// .global sprite_831E8C0
// .global sprite_831EA40
// .global sprite_831FA84
// .global sprite_831FCF0
// .global sprite_832154C
// .global sprite_8322920
// .global sprite_83234D4
// .global sprite_8323728
// .global sprite_83241F4
// .global sprite_83245E8
// .global sprite_83249B0
// .global sprite_8324E14
// .global sprite_8325038
// .global sprite_83255C0
// .global sprite_8325C94
// .global sprite_8325EF4
// .global sprite_83262C0
// .global sprite_8326724
// .global sprite_83279C0
// .global sprite_8329D28
// .global sprite_832C418
// .global sprite_832E9C8
// .global sprite_832F0C8
// .global sprite_832F8C8
// .global sprite_8330A30
// .global sprite_8330FA8
// .global sprite_83317F0
// .global sprite_83322B8
// .global sprite_8332484
// .global sprite_8333350
// .global comp_8333CC8
// .global comp_8334B0C
// .global comp_83353F4
// .global comp_8338170
// .global comp_834FC40
// .global comp_838B160
// .global comp_838B438
// .global comp_83FDF7C
// .global comp_840A4BC
// .global compNpcSpriteMrFamous
// .global comp_840F4F4
// .global comp_84105EC
// .global comp_8410A18
// .global comp_84114E8
// .global comp_84119D0
// .global compNpcSpriteRoll
// .global compNpcSpriteGutsMan
// .global compNpcSpriteGlyde
// .global comp_8495434
// .global comp_8499CF0
// .global comp_849AAD0
// .global comp_84A03B8
// .global comp_84A0920
// .global comp_84A0DCC
// .global comp_84A1458
// .global comp_84A1B14
// .global comp_84A1E30
// .global comp_84A225C
// .global comp_84A24CC
// .global comp_84A3708
// .global comp_84A3B44
// .global comp_84A3E08
// .global comp_84A40E0
// .global comp_84A47F0
// .global comp_84A4F0C
// .global comp_84A502C
// .global comp_84A642C
// .global comp_84A6D14
// .global comp_84A71A0
// .global comp_84A74A4
// .global comp_84A77A4
// .global comp_84A7A14
// .global comp_84A7FA4
// .global comp_84A8524
// .global comp_84A8F68
// .global comp_84A914C
// .global comp_84A96B8
// .global comp_84AA028
// .global comp_84AA640
// .global comp_84AAC80
// .global comp_84AAE70
// .global comp_84AAF18
// .global comp_84AE340
// .global comp_84B42EC
// .global comp_84B5734
// .global comp_84B6744
// .global comp_84BADF8
// .global comp_84BB07C
// .global comp_84BB704
// .global comp_84BBA74
// .global comp_84BC4D0
// .global comp_84BD3FC
// .global comp_84BD83C
// .global comp_84BE924
// .global comp_84BECDC
// .global comp_84BEF4C
// .global comp_84BF174
// .global comp_84C0150
// .global comp_84C3C90
// .global comp_84C3F54
// .global comp_84C43AC
// .global comp_84C8DEC
// .global comp_84CA1BC
// .global comp_84CA74C
// .global comp_84CA9E8
// .global comp_84CAD70
// .global comp_84CB0F4
// .global comp_84CB3A8
// .global comp_84CB638
// .global comp_84CB930
// .global comp_84CBC1C
// .global comp_84CBDE8
// .global comp_84CC308
// .global comp_84CC8AC
// .global comp_84CD83C
// .global comp_84CDCE8
// .global comp_84CDE24
// .global comp_84CF9D8
// .global comp_84CFC7C
// .global comp_84D014C
// .global comp_84D230C
// .global comp_84D26BC
// .global comp_84D2820
// .global comp_84D2A54
// .global comp_84D3998
// .global comp_84D4AC4
// .global comp_84D4CC8
// .global comp_84D4FF0
// .global comp_84D5764
// .global comp_84D5C94
// .global comp_84D5DF0
// .global comp_84D6370
// .global comp_84D66B8
// .global comp_84D6908
// .global comp_84D6BF0
// .global comp_84D6E50
// .global comp_84D701C
// .global comp_84D77D8
// .global comp_84D84E4
// .global comp_84D9344
// .global comp_84D9954
// .global comp_84DA604
// .global comp_84DAD14
// .global comp_84DB04C
// .global comp_84DB1CC
// .global comp_84DB8F8
// .global comp_84DBD30
// .global comp_84DC2B0
// .global comp_84DCBD8
// .global comp_84DD20C
// .global comp_84DD40C
// .global comp_84DDDB8
// .global comp_84DDF94
// .global comp_84DE328
// .global comp_84DE598
// .global comp_84DE728
// .global comp_84DEFD8
// .global comp_84DF674
// .global comp_84E00A0
// .global spriteWhiteDot
// .global compSpriteWhiteDot_84E0C4C
// .global comp_86C33B4
// .global comp_86C6B30
// .global comp_86C6FD0
// .global comp_86C73D8
// .global comp_86C7764
// .global comp_86C7980
// .global comp_86CDEA8
// .global comp_86CE51C
// .global comp_86CEAA8
// .global comp_86CEC3C
// .global comp_86CFD1C
// .global comp_86D471C
// .global comp_86D497C
// .global comp_86D4FC4
// .global comp_86D5070
// .global comp_86D5224
// .global comp_86D54F4
// .global comp_86D8C80
// .global comp_86D91FC
// .global comp_86D93E0
// .global comp_86D9C40
// .global comp_86D9D10
// .global comp_86DB208
// .global comp_86DB9C4
// .global comp_86DBB0C
// .global comp_86DC518
// .global comp_86DC688
// .global comp_86DCCF0
// .global comp_86DD328
// .global comp_87F0664
// .global comp_87F0834

	.endif // INC_DATA_SPRITEPOINTERS_8031CC4
