// Memory map for fixed data/structs in the 0x2000000 EWRAM region.
//
// The struct types referenced here live under
// constants/headers/structs/, generated by
// tools/struct_inc_to_h.py from include/structs/*.inc. Symbols whose
// underlying type isn't yet defined as a struct fall back to
// `void *` / `u8 *` / `u32 *` — refine those incrementally.
#ifndef EWRAM_H
#define EWRAM_H

#include "types.h"

#include "structs/Toolkit.h"
#include "structs/GameState.h"
#include "structs/Camera.h"
#include "structs/Chatbox.h"
#include "structs/CutsceneState.h"
#include "structs/Joypad.h"
#include "structs/NaviStats.h"
#include "structs/RenderInfo.h"
#include "structs/S2001c04.h"
#include "structs/ScreenFade.h"
#include "structs/StartScreen.h"
#include "structs/SubMenu.h"
#include "structs/ReqBBS2001150.h"
#include "structs/ReqBBSGui.h"
#include "structs/ObjectHeader.h"
#include "structs/OWPlayerObject.h"

// Untyped — generic byte/word pointers until the corresponding struct
// landing pages exist. Promote to a typed pointer once the relevant
// .inc / .h is in place.
#define timer_2000000               ((u32 *)            0x02000000)
#define reqBBS_requestEntries_list  ((u8 *)             0x02000290)
#define eReqBBS2001150              ((ReqBBS2001150 *)  0x02001150)
#define eGameState                  ((GameState *)      0x02001B80)
#define sReqBBS_GUI                 ((ReqBBSGui *)      0x02005780)
#define npc_2005F48                 ((u8 *)             0x02005F48)
#define reqBBS_num_requests_sent    ((u8 *)             0x020065B0)

// Toolkit lives at 0x20093B0 and is canonically held in r10 in ASM.
// From C, `eToolkit->GameStatePtr` is equivalent to what ASM does as
// `ldr r3, [r10, #oToolkit_GameStatePtr]`.
#define eToolkit                    ((Toolkit *)        0x020093B0)
#define eCamera                     ((Camera *)         0x02009980)
#define sSubmenu                    ((SubMenu *)        0x02009A30)
#define eChatbox                    ((Chatbox *)        0x02009CD0)

#define pCoords                     ((u32 *)            0x02009F60)
#define iCurrFrame                  ((u16 *)            0x0200A210)
#define eJoypad                     ((Joypad *)         0x0200A270)
#define i_joGameSubsysSel           ((u8 *)             0x0200A480)
#define eStartScreen                ((StartScreen *)    0x0200AD10)

#define reqBBS_tile_data            ((u8 *)             0x02018204)
#define reqBBS_eRequestEntriesIDs   ((u8 *)             0x02023A00)
#define reqBBS_requestNames_textualData  ((u8 *)        0x02025A04)
#define reqBBS_requestInfo_textOffsets   ((u8 *)        0x02029A04)
#define reqBBS_dialog_list          ((u16 *)            0x02033A04)

#define eBattleState                ((BattleState *)    0x02034880)
#define eT1BattleObject0            ((u8 *)             0x0203A9B0)
#define eBattleObject1              ((u8 *)             0x0203AA88)
#define eBattleObject2              ((u8 *)             0x0203AB60)
#define eBattleObject3              ((u8 *)             0x0203AC38)

#endif // EWRAM_H
