// eEventFlags
	// huge buffer of flags
	// bit position is reversed for continuity

		// [0x2E3] = 0x2001f6b


		enum_start 0x0 // 0x0
	enum EVENT_0
	enum EVENT_1
	enum EVENT_2
	enum EVENT_3
	enum EVENT_4
	enum EVENT_5
	enum EVENT_6
	enum EVENT_7

		enum_start 0x8 // 0x1
	enum EVENT_8
	enum EVENT_9
	enum EVENT_A
	enum EVENT_B
	enum EVENT_C
	enum EVENT_D
	enum EVENT_E
	enum EVENT_F

		enum_start 0x10 // 0x2
	enum EVENT_10
	enum EVENT_11
	enum EVENT_12
	enum EVENT_13
	enum EVENT_14
	enum EVENT_15
	enum EVENT_16
	enum EVENT_17

		enum_start 0x18 // 0x3
	enum EVENT_18
	enum EVENT_19
	enum EVENT_1A
	enum EVENT_1B
	enum EVENT_1C
	enum EVENT_1D
	enum EVENT_1E
	enum EVENT_1F

		enum_start 0x20 // 0x4
	enum EVENT_20
	enum EVENT_21
	enum EVENT_22
	enum EVENT_23
	enum EVENT_24
	enum EVENT_25
	enum EVENT_26
	enum EVENT_27

		enum_start 0x28 // 0x5
	enum EVENT_28
	enum EVENT_29
	enum EVENT_2A
	enum EVENT_2B
	enum EVENT_2C
	enum EVENT_2D
	enum EVENT_2E
	enum EVENT_2F

		enum_start 0x30 // 0x6
	enum EVENT_30
	enum EVENT_31
	enum EVENT_32
	enum EVENT_33
	enum EVENT_34
	enum EVENT_35
	enum EVENT_36
	enum EVENT_37

		enum_start 0x38 // 0x7
	enum EVENT_38
	enum EVENT_39
	enum EVENT_3A
	enum EVENT_3B
	enum EVENT_3C
	enum EVENT_3D
	enum EVENT_3E
	enum EVENT_3F

		enum_start 0x40 // 0x8
	enum EVENT_40
	enum EVENT_41
	enum EVENT_42
	enum EVENT_43
	enum EVENT_44
	enum EVENT_45
	enum EVENT_46
	enum EVENT_47

		enum_start 0x48 // 0x9
	enum EVENT_48
	enum EVENT_49
	enum EVENT_4A
	enum EVENT_4B
	enum EVENT_4C
	enum EVENT_4D
	enum EVENT_4E
	enum EVENT_4F

		enum_start 0x50 // 0xA
	enum EVENT_50
	enum EVENT_51
	enum EVENT_52
	enum EVENT_53
	enum EVENT_54
	enum EVENT_55
	enum EVENT_56
	enum EVENT_57

		enum_start 0x58 // 0xB
	enum EVENT_58
	enum EVENT_59
	enum EVENT_5A
	enum EVENT_5B
	enum EVENT_5C
	enum EVENT_5D
	enum EVENT_5E
	enum EVENT_5F

		enum_start 0x60 // 0xC
	enum EVENT_60
	enum EVENT_61
	enum EVENT_62
	enum EVENT_63
	enum EVENT_64
	enum EVENT_65
	enum EVENT_66
	enum EVENT_67

		enum_start 0x68 // 0xD
	enum EVENT_68
	enum EVENT_69
	enum EVENT_6A
	enum EVENT_6B
	enum EVENT_6C
	enum EVENT_6D
	enum EVENT_6E
	enum EVENT_6F

		enum_start 0x70 // 0xE
	enum EVENT_70
	enum EVENT_71
	enum EVENT_72
	enum EVENT_73
	enum EVENT_74
	enum EVENT_75
	enum EVENT_76
	enum EVENT_77

		enum_start 0x78 // 0xF
	enum EVENT_78
	enum EVENT_79
	enum EVENT_7A
	enum EVENT_7B
	enum EVENT_7C
	enum EVENT_7D
	enum EVENT_7E
	enum EVENT_7F

		enum_start 0x80 // 0x10
	enum EVENT_80
	enum EVENT_81
	enum EVENT_82
	enum EVENT_83
	enum EVENT_84
	enum EVENT_85
	enum EVENT_86
	enum EVENT_87

		enum_start 0x88 // 0x11
	enum EVENT_88
	enum EVENT_89
	enum EVENT_8A
	enum EVENT_8B
	enum EVENT_8C
	enum EVENT_8D
	enum EVENT_8E
	enum EVENT_8F

		enum_start 0x90 // 0x12
	enum EVENT_90
	enum EVENT_91
	enum EVENT_92
	enum EVENT_93
	enum EVENT_94
	enum EVENT_95
	enum EVENT_96
	enum EVENT_97

		enum_start 0x98 // 0x13
	enum EVENT_98
	enum EVENT_99
	enum EVENT_9A
	enum EVENT_9B
	enum EVENT_9C
	enum EVENT_9D
	enum EVENT_9E
	enum EVENT_9F

		enum_start 0xa0 // 0x14
	enum EVENT_A0
	enum EVENT_A1
	enum EVENT_A2
	enum EVENT_A3
	enum EVENT_A4
	enum EVENT_A5
	enum EVENT_A6
	enum EVENT_A7

		enum_start 0xa8 // 0x15
	enum EVENT_A8
	enum EVENT_A9
	enum EVENT_AA
	enum EVENT_AB
	enum EVENT_AC
	enum EVENT_AD
	enum EVENT_AE
	enum EVENT_AF

		enum_start 0xb0 // 0x16
	enum EVENT_B0
	enum EVENT_B1
	enum EVENT_B2
	enum EVENT_B3
	enum EVENT_B4
	enum EVENT_B5
	enum EVENT_B6
	enum EVENT_B7

		enum_start 0xb8 // 0x17
	enum EVENT_B8
	enum EVENT_B9
	enum EVENT_BA
	enum EVENT_BB
	enum EVENT_BC
	enum EVENT_BD
	enum EVENT_BE
	enum EVENT_BF

		enum_start 0xc0 // 0x18
	enum EVENT_C0
	enum EVENT_C1
	enum EVENT_C2
	enum EVENT_C3
	enum EVENT_C4
	enum EVENT_C5
	enum EVENT_C6
	enum EVENT_C7

		enum_start 0xc8 // 0x19
	enum EVENT_C8
	enum EVENT_C9
	enum EVENT_CA
	enum EVENT_CB
	enum EVENT_CC
	enum EVENT_CD
	enum EVENT_CE
	enum EVENT_CF

		enum_start 0xd0 // 0x1A
	enum EVENT_D0
	enum EVENT_D1
	enum EVENT_D2
	enum EVENT_D3
	enum EVENT_D4
	enum EVENT_D5
	enum EVENT_D6
	enum EVENT_D7

		enum_start 0xd8 // 0x1B
	enum EVENT_D8
	enum EVENT_D9
	enum EVENT_DA
	enum EVENT_DB
	enum EVENT_DC
	enum EVENT_DD
	enum EVENT_DE
	enum EVENT_DF

		enum_start 0xe0 // 0x1C
	enum EVENT_E0
	enum EVENT_E1
	enum EVENT_E2
	enum EVENT_E3
	enum EVENT_E4
	enum EVENT_E5
	enum EVENT_E6
	enum EVENT_E7

		enum_start 0xe8 // 0x1D
	enum EVENT_E8
	enum EVENT_E9
	enum EVENT_EA
	enum EVENT_EB
	enum EVENT_EC
	enum EVENT_ED
	enum EVENT_EE
	enum EVENT_EF

		enum_start 0xf0 // 0x1E
	enum EVENT_F0
	enum EVENT_F1
	enum EVENT_F2
	enum EVENT_F3
	enum EVENT_F4
	enum EVENT_F5
	enum EVENT_F6
	enum EVENT_F7

		enum_start 0xf8 // 0x1F
	enum EVENT_F8
	enum EVENT_F9
	enum EVENT_FA
	enum EVENT_FB
	enum EVENT_FC
	enum EVENT_FD
	enum EVENT_FE
	enum EVENT_FF

		enum_start 0x100 // 0x20
	enum EVENT_100
	enum EVENT_101
	enum EVENT_102
	enum EVENT_103
	enum EVENT_104
	enum EVENT_105
	enum EVENT_106
	enum EVENT_107

		enum_start 0x108 // 0x21
	enum EVENT_108
	enum EVENT_109
	enum EVENT_10A
	enum EVENT_10B
	enum EVENT_10C
	enum EVENT_10D
	enum EVENT_10E
	enum EVENT_10F

		enum_start 0x110 // 0x22
	enum EVENT_110
	enum EVENT_111
	enum EVENT_112
	enum EVENT_113
	enum EVENT_114
	enum EVENT_115
	enum EVENT_116
	enum EVENT_117

		enum_start 0x118 // 0x23
	enum EVENT_118
	enum EVENT_119
	enum EVENT_11A
	enum EVENT_11B
	enum EVENT_11C
	enum EVENT_11D
	enum EVENT_11E
	enum EVENT_11F

		enum_start 0x120 // 0x24
	enum EVENT_120
	enum EVENT_121
	enum EVENT_122
	enum EVENT_123
	enum EVENT_124
	enum EVENT_125
	enum EVENT_126
	enum EVENT_127

		enum_start 0x128 // 0x25
	enum EVENT_128
	enum EVENT_129
	enum EVENT_12A
	enum EVENT_12B
	enum EVENT_12C
	enum EVENT_12D
	enum EVENT_12E
	enum EVENT_12F

		enum_start 0x130 // 0x26
	enum EVENT_130
	enum EVENT_131
	enum EVENT_132
	enum EVENT_133
	enum EVENT_134
	enum EVENT_135
	enum EVENT_136
	enum EVENT_137

		enum_start 0x138 // 0x27
	enum EVENT_138
	enum EVENT_139
	enum EVENT_13A
	enum EVENT_13B
	enum EVENT_13C
	enum EVENT_13D
	enum EVENT_13E
	enum EVENT_13F

		enum_start 0x140 // 0x28
	enum EVENT_140
	enum EVENT_141
	enum EVENT_142
	enum EVENT_143
	enum EVENT_144
	enum EVENT_145
	enum EVENT_146
	enum EVENT_147

		enum_start 0x148 // 0x29
	enum EVENT_148
	enum EVENT_149
	enum EVENT_14A
	enum EVENT_14B
	enum EVENT_14C
	enum EVENT_14D
	enum EVENT_14E
	enum EVENT_14F

		enum_start 0x150 // 0x2A
	enum EVENT_150
	enum EVENT_151
	enum EVENT_152
	enum EVENT_153
	enum EVENT_154
	enum EVENT_155
	enum EVENT_156
	enum EVENT_157

		enum_start 0x158 // 0x2B
	enum EVENT_158
	enum EVENT_159
	enum EVENT_15A
	enum EVENT_15B
	enum EVENT_15C
	enum EVENT_15D
	enum EVENT_15E
	enum EVENT_15F

		enum_start 0x160 // 0x2C
	enum EVENT_160
	enum EVENT_161
	enum EVENT_162
	enum EVENT_163
	enum EVENT_164
	enum EVENT_165
	enum EVENT_166
	enum EVENT_167

		enum_start 0x168 // 0x2D
	enum EVENT_168
	enum EVENT_169
	enum EVENT_16A
	enum EVENT_16B
	enum EVENT_16C
	enum EVENT_16D
	enum EVENT_16E
	enum EVENT_16F

		enum_start 0x170 // 0x2E
	enum EVENT_170
	enum EVENT_171
	enum EVENT_172
	enum EVENT_173
	enum EVENT_174
	enum EVENT_175
	enum EVENT_176
	enum EVENT_177

		enum_start 0x178 // 0x2F
	enum EVENT_178
	enum EVENT_179
	enum EVENT_17A
	enum EVENT_17B
	enum EVENT_17C
	enum EVENT_17D
	enum EVENT_17E
	enum EVENT_17F

		enum_start 0x180 // 0x30
	enum EVENT_180
	enum EVENT_181
	enum EVENT_182
	enum EVENT_183
	enum EVENT_184
	enum EVENT_185
	enum EVENT_186
	enum EVENT_187

		enum_start 0x188 // 0x31
	enum EVENT_188
	enum EVENT_189
	enum EVENT_18A
	enum EVENT_18B
	enum EVENT_18C
	enum EVENT_18D
	enum EVENT_18E
	enum EVENT_18F

		enum_start 0x190 // 0x32
	enum EVENT_190
	enum EVENT_191
	enum EVENT_192
	enum EVENT_193
	enum EVENT_194
	enum EVENT_195
	enum EVENT_196
	enum EVENT_197

		enum_start 0x198 // 0x33
	enum EVENT_198
	enum EVENT_199
	enum EVENT_19A
	enum EVENT_19B
	enum EVENT_19C
	enum EVENT_19D
	enum EVENT_19E
	enum EVENT_19F

		enum_start 0x1a0 // 0x34
	enum EVENT_1A0
	enum EVENT_1A1
	enum EVENT_1A2
	enum EVENT_1A3
	enum EVENT_1A4
	enum EVENT_1A5
	enum EVENT_1A6
	enum EVENT_1A7

		enum_start 0x1a8 // 0x35
	enum EVENT_1A8
	enum EVENT_1A9
	enum EVENT_1AA
	enum EVENT_1AB
	enum EVENT_1AC
	enum EVENT_1AD
	enum EVENT_1AE
	enum EVENT_1AF

		enum_start 0x1b0 // 0x36
	enum EVENT_1B0
	enum EVENT_1B1
	enum EVENT_1B2
	enum EVENT_1B3
	enum EVENT_1B4
	enum EVENT_1B5
	enum EVENT_1B6
	enum EVENT_1B7

		enum_start 0x1b8 // 0x37
	enum EVENT_1B8
	enum EVENT_1B9
	enum EVENT_1BA
	enum EVENT_1BB
	enum EVENT_1BC
	enum EVENT_1BD
	enum EVENT_1BE
	enum EVENT_1BF

		enum_start 0x1c0 // 0x38
	enum EVENT_1C0
	enum EVENT_1C1
	enum EVENT_1C2
	enum EVENT_1C3
	enum EVENT_1C4
	enum EVENT_1C5
	enum EVENT_1C6
	enum EVENT_1C7

		enum_start 0x1c8 // 0x39
	enum EVENT_1C8
	enum EVENT_1C9
	enum EVENT_1CA
	enum EVENT_1CB
	enum EVENT_1CC
	enum EVENT_1CD
	enum EVENT_1CE
	enum EVENT_1CF

		enum_start 0x1d0 // 0x3A
	enum EVENT_1D0
	enum EVENT_1D1
	enum EVENT_1D2
	enum EVENT_1D3
	enum EVENT_1D4
	enum EVENT_1D5
	enum EVENT_1D6
	enum EVENT_1D7

		enum_start 0x1d8 // 0x3B
	enum EVENT_1D8
	enum EVENT_1D9
	enum EVENT_1DA
	enum EVENT_1DB
	enum EVENT_1DC
	enum EVENT_1DD
	enum EVENT_1DE
	enum EVENT_1DF

		enum_start 0x1e0 // 0x3C
	enum EVENT_1E0
	enum EVENT_1E1
	enum EVENT_1E2
	enum EVENT_1E3
	enum EVENT_1E4
	enum EVENT_1E5
	enum EVENT_1E6
	enum EVENT_1E7

		enum_start 0x1e8 // 0x3D
	enum EVENT_1E8
	enum EVENT_1E9
	enum EVENT_1EA
	enum EVENT_1EB
	enum EVENT_1EC
	enum EVENT_1ED
	enum EVENT_1EE
	enum EVENT_1EF

		enum_start 0x1f0 // 0x3E
	enum EVENT_1F0
	enum EVENT_1F1
	enum EVENT_1F2
	enum EVENT_1F3
	enum EVENT_1F4
	enum EVENT_1F5
	enum EVENT_1F6
	enum EVENT_1F7

		enum_start 0x1f8 // 0x3F
	enum EVENT_1F8
	enum EVENT_1F9
	enum EVENT_1FA
	enum EVENT_1FB
	enum EVENT_1FC
	enum EVENT_1FD
	enum EVENT_1FE
	enum EVENT_1FF

		enum_start 0x200 // 0x40
	enum EVENT_200
	enum EVENT_201
	enum EVENT_202
	enum EVENT_203
	enum EVENT_204
	enum EVENT_205
	enum EVENT_206
	enum EVENT_207

		enum_start 0x208 // 0x41
	enum EVENT_208
	enum EVENT_209
	enum EVENT_20A
	enum EVENT_20B
	enum EVENT_20C
	enum EVENT_20D
	enum EVENT_20E
	enum EVENT_20F

		enum_start 0x210 // 0x42
	enum EVENT_210
	enum EVENT_211
	enum EVENT_212
	enum EVENT_213
	enum EVENT_214
	enum EVENT_215
	enum EVENT_216
	enum EVENT_217

		enum_start 0x218 // 0x43
	enum EVENT_218
	enum EVENT_219
	enum EVENT_21A
	enum EVENT_21B
	enum EVENT_21C
	enum EVENT_21D
	enum EVENT_21E
	enum EVENT_21F

		enum_start 0x220 // 0x44
	enum EVENT_220
	enum EVENT_221
	enum EVENT_222
	enum EVENT_223
	enum EVENT_224
	enum EVENT_225
	enum EVENT_226
	enum EVENT_227

		enum_start 0x228 // 0x45
	enum EVENT_228
	enum EVENT_229
	enum EVENT_22A
	enum EVENT_22B
	enum EVENT_22C
	enum EVENT_22D
	enum EVENT_22E
	enum EVENT_22F

		enum_start 0x230 // 0x46
	enum EVENT_230
	enum EVENT_231
	enum EVENT_232
	enum EVENT_233
	enum EVENT_234
	enum EVENT_235
	enum EVENT_236
	enum EVENT_237

		enum_start 0x238 // 0x47
	enum EVENT_238
	enum EVENT_239
	enum EVENT_23A
	enum EVENT_23B
	enum EVENT_23C
	enum EVENT_23D
	enum EVENT_23E
	enum EVENT_23F

		enum_start 0x240 // 0x48
	enum EVENT_240
	enum EVENT_241
	enum EVENT_242
	enum EVENT_243
	enum EVENT_244
	enum EVENT_245
	enum EVENT_246
	enum EVENT_247

		enum_start 0x248 // 0x49
	enum EVENT_248
	enum EVENT_249
	enum EVENT_24A
	enum EVENT_24B
	enum EVENT_24C
	enum EVENT_24D
	enum EVENT_24E
	enum EVENT_24F

		enum_start 0x250 // 0x4A
	enum EVENT_250
	enum EVENT_251
	enum EVENT_252
	enum EVENT_253
	enum EVENT_254
	enum EVENT_255
	enum EVENT_256
	enum EVENT_257

		enum_start 0x258 // 0x4B
	enum EVENT_258
	enum EVENT_259
	enum EVENT_25A
	enum EVENT_25B
	enum EVENT_25C
	enum EVENT_25D
	enum EVENT_25E
	enum EVENT_25F

		enum_start 0x260 // 0x4C
	enum EVENT_260
	enum EVENT_261
	enum EVENT_262
	enum EVENT_263
	enum EVENT_264
	enum EVENT_265
	enum EVENT_266
	enum EVENT_267

		enum_start 0x268 // 0x4D
	enum EVENT_268
	enum EVENT_269
	enum EVENT_26A
	enum EVENT_26B
	enum EVENT_26C
	enum EVENT_26D
	enum EVENT_26E
	enum EVENT_26F

		enum_start 0x270 // 0x4E
	enum EVENT_270
	enum EVENT_271
	enum EVENT_272
	enum EVENT_273
	enum EVENT_274
	enum EVENT_275
	enum EVENT_276
	enum EVENT_277

		enum_start 0x278 // 0x4F
	enum EVENT_278
	enum EVENT_279
	enum EVENT_27A
	enum EVENT_27B
	enum EVENT_27C
	enum EVENT_27D
	enum EVENT_27E
	enum EVENT_27F

		enum_start 0x280 // 0x50
	enum EVENT_280
	enum EVENT_281
	enum EVENT_282
	enum EVENT_283
	enum EVENT_284
	enum EVENT_285
	enum EVENT_286
	enum EVENT_287

		enum_start 0x288 // 0x51
	enum EVENT_288
	enum EVENT_289
	enum EVENT_28A
	enum EVENT_28B
	enum EVENT_28C
	enum EVENT_28D
	enum EVENT_28E
	enum EVENT_28F

		enum_start 0x290 // 0x52
	enum EVENT_290
	enum EVENT_291
	enum EVENT_292
	enum EVENT_293
	enum EVENT_294
	enum EVENT_295
	enum EVENT_296
	enum EVENT_297

		enum_start 0x298 // 0x53
	enum EVENT_298
	enum EVENT_299
	enum EVENT_29A
	enum EVENT_29B
	enum EVENT_29C
	enum EVENT_29D
	enum EVENT_29E
	enum EVENT_29F

		enum_start 0x2a0 // 0x54
	enum EVENT_2A0
	enum EVENT_2A1
	enum EVENT_2A2
	enum EVENT_2A3
	enum EVENT_2A4
	enum EVENT_2A5
	enum EVENT_2A6
	enum EVENT_2A7

		enum_start 0x2a8 // 0x55
	enum EVENT_2A8
	enum EVENT_2A9
	enum EVENT_2AA
	enum EVENT_2AB
	enum EVENT_2AC
	enum EVENT_2AD
	enum EVENT_2AE
	enum EVENT_2AF

		enum_start 0x2b0 // 0x56
	enum EVENT_2B0
	enum EVENT_2B1
	enum EVENT_2B2
	enum EVENT_2B3
	enum EVENT_2B4
	enum EVENT_2B5
	enum EVENT_2B6
	enum EVENT_2B7

		enum_start 0x2b8 // 0x57
	enum EVENT_2B8
	enum EVENT_2B9
	enum EVENT_2BA
	enum EVENT_2BB
	enum EVENT_2BC
	enum EVENT_2BD
	enum EVENT_2BE
	enum EVENT_2BF

		enum_start 0x2c0 // 0x58
	enum EVENT_2C0
	enum EVENT_2C1
	enum EVENT_2C2
	enum EVENT_2C3
	enum EVENT_2C4
	enum EVENT_2C5
	enum EVENT_2C6
	enum EVENT_2C7

		enum_start 0x2c8 // 0x59
	enum EVENT_2C8
	enum EVENT_2C9
	enum EVENT_2CA
	enum EVENT_2CB
	enum EVENT_2CC
	enum EVENT_2CD
	enum EVENT_2CE
	enum EVENT_2CF

		enum_start 0x2d0 // 0x5A
	enum EVENT_2D0
	enum EVENT_2D1
	enum EVENT_2D2
	enum EVENT_2D3
	enum EVENT_2D4
	enum EVENT_2D5
	enum EVENT_2D6
	enum EVENT_2D7

		enum_start 0x2d8 // 0x5B
	enum EVENT_2D8
	enum EVENT_2D9
	enum EVENT_2DA
	enum EVENT_2DB
	enum EVENT_2DC
	enum EVENT_2DD
	enum EVENT_2DE
	enum EVENT_2DF

		enum_start 0x2e0 // 0x5C
	enum EVENT_2E0
	enum EVENT_2E1
	enum EVENT_2E2
	enum EVENT_2E3
	enum EVENT_2E4
	enum EVENT_2E5
	enum EVENT_2E6
	enum EVENT_2E7

		enum_start 0x2e8 // 0x5D
	enum EVENT_2E8
	enum EVENT_2E9
	enum EVENT_2EA
	enum EVENT_2EB
	enum EVENT_2EC
	enum EVENT_2ED
	enum EVENT_2EE
	enum EVENT_2EF

		enum_start 0x2f0 // 0x5E
	enum EVENT_2F0
	enum EVENT_2F1
	enum EVENT_2F2
	enum EVENT_2F3
	enum EVENT_2F4
	enum EVENT_2F5
	enum EVENT_2F6
	enum EVENT_2F7

		enum_start 0x2f8 // 0x5F
	enum EVENT_2F8
	enum EVENT_2F9
	enum EVENT_2FA
	enum EVENT_2FB
	enum EVENT_2FC
	enum EVENT_2FD
	enum EVENT_2FE
	enum EVENT_2FF

		enum_start 0x300 // 0x60
	enum EVENT_300
	enum EVENT_301
	enum EVENT_302
	enum EVENT_303
	enum EVENT_304
	enum EVENT_305
	enum EVENT_306
	enum EVENT_307

		enum_start 0x308 // 0x61
	enum EVENT_308
	enum EVENT_309
	enum EVENT_30A
	enum EVENT_30B
	enum EVENT_30C
	enum EVENT_30D
	enum EVENT_30E
	enum EVENT_30F

		enum_start 0x310 // 0x62
	enum EVENT_310
	enum EVENT_311
	enum EVENT_312
	enum EVENT_313
	enum EVENT_314
	enum EVENT_315
	enum EVENT_316
	enum EVENT_317

		enum_start 0x318 // 0x63
	enum EVENT_318
	enum EVENT_319
	enum EVENT_31A
	enum EVENT_31B
	enum EVENT_31C
	enum EVENT_31D
	enum EVENT_31E
	enum EVENT_31F

		enum_start 0x320 // 0x64
	enum EVENT_320
	enum EVENT_321
	enum EVENT_322
	enum EVENT_323
	enum EVENT_324
	enum EVENT_325
	enum EVENT_326
	enum EVENT_327

		enum_start 0x328 // 0x65
	enum EVENT_328
	enum EVENT_329
	enum EVENT_32A
	enum EVENT_32B
	enum EVENT_32C
	enum EVENT_32D
	enum EVENT_32E
	enum EVENT_32F

		enum_start 0x330 // 0x66
	enum EVENT_330
	enum EVENT_331
	enum EVENT_332
	enum EVENT_333
	enum EVENT_334
	enum EVENT_335
	enum EVENT_336
	enum EVENT_337

		enum_start 0x338 // 0x67
	enum EVENT_338
	enum EVENT_339
	enum EVENT_33A
	enum EVENT_33B
	enum EVENT_33C
	enum EVENT_33D
	enum EVENT_33E
	enum EVENT_33F

		enum_start 0x340 // 0x68
	enum EVENT_340
	enum EVENT_341
	enum EVENT_342
	enum EVENT_343
	enum EVENT_344
	enum EVENT_345
	enum EVENT_346
	enum EVENT_347

		enum_start 0x348 // 0x69
	enum EVENT_348
	enum EVENT_349
	enum EVENT_34A
	enum EVENT_34B
	enum EVENT_34C
	enum EVENT_34D
	enum EVENT_34E
	enum EVENT_34F

		enum_start 0x350 // 0x6A
	enum EVENT_350
	enum EVENT_351
	enum EVENT_352
	enum EVENT_353
	enum EVENT_354
	enum EVENT_355
	enum EVENT_356
	enum EVENT_357

		enum_start 0x358 // 0x6B
	enum EVENT_358
	enum EVENT_359
	enum EVENT_35A
	enum EVENT_35B
	enum EVENT_35C
	enum EVENT_35D
	enum EVENT_35E
	enum EVENT_35F

		enum_start 0x360 // 0x6C
	enum EVENT_360
	enum EVENT_361
	enum EVENT_362
	enum EVENT_363
	enum EVENT_364
	enum EVENT_365
	enum EVENT_366
	enum EVENT_367

		enum_start 0x368 // 0x6D
	enum EVENT_368
	enum EVENT_369
	enum EVENT_36A
	enum EVENT_36B
	enum EVENT_36C
	enum EVENT_36D
	enum EVENT_36E
	enum EVENT_36F

		enum_start 0x370 // 0x6E
	enum EVENT_370
	enum EVENT_371
	enum EVENT_372
	enum EVENT_373
	enum EVENT_374
	enum EVENT_375
	enum EVENT_376
	enum EVENT_377

		enum_start 0x378 // 0x6F
	enum EVENT_378
	enum EVENT_379
	enum EVENT_37A
	enum EVENT_37B
	enum EVENT_37C
	enum EVENT_37D
	enum EVENT_37E
	enum EVENT_37F

		enum_start 0x380 // 0x70
	enum EVENT_380
	enum EVENT_381
	enum EVENT_382
	enum EVENT_383
	enum EVENT_384
	enum EVENT_385
	enum EVENT_386
	enum EVENT_387

		enum_start 0x388 // 0x71
	enum EVENT_388
	enum EVENT_389
	enum EVENT_38A
	enum EVENT_38B
	enum EVENT_38C
	enum EVENT_38D
	enum EVENT_38E
	enum EVENT_38F

		enum_start 0x390 // 0x72
	enum EVENT_390
	enum EVENT_391
	enum EVENT_392
	enum EVENT_393
	enum EVENT_394
	enum EVENT_395
	enum EVENT_396
	enum EVENT_397

		enum_start 0x398 // 0x73
	enum EVENT_398
	enum EVENT_399
	enum EVENT_39A
	enum EVENT_39B
	enum EVENT_39C
	enum EVENT_39D
	enum EVENT_39E
	enum EVENT_39F

		enum_start 0x3a0 // 0x74
	enum EVENT_3A0
	enum EVENT_3A1
	enum EVENT_3A2
	enum EVENT_3A3
	enum EVENT_3A4
	enum EVENT_3A5
	enum EVENT_3A6
	enum EVENT_3A7

		enum_start 0x3a8 // 0x75
	enum EVENT_3A8
	enum EVENT_3A9
	enum EVENT_3AA
	enum EVENT_3AB
	enum EVENT_3AC
	enum EVENT_3AD
	enum EVENT_3AE
	enum EVENT_3AF

		enum_start 0x3b0 // 0x76
	enum EVENT_3B0
	enum EVENT_3B1
	enum EVENT_3B2
	enum EVENT_3B3
	enum EVENT_3B4
	enum EVENT_3B5
	enum EVENT_3B6
	enum EVENT_3B7

		enum_start 0x3b8 // 0x77
	enum EVENT_3B8
	enum EVENT_3B9
	enum EVENT_3BA
	enum EVENT_3BB
	enum EVENT_3BC
	enum EVENT_3BD
	enum EVENT_3BE
	enum EVENT_3BF

		enum_start 0x3c0 // 0x78
	enum EVENT_3C0
	enum EVENT_3C1
	enum EVENT_3C2
	enum EVENT_3C3
	enum EVENT_3C4
	enum EVENT_3C5
	enum EVENT_3C6
	enum EVENT_3C7

		enum_start 0x3c8 // 0x79
	enum EVENT_3C8
	enum EVENT_3C9
	enum EVENT_3CA
	enum EVENT_3CB
	enum EVENT_3CC
	enum EVENT_3CD
	enum EVENT_3CE
	enum EVENT_3CF

		enum_start 0x3d0 // 0x7A
	enum EVENT_3D0
	enum EVENT_3D1
	enum EVENT_3D2
	enum EVENT_3D3
	enum EVENT_3D4
	enum EVENT_3D5
	enum EVENT_3D6
	enum EVENT_3D7

		enum_start 0x3d8 // 0x7B
	enum EVENT_3D8
	enum EVENT_3D9
	enum EVENT_3DA
	enum EVENT_3DB
	enum EVENT_3DC
	enum EVENT_3DD
	enum EVENT_3DE
	enum EVENT_3DF

		enum_start 0x3e0 // 0x7C
	enum EVENT_3E0
	enum EVENT_3E1
	enum EVENT_3E2
	enum EVENT_3E3
	enum EVENT_3E4
	enum EVENT_3E5
	enum EVENT_3E6
	enum EVENT_3E7

		enum_start 0x3e8 // 0x7D
	enum EVENT_3E8
	enum EVENT_3E9
	enum EVENT_3EA
	enum EVENT_3EB
	enum EVENT_3EC
	enum EVENT_3ED
	enum EVENT_3EE
	enum EVENT_3EF

		enum_start 0x3f0 // 0x7E
	enum EVENT_3F0
	enum EVENT_3F1
	enum EVENT_3F2
	enum EVENT_3F3
	enum EVENT_3F4
	enum EVENT_3F5
	enum EVENT_3F6
	enum EVENT_3F7

		enum_start 0x3f8 // 0x7F
	enum EVENT_3F8
	enum EVENT_3F9
	enum EVENT_3FA
	enum EVENT_3FB
	enum EVENT_3FC
	enum EVENT_3FD
	enum EVENT_3FE
	enum EVENT_3FF

		enum_start 0x400 // 0x80
	enum EVENT_400
	enum EVENT_401
	enum EVENT_402
	enum EVENT_403
	enum EVENT_404
	enum EVENT_405
	enum EVENT_406
	enum EVENT_407

		enum_start 0x408 // 0x81
	enum EVENT_408
	enum EVENT_409
	enum EVENT_40A
	enum EVENT_40B
	enum EVENT_40C
	enum EVENT_40D
	enum EVENT_40E
	enum EVENT_40F

		enum_start 0x410 // 0x82
	enum EVENT_410
	enum EVENT_411
	enum EVENT_412
	enum EVENT_413
	enum EVENT_414
	enum EVENT_415
	enum EVENT_416
	enum EVENT_417

		enum_start 0x418 // 0x83
	enum EVENT_418
	enum EVENT_419
	enum EVENT_41A
	enum EVENT_41B
	enum EVENT_41C
	enum EVENT_41D
	enum EVENT_41E
	enum EVENT_41F

		enum_start 0x420 // 0x84
	enum EVENT_420
	enum EVENT_421
	enum EVENT_422
	enum EVENT_423
	enum EVENT_424
	enum EVENT_425
	enum EVENT_426
	enum EVENT_427

		enum_start 0x428 // 0x85
	enum EVENT_428
	enum EVENT_429
	enum EVENT_42A
	enum EVENT_42B
	enum EVENT_42C
	enum EVENT_42D
	enum EVENT_42E
	enum EVENT_42F

		enum_start 0x430 // 0x86
	enum EVENT_430
	enum EVENT_431
	enum EVENT_432
	enum EVENT_433
	enum EVENT_434
	enum EVENT_435
	enum EVENT_436
	enum EVENT_437

		enum_start 0x438 // 0x87
	enum EVENT_438
	enum EVENT_439
	enum EVENT_43A
	enum EVENT_43B
	enum EVENT_43C
	enum EVENT_43D
	enum EVENT_43E
	enum EVENT_43F

		enum_start 0x440 // 0x88
	enum EVENT_440
	enum EVENT_441
	enum EVENT_442
	enum EVENT_443
	enum EVENT_444
	enum EVENT_445
	enum EVENT_446
	enum EVENT_447

		enum_start 0x448 // 0x89
	enum EVENT_448
	enum EVENT_449
	enum EVENT_44A
	enum EVENT_44B
	enum EVENT_44C
	enum EVENT_44D
	enum EVENT_44E
	enum EVENT_44F

		enum_start 0x450 // 0x8A
	enum EVENT_450
	enum EVENT_451
	enum EVENT_452
	enum EVENT_453
	enum EVENT_454
	enum EVENT_455
	enum EVENT_456
	enum EVENT_457

		enum_start 0x458 // 0x8B
	enum EVENT_458
	enum EVENT_459
	enum EVENT_45A
	enum EVENT_45B
	enum EVENT_45C
	enum EVENT_45D
	enum EVENT_45E
	enum EVENT_45F

		enum_start 0x460 // 0x8C
	enum EVENT_460
	enum EVENT_461
	enum EVENT_462
	enum EVENT_463
	enum EVENT_464
	enum EVENT_465
	enum EVENT_466
	enum EVENT_467

		enum_start 0x468 // 0x8D
	enum EVENT_468
	enum EVENT_469
	enum EVENT_46A
	enum EVENT_46B
	enum EVENT_46C
	enum EVENT_46D
	enum EVENT_46E
	enum EVENT_46F

		enum_start 0x470 // 0x8E
	enum EVENT_470
	enum EVENT_471
	enum EVENT_472
	enum EVENT_473
	enum EVENT_474
	enum EVENT_475
	enum EVENT_476
	enum EVENT_477

		enum_start 0x478 // 0x8F
	enum EVENT_478
	enum EVENT_479
	enum EVENT_47A
	enum EVENT_47B
	enum EVENT_47C
	enum EVENT_47D
	enum EVENT_47E
	enum EVENT_47F

		enum_start 0x480 // 0x90
	enum EVENT_480
	enum EVENT_481
	enum EVENT_482
	enum EVENT_483
	enum EVENT_484
	enum EVENT_485
	enum EVENT_486
	enum EVENT_487

		enum_start 0x488 // 0x91
	enum EVENT_488
	enum EVENT_489
	enum EVENT_48A
	enum EVENT_48B
	enum EVENT_48C
	enum EVENT_48D
	enum EVENT_48E
	enum EVENT_48F

		enum_start 0x490 // 0x92
	enum EVENT_490
	enum EVENT_491
	enum EVENT_492
	enum EVENT_493
	enum EVENT_494
	enum EVENT_495
	enum EVENT_496
	enum EVENT_497

		enum_start 0x498 // 0x93
	enum EVENT_498
	enum EVENT_499
	enum EVENT_49A
	enum EVENT_49B
	enum EVENT_49C
	enum EVENT_49D
	enum EVENT_49E
	enum EVENT_49F

		enum_start 0x4a0 // 0x94
	enum EVENT_4A0
	enum EVENT_4A1
	enum EVENT_4A2
	enum EVENT_4A3
	enum EVENT_4A4
	enum EVENT_4A5
	enum EVENT_4A6
	enum EVENT_4A7

		enum_start 0x4a8 // 0x95
	enum EVENT_4A8
	enum EVENT_4A9
	enum EVENT_4AA
	enum EVENT_4AB
	enum EVENT_4AC
	enum EVENT_4AD
	enum EVENT_4AE
	enum EVENT_4AF

		enum_start 0x4b0 // 0x96
	enum EVENT_4B0
	enum EVENT_4B1
	enum EVENT_4B2
	enum EVENT_4B3
	enum EVENT_4B4
	enum EVENT_4B5
	enum EVENT_4B6
	enum EVENT_4B7

		enum_start 0x4b8 // 0x97
	enum EVENT_4B8
	enum EVENT_4B9
	enum EVENT_4BA
	enum EVENT_4BB
	enum EVENT_4BC
	enum EVENT_4BD
	enum EVENT_4BE
	enum EVENT_4BF

		enum_start 0x4c0 // 0x98
	enum EVENT_4C0
	enum EVENT_4C1
	enum EVENT_4C2
	enum EVENT_4C3
	enum EVENT_4C4
	enum EVENT_4C5
	enum EVENT_4C6
	enum EVENT_4C7

		enum_start 0x4c8 // 0x99
	enum EVENT_4C8
	enum EVENT_4C9
	enum EVENT_4CA
	enum EVENT_4CB
	enum EVENT_4CC
	enum EVENT_4CD
	enum EVENT_4CE
	enum EVENT_4CF

		enum_start 0x4d0 // 0x9A
	enum EVENT_4D0
	enum EVENT_4D1
	enum EVENT_4D2
	enum EVENT_4D3
	enum EVENT_4D4
	enum EVENT_4D5
	enum EVENT_4D6
	enum EVENT_4D7

		enum_start 0x4d8 // 0x9B
	enum EVENT_4D8
	enum EVENT_4D9
	enum EVENT_4DA
	enum EVENT_4DB
	enum EVENT_4DC
	enum EVENT_4DD
	enum EVENT_4DE
	enum EVENT_4DF

		enum_start 0x4e0 // 0x9C
	enum EVENT_4E0
	enum EVENT_4E1
	enum EVENT_4E2
	enum EVENT_4E3
	enum EVENT_4E4
	enum EVENT_4E5
	enum EVENT_4E6
	enum EVENT_4E7

		enum_start 0x4e8 // 0x9D
	enum EVENT_4E8
	enum EVENT_4E9
	enum EVENT_4EA
	enum EVENT_4EB
	enum EVENT_4EC
	enum EVENT_4ED
	enum EVENT_4EE
	enum EVENT_4EF

		enum_start 0x4f0 // 0x9E
	enum EVENT_4F0
	enum EVENT_4F1
	enum EVENT_4F2
	enum EVENT_4F3
	enum EVENT_4F4
	enum EVENT_4F5
	enum EVENT_4F6
	enum EVENT_4F7

		enum_start 0x4f8 // 0x9F
	enum EVENT_4F8
	enum EVENT_4F9
	enum EVENT_4FA
	enum EVENT_4FB
	enum EVENT_4FC
	enum EVENT_4FD
	enum EVENT_4FE
	enum EVENT_4FF

		enum_start 0x500 // 0xA0
	enum EVENT_500
	enum EVENT_501
	enum EVENT_502
	enum EVENT_503
	enum EVENT_504
	enum EVENT_505
	enum EVENT_506
	enum EVENT_507

		enum_start 0x508 // 0xA1
	enum EVENT_508
	enum EVENT_509
	enum EVENT_50A
	enum EVENT_50B
	enum EVENT_50C
	enum EVENT_50D
	enum EVENT_50E
	enum EVENT_50F

		enum_start 0x510 // 0xA2
	enum EVENT_510
	enum EVENT_511
	enum EVENT_512
	enum EVENT_513
	enum EVENT_514
	enum EVENT_515
	enum EVENT_516
	enum EVENT_517

		enum_start 0x518 // 0xA3
	enum EVENT_518
	enum EVENT_519
	enum EVENT_51A
	enum EVENT_51B
	enum EVENT_51C
	enum EVENT_51D
	enum EVENT_51E
	enum EVENT_51F

		enum_start 0x520 // 0xA4
	enum EVENT_520
	enum EVENT_521
	enum EVENT_522
	enum EVENT_523
	enum EVENT_524
	enum EVENT_525
	enum EVENT_526
	enum EVENT_527

		enum_start 0x528 // 0xA5
	enum EVENT_528
	enum EVENT_529
	enum EVENT_52A
	enum EVENT_52B
	enum EVENT_52C
	enum EVENT_52D
	enum EVENT_52E
	enum EVENT_52F

		enum_start 0x530 // 0xA6
	enum EVENT_530
	enum EVENT_531
	enum EVENT_532
	enum EVENT_533
	enum EVENT_534
	enum EVENT_535
	enum EVENT_536
	enum EVENT_537

		enum_start 0x538 // 0xA7
	enum EVENT_538
	enum EVENT_539
	enum EVENT_53A
	enum EVENT_53B
	enum EVENT_53C
	enum EVENT_53D
	enum EVENT_53E
	enum EVENT_53F

		enum_start 0x540 // 0xA8
	enum EVENT_540
	enum EVENT_541
	enum EVENT_542
	enum EVENT_543
	enum EVENT_544
	enum EVENT_545
	enum EVENT_546
	enum EVENT_547

		enum_start 0x548 // 0xA9
	enum EVENT_548
	enum EVENT_549
	enum EVENT_54A
	enum EVENT_54B
	enum EVENT_54C
	enum EVENT_54D
	enum EVENT_54E
	enum EVENT_54F

		enum_start 0x550 // 0xAA
	enum EVENT_550
	enum EVENT_551
	enum EVENT_552
	enum EVENT_553
	enum EVENT_554
	enum EVENT_555
	enum EVENT_556
	enum EVENT_557

		enum_start 0x558 // 0xAB
	enum EVENT_558
	enum EVENT_559
	enum EVENT_55A
	enum EVENT_55B
	enum EVENT_55C
	enum EVENT_55D
	enum EVENT_55E
	enum EVENT_55F

		enum_start 0x560 // 0xAC
	enum EVENT_560
	enum EVENT_561
	enum EVENT_562
	enum EVENT_563
	enum EVENT_564
	enum EVENT_565
	enum EVENT_566
	enum EVENT_567

		enum_start 0x568 // 0xAD
	enum EVENT_568
	enum EVENT_569
	enum EVENT_56A
	enum EVENT_56B
	enum EVENT_56C
	enum EVENT_56D
	enum EVENT_56E
	enum EVENT_56F

		enum_start 0x570 // 0xAE
	enum EVENT_570
	enum EVENT_571
	enum EVENT_572
	enum EVENT_573
	enum EVENT_574
	enum EVENT_575
	enum EVENT_576
	enum EVENT_577

		enum_start 0x578 // 0xAF
	enum EVENT_578
	enum EVENT_579
	enum EVENT_57A
	enum EVENT_57B
	enum EVENT_57C
	enum EVENT_57D
	enum EVENT_57E
	enum EVENT_57F

		enum_start 0x580 // 0xB0
	enum EVENT_580
	enum EVENT_581
	enum EVENT_582
	enum EVENT_583
	enum EVENT_584
	enum EVENT_585
	enum EVENT_586
	enum EVENT_587

		enum_start 0x588 // 0xB1
	enum EVENT_588
	enum EVENT_589
	enum EVENT_58A
	enum EVENT_58B
	enum EVENT_58C
	enum EVENT_58D
	enum EVENT_58E
	enum EVENT_58F

		enum_start 0x590 // 0xB2
	enum EVENT_590
	enum EVENT_591
	enum EVENT_592
	enum EVENT_593
	enum EVENT_594
	enum EVENT_595
	enum EVENT_596
	enum EVENT_597

		enum_start 0x598 // 0xB3
	enum EVENT_598
	enum EVENT_599
	enum EVENT_59A
	enum EVENT_59B
	enum EVENT_59C
	enum EVENT_59D
	enum EVENT_59E
	enum EVENT_59F

		enum_start 0x5a0 // 0xB4
	enum EVENT_5A0
	enum EVENT_5A1
	enum EVENT_5A2
	enum EVENT_5A3
	enum EVENT_5A4
	enum EVENT_5A5
	enum EVENT_5A6
	enum EVENT_5A7

		enum_start 0x5a8 // 0xB5
	enum EVENT_5A8
	enum EVENT_5A9
	enum EVENT_5AA
	enum EVENT_5AB
	enum EVENT_5AC
	enum EVENT_5AD
	enum EVENT_5AE
	enum EVENT_5AF

		enum_start 0x5b0 // 0xB6
	enum EVENT_5B0
	enum EVENT_5B1
	enum EVENT_5B2
	enum EVENT_5B3
	enum EVENT_5B4
	enum EVENT_5B5
	enum EVENT_5B6
	enum EVENT_5B7

		enum_start 0x5b8 // 0xB7
	enum EVENT_5B8
	enum EVENT_5B9
	enum EVENT_5BA
	enum EVENT_5BB
	enum EVENT_5BC
	enum EVENT_5BD
	enum EVENT_5BE
	enum EVENT_5BF

		enum_start 0x5c0 // 0xB8
	enum EVENT_5C0
	enum EVENT_5C1
	enum EVENT_5C2
	enum EVENT_5C3
	enum EVENT_5C4
	enum EVENT_5C5
	enum EVENT_5C6
	enum EVENT_5C7

		enum_start 0x5c8 // 0xB9
	enum EVENT_5C8
	enum EVENT_5C9
	enum EVENT_5CA
	enum EVENT_5CB
	enum EVENT_5CC
	enum EVENT_5CD
	enum EVENT_5CE
	enum EVENT_5CF

		enum_start 0x5d0 // 0xBA
	enum EVENT_5D0
	enum EVENT_5D1
	enum EVENT_5D2
	enum EVENT_5D3
	enum EVENT_5D4
	enum EVENT_5D5
	enum EVENT_5D6
	enum EVENT_5D7

		enum_start 0x5d8 // 0xBB
	enum EVENT_5D8
	enum EVENT_5D9
	enum EVENT_5DA
	enum EVENT_5DB
	enum EVENT_5DC
	enum EVENT_5DD
	enum EVENT_5DE
	enum EVENT_5DF

		enum_start 0x5e0 // 0xBC
	enum EVENT_5E0
	enum EVENT_5E1
	enum EVENT_5E2
	enum EVENT_5E3
	enum EVENT_5E4
	enum EVENT_5E5
	enum EVENT_5E6
	enum EVENT_5E7

		enum_start 0x5e8 // 0xBD
	enum EVENT_5E8
	enum EVENT_5E9
	enum EVENT_5EA
	enum EVENT_5EB
	enum EVENT_5EC
	enum EVENT_5ED
	enum EVENT_5EE
	enum EVENT_5EF

		enum_start 0x5f0 // 0xBE
	enum EVENT_5F0
	enum EVENT_5F1
	enum EVENT_5F2
	enum EVENT_5F3
	enum EVENT_5F4
	enum EVENT_5F5
	enum EVENT_5F6
	enum EVENT_5F7

		enum_start 0x5f8 // 0xBF
	enum EVENT_5F8
	enum EVENT_5F9
	enum EVENT_5FA
	enum EVENT_5FB
	enum EVENT_5FC
	enum EVENT_5FD
	enum EVENT_5FE
	enum EVENT_5FF

		enum_start 0x600 // 0xC0
	enum EVENT_600
	enum EVENT_601
	enum EVENT_602
	enum EVENT_603
	enum EVENT_604
	enum EVENT_605
	enum EVENT_606
	enum EVENT_607

		enum_start 0x608 // 0xC1
	enum EVENT_608
	enum EVENT_609
	enum EVENT_60A
	enum EVENT_60B
	enum EVENT_60C
	enum EVENT_60D
	enum EVENT_60E
	enum EVENT_60F

		enum_start 0x610 // 0xC2
	enum EVENT_610
	enum EVENT_611
	enum EVENT_612
	enum EVENT_613
	enum EVENT_614
	enum EVENT_615
	enum EVENT_616
	enum EVENT_617

		enum_start 0x618 // 0xC3
	enum EVENT_618
	enum EVENT_619
	enum EVENT_61A
	enum EVENT_61B
	enum EVENT_61C
	enum EVENT_61D
	enum EVENT_61E
	enum EVENT_61F

		enum_start 0x620 // 0xC4
	enum EVENT_620
	enum EVENT_621
	enum EVENT_622
	enum EVENT_623
	enum EVENT_624
	enum EVENT_625
	enum EVENT_626
	enum EVENT_627

		enum_start 0x628 // 0xC5
	enum EVENT_628
	enum EVENT_629
	enum EVENT_62A
	enum EVENT_62B
	enum EVENT_62C
	enum EVENT_62D
	enum EVENT_62E
	enum EVENT_62F

		enum_start 0x630 // 0xC6
	enum EVENT_630
	enum EVENT_631
	enum EVENT_632
	enum EVENT_633
	enum EVENT_634
	enum EVENT_635
	enum EVENT_636
	enum EVENT_637

		enum_start 0x638 // 0xC7
	enum EVENT_638
	enum EVENT_639
	enum EVENT_63A
	enum EVENT_63B
	enum EVENT_63C
	enum EVENT_63D
	enum EVENT_63E
	enum EVENT_63F

		enum_start 0x640 // 0xC8
	enum EVENT_640
	enum EVENT_641
	enum EVENT_642
	enum EVENT_643
	enum EVENT_644
	enum EVENT_645
	enum EVENT_646
	enum EVENT_647

		enum_start 0x648 // 0xC9
	enum EVENT_648
	enum EVENT_649
	enum EVENT_64A
	enum EVENT_64B
	enum EVENT_64C
	enum EVENT_64D
	enum EVENT_64E
	enum EVENT_64F

		enum_start 0x650 // 0xCA
	enum EVENT_650
	enum EVENT_651
	enum EVENT_652
	enum EVENT_653
	enum EVENT_654
	enum EVENT_655
	enum EVENT_656
	enum EVENT_657

		enum_start 0x658 // 0xCB
	enum EVENT_658
	enum EVENT_659
	enum EVENT_65A
	enum EVENT_65B
	enum EVENT_65C
	enum EVENT_65D
	enum EVENT_65E
	enum EVENT_65F

		enum_start 0x660 // 0xCC
	enum EVENT_660
	enum EVENT_661
	enum EVENT_662
	enum EVENT_663
	enum EVENT_664
	enum EVENT_665
	enum EVENT_666
	enum EVENT_667

		enum_start 0x668 // 0xCD
	enum EVENT_668
	enum EVENT_669
	enum EVENT_66A
	enum EVENT_66B
	enum EVENT_66C
	enum EVENT_66D
	enum EVENT_66E
	enum EVENT_66F

		enum_start 0x670 // 0xCE
	enum EVENT_670
	enum EVENT_671
	enum EVENT_672
	enum EVENT_673
	enum EVENT_674
	enum EVENT_675
	enum EVENT_676
	enum EVENT_677

		enum_start 0x678 // 0xCF
	enum EVENT_678
	enum EVENT_679
	enum EVENT_67A
	enum EVENT_67B
	enum EVENT_67C
	enum EVENT_67D
	enum EVENT_67E
	enum EVENT_67F

		enum_start 0x680 // 0xD0
	enum EVENT_680
	enum EVENT_681
	enum EVENT_682
	enum EVENT_683
	enum EVENT_684
	enum EVENT_685
	enum EVENT_686
	enum EVENT_687

		enum_start 0x688 // 0xD1
	enum EVENT_688
	enum EVENT_689
	enum EVENT_68A
	enum EVENT_68B
	enum EVENT_68C
	enum EVENT_68D
	enum EVENT_68E
	enum EVENT_68F

		enum_start 0x690 // 0xD2
	enum EVENT_690
	enum EVENT_691
	enum EVENT_692
	enum EVENT_693
	enum EVENT_694
	enum EVENT_695
	enum EVENT_696
	enum EVENT_697

		enum_start 0x698 // 0xD3
	enum EVENT_698
	enum EVENT_699
	enum EVENT_69A
	enum EVENT_69B
	enum EVENT_69C
	enum EVENT_69D
	enum EVENT_69E
	enum EVENT_69F

		enum_start 0x6a0 // 0xD4
	enum EVENT_6A0
	enum EVENT_6A1
	enum EVENT_6A2
	enum EVENT_6A3
	enum EVENT_6A4
	enum EVENT_6A5
	enum EVENT_6A6
	enum EVENT_6A7

		enum_start 0x6a8 // 0xD5
	enum EVENT_6A8
	enum EVENT_6A9
	enum EVENT_6AA
	enum EVENT_6AB
	enum EVENT_6AC
	enum EVENT_6AD
	enum EVENT_6AE
	enum EVENT_6AF

		enum_start 0x6b0 // 0xD6
	enum EVENT_6B0
	enum EVENT_6B1
	enum EVENT_6B2
	enum EVENT_6B3
	enum EVENT_6B4
	enum EVENT_6B5
	enum EVENT_6B6
	enum EVENT_6B7

		enum_start 0x6b8 // 0xD7
	enum EVENT_6B8
	enum EVENT_6B9
	enum EVENT_6BA
	enum EVENT_6BB
	enum EVENT_6BC
	enum EVENT_6BD
	enum EVENT_6BE
	enum EVENT_6BF

		enum_start 0x6c0 // 0xD8
	enum EVENT_6C0
	enum EVENT_6C1
	enum EVENT_6C2
	enum EVENT_6C3
	enum EVENT_6C4
	enum EVENT_6C5
	enum EVENT_6C6
	enum EVENT_6C7

		enum_start 0x6c8 // 0xD9
	enum EVENT_6C8
	enum EVENT_6C9
	enum EVENT_6CA
	enum EVENT_6CB
	enum EVENT_6CC
	enum EVENT_6CD
	enum EVENT_6CE
	enum EVENT_6CF

		enum_start 0x6d0 // 0xDA
	enum EVENT_6D0
	enum EVENT_6D1
	enum EVENT_6D2
	enum EVENT_6D3
	enum EVENT_6D4
	enum EVENT_6D5
	enum EVENT_6D6
	enum EVENT_6D7

		enum_start 0x6d8 // 0xDB
	enum EVENT_6D8
	enum EVENT_6D9
	enum EVENT_6DA
	enum EVENT_6DB
	enum EVENT_6DC
	enum EVENT_6DD
	enum EVENT_6DE
	enum EVENT_6DF

		enum_start 0x6e0 // 0xDC
	enum EVENT_6E0
	enum EVENT_6E1
	enum EVENT_6E2
	enum EVENT_6E3
	enum EVENT_6E4
	enum EVENT_6E5
	enum EVENT_6E6
	enum EVENT_6E7

		enum_start 0x6e8 // 0xDD
	enum EVENT_6E8
	enum EVENT_6E9
	enum EVENT_6EA
	enum EVENT_6EB
	enum EVENT_6EC
	enum EVENT_6ED
	enum EVENT_6EE
	enum EVENT_6EF

		enum_start 0x6f0 // 0xDE
	enum EVENT_6F0
	enum EVENT_6F1
	enum EVENT_6F2
	enum EVENT_6F3
	enum EVENT_6F4
	enum EVENT_6F5
	enum EVENT_6F6
	enum EVENT_6F7

		enum_start 0x6f8 // 0xDF
	enum EVENT_6F8
	enum EVENT_6F9
	enum EVENT_6FA
	enum EVENT_6FB
	enum EVENT_6FC
	enum EVENT_6FD
	enum EVENT_6FE
	enum EVENT_6FF

		enum_start 0x700 // 0xE0
	enum EVENT_700
	enum EVENT_701
	enum EVENT_702
	enum EVENT_703
	enum EVENT_704
	enum EVENT_705
	enum EVENT_706
	enum EVENT_707

		enum_start 0x708 // 0xE1
	enum EVENT_708
	enum EVENT_709
	enum EVENT_70A
	enum EVENT_70B
	enum EVENT_70C
	enum EVENT_70D
	enum EVENT_70E
	enum EVENT_70F

		enum_start 0x710 // 0xE2
	enum EVENT_710
	enum EVENT_711
	enum EVENT_712
	enum EVENT_713
	enum EVENT_714
	enum EVENT_715
	enum EVENT_716
	enum EVENT_717

		enum_start 0x718 // 0xE3
	enum EVENT_718
	enum EVENT_719
	enum EVENT_71A
	enum EVENT_71B
	enum EVENT_71C
	enum EVENT_71D
	enum EVENT_71E
	enum EVENT_71F

		enum_start 0x720 // 0xE4
	enum EVENT_720
	enum EVENT_721
	enum EVENT_722
	enum EVENT_723
	enum EVENT_724
	enum EVENT_725
	enum EVENT_726
	enum EVENT_727

		enum_start 0x728 // 0xE5
	enum EVENT_728
	enum EVENT_729
	enum EVENT_72A
	enum EVENT_72B
	enum EVENT_72C
	enum EVENT_72D
	enum EVENT_72E
	enum EVENT_72F

		enum_start 0x730 // 0xE6
	enum EVENT_730
	enum EVENT_731
	enum EVENT_732
	enum EVENT_733
	enum EVENT_734
	enum EVENT_735
	enum EVENT_736
	enum EVENT_737

		enum_start 0x738 // 0xE7
	enum EVENT_738
	enum EVENT_739
	enum EVENT_73A
	enum EVENT_73B
	enum EVENT_73C
	enum EVENT_73D
	enum EVENT_73E
	enum EVENT_73F

		enum_start 0x740 // 0xE8
	enum EVENT_740
	enum EVENT_741
	enum EVENT_742
	enum EVENT_743
	enum EVENT_744
	enum EVENT_745
	enum EVENT_746
	enum EVENT_747

		enum_start 0x748 // 0xE9
	enum EVENT_748
	enum EVENT_749
	enum EVENT_74A
	enum EVENT_74B
	enum EVENT_74C
	enum EVENT_74D
	enum EVENT_74E
	enum EVENT_74F

		enum_start 0x750 // 0xEA
	enum EVENT_750
	enum EVENT_751
	enum EVENT_752
	enum EVENT_753
	enum EVENT_754
	enum EVENT_755
	enum EVENT_756
	enum EVENT_757

		enum_start 0x758 // 0xEB
	enum EVENT_758
	enum EVENT_759
	enum EVENT_75A
	enum EVENT_75B
	enum EVENT_75C
	enum EVENT_75D
	enum EVENT_75E
	enum EVENT_75F

		enum_start 0x760 // 0xEC
	enum EVENT_760
	enum EVENT_761
	enum EVENT_762
	enum EVENT_763
	enum EVENT_764
	enum EVENT_765
	enum EVENT_766
	enum EVENT_767

		enum_start 0x768 // 0xED
	enum EVENT_768
	enum EVENT_769
	enum EVENT_76A
	enum EVENT_76B
	enum EVENT_76C
	enum EVENT_76D
	enum EVENT_76E
	enum EVENT_76F

		enum_start 0x770 // 0xEE
	enum EVENT_770
	enum EVENT_771
	enum EVENT_772
	enum EVENT_773
	enum EVENT_774
	enum EVENT_775
	enum EVENT_776
	enum EVENT_777

		enum_start 0x778 // 0xEF
	enum EVENT_778
	enum EVENT_779
	enum EVENT_77A
	enum EVENT_77B
	enum EVENT_77C
	enum EVENT_77D
	enum EVENT_77E
	enum EVENT_77F

		enum_start 0x780 // 0xF0
	enum EVENT_780
	enum EVENT_781
	enum EVENT_782
	enum EVENT_783
	enum EVENT_784
	enum EVENT_785
	enum EVENT_786
	enum EVENT_787

		enum_start 0x788 // 0xF1
	enum EVENT_788
	enum EVENT_789
	enum EVENT_78A
	enum EVENT_78B
	enum EVENT_78C
	enum EVENT_78D
	enum EVENT_78E
	enum EVENT_78F

		enum_start 0x790 // 0xF2
	enum EVENT_790
	enum EVENT_791
	enum EVENT_792
	enum EVENT_793
	enum EVENT_794
	enum EVENT_795
	enum EVENT_796
	enum EVENT_797

		enum_start 0x798 // 0xF3
	enum EVENT_798
	enum EVENT_799
	enum EVENT_79A
	enum EVENT_79B
	enum EVENT_79C
	enum EVENT_79D
	enum EVENT_79E
	enum EVENT_79F

		enum_start 0x7a0 // 0xF4
	enum EVENT_7A0
	enum EVENT_7A1
	enum EVENT_7A2
	enum EVENT_7A3
	enum EVENT_7A4
	enum EVENT_7A5
	enum EVENT_7A6
	enum EVENT_7A7

		enum_start 0x7a8 // 0xF5
	enum EVENT_7A8
	enum EVENT_7A9
	enum EVENT_7AA
	enum EVENT_7AB
	enum EVENT_7AC
	enum EVENT_7AD
	enum EVENT_7AE
	enum EVENT_7AF

		enum_start 0x7b0 // 0xF6
	enum EVENT_7B0
	enum EVENT_7B1
	enum EVENT_7B2
	enum EVENT_7B3
	enum EVENT_7B4
	enum EVENT_7B5
	enum EVENT_7B6
	enum EVENT_7B7

		enum_start 0x7b8 // 0xF7
	enum EVENT_7B8
	enum EVENT_7B9
	enum EVENT_7BA
	enum EVENT_7BB
	enum EVENT_7BC
	enum EVENT_7BD
	enum EVENT_7BE
	enum EVENT_7BF

		enum_start 0x7c0 // 0xF8
	enum EVENT_7C0
	enum EVENT_7C1
	enum EVENT_7C2
	enum EVENT_7C3
	enum EVENT_7C4
	enum EVENT_7C5
	enum EVENT_7C6
	enum EVENT_7C7

		enum_start 0x7c8 // 0xF9
	enum EVENT_7C8
	enum EVENT_7C9
	enum EVENT_7CA
	enum EVENT_7CB
	enum EVENT_7CC
	enum EVENT_7CD
	enum EVENT_7CE
	enum EVENT_7CF

		enum_start 0x7d0 // 0xFA
	enum EVENT_7D0
	enum EVENT_7D1
	enum EVENT_7D2
	enum EVENT_7D3
	enum EVENT_7D4
	enum EVENT_7D5
	enum EVENT_7D6
	enum EVENT_7D7

		enum_start 0x7d8 // 0xFB
	enum EVENT_7D8
	enum EVENT_7D9
	enum EVENT_7DA
	enum EVENT_7DB
	enum EVENT_7DC
	enum EVENT_7DD
	enum EVENT_7DE
	enum EVENT_7DF

		enum_start 0x7e0 // 0xFC
	enum EVENT_7E0
	enum EVENT_7E1
	enum EVENT_7E2
	enum EVENT_7E3
	enum EVENT_7E4
	enum EVENT_7E5
	enum EVENT_7E6
	enum EVENT_7E7

		enum_start 0x7e8 // 0xFD
	enum EVENT_7E8
	enum EVENT_7E9
	enum EVENT_7EA
	enum EVENT_7EB
	enum EVENT_7EC
	enum EVENT_7ED
	enum EVENT_7EE
	enum EVENT_7EF

		enum_start 0x7f0 // 0xFE
	enum EVENT_7F0
	enum EVENT_7F1
	enum EVENT_7F2
	enum EVENT_7F3
	enum EVENT_7F4
	enum EVENT_7F5
	enum EVENT_7F6
	enum EVENT_7F7

		enum_start 0x7f8 // 0xFF
	enum EVENT_7F8
	enum EVENT_7F9
	enum EVENT_7FA
	enum EVENT_7FB
	enum EVENT_7FC
	enum EVENT_7FD
	enum EVENT_7FE
	enum EVENT_7FF

		enum_start 0x800 // 0x100
	enum EVENT_800
	enum EVENT_801
	enum EVENT_802
	enum EVENT_803
	enum EVENT_804
	enum EVENT_805
	enum EVENT_806
	enum EVENT_807

		enum_start 0x808 // 0x101
	enum EVENT_808
	enum EVENT_809
	enum EVENT_80A
	enum EVENT_80B
	enum EVENT_80C
	enum EVENT_80D
	enum EVENT_80E
	enum EVENT_80F

		enum_start 0x810 // 0x102
	enum EVENT_810
	enum EVENT_811
	enum EVENT_812
	enum EVENT_813
	enum EVENT_814
	enum EVENT_815
	enum EVENT_816
	enum EVENT_817

		enum_start 0x818 // 0x103
	enum EVENT_818
	enum EVENT_819
	enum EVENT_81A
	enum EVENT_81B
	enum EVENT_81C
	enum EVENT_81D
	enum EVENT_81E
	enum EVENT_81F

		enum_start 0x820 // 0x104
	enum EVENT_820
	enum EVENT_821
	enum EVENT_822
	enum EVENT_823
	enum EVENT_824
	enum EVENT_825
	enum EVENT_826
	enum EVENT_827

		enum_start 0x828 // 0x105
	enum EVENT_828
	enum EVENT_829
	enum EVENT_82A
	enum EVENT_82B
	enum EVENT_82C
	enum EVENT_82D
	enum EVENT_82E
	enum EVENT_82F

		enum_start 0x830 // 0x106
	enum EVENT_830
	enum EVENT_831
	enum EVENT_832
	enum EVENT_833
	enum EVENT_834
	enum EVENT_835
	enum EVENT_836
	enum EVENT_837

		enum_start 0x838 // 0x107
	enum EVENT_838
	enum EVENT_839
	enum EVENT_83A
	enum EVENT_83B
	enum EVENT_83C
	enum EVENT_83D
	enum EVENT_83E
	enum EVENT_83F

		enum_start 0x840 // 0x108
	enum EVENT_840
	enum EVENT_841
	enum EVENT_842
	enum EVENT_843
	enum EVENT_844
	enum EVENT_845
	enum EVENT_846
	enum EVENT_847

		enum_start 0x848 // 0x109
	enum EVENT_848
	enum EVENT_849
	enum EVENT_84A
	enum EVENT_84B
	enum EVENT_84C
	enum EVENT_84D
	enum EVENT_84E
	enum EVENT_84F

		enum_start 0x850 // 0x10A
	enum EVENT_850
	enum EVENT_851
	enum EVENT_852
	enum EVENT_853
	enum EVENT_854
	enum EVENT_855
	enum EVENT_856
	enum EVENT_857

		enum_start 0x858 // 0x10B
	enum EVENT_858
	enum EVENT_859
	enum EVENT_85A
	enum EVENT_85B
	enum EVENT_85C
	enum EVENT_85D
	enum EVENT_85E
	enum EVENT_85F

		enum_start 0x860 // 0x10C
	enum EVENT_860
	enum EVENT_861
	enum EVENT_862
	enum EVENT_863
	enum EVENT_864
	enum EVENT_865
	enum EVENT_866
	enum EVENT_867

		enum_start 0x868 // 0x10D
	enum EVENT_868
	enum EVENT_869
	enum EVENT_86A
	enum EVENT_86B
	enum EVENT_86C
	enum EVENT_86D
	enum EVENT_86E
	enum EVENT_86F

		enum_start 0x870 // 0x10E
	enum EVENT_870
	enum EVENT_871
	enum EVENT_872
	enum EVENT_873
	enum EVENT_874
	enum EVENT_875
	enum EVENT_876
	enum EVENT_877

		enum_start 0x878 // 0x10F
	enum EVENT_878
	enum EVENT_879
	enum EVENT_87A
	enum EVENT_87B
	enum EVENT_87C
	enum EVENT_87D
	enum EVENT_87E
	enum EVENT_87F

		enum_start 0x880 // 0x110
	enum EVENT_880
	enum EVENT_881
	enum EVENT_882
	enum EVENT_883
	enum EVENT_884
	enum EVENT_885
	enum EVENT_886
	enum EVENT_887

		enum_start 0x888 // 0x111
	enum EVENT_888
	enum EVENT_889
	enum EVENT_88A
	enum EVENT_88B
	enum EVENT_88C
	enum EVENT_88D
	enum EVENT_88E
	enum EVENT_88F

		enum_start 0x890 // 0x112
	enum EVENT_890
	enum EVENT_891
	enum EVENT_892
	enum EVENT_893
	enum EVENT_894
	enum EVENT_895
	enum EVENT_896
	enum EVENT_897

		enum_start 0x898 // 0x113
	enum EVENT_898
	enum EVENT_899
	enum EVENT_89A
	enum EVENT_89B
	enum EVENT_89C
	enum EVENT_89D
	enum EVENT_89E
	enum EVENT_89F

		enum_start 0x8a0 // 0x114
	enum EVENT_8A0
	enum EVENT_8A1
	enum EVENT_8A2
	enum EVENT_8A3
	enum EVENT_8A4
	enum EVENT_8A5
	enum EVENT_8A6
	enum EVENT_8A7

		enum_start 0x8a8 // 0x115
	enum EVENT_8A8
	enum EVENT_8A9
	enum EVENT_8AA
	enum EVENT_8AB
	enum EVENT_8AC
	enum EVENT_8AD
	enum EVENT_8AE
	enum EVENT_8AF

		enum_start 0x8b0 // 0x116
	enum EVENT_8B0
	enum EVENT_8B1
	enum EVENT_8B2
	enum EVENT_8B3
	enum EVENT_8B4
	enum EVENT_8B5
	enum EVENT_8B6
	enum EVENT_8B7

		enum_start 0x8b8 // 0x117
	enum EVENT_8B8
	enum EVENT_8B9
	enum EVENT_8BA
	enum EVENT_8BB
	enum EVENT_8BC
	enum EVENT_8BD
	enum EVENT_8BE
	enum EVENT_8BF

		enum_start 0x8c0 // 0x118
	enum EVENT_8C0
	enum EVENT_8C1
	enum EVENT_8C2
	enum EVENT_8C3
	enum EVENT_8C4
	enum EVENT_8C5
	enum EVENT_8C6
	enum EVENT_8C7

		enum_start 0x8c8 // 0x119
	enum EVENT_8C8
	enum EVENT_8C9
	enum EVENT_8CA
	enum EVENT_8CB
	enum EVENT_8CC
	enum EVENT_8CD
	enum EVENT_8CE
	enum EVENT_8CF

		enum_start 0x8d0 // 0x11A
	enum EVENT_8D0
	enum EVENT_8D1
	enum EVENT_8D2
	enum EVENT_8D3
	enum EVENT_8D4
	enum EVENT_8D5
	enum EVENT_8D6
	enum EVENT_8D7

		enum_start 0x8d8 // 0x11B
	enum EVENT_8D8
	enum EVENT_8D9
	enum EVENT_8DA
	enum EVENT_8DB
	enum EVENT_8DC
	enum EVENT_8DD
	enum EVENT_8DE
	enum EVENT_8DF

		enum_start 0x8e0 // 0x11C
	enum EVENT_8E0
	enum EVENT_8E1
	enum EVENT_8E2
	enum EVENT_8E3
	enum EVENT_8E4
	enum EVENT_8E5
	enum EVENT_8E6
	enum EVENT_8E7

		enum_start 0x8e8 // 0x11D
	enum EVENT_8E8
	enum EVENT_8E9
	enum EVENT_8EA
	enum EVENT_8EB
	enum EVENT_8EC
	enum EVENT_8ED
	enum EVENT_8EE
	enum EVENT_8EF

		enum_start 0x8f0 // 0x11E
	enum EVENT_8F0
	enum EVENT_8F1
	enum EVENT_8F2
	enum EVENT_8F3
	enum EVENT_8F4
	enum EVENT_8F5
	enum EVENT_8F6
	enum EVENT_8F7

		enum_start 0x8f8 // 0x11F
	enum EVENT_8F8
	enum EVENT_8F9
	enum EVENT_8FA
	enum EVENT_8FB
	enum EVENT_8FC
	enum EVENT_8FD
	enum EVENT_8FE
	enum EVENT_8FF

		enum_start 0x900 // 0x120
	enum EVENT_900
	enum EVENT_901
	enum EVENT_902
	enum EVENT_903
	enum EVENT_904
	enum EVENT_905
	enum EVENT_906
	enum EVENT_907

		enum_start 0x908 // 0x121
	enum EVENT_908
	enum EVENT_909
	enum EVENT_90A
	enum EVENT_90B
	enum EVENT_90C
	enum EVENT_90D
	enum EVENT_90E
	enum EVENT_90F

		enum_start 0x910 // 0x122
	enum EVENT_910
	enum EVENT_911
	enum EVENT_912
	enum EVENT_913
	enum EVENT_914
	enum EVENT_915
	enum EVENT_916
	enum EVENT_917

		enum_start 0x918 // 0x123
	enum EVENT_918
	enum EVENT_919
	enum EVENT_91A
	enum EVENT_91B
	enum EVENT_91C
	enum EVENT_91D
	enum EVENT_91E
	enum EVENT_91F

		enum_start 0x920 // 0x124
	enum EVENT_920
	enum EVENT_921
	enum EVENT_922
	enum EVENT_923
	enum EVENT_924
	enum EVENT_925
	enum EVENT_926
	enum EVENT_927

		enum_start 0x928 // 0x125
	enum EVENT_928
	enum EVENT_929
	enum EVENT_92A
	enum EVENT_92B
	enum EVENT_92C
	enum EVENT_92D
	enum EVENT_92E
	enum EVENT_92F

		enum_start 0x930 // 0x126
	enum EVENT_930
	enum EVENT_931
	enum EVENT_932
	enum EVENT_933
	enum EVENT_934
	enum EVENT_935
	enum EVENT_936
	enum EVENT_937

		enum_start 0x938 // 0x127
	enum EVENT_938
	enum EVENT_939
	enum EVENT_93A
	enum EVENT_93B
	enum EVENT_93C
	enum EVENT_93D
	enum EVENT_93E
	enum EVENT_93F

		enum_start 0x940 // 0x128
	enum EVENT_940
	enum EVENT_941
	enum EVENT_942
	enum EVENT_943
	enum EVENT_944
	enum EVENT_945
	enum EVENT_946
	enum EVENT_947

		enum_start 0x948 // 0x129
	enum EVENT_948
	enum EVENT_949
	enum EVENT_94A
	enum EVENT_94B
	enum EVENT_94C
	enum EVENT_94D
	enum EVENT_94E
	enum EVENT_94F

		enum_start 0x950 // 0x12A
	enum EVENT_950
	enum EVENT_951
	enum EVENT_952
	enum EVENT_953
	enum EVENT_954
	enum EVENT_955
	enum EVENT_956
	enum EVENT_957

		enum_start 0x958 // 0x12B
	enum EVENT_958
	enum EVENT_959
	enum EVENT_95A
	enum EVENT_95B
	enum EVENT_95C
	enum EVENT_95D
	enum EVENT_95E
	enum EVENT_95F

		enum_start 0x960 // 0x12C
	enum EVENT_960
	enum EVENT_961
	enum EVENT_962
	enum EVENT_963
	enum EVENT_964
	enum EVENT_965
	enum EVENT_966
	enum EVENT_967

		enum_start 0x968 // 0x12D
	enum EVENT_968
	enum EVENT_969
	enum EVENT_96A
	enum EVENT_96B
	enum EVENT_96C
	enum EVENT_96D
	enum EVENT_96E
	enum EVENT_96F

		enum_start 0x970 // 0x12E
	enum EVENT_970
	enum EVENT_971
	enum EVENT_972
	enum EVENT_973
	enum EVENT_974
	enum EVENT_975
	enum EVENT_976
	enum EVENT_977

		enum_start 0x978 // 0x12F
	enum EVENT_978
	enum EVENT_979
	enum EVENT_97A
	enum EVENT_97B
	enum EVENT_97C
	enum EVENT_97D
	enum EVENT_97E
	enum EVENT_97F

		enum_start 0x980 // 0x130
	enum EVENT_980
	enum EVENT_981
	enum EVENT_982
	enum EVENT_983
	enum EVENT_984
	enum EVENT_985
	enum EVENT_986
	enum EVENT_987

		enum_start 0x988 // 0x131
	enum EVENT_988
	enum EVENT_989
	enum EVENT_98A
	enum EVENT_98B
	enum EVENT_98C
	enum EVENT_98D
	enum EVENT_98E
	enum EVENT_98F

		enum_start 0x990 // 0x132
	enum EVENT_990
	enum EVENT_991
	enum EVENT_992
	enum EVENT_993
	enum EVENT_994
	enum EVENT_995
	enum EVENT_996
	enum EVENT_997

		enum_start 0x998 // 0x133
	enum EVENT_998
	enum EVENT_999
	enum EVENT_99A
	enum EVENT_99B
	enum EVENT_99C
	enum EVENT_99D
	enum EVENT_99E
	enum EVENT_99F

		enum_start 0x9a0 // 0x134
	enum EVENT_9A0
	enum EVENT_9A1
	enum EVENT_9A2
	enum EVENT_9A3
	enum EVENT_9A4
	enum EVENT_9A5
	enum EVENT_9A6
	enum EVENT_9A7

		enum_start 0x9a8 // 0x135
	enum EVENT_9A8
	enum EVENT_9A9
	enum EVENT_9AA
	enum EVENT_9AB
	enum EVENT_9AC
	enum EVENT_9AD
	enum EVENT_9AE
	enum EVENT_9AF

		enum_start 0x9b0 // 0x136
	enum EVENT_9B0
	enum EVENT_9B1
	enum EVENT_9B2
	enum EVENT_9B3
	enum EVENT_9B4
	enum EVENT_9B5
	enum EVENT_9B6
	enum EVENT_9B7

		enum_start 0x9b8 // 0x137
	enum EVENT_9B8
	enum EVENT_9B9
	enum EVENT_9BA
	enum EVENT_9BB
	enum EVENT_9BC
	enum EVENT_9BD
	enum EVENT_9BE
	enum EVENT_9BF

		enum_start 0x9c0 // 0x138
	enum EVENT_9C0
	enum EVENT_9C1
	enum EVENT_9C2
	enum EVENT_9C3
	enum EVENT_9C4
	enum EVENT_9C5
	enum EVENT_9C6
	enum EVENT_9C7

		enum_start 0x9c8 // 0x139
	enum EVENT_9C8
	enum EVENT_9C9
	enum EVENT_9CA
	enum EVENT_9CB
	enum EVENT_9CC
	enum EVENT_9CD
	enum EVENT_9CE
	enum EVENT_9CF

		enum_start 0x9d0 // 0x13A
	enum EVENT_9D0
	enum EVENT_9D1
	enum EVENT_9D2
	enum EVENT_9D3
	enum EVENT_9D4
	enum EVENT_9D5
	enum EVENT_9D6
	enum EVENT_9D7

		enum_start 0x9d8 // 0x13B
	enum EVENT_9D8
	enum EVENT_9D9
	enum EVENT_9DA
	enum EVENT_9DB
	enum EVENT_9DC
	enum EVENT_9DD
	enum EVENT_9DE
	enum EVENT_9DF

		enum_start 0x9e0 // 0x13C
	enum EVENT_9E0
	enum EVENT_9E1
	enum EVENT_9E2
	enum EVENT_9E3
	enum EVENT_9E4
	enum EVENT_9E5
	enum EVENT_9E6
	enum EVENT_9E7

		enum_start 0x9e8 // 0x13D
	enum EVENT_9E8
	enum EVENT_9E9
	enum EVENT_9EA
	enum EVENT_9EB
	enum EVENT_9EC
	enum EVENT_9ED
	enum EVENT_9EE
	enum EVENT_9EF

		enum_start 0x9f0 // 0x13E
	enum EVENT_9F0
	enum EVENT_9F1
	enum EVENT_9F2
	enum EVENT_9F3
	enum EVENT_9F4
	enum EVENT_9F5
	enum EVENT_9F6
	enum EVENT_9F7

		enum_start 0x9f8 // 0x13F
	enum EVENT_9F8
	enum EVENT_9F9
	enum EVENT_9FA
	enum EVENT_9FB
	enum EVENT_9FC
	enum EVENT_9FD
	enum EVENT_9FE
	enum EVENT_9FF

		enum_start 0xa00 // 0x140
	enum EVENT_A00
	enum EVENT_A01
	enum EVENT_A02
	enum EVENT_A03
	enum EVENT_A04
	enum EVENT_A05
	enum EVENT_A06
	enum EVENT_A07

		enum_start 0xa08 // 0x141
	enum EVENT_A08
	enum EVENT_A09
	enum EVENT_A0A
	enum EVENT_A0B
	enum EVENT_A0C
	enum EVENT_A0D
	enum EVENT_A0E
	enum EVENT_A0F

		enum_start 0xa10 // 0x142
	enum EVENT_A10
	enum EVENT_A11
	enum EVENT_A12
	enum EVENT_A13
	enum EVENT_A14
	enum EVENT_A15
	enum EVENT_A16
	enum EVENT_A17

		enum_start 0xa18 // 0x143
	enum EVENT_A18
	enum EVENT_A19
	enum EVENT_A1A
	enum EVENT_A1B
	enum EVENT_A1C
	enum EVENT_A1D
	enum EVENT_A1E
	enum EVENT_A1F

		enum_start 0xa20 // 0x144
	enum EVENT_A20
	enum EVENT_A21
	enum EVENT_A22
	enum EVENT_A23
	enum EVENT_A24
	enum EVENT_A25
	enum EVENT_A26
	enum EVENT_A27

		enum_start 0xa28 // 0x145
	enum EVENT_A28
	enum EVENT_A29
	enum EVENT_A2A
	enum EVENT_A2B
	enum EVENT_A2C
	enum EVENT_A2D
	enum EVENT_A2E
	enum EVENT_A2F

		enum_start 0xa30 // 0x146
	enum EVENT_A30
	enum EVENT_A31
	enum EVENT_A32
	enum EVENT_A33
	enum EVENT_A34
	enum EVENT_A35
	enum EVENT_A36
	enum EVENT_A37

		enum_start 0xa38 // 0x147
	enum EVENT_A38
	enum EVENT_A39
	enum EVENT_A3A
	enum EVENT_A3B
	enum EVENT_A3C
	enum EVENT_A3D
	enum EVENT_A3E
	enum EVENT_A3F

		enum_start 0xa40 // 0x148
	enum EVENT_A40
	enum EVENT_A41
	enum EVENT_A42
	enum EVENT_A43
	enum EVENT_A44
	enum EVENT_A45
	enum EVENT_A46
	enum EVENT_A47

		enum_start 0xa48 // 0x149
	enum EVENT_A48
	enum EVENT_A49
	enum EVENT_A4A
	enum EVENT_A4B
	enum EVENT_A4C
	enum EVENT_A4D
	enum EVENT_A4E
	enum EVENT_A4F

		enum_start 0xa50 // 0x14A
	enum EVENT_A50
	enum EVENT_A51
	enum EVENT_A52
	enum EVENT_A53
	enum EVENT_A54
	enum EVENT_A55
	enum EVENT_A56
	enum EVENT_A57

		enum_start 0xa58 // 0x14B
	enum EVENT_A58
	enum EVENT_A59
	enum EVENT_A5A
	enum EVENT_A5B
	enum EVENT_A5C
	enum EVENT_A5D
	enum EVENT_A5E
	enum EVENT_A5F

		enum_start 0xa60 // 0x14C
	enum EVENT_A60
	enum EVENT_A61
	enum EVENT_A62
	enum EVENT_A63
	enum EVENT_A64
	enum EVENT_A65
	enum EVENT_A66
	enum EVENT_A67

		enum_start 0xa68 // 0x14D
	enum EVENT_A68
	enum EVENT_A69
	enum EVENT_A6A
	enum EVENT_A6B
	enum EVENT_A6C
	enum EVENT_A6D
	enum EVENT_A6E
	enum EVENT_A6F

		enum_start 0xa70 // 0x14E
	enum EVENT_A70
	enum EVENT_A71
	enum EVENT_A72
	enum EVENT_A73
	enum EVENT_A74
	enum EVENT_A75
	enum EVENT_A76
	enum EVENT_A77

		enum_start 0xa78 // 0x14F
	enum EVENT_A78
	enum EVENT_A79
	enum EVENT_A7A
	enum EVENT_A7B
	enum EVENT_A7C
	enum EVENT_A7D
	enum EVENT_A7E
	enum EVENT_A7F

		enum_start 0xa80 // 0x150
	enum EVENT_A80
	enum EVENT_A81
	enum EVENT_A82
	enum EVENT_A83
	enum EVENT_A84
	enum EVENT_A85
	enum EVENT_A86
	enum EVENT_A87

		enum_start 0xa88 // 0x151
	enum EVENT_A88
	enum EVENT_A89
	enum EVENT_A8A
	enum EVENT_A8B
	enum EVENT_A8C
	enum EVENT_A8D
	enum EVENT_A8E
	enum EVENT_A8F

		enum_start 0xa90 // 0x152
	enum EVENT_A90
	enum EVENT_A91
	enum EVENT_A92
	enum EVENT_A93
	enum EVENT_A94
	enum EVENT_A95
	enum EVENT_A96
	enum EVENT_A97

		enum_start 0xa98 // 0x153
	enum EVENT_A98
	enum EVENT_A99
	enum EVENT_A9A
	enum EVENT_A9B
	enum EVENT_A9C
	enum EVENT_A9D
	enum EVENT_A9E
	enum EVENT_A9F

		enum_start 0xaa0 // 0x154
	enum EVENT_AA0
	enum EVENT_AA1
	enum EVENT_AA2
	enum EVENT_AA3
	enum EVENT_AA4
	enum EVENT_AA5
	enum EVENT_AA6
	enum EVENT_AA7

		enum_start 0xaa8 // 0x155
	enum EVENT_AA8
	enum EVENT_AA9
	enum EVENT_AAA
	enum EVENT_AAB
	enum EVENT_AAC
	enum EVENT_AAD
	enum EVENT_AAE
	enum EVENT_AAF

		enum_start 0xab0 // 0x156
	enum EVENT_AB0
	enum EVENT_AB1
	enum EVENT_AB2
	enum EVENT_AB3
	enum EVENT_AB4
	enum EVENT_AB5
	enum EVENT_AB6
	enum EVENT_AB7

		enum_start 0xab8 // 0x157
	enum EVENT_AB8
	enum EVENT_AB9
	enum EVENT_ABA
	enum EVENT_ABB
	enum EVENT_ABC
	enum EVENT_ABD
	enum EVENT_ABE
	enum EVENT_ABF

		enum_start 0xac0 // 0x158
	enum EVENT_AC0
	enum EVENT_AC1
	enum EVENT_AC2
	enum EVENT_AC3
	enum EVENT_AC4
	enum EVENT_AC5
	enum EVENT_AC6
	enum EVENT_AC7

		enum_start 0xac8 // 0x159
	enum EVENT_AC8
	enum EVENT_AC9
	enum EVENT_ACA
	enum EVENT_ACB
	enum EVENT_ACC
	enum EVENT_ACD
	enum EVENT_ACE
	enum EVENT_ACF

		enum_start 0xad0 // 0x15A
	enum EVENT_AD0
	enum EVENT_AD1
	enum EVENT_AD2
	enum EVENT_AD3
	enum EVENT_AD4
	enum EVENT_AD5
	enum EVENT_AD6
	enum EVENT_AD7

		enum_start 0xad8 // 0x15B
	enum EVENT_AD8
	enum EVENT_AD9
	enum EVENT_ADA
	enum EVENT_ADB
	enum EVENT_ADC
	enum EVENT_ADD
	enum EVENT_ADE
	enum EVENT_ADF

		enum_start 0xae0 // 0x15C
	enum EVENT_AE0
	enum EVENT_AE1
	enum EVENT_AE2
	enum EVENT_AE3
	enum EVENT_AE4
	enum EVENT_AE5
	enum EVENT_AE6
	enum EVENT_AE7

		enum_start 0xae8 // 0x15D
	enum EVENT_AE8
	enum EVENT_AE9
	enum EVENT_AEA
	enum EVENT_AEB
	enum EVENT_AEC
	enum EVENT_AED
	enum EVENT_AEE
	enum EVENT_AEF

		enum_start 0xaf0 // 0x15E
	enum EVENT_AF0
	enum EVENT_AF1
	enum EVENT_AF2
	enum EVENT_AF3
	enum EVENT_AF4
	enum EVENT_AF5
	enum EVENT_AF6
	enum EVENT_AF7

		enum_start 0xaf8 // 0x15F
	enum EVENT_AF8
	enum EVENT_AF9
	enum EVENT_AFA
	enum EVENT_AFB
	enum EVENT_AFC
	enum EVENT_AFD
	enum EVENT_AFE
	enum EVENT_AFF

		enum_start 0xb00 // 0x160
	enum EVENT_B00
	enum EVENT_B01
	enum EVENT_B02
	enum EVENT_B03
	enum EVENT_B04
	enum EVENT_B05
	enum EVENT_B06
	enum EVENT_B07

		enum_start 0xb08 // 0x161
	enum EVENT_B08
	enum EVENT_B09
	enum EVENT_B0A
	enum EVENT_B0B
	enum EVENT_B0C
	enum EVENT_B0D
	enum EVENT_B0E
	enum EVENT_B0F

		enum_start 0xb10 // 0x162
	enum EVENT_B10
	enum EVENT_B11
	enum EVENT_B12
	enum EVENT_B13
	enum EVENT_B14
	enum EVENT_B15
	enum EVENT_B16
	enum EVENT_B17

		enum_start 0xb18 // 0x163
	enum EVENT_B18
	enum EVENT_B19
	enum EVENT_B1A
	enum EVENT_B1B
	enum EVENT_B1C
	enum EVENT_B1D
	enum EVENT_B1E
	enum EVENT_B1F

		enum_start 0xb20 // 0x164
	enum EVENT_B20
	enum EVENT_B21
	enum EVENT_B22
	enum EVENT_B23
	enum EVENT_B24
	enum EVENT_B25
	enum EVENT_B26
	enum EVENT_B27

		enum_start 0xb28 // 0x165
	enum EVENT_B28
	enum EVENT_B29
	enum EVENT_B2A
	enum EVENT_B2B
	enum EVENT_B2C
	enum EVENT_B2D
	enum EVENT_B2E
	enum EVENT_B2F

		enum_start 0xb30 // 0x166
	enum EVENT_B30
	enum EVENT_B31
	enum EVENT_B32
	enum EVENT_B33
	enum EVENT_B34
	enum EVENT_B35
	enum EVENT_B36
	enum EVENT_B37

		enum_start 0xb38 // 0x167
	enum EVENT_B38
	enum EVENT_B39
	enum EVENT_B3A
	enum EVENT_B3B
	enum EVENT_B3C
	enum EVENT_B3D
	enum EVENT_B3E
	enum EVENT_B3F

		enum_start 0xb40 // 0x168
	enum EVENT_B40
	enum EVENT_B41
	enum EVENT_B42
	enum EVENT_B43
	enum EVENT_B44
	enum EVENT_B45
	enum EVENT_B46
	enum EVENT_B47

		enum_start 0xb48 // 0x169
	enum EVENT_B48
	enum EVENT_B49
	enum EVENT_B4A
	enum EVENT_B4B
	enum EVENT_B4C
	enum EVENT_B4D
	enum EVENT_B4E
	enum EVENT_B4F

		enum_start 0xb50 // 0x16A
	enum EVENT_B50
	enum EVENT_B51
	enum EVENT_B52
	enum EVENT_B53
	enum EVENT_B54
	enum EVENT_B55
	enum EVENT_B56
	enum EVENT_B57

		enum_start 0xb58 // 0x16B
	enum EVENT_B58
	enum EVENT_B59
	enum EVENT_B5A
	enum EVENT_B5B
	enum EVENT_B5C
	enum EVENT_B5D
	enum EVENT_B5E
	enum EVENT_B5F

		enum_start 0xb60 // 0x16C
	enum EVENT_B60
	enum EVENT_B61
	enum EVENT_B62
	enum EVENT_B63
	enum EVENT_B64
	enum EVENT_B65
	enum EVENT_B66
	enum EVENT_B67

		enum_start 0xb68 // 0x16D
	enum EVENT_B68
	enum EVENT_B69
	enum EVENT_B6A
	enum EVENT_B6B
	enum EVENT_B6C
	enum EVENT_B6D
	enum EVENT_B6E
	enum EVENT_B6F

		enum_start 0xb70 // 0x16E
	enum EVENT_B70
	enum EVENT_B71
	enum EVENT_B72
	enum EVENT_B73
	enum EVENT_B74
	enum EVENT_B75
	enum EVENT_B76
	enum EVENT_B77

		enum_start 0xb78 // 0x16F
	enum EVENT_B78
	enum EVENT_B79
	enum EVENT_B7A
	enum EVENT_B7B
	enum EVENT_B7C
	enum EVENT_B7D
	enum EVENT_B7E
	enum EVENT_B7F

		enum_start 0xb80 // 0x170
	enum EVENT_B80
	enum EVENT_B81
	enum EVENT_B82
	enum EVENT_B83
	enum EVENT_B84
	enum EVENT_B85
	enum EVENT_B86
	enum EVENT_B87

		enum_start 0xb88 // 0x171
	enum EVENT_B88
	enum EVENT_B89
	enum EVENT_B8A
	enum EVENT_B8B
	enum EVENT_B8C
	enum EVENT_B8D
	enum EVENT_B8E
	enum EVENT_B8F

		enum_start 0xb90 // 0x172
	enum EVENT_B90
	enum EVENT_B91
	enum EVENT_B92
	enum EVENT_B93
	enum EVENT_B94
	enum EVENT_B95
	enum EVENT_B96
	enum EVENT_B97

		enum_start 0xb98 // 0x173
	enum EVENT_B98
	enum EVENT_B99
	enum EVENT_B9A
	enum EVENT_B9B
	enum EVENT_B9C
	enum EVENT_B9D
	enum EVENT_B9E
	enum EVENT_B9F

		enum_start 0xba0 // 0x174
	enum EVENT_BA0
	enum EVENT_BA1
	enum EVENT_BA2
	enum EVENT_BA3
	enum EVENT_BA4
	enum EVENT_BA5
	enum EVENT_BA6
	enum EVENT_BA7

		enum_start 0xba8 // 0x175
	enum EVENT_BA8
	enum EVENT_BA9
	enum EVENT_BAA
	enum EVENT_BAB
	enum EVENT_BAC
	enum EVENT_BAD
	enum EVENT_BAE
	enum EVENT_BAF

		enum_start 0xbb0 // 0x176
	enum EVENT_BB0
	enum EVENT_BB1
	enum EVENT_BB2
	enum EVENT_BB3
	enum EVENT_BB4
	enum EVENT_BB5
	enum EVENT_BB6
	enum EVENT_BB7

		enum_start 0xbb8 // 0x177
	enum EVENT_BB8
	enum EVENT_BB9
	enum EVENT_BBA
	enum EVENT_BBB
	enum EVENT_BBC
	enum EVENT_BBD
	enum EVENT_BBE
	enum EVENT_BBF

		enum_start 0xbc0 // 0x178
	enum EVENT_BC0
	enum EVENT_BC1
	enum EVENT_BC2
	enum EVENT_BC3
	enum EVENT_BC4
	enum EVENT_BC5
	enum EVENT_BC6
	enum EVENT_BC7

		enum_start 0xbc8 // 0x179
	enum EVENT_BC8
	enum EVENT_BC9
	enum EVENT_BCA
	enum EVENT_BCB
	enum EVENT_BCC
	enum EVENT_BCD
	enum EVENT_BCE
	enum EVENT_BCF

		enum_start 0xbd0 // 0x17A
	enum EVENT_BD0
	enum EVENT_BD1
	enum EVENT_BD2
	enum EVENT_BD3
	enum EVENT_BD4
	enum EVENT_BD5
	enum EVENT_BD6
	enum EVENT_BD7

		enum_start 0xbd8 // 0x17B
	enum EVENT_BD8
	enum EVENT_BD9
	enum EVENT_BDA
	enum EVENT_BDB
	enum EVENT_BDC
	enum EVENT_BDD
	enum EVENT_BDE
	enum EVENT_BDF

		enum_start 0xbe0 // 0x17C
	enum EVENT_BE0
	enum EVENT_BE1
	enum EVENT_BE2
	enum EVENT_BE3
	enum EVENT_BE4
	enum EVENT_BE5
	enum EVENT_BE6
	enum EVENT_BE7

		enum_start 0xbe8 // 0x17D
	enum EVENT_BE8
	enum EVENT_BE9
	enum EVENT_BEA
	enum EVENT_BEB
	enum EVENT_BEC
	enum EVENT_BED
	enum EVENT_BEE
	enum EVENT_BEF

		enum_start 0xbf0 // 0x17E
	enum EVENT_BF0
	enum EVENT_BF1
	enum EVENT_BF2
	enum EVENT_BF3
	enum EVENT_BF4
	enum EVENT_BF5
	enum EVENT_BF6
	enum EVENT_BF7

		enum_start 0xbf8 // 0x17F
	enum EVENT_BF8
	enum EVENT_BF9
	enum EVENT_BFA
	enum EVENT_BFB
	enum EVENT_BFC
	enum EVENT_BFD
	enum EVENT_BFE
	enum EVENT_BFF

		enum_start 0xc00 // 0x180
	enum EVENT_C00
	enum EVENT_C01
	enum EVENT_C02
	enum EVENT_C03
	enum EVENT_C04
	enum EVENT_C05
	enum EVENT_C06
	enum EVENT_C07

		enum_start 0xc08 // 0x181
	enum EVENT_C08
	enum EVENT_C09
	enum EVENT_C0A
	enum EVENT_C0B
	enum EVENT_C0C
	enum EVENT_C0D
	enum EVENT_C0E
	enum EVENT_C0F

		enum_start 0xc10 // 0x182
	enum EVENT_C10
	enum EVENT_C11
	enum EVENT_C12
	enum EVENT_C13
	enum EVENT_C14
	enum EVENT_C15
	enum EVENT_C16
	enum EVENT_C17

		enum_start 0xc18 // 0x183
	enum EVENT_C18
	enum EVENT_C19
	enum EVENT_C1A
	enum EVENT_C1B
	enum EVENT_C1C
	enum EVENT_C1D
	enum EVENT_C1E
	enum EVENT_C1F

		enum_start 0xc20 // 0x184
	enum EVENT_C20
	enum EVENT_C21
	enum EVENT_C22
	enum EVENT_C23
	enum EVENT_C24
	enum EVENT_C25
	enum EVENT_C26
	enum EVENT_C27

		enum_start 0xc28 // 0x185
	enum EVENT_C28
	enum EVENT_C29
	enum EVENT_C2A
	enum EVENT_C2B
	enum EVENT_C2C
	enum EVENT_C2D
	enum EVENT_C2E
	enum EVENT_C2F

		enum_start 0xc30 // 0x186
	enum EVENT_C30
	enum EVENT_C31
	enum EVENT_C32
	enum EVENT_C33
	enum EVENT_C34
	enum EVENT_C35
	enum EVENT_C36
	enum EVENT_C37

		enum_start 0xc38 // 0x187
	enum EVENT_C38
	enum EVENT_C39
	enum EVENT_C3A
	enum EVENT_C3B
	enum EVENT_C3C
	enum EVENT_C3D
	enum EVENT_C3E
	enum EVENT_C3F

		enum_start 0xc40 // 0x188
	enum EVENT_C40
	enum EVENT_C41
	enum EVENT_C42
	enum EVENT_C43
	enum EVENT_C44
	enum EVENT_C45
	enum EVENT_C46
	enum EVENT_C47

		enum_start 0xc48 // 0x189
	enum EVENT_C48
	enum EVENT_C49
	enum EVENT_C4A
	enum EVENT_C4B
	enum EVENT_C4C
	enum EVENT_C4D
	enum EVENT_C4E
	enum EVENT_C4F

		enum_start 0xc50 // 0x18A
	enum EVENT_C50
	enum EVENT_C51
	enum EVENT_C52
	enum EVENT_C53
	enum EVENT_C54
	enum EVENT_C55
	enum EVENT_C56
	enum EVENT_C57

		enum_start 0xc58 // 0x18B
	enum EVENT_C58
	enum EVENT_C59
	enum EVENT_C5A
	enum EVENT_C5B
	enum EVENT_C5C
	enum EVENT_C5D
	enum EVENT_C5E
	enum EVENT_C5F

		enum_start 0xc60 // 0x18C
	enum EVENT_C60
	enum EVENT_C61
	enum EVENT_C62
	enum EVENT_C63
	enum EVENT_C64
	enum EVENT_C65
	enum EVENT_C66
	enum EVENT_C67

		enum_start 0xc68 // 0x18D
	enum EVENT_C68
	enum EVENT_C69
	enum EVENT_C6A
	enum EVENT_C6B
	enum EVENT_C6C
	enum EVENT_C6D
	enum EVENT_C6E
	enum EVENT_C6F

		enum_start 0xc70 // 0x18E
	enum EVENT_C70
	enum EVENT_C71
	enum EVENT_C72
	enum EVENT_C73
	enum EVENT_C74
	enum EVENT_C75
	enum EVENT_C76
	enum EVENT_C77

		enum_start 0xc78 // 0x18F
	enum EVENT_C78
	enum EVENT_C79
	enum EVENT_C7A
	enum EVENT_C7B
	enum EVENT_C7C
	enum EVENT_C7D
	enum EVENT_C7E
	enum EVENT_C7F

		enum_start 0xc80 // 0x190
	enum EVENT_C80
	enum EVENT_C81
	enum EVENT_C82
	enum EVENT_C83
	enum EVENT_C84
	enum EVENT_C85
	enum EVENT_C86
	enum EVENT_C87

		enum_start 0xc88 // 0x191
	enum EVENT_C88
	enum EVENT_C89
	enum EVENT_C8A
	enum EVENT_C8B
	enum EVENT_C8C
	enum EVENT_C8D
	enum EVENT_C8E
	enum EVENT_C8F

		enum_start 0xc90 // 0x192
	enum EVENT_C90
	enum EVENT_C91
	enum EVENT_C92
	enum EVENT_C93
	enum EVENT_C94
	enum EVENT_C95
	enum EVENT_C96
	enum EVENT_C97

		enum_start 0xc98 // 0x193
	enum EVENT_C98
	enum EVENT_C99
	enum EVENT_C9A
	enum EVENT_C9B
	enum EVENT_C9C
	enum EVENT_C9D
	enum EVENT_C9E
	enum EVENT_C9F

		enum_start 0xca0 // 0x194
	enum EVENT_CA0
	enum EVENT_CA1
	enum EVENT_CA2
	enum EVENT_CA3
	enum EVENT_CA4
	enum EVENT_CA5
	enum EVENT_CA6
	enum EVENT_CA7

		enum_start 0xca8 // 0x195
	enum EVENT_CA8
	enum EVENT_CA9
	enum EVENT_CAA
	enum EVENT_CAB
	enum EVENT_CAC
	enum EVENT_CAD
	enum EVENT_CAE
	enum EVENT_CAF

		enum_start 0xcb0 // 0x196
	enum EVENT_CB0
	enum EVENT_CB1
	enum EVENT_CB2
	enum EVENT_CB3
	enum EVENT_CB4
	enum EVENT_CB5
	enum EVENT_CB6
	enum EVENT_CB7

		enum_start 0xcb8 // 0x197
	enum EVENT_CB8
	enum EVENT_CB9
	enum EVENT_CBA
	enum EVENT_CBB
	enum EVENT_CBC
	enum EVENT_CBD
	enum EVENT_CBE
	enum EVENT_CBF

		enum_start 0xcc0 // 0x198
	enum EVENT_CC0
	enum EVENT_CC1
	enum EVENT_CC2
	enum EVENT_CC3
	enum EVENT_CC4
	enum EVENT_CC5
	enum EVENT_CC6
	enum EVENT_CC7

		enum_start 0xcc8 // 0x199
	enum EVENT_CC8
	enum EVENT_CC9
	enum EVENT_CCA
	enum EVENT_CCB
	enum EVENT_CCC
	enum EVENT_CCD
	enum EVENT_CCE
	enum EVENT_CCF

		enum_start 0xcd0 // 0x19A
	enum EVENT_CD0
	enum EVENT_CD1
	enum EVENT_CD2
	enum EVENT_CD3
	enum EVENT_CD4
	enum EVENT_CD5
	enum EVENT_CD6
	enum EVENT_CD7

		enum_start 0xcd8 // 0x19B
	enum EVENT_CD8
	enum EVENT_CD9
	enum EVENT_CDA
	enum EVENT_CDB
	enum EVENT_CDC
	enum EVENT_CDD
	enum EVENT_CDE
	enum EVENT_CDF

		enum_start 0xce0 // 0x19C
	enum EVENT_CE0
	enum EVENT_CE1
	enum EVENT_CE2
	enum EVENT_CE3
	enum EVENT_CE4
	enum EVENT_CE5
	enum EVENT_CE6
	enum EVENT_CE7

		enum_start 0xce8 // 0x19D
	enum EVENT_CE8
	enum EVENT_CE9
	enum EVENT_CEA
	enum EVENT_CEB
	enum EVENT_CEC
	enum EVENT_CED
	enum EVENT_CEE
	enum EVENT_CEF

		enum_start 0xcf0 // 0x19E
	enum EVENT_CF0
	enum EVENT_CF1
	enum EVENT_CF2
	enum EVENT_CF3
	enum EVENT_CF4
	enum EVENT_CF5
	enum EVENT_CF6
	enum EVENT_CF7

		enum_start 0xcf8 // 0x19F
	enum EVENT_CF8
	enum EVENT_CF9
	enum EVENT_CFA
	enum EVENT_CFB
	enum EVENT_CFC
	enum EVENT_CFD
	enum EVENT_CFE
	enum EVENT_CFF

		enum_start 0xd00 // 0x1A0
	enum EVENT_D00
	enum EVENT_D01
	enum EVENT_D02
	enum EVENT_D03
	enum EVENT_D04
	enum EVENT_D05
	enum EVENT_D06
	enum EVENT_D07

		enum_start 0xd08 // 0x1A1
	enum EVENT_D08
	enum EVENT_D09
	enum EVENT_D0A
	enum EVENT_D0B
	enum EVENT_D0C
	enum EVENT_D0D
	enum EVENT_D0E
	enum EVENT_D0F

		enum_start 0xd10 // 0x1A2
	enum EVENT_D10
	enum EVENT_D11
	enum EVENT_D12
	enum EVENT_D13
	enum EVENT_D14
	enum EVENT_D15
	enum EVENT_D16
	enum EVENT_D17

		enum_start 0xd18 // 0x1A3
	enum EVENT_D18
	enum EVENT_D19
	enum EVENT_D1A
	enum EVENT_D1B
	enum EVENT_D1C
	enum EVENT_D1D
	enum EVENT_D1E
	enum EVENT_D1F

		enum_start 0xd20 // 0x1A4
	enum EVENT_D20
	enum EVENT_D21
	enum EVENT_D22
	enum EVENT_D23
	enum EVENT_D24
	enum EVENT_D25
	enum EVENT_D26
	enum EVENT_D27

		enum_start 0xd28 // 0x1A5
	enum EVENT_D28
	enum EVENT_D29
	enum EVENT_D2A
	enum EVENT_D2B
	enum EVENT_D2C
	enum EVENT_D2D
	enum EVENT_D2E
	enum EVENT_D2F

		enum_start 0xd30 // 0x1A6
	enum EVENT_D30
	enum EVENT_D31
	enum EVENT_D32
	enum EVENT_D33
	enum EVENT_D34
	enum EVENT_D35
	enum EVENT_D36
	enum EVENT_D37

		enum_start 0xd38 // 0x1A7
	enum EVENT_D38
	enum EVENT_D39
	enum EVENT_D3A
	enum EVENT_D3B
	enum EVENT_D3C
	enum EVENT_D3D
	enum EVENT_D3E
	enum EVENT_D3F

		enum_start 0xd40 // 0x1A8
	enum EVENT_D40
	enum EVENT_D41
	enum EVENT_D42
	enum EVENT_D43
	enum EVENT_D44
	enum EVENT_D45
	enum EVENT_D46
	enum EVENT_D47

		enum_start 0xd48 // 0x1A9
	enum EVENT_D48
	enum EVENT_D49
	enum EVENT_D4A
	enum EVENT_D4B
	enum EVENT_D4C
	enum EVENT_D4D
	enum EVENT_D4E
	enum EVENT_D4F

		enum_start 0xd50 // 0x1AA
	enum EVENT_D50
	enum EVENT_D51
	enum EVENT_D52
	enum EVENT_D53
	enum EVENT_D54
	enum EVENT_D55
	enum EVENT_D56
	enum EVENT_D57

		enum_start 0xd58 // 0x1AB
	enum EVENT_D58
	enum EVENT_D59
	enum EVENT_D5A
	enum EVENT_D5B
	enum EVENT_D5C
	enum EVENT_D5D
	enum EVENT_D5E
	enum EVENT_D5F

		enum_start 0xd60 // 0x1AC
	enum EVENT_D60
	enum EVENT_D61
	enum EVENT_D62
	enum EVENT_D63
	enum EVENT_D64
	enum EVENT_D65
	enum EVENT_D66
	enum EVENT_D67

		enum_start 0xd68 // 0x1AD
	enum EVENT_D68
	enum EVENT_D69
	enum EVENT_D6A
	enum EVENT_D6B
	enum EVENT_D6C
	enum EVENT_D6D
	enum EVENT_D6E
	enum EVENT_D6F

		enum_start 0xd70 // 0x1AE
	enum EVENT_D70
	enum EVENT_D71
	enum EVENT_D72
	enum EVENT_D73
	enum EVENT_D74
	enum EVENT_D75
	enum EVENT_D76
	enum EVENT_D77

		enum_start 0xd78 // 0x1AF
	enum EVENT_D78
	enum EVENT_D79
	enum EVENT_D7A
	enum EVENT_D7B
	enum EVENT_D7C
	enum EVENT_D7D
	enum EVENT_D7E
	enum EVENT_D7F

		enum_start 0xd80 // 0x1B0
	enum EVENT_D80
	enum EVENT_D81
	enum EVENT_D82
	enum EVENT_D83
	enum EVENT_D84
	enum EVENT_D85
	enum EVENT_D86
	enum EVENT_D87

		enum_start 0xd88 // 0x1B1
	enum EVENT_D88
	enum EVENT_D89
	enum EVENT_D8A
	enum EVENT_D8B
	enum EVENT_D8C
	enum EVENT_D8D
	enum EVENT_D8E
	enum EVENT_D8F

		enum_start 0xd90 // 0x1B2
	enum EVENT_D90
	enum EVENT_D91
	enum EVENT_D92
	enum EVENT_D93
	enum EVENT_D94
	enum EVENT_D95
	enum EVENT_D96
	enum EVENT_D97

		enum_start 0xd98 // 0x1B3
	enum EVENT_D98
	enum EVENT_D99
	enum EVENT_D9A
	enum EVENT_D9B
	enum EVENT_D9C
	enum EVENT_D9D
	enum EVENT_D9E
	enum EVENT_D9F

		enum_start 0xda0 // 0x1B4
	enum EVENT_DA0
	enum EVENT_DA1
	enum EVENT_DA2
	enum EVENT_DA3
	enum EVENT_DA4
	enum EVENT_DA5
	enum EVENT_DA6
	enum EVENT_DA7

		enum_start 0xda8 // 0x1B5
	enum EVENT_DA8
	enum EVENT_DA9
	enum EVENT_DAA
	enum EVENT_DAB
	enum EVENT_DAC
	enum EVENT_DAD
	enum EVENT_DAE
	enum EVENT_DAF

		enum_start 0xdb0 // 0x1B6
	enum EVENT_DB0
	enum EVENT_DB1
	enum EVENT_DB2
	enum EVENT_DB3
	enum EVENT_DB4
	enum EVENT_DB5
	enum EVENT_DB6
	enum EVENT_DB7

		enum_start 0xdb8 // 0x1B7
	enum EVENT_DB8
	enum EVENT_DB9
	enum EVENT_DBA
	enum EVENT_DBB
	enum EVENT_DBC
	enum EVENT_DBD
	enum EVENT_DBE
	enum EVENT_DBF

		enum_start 0xdc0 // 0x1B8
	enum EVENT_DC0
	enum EVENT_DC1
	enum EVENT_DC2
	enum EVENT_DC3
	enum EVENT_DC4
	enum EVENT_DC5
	enum EVENT_DC6
	enum EVENT_DC7

		enum_start 0xdc8 // 0x1B9
	enum EVENT_DC8
	enum EVENT_DC9
	enum EVENT_DCA
	enum EVENT_DCB
	enum EVENT_DCC
	enum EVENT_DCD
	enum EVENT_DCE
	enum EVENT_DCF

		enum_start 0xdd0 // 0x1BA
	enum EVENT_DD0
	enum EVENT_DD1
	enum EVENT_DD2
	enum EVENT_DD3
	enum EVENT_DD4
	enum EVENT_DD5
	enum EVENT_DD6
	enum EVENT_DD7

		enum_start 0xdd8 // 0x1BB
	enum EVENT_DD8
	enum EVENT_DD9
	enum EVENT_DDA
	enum EVENT_DDB
	enum EVENT_DDC
	enum EVENT_DDD
	enum EVENT_DDE
	enum EVENT_DDF

		enum_start 0xde0 // 0x1BC
	enum EVENT_DE0
	enum EVENT_DE1
	enum EVENT_DE2
	enum EVENT_DE3
	enum EVENT_DE4
	enum EVENT_DE5
	enum EVENT_DE6
	enum EVENT_DE7

		enum_start 0xde8 // 0x1BD
	enum EVENT_DE8
	enum EVENT_DE9
	enum EVENT_DEA
	enum EVENT_DEB
	enum EVENT_DEC
	enum EVENT_DED
	enum EVENT_DEE
	enum EVENT_DEF

		enum_start 0xdf0 // 0x1BE
	enum EVENT_DF0
	enum EVENT_DF1
	enum EVENT_DF2
	enum EVENT_DF3
	enum EVENT_DF4
	enum EVENT_DF5
	enum EVENT_DF6
	enum EVENT_DF7

		enum_start 0xdf8 // 0x1BF
	enum EVENT_DF8
	enum EVENT_DF9
	enum EVENT_DFA
	enum EVENT_DFB
	enum EVENT_DFC
	enum EVENT_DFD
	enum EVENT_DFE
	enum EVENT_DFF

		enum_start 0xe00 // 0x1C0
	enum EVENT_E00
	enum EVENT_E01
	enum EVENT_E02
	enum EVENT_E03
	enum EVENT_E04
	enum EVENT_E05
	enum EVENT_E06
	enum EVENT_E07

		enum_start 0xe08 // 0x1C1
	enum EVENT_E08
	enum EVENT_E09
	enum EVENT_E0A
	enum EVENT_E0B
	enum EVENT_E0C
	enum EVENT_E0D
	enum EVENT_E0E
	enum EVENT_E0F

		enum_start 0xe10 // 0x1C2
	enum EVENT_E10
	enum EVENT_E11
	enum EVENT_E12
	enum EVENT_E13
	enum EVENT_E14
	enum EVENT_E15
	enum EVENT_E16
	enum EVENT_E17

		enum_start 0xe18 // 0x1C3
	enum EVENT_E18
	enum EVENT_E19
	enum EVENT_E1A
	enum EVENT_E1B
	enum EVENT_E1C
	enum EVENT_E1D
	enum EVENT_E1E
	enum EVENT_E1F

		enum_start 0xe20 // 0x1C4
	enum EVENT_E20
	enum EVENT_E21
	enum EVENT_E22
	enum EVENT_E23
	enum EVENT_E24
	enum EVENT_E25
	enum EVENT_E26
	enum EVENT_E27

		enum_start 0xe28 // 0x1C5
	enum EVENT_E28
	enum EVENT_E29
	enum EVENT_E2A
	enum EVENT_E2B
	enum EVENT_E2C
	enum EVENT_E2D
	enum EVENT_E2E
	enum EVENT_E2F

		enum_start 0xe30 // 0x1C6
	enum EVENT_E30
	enum EVENT_E31
	enum EVENT_E32
	enum EVENT_E33
	enum EVENT_E34
	enum EVENT_E35
	enum EVENT_E36
	enum EVENT_E37

		enum_start 0xe38 // 0x1C7
	enum EVENT_E38
	enum EVENT_E39
	enum EVENT_E3A
	enum EVENT_E3B
	enum EVENT_E3C
	enum EVENT_E3D
	enum EVENT_E3E
	enum EVENT_E3F

		enum_start 0xe40 // 0x1C8
	enum EVENT_E40
	enum EVENT_E41
	enum EVENT_E42
	enum EVENT_E43
	enum EVENT_E44
	enum EVENT_E45
	enum EVENT_E46
	enum EVENT_E47

		enum_start 0xe48 // 0x1C9
	enum EVENT_E48
	enum EVENT_E49
	enum EVENT_E4A
	enum EVENT_E4B
	enum EVENT_E4C
	enum EVENT_E4D
	enum EVENT_E4E
	enum EVENT_E4F

		enum_start 0xe50 // 0x1CA
	enum EVENT_E50
	enum EVENT_E51
	enum EVENT_E52
	enum EVENT_E53
	enum EVENT_E54
	enum EVENT_E55
	enum EVENT_E56
	enum EVENT_E57

		enum_start 0xe58 // 0x1CB
	enum EVENT_E58
	enum EVENT_E59
	enum EVENT_E5A
	enum EVENT_E5B
	enum EVENT_E5C
	enum EVENT_E5D
	enum EVENT_E5E
	enum EVENT_E5F

		enum_start 0xe60 // 0x1CC
	enum EVENT_E60
	enum EVENT_E61
	enum EVENT_E62
	enum EVENT_E63
	enum EVENT_E64
	enum EVENT_E65
	enum EVENT_E66
	enum EVENT_E67

		enum_start 0xe68 // 0x1CD
	enum EVENT_E68
	enum EVENT_E69
	enum EVENT_E6A
	enum EVENT_E6B
	enum EVENT_E6C
	enum EVENT_E6D
	enum EVENT_E6E
	enum EVENT_E6F

		enum_start 0xe70 // 0x1CE
	enum EVENT_E70
	enum EVENT_E71
	enum EVENT_E72
	enum EVENT_E73
	enum EVENT_E74
	enum EVENT_E75
	enum EVENT_E76
	enum EVENT_E77

		enum_start 0xe78 // 0x1CF
	enum EVENT_E78
	enum EVENT_E79
	enum EVENT_E7A
	enum EVENT_E7B
	enum EVENT_E7C
	enum EVENT_E7D
	enum EVENT_E7E
	enum EVENT_E7F

		enum_start 0xe80 // 0x1D0
	enum EVENT_E80
	enum EVENT_E81
	enum EVENT_E82
	enum EVENT_E83
	enum EVENT_E84
	enum EVENT_E85
	enum EVENT_E86
	enum EVENT_E87

		enum_start 0xe88 // 0x1D1
	enum EVENT_E88
	enum EVENT_E89
	enum EVENT_E8A
	enum EVENT_E8B
	enum EVENT_E8C
	enum EVENT_E8D
	enum EVENT_E8E
	enum EVENT_E8F

		enum_start 0xe90 // 0x1D2
	enum EVENT_E90
	enum EVENT_E91
	enum EVENT_E92
	enum EVENT_E93
	enum EVENT_E94
	enum EVENT_E95
	enum EVENT_E96
	enum EVENT_E97

		enum_start 0xe98 // 0x1D3
	enum EVENT_E98
	enum EVENT_E99
	enum EVENT_E9A
	enum EVENT_E9B
	enum EVENT_E9C
	enum EVENT_E9D
	enum EVENT_E9E
	enum EVENT_E9F

		enum_start 0xea0 // 0x1D4
	enum EVENT_EA0
	enum EVENT_EA1
	enum EVENT_EA2
	enum EVENT_EA3
	enum EVENT_EA4
	enum EVENT_EA5
	enum EVENT_EA6
	enum EVENT_EA7

		enum_start 0xea8 // 0x1D5
	enum EVENT_EA8
	enum EVENT_EA9
	enum EVENT_EAA
	enum EVENT_EAB
	enum EVENT_EAC
	enum EVENT_EAD
	enum EVENT_EAE
	enum EVENT_EAF

		enum_start 0xeb0 // 0x1D6
	enum EVENT_EB0
	enum EVENT_EB1
	enum EVENT_EB2
	enum EVENT_EB3
	enum EVENT_EB4
	enum EVENT_EB5
	enum EVENT_EB6
	enum EVENT_EB7

		enum_start 0xeb8 // 0x1D7
	enum EVENT_EB8
	enum EVENT_EB9
	enum EVENT_EBA
	enum EVENT_EBB
	enum EVENT_EBC
	enum EVENT_EBD
	enum EVENT_EBE
	enum EVENT_EBF

		enum_start 0xec0 // 0x1D8
	enum EVENT_EC0
	enum EVENT_EC1
	enum EVENT_EC2
	enum EVENT_EC3
	enum EVENT_EC4
	enum EVENT_EC5
	enum EVENT_EC6
	enum EVENT_EC7

		enum_start 0xec8 // 0x1D9
	enum EVENT_EC8
	enum EVENT_EC9
	enum EVENT_ECA
	enum EVENT_ECB
	enum EVENT_ECC
	enum EVENT_ECD
	enum EVENT_ECE
	enum EVENT_ECF

		enum_start 0xed0 // 0x1DA
	enum EVENT_ED0
	enum EVENT_ED1
	enum EVENT_ED2
	enum EVENT_ED3
	enum EVENT_ED4
	enum EVENT_ED5
	enum EVENT_ED6
	enum EVENT_ED7

		enum_start 0xed8 // 0x1DB
	enum EVENT_ED8
	enum EVENT_ED9
	enum EVENT_EDA
	enum EVENT_EDB
	enum EVENT_EDC
	enum EVENT_EDD
	enum EVENT_EDE
	enum EVENT_EDF

		enum_start 0xee0 // 0x1DC
	enum EVENT_EE0
	enum EVENT_EE1
	enum EVENT_EE2
	enum EVENT_EE3
	enum EVENT_EE4
	enum EVENT_EE5
	enum EVENT_EE6
	enum EVENT_EE7

		enum_start 0xee8 // 0x1DD
	enum EVENT_EE8
	enum EVENT_EE9
	enum EVENT_EEA
	enum EVENT_EEB
	enum EVENT_EEC
	enum EVENT_EED
	enum EVENT_EEE
	enum EVENT_EEF

		enum_start 0xef0 // 0x1DE
	enum EVENT_EF0
	enum EVENT_EF1
	enum EVENT_EF2
	enum EVENT_EF3
	enum EVENT_EF4
	enum EVENT_EF5
	enum EVENT_EF6
	enum EVENT_EF7

		enum_start 0xef8 // 0x1DF
	enum EVENT_EF8
	enum EVENT_EF9
	enum EVENT_EFA
	enum EVENT_EFB
	enum EVENT_EFC
	enum EVENT_EFD
	enum EVENT_EFE
	enum EVENT_EFF

		enum_start 0xf00 // 0x1E0
	enum EVENT_F00
	enum EVENT_F01
	enum EVENT_F02
	enum EVENT_F03
	enum EVENT_F04
	enum EVENT_F05
	enum EVENT_F06
	enum EVENT_F07

		enum_start 0xf08 // 0x1E1
	enum EVENT_F08
	enum EVENT_F09
	enum EVENT_F0A
	enum EVENT_F0B
	enum EVENT_F0C
	enum EVENT_F0D
	enum EVENT_F0E
	enum EVENT_F0F

		enum_start 0xf10 // 0x1E2
	enum EVENT_F10
	enum EVENT_F11
	enum EVENT_F12
	enum EVENT_F13
	enum EVENT_F14
	enum EVENT_F15
	enum EVENT_F16
	enum EVENT_F17

		enum_start 0xf18 // 0x1E3
	enum EVENT_F18
	enum EVENT_F19
	enum EVENT_F1A
	enum EVENT_F1B
	enum EVENT_F1C
	enum EVENT_F1D
	enum EVENT_F1E
	enum EVENT_F1F

		enum_start 0xf20 // 0x1E4
	enum EVENT_F20
	enum EVENT_F21
	enum EVENT_F22
	enum EVENT_F23
	enum EVENT_F24
	enum EVENT_F25
	enum EVENT_F26
	enum EVENT_F27

		enum_start 0xf28 // 0x1E5
	enum EVENT_F28
	enum EVENT_F29
	enum EVENT_F2A
	enum EVENT_F2B
	enum EVENT_F2C
	enum EVENT_F2D
	enum EVENT_F2E
	enum EVENT_F2F

		enum_start 0xf30 // 0x1E6
	enum EVENT_F30
	enum EVENT_F31
	enum EVENT_F32
	enum EVENT_F33
	enum EVENT_F34
	enum EVENT_F35
	enum EVENT_F36
	enum EVENT_F37

		enum_start 0xf38 // 0x1E7
	enum EVENT_F38
	enum EVENT_F39
	enum EVENT_F3A
	enum EVENT_F3B
	enum EVENT_F3C
	enum EVENT_F3D
	enum EVENT_F3E
	enum EVENT_F3F

		enum_start 0xf40 // 0x1E8
	enum EVENT_F40
	enum EVENT_F41
	enum EVENT_F42
	enum EVENT_F43
	enum EVENT_F44
	enum EVENT_F45
	enum EVENT_F46
	enum EVENT_F47

		enum_start 0xf48 // 0x1E9
	enum EVENT_F48
	enum EVENT_F49
	enum EVENT_F4A
	enum EVENT_F4B
	enum EVENT_F4C
	enum EVENT_F4D
	enum EVENT_F4E
	enum EVENT_F4F

		enum_start 0xf50 // 0x1EA
	enum EVENT_F50
	enum EVENT_F51
	enum EVENT_F52
	enum EVENT_F53
	enum EVENT_F54
	enum EVENT_F55
	enum EVENT_F56
	enum EVENT_F57

		enum_start 0xf58 // 0x1EB
	enum EVENT_F58
	enum EVENT_F59
	enum EVENT_F5A
	enum EVENT_F5B
	enum EVENT_F5C
	enum EVENT_F5D
	enum EVENT_F5E
	enum EVENT_F5F

		enum_start 0xf60 // 0x1EC
	enum EVENT_F60
	enum EVENT_F61
	enum EVENT_F62
	enum EVENT_F63
	enum EVENT_F64
	enum EVENT_F65
	enum EVENT_F66
	enum EVENT_F67

		enum_start 0xf68 // 0x1ED
	enum EVENT_F68
	enum EVENT_F69
	enum EVENT_F6A
	enum EVENT_F6B
	enum EVENT_F6C
	enum EVENT_F6D
	enum EVENT_F6E
	enum EVENT_F6F

		enum_start 0xf70 // 0x1EE
	enum EVENT_F70
	enum EVENT_F71
	enum EVENT_F72
	enum EVENT_F73
	enum EVENT_F74
	enum EVENT_F75
	enum EVENT_F76
	enum EVENT_F77

		enum_start 0xf78 // 0x1EF
	enum EVENT_F78
	enum EVENT_F79
	enum EVENT_F7A
	enum EVENT_F7B
	enum EVENT_F7C
	enum EVENT_F7D
	enum EVENT_F7E
	enum EVENT_F7F

		enum_start 0xf80 // 0x1F0
	enum EVENT_F80
	enum EVENT_F81
	enum EVENT_F82
	enum EVENT_F83
	enum EVENT_F84
	enum EVENT_F85
	enum EVENT_F86
	enum EVENT_F87

		enum_start 0xf88 // 0x1F1
	enum EVENT_F88
	enum EVENT_F89
	enum EVENT_F8A
	enum EVENT_F8B
	enum EVENT_F8C
	enum EVENT_F8D
	enum EVENT_F8E
	enum EVENT_F8F

		enum_start 0xf90 // 0x1F2
	enum EVENT_F90
	enum EVENT_F91
	enum EVENT_F92
	enum EVENT_F93
	enum EVENT_F94
	enum EVENT_F95
	enum EVENT_F96
	enum EVENT_F97

		enum_start 0xf98 // 0x1F3
	enum EVENT_F98
	enum EVENT_F99
	enum EVENT_F9A
	enum EVENT_F9B
	enum EVENT_F9C
	enum EVENT_F9D
	enum EVENT_F9E
	enum EVENT_F9F

		enum_start 0xfa0 // 0x1F4
	enum EVENT_FA0
	enum EVENT_FA1
	enum EVENT_FA2
	enum EVENT_FA3
	enum EVENT_FA4
	enum EVENT_FA5
	enum EVENT_FA6
	enum EVENT_FA7

		enum_start 0xfa8 // 0x1F5
	enum EVENT_FA8
	enum EVENT_FA9
	enum EVENT_FAA
	enum EVENT_FAB
	enum EVENT_FAC
	enum EVENT_FAD
	enum EVENT_FAE
	enum EVENT_FAF

		enum_start 0xfb0 // 0x1F6
	enum EVENT_FB0
	enum EVENT_FB1
	enum EVENT_FB2
	enum EVENT_FB3
	enum EVENT_FB4
	enum EVENT_FB5
	enum EVENT_FB6
	enum EVENT_FB7

		enum_start 0xfb8 // 0x1F7
	enum EVENT_FB8
	enum EVENT_FB9
	enum EVENT_FBA
	enum EVENT_FBB
	enum EVENT_FBC
	enum EVENT_FBD
	enum EVENT_FBE
	enum EVENT_FBF

		enum_start 0xfc0 // 0x1F8
	enum EVENT_FC0
	enum EVENT_FC1
	enum EVENT_FC2
	enum EVENT_FC3
	enum EVENT_FC4
	enum EVENT_FC5
	enum EVENT_FC6
	enum EVENT_FC7

		enum_start 0xfc8 // 0x1F9
	enum EVENT_FC8
	enum EVENT_FC9
	enum EVENT_FCA
	enum EVENT_FCB
	enum EVENT_FCC
	enum EVENT_FCD
	enum EVENT_FCE
	enum EVENT_FCF

		enum_start 0xfd0 // 0x1FA
	enum EVENT_FD0
	enum EVENT_FD1
	enum EVENT_FD2
	enum EVENT_FD3
	enum EVENT_FD4
	enum EVENT_FD5
	enum EVENT_FD6
	enum EVENT_FD7

		enum_start 0xfd8 // 0x1FB
	enum EVENT_FD8
	enum EVENT_FD9
	enum EVENT_FDA
	enum EVENT_FDB
	enum EVENT_FDC
	enum EVENT_FDD
	enum EVENT_FDE
	enum EVENT_FDF

		enum_start 0xfe0 // 0x1FC
	enum EVENT_FE0
	enum EVENT_FE1
	enum EVENT_FE2
	enum EVENT_FE3
	enum EVENT_FE4
	enum EVENT_FE5
	enum EVENT_FE6
	enum EVENT_FE7

		enum_start 0xfe8 // 0x1FD
	enum EVENT_FE8
	enum EVENT_FE9
	enum EVENT_FEA
	enum EVENT_FEB
	enum EVENT_FEC
	enum EVENT_FED
	enum EVENT_FEE
	enum EVENT_FEF

		enum_start 0xff0 // 0x1FE
	enum EVENT_FF0
	enum EVENT_FF1
	enum EVENT_FF2
	enum EVENT_FF3
	enum EVENT_FF4
	enum EVENT_FF5
	enum EVENT_FF6
	enum EVENT_FF7

		enum_start 0xff8 // 0x1FF
	enum EVENT_FF8
	enum EVENT_FF9
	enum EVENT_FFA
	enum EVENT_FFB
	enum EVENT_FFC
	enum EVENT_FFD
	enum EVENT_FFE
	enum EVENT_FFF

		enum_start 0x1000 // 0x200
	enum EVENT_1000
	enum EVENT_1001
	enum EVENT_1002
	enum EVENT_1003
	enum EVENT_1004
	enum EVENT_1005
	enum EVENT_1006
	enum EVENT_1007

		enum_start 0x1008 // 0x201
	enum EVENT_1008
	enum EVENT_1009
	enum EVENT_100A
	enum EVENT_100B
	enum EVENT_100C
	enum EVENT_100D
	enum EVENT_100E
	enum EVENT_100F

		enum_start 0x1010 // 0x202
	enum EVENT_1010
	enum EVENT_1011
	enum EVENT_1012
	enum EVENT_1013
	enum EVENT_1014
	enum EVENT_1015
	enum EVENT_1016
	enum EVENT_1017

		enum_start 0x1018 // 0x203
	enum EVENT_1018
	enum EVENT_1019
	enum EVENT_101A
	enum EVENT_101B
	enum EVENT_101C
	enum EVENT_101D
	enum EVENT_101E
	enum EVENT_101F

		enum_start 0x1020 // 0x204
	enum EVENT_1020
	enum EVENT_1021
	enum EVENT_1022
	enum EVENT_1023
	enum EVENT_1024
	enum EVENT_1025
	enum EVENT_1026
	enum EVENT_1027

		enum_start 0x1028 // 0x205
	enum EVENT_1028
	enum EVENT_1029
	enum EVENT_102A
	enum EVENT_102B
	enum EVENT_102C
	enum EVENT_102D
	enum EVENT_102E
	enum EVENT_102F

		enum_start 0x1030 // 0x206
	enum EVENT_1030
	enum EVENT_1031
	enum EVENT_1032
	enum EVENT_1033
	enum EVENT_1034
	enum EVENT_1035
	enum EVENT_1036
	enum EVENT_1037

		enum_start 0x1038 // 0x207
	enum EVENT_1038
	enum EVENT_1039
	enum EVENT_103A
	enum EVENT_103B
	enum EVENT_103C
	enum EVENT_103D
	enum EVENT_103E
	enum EVENT_103F

		enum_start 0x1040 // 0x208
	enum EVENT_1040
	enum EVENT_1041
	enum EVENT_1042
	enum EVENT_1043
	enum EVENT_1044
	enum EVENT_1045
	enum EVENT_1046
	enum EVENT_1047

		enum_start 0x1048 // 0x209
	enum EVENT_1048
	enum EVENT_1049
	enum EVENT_104A
	enum EVENT_104B
	enum EVENT_104C
	enum EVENT_104D
	enum EVENT_104E
	enum EVENT_104F

		enum_start 0x1050 // 0x20A
	enum EVENT_1050
	enum EVENT_1051
	enum EVENT_1052
	enum EVENT_1053
	enum EVENT_1054
	enum EVENT_1055
	enum EVENT_1056
	enum EVENT_1057

		enum_start 0x1058 // 0x20B
	enum EVENT_1058
	enum EVENT_1059
	enum EVENT_105A
	enum EVENT_105B
	enum EVENT_105C
	enum EVENT_105D
	enum EVENT_105E
	enum EVENT_105F

		enum_start 0x1060 // 0x20C
	enum EVENT_1060
	enum EVENT_1061
	enum EVENT_1062
	enum EVENT_1063
	enum EVENT_1064
	enum EVENT_1065
	enum EVENT_1066
	enum EVENT_1067

		enum_start 0x1068 // 0x20D
	enum EVENT_1068
	enum EVENT_1069
	enum EVENT_106A
	enum EVENT_106B
	enum EVENT_106C
	enum EVENT_106D
	enum EVENT_106E
	enum EVENT_106F

		enum_start 0x1070 // 0x20E
	enum EVENT_1070
	enum EVENT_1071
	enum EVENT_1072
	enum EVENT_1073
	enum EVENT_1074
	enum EVENT_1075
	enum EVENT_1076
	enum EVENT_1077

		enum_start 0x1078 // 0x20F
	enum EVENT_1078
	enum EVENT_1079
	enum EVENT_107A
	enum EVENT_107B
	enum EVENT_107C
	enum EVENT_107D
	enum EVENT_107E
	enum EVENT_107F

		enum_start 0x1080 // 0x210
	enum EVENT_1080
	enum EVENT_1081
	enum EVENT_1082
	enum EVENT_1083
	enum EVENT_1084
	enum EVENT_1085
	enum EVENT_1086
	enum EVENT_1087

		enum_start 0x1088 // 0x211
	enum EVENT_1088
	enum EVENT_1089
	enum EVENT_108A
	enum EVENT_108B
	enum EVENT_108C
	enum EVENT_108D
	enum EVENT_108E
	enum EVENT_108F

		enum_start 0x1090 // 0x212
	enum EVENT_1090
	enum EVENT_1091
	enum EVENT_1092
	enum EVENT_1093
	enum EVENT_1094
	enum EVENT_1095
	enum EVENT_1096
	enum EVENT_1097

		enum_start 0x1098 // 0x213
	enum EVENT_1098
	enum EVENT_1099
	enum EVENT_109A
	enum EVENT_109B
	enum EVENT_109C
	enum EVENT_109D
	enum EVENT_109E
	enum EVENT_109F

		enum_start 0x10a0 // 0x214
	enum EVENT_10A0
	enum EVENT_10A1
	enum EVENT_10A2
	enum EVENT_10A3
	enum EVENT_10A4
	enum EVENT_10A5
	enum EVENT_10A6
	enum EVENT_10A7

		enum_start 0x10a8 // 0x215
	enum EVENT_10A8
	enum EVENT_10A9
	enum EVENT_10AA
	enum EVENT_10AB
	enum EVENT_10AC
	enum EVENT_10AD
	enum EVENT_10AE
	enum EVENT_10AF

		enum_start 0x10b0 // 0x216
	enum EVENT_10B0
	enum EVENT_10B1
	enum EVENT_10B2
	enum EVENT_10B3
	enum EVENT_10B4
	enum EVENT_10B5
	enum EVENT_10B6
	enum EVENT_10B7

		enum_start 0x10b8 // 0x217
	enum EVENT_10B8
	enum EVENT_10B9
	enum EVENT_10BA
	enum EVENT_10BB
	enum EVENT_10BC
	enum EVENT_10BD
	enum EVENT_10BE
	enum EVENT_10BF

		enum_start 0x10c0 // 0x218
	enum EVENT_10C0
	enum EVENT_10C1
	enum EVENT_10C2
	enum EVENT_10C3
	enum EVENT_10C4
	enum EVENT_10C5
	enum EVENT_10C6
	enum EVENT_10C7

		enum_start 0x10c8 // 0x219
	enum EVENT_10C8
	enum EVENT_10C9
	enum EVENT_10CA
	enum EVENT_10CB
	enum EVENT_10CC
	enum EVENT_10CD
	enum EVENT_10CE
	enum EVENT_10CF

		enum_start 0x10d0 // 0x21A
	enum EVENT_10D0
	enum EVENT_10D1
	enum EVENT_10D2
	enum EVENT_10D3
	enum EVENT_10D4
	enum EVENT_10D5
	enum EVENT_10D6
	enum EVENT_10D7

		enum_start 0x10d8 // 0x21B
	enum EVENT_10D8
	enum EVENT_10D9
	enum EVENT_10DA
	enum EVENT_10DB
	enum EVENT_10DC
	enum EVENT_10DD
	enum EVENT_10DE
	enum EVENT_10DF

		enum_start 0x10e0 // 0x21C
	enum EVENT_10E0
	enum EVENT_10E1
	enum EVENT_10E2
	enum EVENT_10E3
	enum EVENT_10E4
	enum EVENT_10E5
	enum EVENT_10E6
	enum EVENT_10E7

		enum_start 0x10e8 // 0x21D
	enum EVENT_10E8
	enum EVENT_10E9
	enum EVENT_10EA
	enum EVENT_10EB
	enum EVENT_10EC
	enum EVENT_10ED
	enum EVENT_10EE
	enum EVENT_10EF

		enum_start 0x10f0 // 0x21E
	enum EVENT_10F0
	enum EVENT_10F1
	enum EVENT_10F2
	enum EVENT_10F3
	enum EVENT_10F4
	enum EVENT_10F5
	enum EVENT_10F6
	enum EVENT_10F7

		enum_start 0x10f8 // 0x21F
	enum EVENT_10F8
	enum EVENT_10F9
	enum EVENT_10FA
	enum EVENT_10FB
	enum EVENT_10FC
	enum EVENT_10FD
	enum EVENT_10FE
	enum EVENT_10FF

		enum_start 0x1100 // 0x220
	enum EVENT_1100
	enum EVENT_1101
	enum EVENT_1102
	enum EVENT_1103
	enum EVENT_1104
	enum EVENT_1105
	enum EVENT_1106
	enum EVENT_1107

		enum_start 0x1108 // 0x221
	enum EVENT_1108
	enum EVENT_1109
	enum EVENT_110A
	enum EVENT_110B
	enum EVENT_110C
	enum EVENT_110D
	enum EVENT_110E
	enum EVENT_110F

		enum_start 0x1110 // 0x222
	enum EVENT_1110
	enum EVENT_1111
	enum EVENT_1112
	enum EVENT_1113
	enum EVENT_1114
	enum EVENT_1115
	enum EVENT_1116
	enum EVENT_1117

		enum_start 0x1118 // 0x223
	enum EVENT_1118
	enum EVENT_1119
	enum EVENT_111A
	enum EVENT_111B
	enum EVENT_111C
	enum EVENT_111D
	enum EVENT_111E
	enum EVENT_111F

		enum_start 0x1120 // 0x224
	enum EVENT_1120
	enum EVENT_1121
	enum EVENT_1122
	enum EVENT_1123
	enum EVENT_1124
	enum EVENT_1125
	enum EVENT_1126
	enum EVENT_1127

		enum_start 0x1128 // 0x225
	enum EVENT_1128
	enum EVENT_1129
	enum EVENT_112A
	enum EVENT_112B
	enum EVENT_112C
	enum EVENT_112D
	enum EVENT_112E
	enum EVENT_112F

		enum_start 0x1130 // 0x226
	enum EVENT_1130
	enum EVENT_1131
	enum EVENT_1132
	enum EVENT_1133
	enum EVENT_1134
	enum EVENT_1135
	enum EVENT_1136
	enum EVENT_1137

		enum_start 0x1138 // 0x227
	enum EVENT_1138
	enum EVENT_1139
	enum EVENT_113A
	enum EVENT_113B
	enum EVENT_113C
	enum EVENT_113D
	enum EVENT_113E
	enum EVENT_113F

		enum_start 0x1140 // 0x228
	enum EVENT_1140
	enum EVENT_1141
	enum EVENT_1142
	enum EVENT_1143
	enum EVENT_1144
	enum EVENT_1145
	enum EVENT_1146
	enum EVENT_1147

		enum_start 0x1148 // 0x229
	enum EVENT_1148
	enum EVENT_1149
	enum EVENT_114A
	enum EVENT_114B
	enum EVENT_114C
	enum EVENT_114D
	enum EVENT_114E
	enum EVENT_114F

		enum_start 0x1150 // 0x22A
	enum EVENT_1150
	enum EVENT_1151
	enum EVENT_1152
	enum EVENT_1153
	enum EVENT_1154
	enum EVENT_1155
	enum EVENT_1156
	enum EVENT_1157

		enum_start 0x1158 // 0x22B
	enum EVENT_1158
	enum EVENT_1159
	enum EVENT_115A
	enum EVENT_115B
	enum EVENT_115C
	enum EVENT_115D
	enum EVENT_115E
	enum EVENT_115F

		enum_start 0x1160 // 0x22C
	enum EVENT_1160
	enum EVENT_1161
	enum EVENT_1162
	enum EVENT_1163
	enum EVENT_1164
	enum EVENT_1165
	enum EVENT_1166
	enum EVENT_1167

		enum_start 0x1168 // 0x22D
	enum EVENT_1168
	enum EVENT_1169
	enum EVENT_116A
	enum EVENT_116B
	enum EVENT_116C
	enum EVENT_116D
	enum EVENT_116E
	enum EVENT_116F

		enum_start 0x1170 // 0x22E
	enum EVENT_1170
	enum EVENT_1171
	enum EVENT_1172
	enum EVENT_1173
	enum EVENT_1174
	enum EVENT_1175
	enum EVENT_1176
	enum EVENT_1177

		enum_start 0x1178 // 0x22F
	enum EVENT_1178
	enum EVENT_1179
	enum EVENT_117A
	enum EVENT_117B
	enum EVENT_117C
	enum EVENT_117D
	enum EVENT_117E
	enum EVENT_117F

		enum_start 0x1180 // 0x230
	enum EVENT_1180
	enum EVENT_1181
	enum EVENT_1182
	enum EVENT_1183
	enum EVENT_1184
	enum EVENT_1185
	enum EVENT_1186
	enum EVENT_1187

		enum_start 0x1188 // 0x231
	enum EVENT_1188
	enum EVENT_1189
	enum EVENT_118A
	enum EVENT_118B
	enum EVENT_118C
	enum EVENT_118D
	enum EVENT_118E
	enum EVENT_118F

		enum_start 0x1190 // 0x232
	enum EVENT_1190
	enum EVENT_1191
	enum EVENT_1192
	enum EVENT_1193
	enum EVENT_1194
	enum EVENT_1195
	enum EVENT_1196
	enum EVENT_1197

		enum_start 0x1198 // 0x233
	enum EVENT_1198
	enum EVENT_1199
	enum EVENT_119A
	enum EVENT_119B
	enum EVENT_119C
	enum EVENT_119D
	enum EVENT_119E
	enum EVENT_119F

		enum_start 0x11a0 // 0x234
	enum EVENT_11A0
	enum EVENT_11A1
	enum EVENT_11A2
	enum EVENT_11A3
	enum EVENT_11A4
	enum EVENT_11A5
	enum EVENT_11A6
	enum EVENT_11A7

		enum_start 0x11a8 // 0x235
	enum EVENT_11A8
	enum EVENT_11A9
	enum EVENT_11AA
	enum EVENT_11AB
	enum EVENT_11AC
	enum EVENT_11AD
	enum EVENT_11AE
	enum EVENT_11AF

		enum_start 0x11b0 // 0x236
	enum EVENT_11B0
	enum EVENT_11B1
	enum EVENT_11B2
	enum EVENT_11B3
	enum EVENT_11B4
	enum EVENT_11B5
	enum EVENT_11B6
	enum EVENT_11B7

		enum_start 0x11b8 // 0x237
	enum EVENT_11B8
	enum EVENT_11B9
	enum EVENT_11BA
	enum EVENT_11BB
	enum EVENT_11BC
	enum EVENT_11BD
	enum EVENT_11BE
	enum EVENT_11BF

		enum_start 0x11c0 // 0x238
	enum EVENT_11C0
	enum EVENT_11C1
	enum EVENT_11C2
	enum EVENT_11C3
	enum EVENT_11C4
	enum EVENT_11C5
	enum EVENT_11C6
	enum EVENT_11C7

		enum_start 0x11c8 // 0x239
	enum EVENT_11C8
	enum EVENT_11C9
	enum EVENT_11CA
	enum EVENT_11CB
	enum EVENT_11CC
	enum EVENT_11CD
	enum EVENT_11CE
	enum EVENT_11CF

		enum_start 0x11d0 // 0x23A
	enum EVENT_11D0
	enum EVENT_11D1
	enum EVENT_11D2
	enum EVENT_11D3
	enum EVENT_11D4
	enum EVENT_11D5
	enum EVENT_11D6
	enum EVENT_11D7

		enum_start 0x11d8 // 0x23B
	enum EVENT_11D8
	enum EVENT_11D9
	enum EVENT_11DA
	enum EVENT_11DB
	enum EVENT_11DC
	enum EVENT_11DD
	enum EVENT_11DE
	enum EVENT_11DF

		enum_start 0x11e0 // 0x23C
	enum EVENT_11E0
	enum EVENT_11E1
	enum EVENT_11E2
	enum EVENT_11E3
	enum EVENT_11E4
	enum EVENT_11E5
	enum EVENT_11E6
	enum EVENT_11E7

		enum_start 0x11e8 // 0x23D
	enum EVENT_11E8
	enum EVENT_11E9
	enum EVENT_11EA
	enum EVENT_11EB
	enum EVENT_11EC
	enum EVENT_11ED
	enum EVENT_11EE
	enum EVENT_11EF

		enum_start 0x11f0 // 0x23E
	enum EVENT_11F0
	enum EVENT_11F1
	enum EVENT_11F2
	enum EVENT_11F3
	enum EVENT_11F4
	enum EVENT_11F5
	enum EVENT_11F6
	enum EVENT_11F7

		enum_start 0x11f8 // 0x23F
	enum EVENT_11F8
	enum EVENT_11F9
	enum EVENT_11FA
	enum EVENT_11FB
	enum EVENT_11FC
	enum EVENT_11FD
	enum EVENT_11FE
	enum EVENT_11FF

		enum_start 0x1200 // 0x240
	enum EVENT_1200
	enum EVENT_1201
	enum EVENT_1202
	enum EVENT_1203
	enum EVENT_1204
	enum EVENT_1205
	enum EVENT_1206
	enum EVENT_1207

		enum_start 0x1208 // 0x241
	enum EVENT_1208
	enum EVENT_1209
	enum EVENT_120A
	enum EVENT_120B
	enum EVENT_120C
	enum EVENT_120D
	enum EVENT_120E
	enum EVENT_120F

		enum_start 0x1210 // 0x242
	enum EVENT_1210
	enum EVENT_1211
	enum EVENT_1212
	enum EVENT_1213
	enum EVENT_1214
	enum EVENT_1215
	enum EVENT_1216
	enum EVENT_1217

		enum_start 0x1218 // 0x243
	enum EVENT_1218
	enum EVENT_1219
	enum EVENT_121A
	enum EVENT_121B
	enum EVENT_121C
	enum EVENT_121D
	enum EVENT_121E
	enum EVENT_121F

		enum_start 0x1220 // 0x244
	enum EVENT_1220
	enum EVENT_1221
	enum EVENT_1222
	enum EVENT_1223
	enum EVENT_1224
	enum EVENT_1225
	enum EVENT_1226
	enum EVENT_1227

		enum_start 0x1228 // 0x245
	enum EVENT_1228
	enum EVENT_1229
	enum EVENT_122A
	enum EVENT_122B
	enum EVENT_122C
	enum EVENT_122D
	enum EVENT_122E
	enum EVENT_122F

		enum_start 0x1230 // 0x246
	enum EVENT_1230
	enum EVENT_1231
	enum EVENT_1232
	enum EVENT_1233
	enum EVENT_1234
	enum EVENT_1235
	enum EVENT_1236
	enum EVENT_1237

		enum_start 0x1238 // 0x247
	enum EVENT_1238
	enum EVENT_1239
	enum EVENT_123A
	enum EVENT_123B
	enum EVENT_123C
	enum EVENT_123D
	enum EVENT_123E
	enum EVENT_123F

		enum_start 0x1240 // 0x248
	enum EVENT_1240
	enum EVENT_1241
	enum EVENT_1242
	enum EVENT_1243
	enum EVENT_1244
	enum EVENT_1245
	enum EVENT_1246
	enum EVENT_1247

		enum_start 0x1248 // 0x249
	enum EVENT_1248
	enum EVENT_1249
	enum EVENT_124A
	enum EVENT_124B
	enum EVENT_124C
	enum EVENT_124D
	enum EVENT_124E
	enum EVENT_124F

		enum_start 0x1250 // 0x24A
	enum EVENT_1250
	enum EVENT_1251
	enum EVENT_1252
	enum EVENT_1253
	enum EVENT_1254
	enum EVENT_1255
	enum EVENT_1256
	enum EVENT_1257

		enum_start 0x1258 // 0x24B
	enum EVENT_1258
	enum EVENT_1259
	enum EVENT_125A
	enum EVENT_125B
	enum EVENT_125C
	enum EVENT_125D
	enum EVENT_125E
	enum EVENT_125F

		enum_start 0x1260 // 0x24C
	enum EVENT_1260
	enum EVENT_1261
	enum EVENT_1262
	enum EVENT_1263
	enum EVENT_1264
	enum EVENT_1265
	enum EVENT_1266
	enum EVENT_1267

		enum_start 0x1268 // 0x24D
	enum EVENT_1268
	enum EVENT_1269
	enum EVENT_126A
	enum EVENT_126B
	enum EVENT_126C
	enum EVENT_126D
	enum EVENT_126E
	enum EVENT_126F

		enum_start 0x1270 // 0x24E
	enum EVENT_1270
	enum EVENT_1271
	enum EVENT_1272
	enum EVENT_1273
	enum EVENT_1274
	enum EVENT_1275
	enum EVENT_1276
	enum EVENT_1277

		enum_start 0x1278 // 0x24F
	enum EVENT_1278
	enum EVENT_1279
	enum EVENT_127A
	enum EVENT_127B
	enum EVENT_127C
	enum EVENT_127D
	enum EVENT_127E
	enum EVENT_127F

		enum_start 0x1280 // 0x250
	enum EVENT_1280
	enum EVENT_1281
	enum EVENT_1282
	enum EVENT_1283
	enum EVENT_1284
	enum EVENT_1285
	enum EVENT_1286
	enum EVENT_1287

		enum_start 0x1288 // 0x251
	enum EVENT_1288
	enum EVENT_1289
	enum EVENT_128A
	enum EVENT_128B
	enum EVENT_128C
	enum EVENT_128D
	enum EVENT_128E
	enum EVENT_128F

		enum_start 0x1290 // 0x252
	enum EVENT_1290
	enum EVENT_1291
	enum EVENT_1292
	enum EVENT_1293
	enum EVENT_1294
	enum EVENT_1295
	enum EVENT_1296
	enum EVENT_1297

		enum_start 0x1298 // 0x253
	enum EVENT_1298
	enum EVENT_1299
	enum EVENT_129A
	enum EVENT_129B
	enum EVENT_129C
	enum EVENT_129D
	enum EVENT_129E
	enum EVENT_129F

		enum_start 0x12a0 // 0x254
	enum EVENT_12A0
	enum EVENT_12A1
	enum EVENT_12A2
	enum EVENT_12A3
	enum EVENT_12A4
	enum EVENT_12A5
	enum EVENT_12A6
	enum EVENT_12A7

		enum_start 0x12a8 // 0x255
	enum EVENT_12A8
	enum EVENT_12A9
	enum EVENT_12AA
	enum EVENT_12AB
	enum EVENT_12AC
	enum EVENT_12AD
	enum EVENT_12AE
	enum EVENT_12AF

		enum_start 0x12b0 // 0x256
	enum EVENT_12B0
	enum EVENT_12B1
	enum EVENT_12B2
	enum EVENT_12B3
	enum EVENT_12B4
	enum EVENT_12B5
	enum EVENT_12B6
	enum EVENT_12B7

		enum_start 0x12b8 // 0x257
	enum EVENT_12B8
	enum EVENT_12B9
	enum EVENT_12BA
	enum EVENT_12BB
	enum EVENT_12BC
	enum EVENT_12BD
	enum EVENT_12BE
	enum EVENT_12BF

		enum_start 0x12c0 // 0x258
	enum EVENT_12C0
	enum EVENT_12C1
	enum EVENT_12C2
	enum EVENT_12C3
	enum EVENT_12C4
	enum EVENT_12C5
	enum EVENT_12C6
	enum EVENT_12C7

		enum_start 0x12c8 // 0x259
	enum EVENT_12C8
	enum EVENT_12C9
	enum EVENT_12CA
	enum EVENT_12CB
	enum EVENT_12CC
	enum EVENT_12CD
	enum EVENT_12CE
	enum EVENT_12CF

		enum_start 0x12d0 // 0x25A
	enum EVENT_12D0
	enum EVENT_12D1
	enum EVENT_12D2
	enum EVENT_12D3
	enum EVENT_12D4
	enum EVENT_12D5
	enum EVENT_12D6
	enum EVENT_12D7

		enum_start 0x12d8 // 0x25B
	enum EVENT_12D8
	enum EVENT_12D9
	enum EVENT_12DA
	enum EVENT_12DB
	enum EVENT_12DC
	enum EVENT_12DD
	enum EVENT_12DE
	enum EVENT_12DF

		enum_start 0x12e0 // 0x25C
	enum EVENT_12E0
	enum EVENT_12E1
	enum EVENT_12E2
	enum EVENT_12E3
	enum EVENT_12E4
	enum EVENT_12E5
	enum EVENT_12E6
	enum EVENT_12E7

		enum_start 0x12e8 // 0x25D
	enum EVENT_12E8
	enum EVENT_12E9
	enum EVENT_12EA
	enum EVENT_12EB
	enum EVENT_12EC
	enum EVENT_12ED
	enum EVENT_12EE
	enum EVENT_12EF

		enum_start 0x12f0 // 0x25E
	enum EVENT_12F0
	enum EVENT_12F1
	enum EVENT_12F2
	enum EVENT_12F3
	enum EVENT_12F4
	enum EVENT_12F5
	enum EVENT_12F6
	enum EVENT_12F7

		enum_start 0x12f8 // 0x25F
	enum EVENT_12F8
	enum EVENT_12F9
	enum EVENT_12FA
	enum EVENT_12FB
	enum EVENT_12FC
	enum EVENT_12FD
	enum EVENT_12FE
	enum EVENT_12FF

		enum_start 0x1300 // 0x260
	enum EVENT_1300
	enum EVENT_1301
	enum EVENT_1302
	enum EVENT_1303
	enum EVENT_1304
	enum EVENT_1305
	enum EVENT_1306
	enum EVENT_1307

		enum_start 0x1308 // 0x261
	enum EVENT_1308
	enum EVENT_1309
	enum EVENT_130A
	enum EVENT_130B
	enum EVENT_130C
	enum EVENT_130D
	enum EVENT_130E
	enum EVENT_130F

		enum_start 0x1310 // 0x262
	enum EVENT_1310
	enum EVENT_1311
	enum EVENT_1312
	enum EVENT_1313
	enum EVENT_1314
	enum EVENT_1315
	enum EVENT_1316
	enum EVENT_1317

		enum_start 0x1318 // 0x263
	enum EVENT_1318
	enum EVENT_1319
	enum EVENT_131A
	enum EVENT_131B
	enum EVENT_131C
	enum EVENT_131D
	enum EVENT_131E
	enum EVENT_131F

		enum_start 0x1320 // 0x264
	enum EVENT_1320
	enum EVENT_1321
	enum EVENT_1322
	enum EVENT_1323
	enum EVENT_1324
	enum EVENT_1325
	enum EVENT_1326
	enum EVENT_1327

		enum_start 0x1328 // 0x265
	enum EVENT_1328
	enum EVENT_1329
	enum EVENT_132A
	enum EVENT_132B
	enum EVENT_132C
	enum EVENT_132D
	enum EVENT_132E
	enum EVENT_132F

		enum_start 0x1330 // 0x266
	enum EVENT_1330
	enum EVENT_1331
	enum EVENT_1332
	enum EVENT_1333
	enum EVENT_1334
	enum EVENT_1335
	enum EVENT_1336
	enum EVENT_1337

		enum_start 0x1338 // 0x267
	enum EVENT_1338
	enum EVENT_1339
	enum EVENT_133A
	enum EVENT_133B
	enum EVENT_133C
	enum EVENT_133D
	enum EVENT_133E
	enum EVENT_133F

		enum_start 0x1340 // 0x268
	enum EVENT_1340
	enum EVENT_1341
	enum EVENT_1342
	enum EVENT_1343
	enum EVENT_1344
	enum EVENT_1345
	enum EVENT_1346
	enum EVENT_1347

		enum_start 0x1348 // 0x269
	enum EVENT_1348
	enum EVENT_1349
	enum EVENT_134A
	enum EVENT_134B
	enum EVENT_134C
	enum EVENT_134D
	enum EVENT_134E
	enum EVENT_134F

		enum_start 0x1350 // 0x26A
	enum EVENT_1350
	enum EVENT_1351
	enum EVENT_1352
	enum EVENT_1353
	enum EVENT_1354
	enum EVENT_1355
	enum EVENT_1356
	enum EVENT_1357

		enum_start 0x1358 // 0x26B
	enum EVENT_1358
	enum EVENT_1359
	enum EVENT_135A
	enum EVENT_135B
	enum EVENT_135C
	enum EVENT_135D
	enum EVENT_135E
	enum EVENT_135F

		enum_start 0x1360 // 0x26C
	enum EVENT_1360
	enum EVENT_1361
	enum EVENT_1362
	enum EVENT_1363
	enum EVENT_1364
	enum EVENT_1365
	enum EVENT_1366
	enum EVENT_1367

		enum_start 0x1368 // 0x26D
	enum EVENT_1368
	enum EVENT_1369
	enum EVENT_136A
	enum EVENT_136B
	enum EVENT_136C
	enum EVENT_136D
	enum EVENT_136E
	enum EVENT_136F

		enum_start 0x1370 // 0x26E
	enum EVENT_1370
	enum EVENT_1371
	enum EVENT_1372
	enum EVENT_1373
	enum EVENT_1374
	enum EVENT_1375
	enum EVENT_1376
	enum EVENT_1377

		enum_start 0x1378 // 0x26F
	enum EVENT_1378
	enum EVENT_1379
	enum EVENT_137A
	enum EVENT_137B
	enum EVENT_137C
	enum EVENT_137D
	enum EVENT_137E
	enum EVENT_137F

		enum_start 0x1380 // 0x270
	enum EVENT_1380
	enum EVENT_1381
	enum EVENT_1382
	enum EVENT_1383
	enum EVENT_1384
	enum EVENT_1385
	enum EVENT_1386
	enum EVENT_1387

		enum_start 0x1388 // 0x271
	enum EVENT_1388
	enum EVENT_1389
	enum EVENT_138A
	enum EVENT_138B
	enum EVENT_138C
	enum EVENT_138D
	enum EVENT_138E
	enum EVENT_138F

		enum_start 0x1390 // 0x272
	enum EVENT_1390
	enum EVENT_1391
	enum EVENT_1392
	enum EVENT_1393
	enum EVENT_1394
	enum EVENT_1395
	enum EVENT_1396
	enum EVENT_1397

		enum_start 0x1398 // 0x273
	enum EVENT_1398
	enum EVENT_1399
	enum EVENT_139A
	enum EVENT_139B
	enum EVENT_139C
	enum EVENT_139D
	enum EVENT_139E
	enum EVENT_139F

		enum_start 0x13a0 // 0x274
	enum EVENT_13A0
	enum EVENT_13A1
	enum EVENT_13A2
	enum EVENT_13A3
	enum EVENT_13A4
	enum EVENT_13A5
	enum EVENT_13A6
	enum EVENT_13A7

		enum_start 0x13a8 // 0x275
	enum EVENT_13A8
	enum EVENT_13A9
	enum EVENT_13AA
	enum EVENT_13AB
	enum EVENT_13AC
	enum EVENT_13AD
	enum EVENT_13AE
	enum EVENT_13AF

		enum_start 0x13b0 // 0x276
	enum EVENT_13B0
	enum EVENT_13B1
	enum EVENT_13B2
	enum EVENT_13B3
	enum EVENT_13B4
	enum EVENT_13B5
	enum EVENT_13B6
	enum EVENT_13B7

		enum_start 0x13b8 // 0x277
	enum EVENT_13B8
	enum EVENT_13B9
	enum EVENT_13BA
	enum EVENT_13BB
	enum EVENT_13BC
	enum EVENT_13BD
	enum EVENT_13BE
	enum EVENT_13BF

		enum_start 0x13c0 // 0x278
	enum EVENT_13C0
	enum EVENT_13C1
	enum EVENT_13C2
	enum EVENT_13C3
	enum EVENT_13C4
	enum EVENT_13C5
	enum EVENT_13C6
	enum EVENT_13C7

		enum_start 0x13c8 // 0x279
	enum EVENT_13C8
	enum EVENT_13C9
	enum EVENT_13CA
	enum EVENT_13CB
	enum EVENT_13CC
	enum EVENT_13CD
	enum EVENT_13CE
	enum EVENT_13CF

		enum_start 0x13d0 // 0x27A
	enum EVENT_13D0
	enum EVENT_13D1
	enum EVENT_13D2
	enum EVENT_13D3
	enum EVENT_13D4
	enum EVENT_13D5
	enum EVENT_13D6
	enum EVENT_13D7

		enum_start 0x13d8 // 0x27B
	enum EVENT_13D8
	enum EVENT_13D9
	enum EVENT_13DA
	enum EVENT_13DB
	enum EVENT_13DC
	enum EVENT_13DD
	enum EVENT_13DE
	enum EVENT_13DF

		enum_start 0x13e0 // 0x27C
	enum EVENT_13E0
	enum EVENT_13E1
	enum EVENT_13E2
	enum EVENT_13E3
	enum EVENT_13E4
	enum EVENT_13E5
	enum EVENT_13E6
	enum EVENT_13E7

		enum_start 0x13e8 // 0x27D
	enum EVENT_13E8
	enum EVENT_13E9
	enum EVENT_13EA
	enum EVENT_13EB
	enum EVENT_13EC
	enum EVENT_13ED
	enum EVENT_13EE
	enum EVENT_13EF

		enum_start 0x13f0 // 0x27E
	enum EVENT_13F0
	enum EVENT_13F1
	enum EVENT_13F2
	enum EVENT_13F3
	enum EVENT_13F4
	enum EVENT_13F5
	enum EVENT_13F6
	enum EVENT_13F7

		enum_start 0x13f8 // 0x27F
	enum EVENT_13F8
	enum EVENT_13F9
	enum EVENT_13FA
	enum EVENT_13FB
	enum EVENT_13FC
	enum EVENT_13FD
	enum EVENT_13FE
	enum EVENT_13FF

		enum_start 0x1400 // 0x280
	enum EVENT_1400
	enum EVENT_1401
	enum EVENT_1402
	enum EVENT_1403
	enum EVENT_1404
	enum EVENT_1405
	enum EVENT_1406
	enum EVENT_1407

		enum_start 0x1408 // 0x281
	enum EVENT_1408
	enum EVENT_1409
	enum EVENT_140A
	enum EVENT_140B
	enum EVENT_140C
	enum EVENT_140D
	enum EVENT_140E
	enum EVENT_140F

		enum_start 0x1410 // 0x282
	enum EVENT_1410
	enum EVENT_1411
	enum EVENT_1412
	enum EVENT_1413
	enum EVENT_1414
	enum EVENT_1415
	enum EVENT_1416
	enum EVENT_1417

		enum_start 0x1418 // 0x283
	enum EVENT_1418
	enum EVENT_1419
	enum EVENT_141A
	enum EVENT_141B
	enum EVENT_141C
	enum EVENT_141D
	enum EVENT_141E
	enum EVENT_141F

		enum_start 0x1420 // 0x284
	enum EVENT_1420
	enum EVENT_1421
	enum EVENT_1422
	enum EVENT_1423
	enum EVENT_1424
	enum EVENT_1425
	enum EVENT_1426
	enum EVENT_1427

		enum_start 0x1428 // 0x285
	enum EVENT_1428
	enum EVENT_1429
	enum EVENT_142A
	enum EVENT_142B
	enum EVENT_142C
	enum EVENT_142D
	enum EVENT_142E
	enum EVENT_142F

		enum_start 0x1430 // 0x286
	enum EVENT_1430
	enum EVENT_1431
	enum EVENT_1432
	enum EVENT_1433
	enum EVENT_1434
	enum EVENT_1435
	enum EVENT_1436
	enum EVENT_1437

		enum_start 0x1438 // 0x287
	enum EVENT_1438
	enum EVENT_1439
	enum EVENT_143A
	enum EVENT_143B
	enum EVENT_143C
	enum EVENT_143D
	enum EVENT_143E
	enum EVENT_143F

		enum_start 0x1440 // 0x288
	enum EVENT_1440
	enum EVENT_1441
	enum EVENT_1442
	enum EVENT_1443
	enum EVENT_1444
	enum EVENT_1445
	enum EVENT_1446
	enum EVENT_1447

		enum_start 0x1448 // 0x289
	enum EVENT_1448
	enum EVENT_1449
	enum EVENT_144A
	enum EVENT_144B
	enum EVENT_144C
	enum EVENT_144D
	enum EVENT_144E
	enum EVENT_144F

		enum_start 0x1450 // 0x28A
	enum EVENT_1450
	enum EVENT_1451
	enum EVENT_1452
	enum EVENT_1453
	enum EVENT_1454
	enum EVENT_1455
	enum EVENT_1456
	enum EVENT_1457

		enum_start 0x1458 // 0x28B
	enum EVENT_1458
	enum EVENT_1459
	enum EVENT_145A
	enum EVENT_145B
	enum EVENT_145C
	enum EVENT_145D
	enum EVENT_145E
	enum EVENT_145F

		enum_start 0x1460 // 0x28C
	enum EVENT_1460
	enum EVENT_1461
	enum EVENT_1462
	enum EVENT_1463
	enum EVENT_1464
	enum EVENT_1465
	enum EVENT_1466
	enum EVENT_1467

		enum_start 0x1468 // 0x28D
	enum EVENT_1468
	enum EVENT_1469
	enum EVENT_146A
	enum EVENT_146B
	enum EVENT_146C
	enum EVENT_146D
	enum EVENT_146E
	enum EVENT_146F

		enum_start 0x1470 // 0x28E
	enum EVENT_1470
	enum EVENT_1471
	enum EVENT_1472
	enum EVENT_1473
	enum EVENT_1474
	enum EVENT_1475
	enum EVENT_1476
	enum EVENT_1477

		enum_start 0x1478 // 0x28F
	enum EVENT_1478
	enum EVENT_1479
	enum EVENT_147A
	enum EVENT_147B
	enum EVENT_147C
	enum EVENT_147D
	enum EVENT_147E
	enum EVENT_147F

		enum_start 0x1480 // 0x290
	enum EVENT_1480
	enum EVENT_1481
	enum EVENT_1482
	enum EVENT_1483
	enum EVENT_1484
	enum EVENT_1485
	enum EVENT_1486
	enum EVENT_1487

		enum_start 0x1488 // 0x291
	enum EVENT_1488
	enum EVENT_1489
	enum EVENT_148A
	enum EVENT_148B
	enum EVENT_148C
	enum EVENT_148D
	enum EVENT_148E
	enum EVENT_148F

		enum_start 0x1490 // 0x292
	enum EVENT_1490
	enum EVENT_1491
	enum EVENT_1492
	enum EVENT_1493
	enum EVENT_1494
	enum EVENT_1495
	enum EVENT_1496
	enum EVENT_1497

		enum_start 0x1498 // 0x293
	enum EVENT_1498
	enum EVENT_1499
	enum EVENT_149A
	enum EVENT_149B
	enum EVENT_149C
	enum EVENT_149D
	enum EVENT_149E
	enum EVENT_149F

		enum_start 0x14a0 // 0x294
	enum EVENT_14A0
	enum EVENT_14A1
	enum EVENT_14A2
	enum EVENT_14A3
	enum EVENT_14A4
	enum EVENT_14A5
	enum EVENT_14A6
	enum EVENT_14A7

		enum_start 0x14a8 // 0x295
	enum EVENT_14A8
	enum EVENT_14A9
	enum EVENT_14AA
	enum EVENT_14AB
	enum EVENT_14AC
	enum EVENT_14AD
	enum EVENT_14AE
	enum EVENT_14AF

		enum_start 0x14b0 // 0x296
	enum EVENT_14B0
	enum EVENT_14B1
	enum EVENT_14B2
	enum EVENT_14B3
	enum EVENT_14B4
	enum EVENT_14B5
	enum EVENT_14B6
	enum EVENT_14B7

		enum_start 0x14b8 // 0x297
	enum EVENT_14B8
	enum EVENT_14B9
	enum EVENT_14BA
	enum EVENT_14BB
	enum EVENT_14BC
	enum EVENT_14BD
	enum EVENT_14BE
	enum EVENT_14BF

		enum_start 0x14c0 // 0x298
	enum EVENT_14C0
	enum EVENT_14C1
	enum EVENT_14C2
	enum EVENT_14C3
	enum EVENT_14C4
	enum EVENT_14C5
	enum EVENT_14C6
	enum EVENT_14C7

		enum_start 0x14c8 // 0x299
	enum EVENT_14C8
	enum EVENT_14C9
	enum EVENT_14CA
	enum EVENT_14CB
	enum EVENT_14CC
	enum EVENT_14CD
	enum EVENT_14CE
	enum EVENT_14CF

		enum_start 0x14d0 // 0x29A
	enum EVENT_14D0
	enum EVENT_14D1
	enum EVENT_14D2
	enum EVENT_14D3
	enum EVENT_14D4
	enum EVENT_14D5
	enum EVENT_14D6
	enum EVENT_14D7

		enum_start 0x14d8 // 0x29B
	enum EVENT_14D8
	enum EVENT_14D9
	enum EVENT_14DA
	enum EVENT_14DB
	enum EVENT_14DC
	enum EVENT_14DD
	enum EVENT_14DE
	enum EVENT_14DF

		enum_start 0x14e0 // 0x29C
	enum EVENT_14E0
	enum EVENT_14E1
	enum EVENT_14E2
	enum EVENT_14E3
	enum EVENT_14E4
	enum EVENT_14E5
	enum EVENT_14E6
	enum EVENT_14E7

		enum_start 0x14e8 // 0x29D
	enum EVENT_14E8
	enum EVENT_14E9
	enum EVENT_14EA
	enum EVENT_14EB
	enum EVENT_14EC
	enum EVENT_14ED
	enum EVENT_14EE
	enum EVENT_14EF

		enum_start 0x14f0 // 0x29E
	enum EVENT_14F0
	enum EVENT_14F1
	enum EVENT_14F2
	enum EVENT_14F3
	enum EVENT_14F4
	enum EVENT_14F5
	enum EVENT_14F6
	enum EVENT_14F7

		enum_start 0x14f8 // 0x29F
	enum EVENT_14F8
	enum EVENT_14F9
	enum EVENT_14FA
	enum EVENT_14FB
	enum EVENT_14FC
	enum EVENT_14FD
	enum EVENT_14FE
	enum EVENT_14FF

		enum_start 0x1500 // 0x2A0
	enum EVENT_1500
	enum EVENT_1501
	enum EVENT_1502
	enum EVENT_1503
	enum EVENT_1504
	enum EVENT_1505
	enum EVENT_1506
	enum EVENT_1507

		enum_start 0x1508 // 0x2A1
	enum EVENT_1508
	enum EVENT_1509
	enum EVENT_150A
	enum EVENT_150B
	enum EVENT_150C
	enum EVENT_150D
	enum EVENT_150E
	enum EVENT_150F

		enum_start 0x1510 // 0x2A2
	enum EVENT_1510
	enum EVENT_1511
	enum EVENT_1512
	enum EVENT_1513
	enum EVENT_1514
	enum EVENT_1515
	enum EVENT_1516
	enum EVENT_1517

		enum_start 0x1518 // 0x2A3
	enum EVENT_1518
	enum EVENT_1519
	enum EVENT_151A
	enum EVENT_151B
	enum EVENT_151C
	enum EVENT_151D
	enum EVENT_151E
	enum EVENT_151F

		enum_start 0x1520 // 0x2A4
	enum EVENT_1520
	enum EVENT_1521
	enum EVENT_1522
	enum EVENT_1523
	enum EVENT_1524
	enum EVENT_1525
	enum EVENT_1526
	enum EVENT_1527

		enum_start 0x1528 // 0x2A5
	enum EVENT_1528
	enum EVENT_1529
	enum EVENT_152A
	enum EVENT_152B
	enum EVENT_152C
	enum EVENT_152D
	enum EVENT_152E
	enum EVENT_152F

		enum_start 0x1530 // 0x2A6
	enum EVENT_1530
	enum EVENT_1531
	enum EVENT_1532
	enum EVENT_1533
	enum EVENT_1534
	enum EVENT_1535
	enum EVENT_1536
	enum EVENT_1537

		enum_start 0x1538 // 0x2A7
	enum EVENT_1538
	enum EVENT_1539
	enum EVENT_153A
	enum EVENT_153B
	enum EVENT_153C
	enum EVENT_153D
	enum EVENT_153E
	enum EVENT_153F

		enum_start 0x1540 // 0x2A8
	enum EVENT_1540
	enum EVENT_1541
	enum EVENT_1542
	enum EVENT_1543
	enum EVENT_1544
	enum EVENT_1545
	enum EVENT_1546
	enum EVENT_1547

		enum_start 0x1548 // 0x2A9
	enum EVENT_1548
	enum EVENT_1549
	enum EVENT_154A
	enum EVENT_154B
	enum EVENT_154C
	enum EVENT_154D
	enum EVENT_154E
	enum EVENT_154F

		enum_start 0x1550 // 0x2AA
	enum EVENT_1550
	enum EVENT_1551
	enum EVENT_1552
	enum EVENT_1553
	enum EVENT_1554
	enum EVENT_1555
	enum EVENT_1556
	enum EVENT_1557

		enum_start 0x1558 // 0x2AB
	enum EVENT_1558
	enum EVENT_1559
	enum EVENT_155A
	enum EVENT_155B
	enum EVENT_155C
	enum EVENT_155D
	enum EVENT_155E
	enum EVENT_155F

		enum_start 0x1560 // 0x2AC
	enum EVENT_1560
	enum EVENT_1561
	enum EVENT_1562
	enum EVENT_1563
	enum EVENT_1564
	enum EVENT_1565
	enum EVENT_1566
	enum EVENT_1567

		enum_start 0x1568 // 0x2AD
	enum EVENT_1568
	enum EVENT_1569
	enum EVENT_156A
	enum EVENT_156B
	enum EVENT_156C
	enum EVENT_156D
	enum EVENT_156E
	enum EVENT_156F

		enum_start 0x1570 // 0x2AE
	enum EVENT_1570
	enum EVENT_1571
	enum EVENT_1572
	enum EVENT_1573
	enum EVENT_1574
	enum EVENT_1575
	enum EVENT_1576
	enum EVENT_1577

		enum_start 0x1578 // 0x2AF
	enum EVENT_1578
	enum EVENT_1579
	enum EVENT_157A
	enum EVENT_157B
	enum EVENT_157C
	enum EVENT_157D
	enum EVENT_157E
	enum EVENT_157F

		enum_start 0x1580 // 0x2B0
	enum EVENT_1580
	enum EVENT_1581
	enum EVENT_1582
	enum EVENT_1583
	enum EVENT_1584
	enum EVENT_1585
	enum EVENT_1586
	enum EVENT_1587

		enum_start 0x1588 // 0x2B1
	enum EVENT_1588
	enum EVENT_1589
	enum EVENT_158A
	enum EVENT_158B
	enum EVENT_158C
	enum EVENT_158D
	enum EVENT_158E
	enum EVENT_158F

		enum_start 0x1590 // 0x2B2
	enum EVENT_1590
	enum EVENT_1591
	enum EVENT_1592
	enum EVENT_1593
	enum EVENT_1594
	enum EVENT_1595
	enum EVENT_1596
	enum EVENT_1597

		enum_start 0x1598 // 0x2B3
	enum EVENT_1598
	enum EVENT_1599
	enum EVENT_159A
	enum EVENT_159B
	enum EVENT_159C
	enum EVENT_159D
	enum EVENT_159E
	enum EVENT_159F

		enum_start 0x15a0 // 0x2B4
	enum EVENT_15A0
	enum EVENT_15A1
	enum EVENT_15A2
	enum EVENT_15A3
	enum EVENT_15A4
	enum EVENT_15A5
	enum EVENT_15A6
	enum EVENT_15A7

		enum_start 0x15a8 // 0x2B5
	enum EVENT_15A8
	enum EVENT_15A9
	enum EVENT_15AA
	enum EVENT_15AB
	enum EVENT_15AC
	enum EVENT_15AD
	enum EVENT_15AE
	enum EVENT_15AF

		enum_start 0x15b0 // 0x2B6
	enum EVENT_15B0
	enum EVENT_15B1
	enum EVENT_15B2
	enum EVENT_15B3
	enum EVENT_15B4
	enum EVENT_15B5
	enum EVENT_15B6
	enum EVENT_15B7

		enum_start 0x15b8 // 0x2B7
	enum EVENT_15B8
	enum EVENT_15B9
	enum EVENT_15BA
	enum EVENT_15BB
	enum EVENT_15BC
	enum EVENT_15BD
	enum EVENT_15BE
	enum EVENT_15BF

		enum_start 0x15c0 // 0x2B8
	enum EVENT_15C0
	enum EVENT_15C1
	enum EVENT_15C2
	enum EVENT_15C3
	enum EVENT_15C4
	enum EVENT_15C5
	enum EVENT_15C6
	enum EVENT_15C7

		enum_start 0x15c8 // 0x2B9
	enum EVENT_15C8
	enum EVENT_15C9
	enum EVENT_15CA
	enum EVENT_15CB
	enum EVENT_15CC
	enum EVENT_15CD
	enum EVENT_15CE
	enum EVENT_15CF

		enum_start 0x15d0 // 0x2BA
	enum EVENT_15D0
	enum EVENT_15D1
	enum EVENT_15D2
	enum EVENT_15D3
	enum EVENT_15D4
	enum EVENT_15D5
	enum EVENT_15D6
	enum EVENT_15D7

		enum_start 0x15d8 // 0x2BB
	enum EVENT_15D8
	enum EVENT_15D9
	enum EVENT_15DA
	enum EVENT_15DB
	enum EVENT_15DC
	enum EVENT_15DD
	enum EVENT_15DE
	enum EVENT_15DF

		enum_start 0x15e0 // 0x2BC
	enum EVENT_15E0
	enum EVENT_15E1
	enum EVENT_15E2
	enum EVENT_15E3
	enum EVENT_15E4
	enum EVENT_15E5
	enum EVENT_15E6
	enum EVENT_15E7

		enum_start 0x15e8 // 0x2BD
	enum EVENT_15E8
	enum EVENT_15E9
	enum EVENT_15EA
	enum EVENT_15EB
	enum EVENT_15EC
	enum EVENT_15ED
	enum EVENT_15EE
	enum EVENT_15EF

		enum_start 0x15f0 // 0x2BE
	enum EVENT_15F0
	enum EVENT_15F1
	enum EVENT_15F2
	enum EVENT_15F3
	enum EVENT_15F4
	enum EVENT_15F5
	enum EVENT_15F6
	enum EVENT_15F7

		enum_start 0x15f8 // 0x2BF
	enum EVENT_15F8
	enum EVENT_15F9
	enum EVENT_15FA
	enum EVENT_15FB
	enum EVENT_15FC
	enum EVENT_15FD
	enum EVENT_15FE
	enum EVENT_15FF

		enum_start 0x1600 // 0x2C0
	enum EVENT_1600
	enum EVENT_1601
	enum EVENT_1602
	enum EVENT_1603
	enum EVENT_1604
	enum EVENT_1605
	enum EVENT_1606
	enum EVENT_1607

		enum_start 0x1608 // 0x2C1
	enum EVENT_1608
	enum EVENT_1609
	enum EVENT_160A
	enum EVENT_160B
	enum EVENT_160C
	enum EVENT_160D
	enum EVENT_160E
	enum EVENT_160F

		enum_start 0x1610 // 0x2C2
	enum EVENT_1610
	enum EVENT_1611
	enum EVENT_1612
	enum EVENT_1613
	enum EVENT_1614
	enum EVENT_1615
	enum EVENT_1616
	enum EVENT_1617

		enum_start 0x1618 // 0x2C3
	enum EVENT_1618
	enum EVENT_1619
	enum EVENT_161A
	enum EVENT_161B
	enum EVENT_161C
	enum EVENT_161D
	enum EVENT_161E
	enum EVENT_161F

		enum_start 0x1620 // 0x2C4
	enum EVENT_1620
	enum EVENT_1621
	enum EVENT_1622
	enum EVENT_1623
	enum EVENT_1624
	enum EVENT_1625
	enum EVENT_1626
	enum EVENT_1627

		enum_start 0x1628 // 0x2C5
	enum EVENT_1628
	enum EVENT_1629
	enum EVENT_162A
	enum EVENT_162B
	enum EVENT_162C
	enum EVENT_162D
	enum EVENT_162E
	enum EVENT_162F

		enum_start 0x1630 // 0x2C6
	enum EVENT_1630
	enum EVENT_1631
	enum EVENT_1632
	enum EVENT_1633
	enum EVENT_1634
	enum EVENT_1635
	enum EVENT_1636
	enum EVENT_1637

		enum_start 0x1638 // 0x2C7
	enum EVENT_1638
	enum EVENT_1639
	enum EVENT_163A
	enum EVENT_163B
	enum EVENT_163C
	enum EVENT_163D
	enum EVENT_163E
	enum EVENT_163F

		enum_start 0x1640 // 0x2C8
	enum EVENT_1640
	enum EVENT_1641
	enum EVENT_1642
	enum EVENT_1643
	enum EVENT_1644
	enum EVENT_1645
	enum EVENT_1646
	enum EVENT_1647

		enum_start 0x1648 // 0x2C9
	enum EVENT_1648
	enum EVENT_1649
	enum EVENT_164A
	enum EVENT_164B
	enum EVENT_164C
	enum EVENT_164D
	enum EVENT_164E
	enum EVENT_164F

		enum_start 0x1650 // 0x2CA
	enum EVENT_1650
	enum EVENT_1651
	enum EVENT_1652
	enum EVENT_1653
	enum EVENT_1654
	enum EVENT_1655
	enum EVENT_1656
	enum EVENT_1657

		enum_start 0x1658 // 0x2CB
	enum EVENT_1658
	enum EVENT_1659
	enum EVENT_165A
	enum EVENT_165B
	enum EVENT_165C
	enum EVENT_165D
	enum EVENT_165E
	enum EVENT_165F

		enum_start 0x1660 // 0x2CC
	enum EVENT_1660
	enum EVENT_1661
	enum EVENT_1662
	enum EVENT_1663
	enum EVENT_1664
	enum EVENT_1665
	enum EVENT_1666
	enum EVENT_1667

		enum_start 0x1668 // 0x2CD
	enum EVENT_1668
	enum EVENT_1669
	enum EVENT_166A
	enum EVENT_166B
	enum EVENT_166C
	enum EVENT_166D
	enum EVENT_166E
	enum EVENT_166F

		enum_start 0x1670 // 0x2CE
	enum EVENT_1670
	enum EVENT_1671
	enum EVENT_1672
	enum EVENT_1673
	enum EVENT_1674
	enum EVENT_1675
	enum EVENT_1676
	enum EVENT_1677

		enum_start 0x1678 // 0x2CF
	enum EVENT_1678
	enum EVENT_1679
	enum EVENT_167A
	enum EVENT_167B
	enum EVENT_167C
	enum EVENT_167D
	enum EVENT_167E
	enum EVENT_167F

		enum_start 0x1680 // 0x2D0
	enum EVENT_1680
	enum EVENT_1681
	enum EVENT_1682
	enum EVENT_1683
	enum EVENT_1684
	enum EVENT_1685
	enum EVENT_1686
	enum EVENT_1687

		enum_start 0x1688 // 0x2D1
	enum EVENT_1688
	enum EVENT_1689
	enum EVENT_168A
	enum EVENT_168B
	enum EVENT_168C
	enum EVENT_168D
	enum EVENT_168E
	enum EVENT_168F

		enum_start 0x1690 // 0x2D2
	enum EVENT_1690
	enum EVENT_1691
	enum EVENT_1692
	enum EVENT_1693
	enum EVENT_1694
	enum EVENT_1695
	enum EVENT_1696
	enum EVENT_1697

		enum_start 0x1698 // 0x2D3
	enum EVENT_1698
	enum EVENT_1699
	enum EVENT_169A
	enum EVENT_169B
	enum EVENT_169C
	enum EVENT_169D
	enum EVENT_169E
	enum EVENT_169F

		enum_start 0x16a0 // 0x2D4
	enum EVENT_16A0
	enum EVENT_16A1
	enum EVENT_16A2
	enum EVENT_16A3
	enum EVENT_16A4
	enum EVENT_16A5
	enum EVENT_16A6
	enum EVENT_16A7

		enum_start 0x16a8 // 0x2D5
	enum EVENT_16A8
	enum EVENT_16A9
	enum EVENT_16AA
	enum EVENT_16AB
	enum EVENT_16AC
	enum EVENT_16AD
	enum EVENT_16AE
	enum EVENT_16AF

		enum_start 0x16b0 // 0x2D6
	enum EVENT_16B0
	enum EVENT_16B1
	enum EVENT_16B2
	enum EVENT_16B3
	enum EVENT_16B4
	enum EVENT_16B5
	enum EVENT_16B6
	enum EVENT_16B7

		enum_start 0x16b8 // 0x2D7
	enum EVENT_16B8
	enum EVENT_16B9
	enum EVENT_16BA
	enum EVENT_16BB
	enum EVENT_16BC
	enum EVENT_16BD
	enum EVENT_16BE
	enum EVENT_16BF

		enum_start 0x16c0 // 0x2D8
	enum EVENT_16C0
	enum EVENT_16C1
	enum EVENT_16C2
	enum EVENT_16C3
	enum EVENT_16C4
	enum EVENT_16C5
	enum EVENT_16C6
	enum EVENT_16C7

		enum_start 0x16c8 // 0x2D9
	enum EVENT_16C8
	enum EVENT_16C9
	enum EVENT_16CA
	enum EVENT_16CB
	enum EVENT_16CC
	enum EVENT_16CD
	enum EVENT_16CE
	enum EVENT_16CF

		enum_start 0x16d0 // 0x2DA
	enum EVENT_16D0
	enum EVENT_16D1
	enum EVENT_16D2
	enum EVENT_16D3
	enum EVENT_16D4
	enum EVENT_16D5
	enum EVENT_16D6
	enum EVENT_16D7

		enum_start 0x16d8 // 0x2DB
	enum EVENT_16D8
	enum EVENT_16D9
	enum EVENT_16DA
	enum EVENT_16DB
	enum EVENT_16DC
	enum EVENT_16DD
	enum EVENT_16DE
	enum EVENT_16DF

		enum_start 0x16e0 // 0x2DC
	enum EVENT_16E0
	enum EVENT_16E1
	enum EVENT_16E2
	enum EVENT_16E3
	enum EVENT_16E4
	enum EVENT_16E5
	enum EVENT_16E6
	enum EVENT_16E7

		enum_start 0x16e8 // 0x2DD
	enum EVENT_16E8
	enum EVENT_16E9
	enum EVENT_16EA
	enum EVENT_16EB
	enum EVENT_16EC
	enum EVENT_16ED
	enum EVENT_16EE
	enum EVENT_16EF

		enum_start 0x16f0 // 0x2DE
	enum EVENT_16F0
	enum EVENT_16F1
	enum EVENT_16F2
	enum EVENT_16F3
	enum EVENT_16F4
	enum EVENT_16F5
	enum EVENT_16F6
	enum EVENT_16F7

		enum_start 0x16f8 // 0x2DF
	enum EVENT_16F8
	enum EVENT_16F9
	enum EVENT_16FA
	enum EVENT_16FB
	enum EVENT_16FC
	enum EVENT_16FD
	enum EVENT_16FE
	enum EVENT_16FF

		enum_start 0x1700 // 0x2E0
	enum EVENT_1700
	// disables object animation/translation and collisions
	enum EVENT_NPC_OBJECTS_DISABLED
	// applies to portals and battle animation
	enum EVENT_NON_NPC_ANIMATION_LOCKED
	enum EVENT_1703
	enum EVENT_1704
	enum EVENT_1705
	enum EVENT_PET_COMM_SAVE_DISABLED
	enum EVENT_PET_DISABLED

		enum_start 0x1708 // 0x2E1
	enum EVENT_1708
	enum EVENT_1709
	enum EVENT_170A
	enum EVENT_170B
	enum EVENT_170C
	enum EVENT_170D
	enum EVENT_170E
	enum EVENT_170F

		enum_start 0x1710 // 0x2E2
	enum EVENT_1710
	enum EVENT_1711
	enum EVENT_1712
	enum EVENT_1713
	enum EVENT_PLAYER_CAN_MOVE
	// if 0, npc resets to default position after talking
	// else they remain in the direction that was facing the player
	enum EVENT_EVENT_CUR_DIR_LOCKED
	enum EVENT_1716 // constantly written
	enum EVENT_1717_PLAYER_ADVANCE_FORWARD

		enum_start 0x1718 // 0x2E3
	enum EVENT_1718
	enum EVENT_1719
	enum EVENT_171A
	enum EVENT_171B
	// activates when pressing L, jacking in,
	// and talking to objects (but not NPCs?)
	// otherwise constantly cleared
	enum EVENT_171C
	// MegaMan disappears from PET, HP becomes 0/0
	enum EVENT_PET_NAVI_ACTIVE
	enum EVENT_171E
	enum EVENT_171F

		enum_start 0x1720 // 0x2E4
	enum EVENT_1720
	enum EVENT_1721
	enum EVENT_1722
	enum EVENT_1723
	enum EVENT_1724
	enum EVENT_1725
	enum EVENT_1726
	enum EVENT_1727

		enum_start 0x1728 // 0x2E5
	enum EVENT_L_MESSAGE_ACTIVE
	// when enabled, Lan's sprite is replaced with MegaMan
	enum EVENT_COPYBOT_ACTIVE
	enum EVENT_172A
	enum EVENT_172B
	enum EVENT_172C
	enum EVENT_172D
	enum EVENT_172E
	enum EVENT_172F

		enum_start 0x1730 // 0x2E6
	enum EVENT_1730
	enum EVENT_1731
	enum EVENT_1732
	enum EVENT_1733
	enum EVENT_1734
	enum EVENT_1735
	enum EVENT_1736
	enum EVENT_1737

		enum_start 0x1738 // 0x2E7
	enum EVENT_1738
	enum EVENT_1739
	enum EVENT_173A
	enum EVENT_173B
	enum EVENT_173C
	enum EVENT_173D
	enum EVENT_173E
	enum EVENT_173F

		enum_start 0x1740 // 0x2E8
	enum EVENT_1740
	enum EVENT_1741
	enum EVENT_1742
	enum EVENT_1743
	enum EVENT_1744
	enum EVENT_1745
	enum EVENT_1746
	enum EVENT_1747

		enum_start 0x1748 // 0x2E9
	enum EVENT_1748
	enum EVENT_1749
	enum EVENT_174A
	enum EVENT_174B
	enum EVENT_174C
	enum EVENT_174D
	enum EVENT_174E
	enum EVENT_174F

		enum_start 0x1750 // 0x2EA
	enum EVENT_1750
	enum EVENT_1751
	enum EVENT_1752
	enum EVENT_1753
	enum EVENT_1754
	enum EVENT_1755
	enum EVENT_1756
	enum EVENT_1757

		enum_start 0x1758 // 0x2EB
	enum EVENT_1758
	enum EVENT_1759
	enum EVENT_175A
	enum EVENT_175B
	enum EVENT_175C
	enum EVENT_175D
	enum EVENT_175E
	enum EVENT_175F

		enum_start 0x1760 // 0x2EC
	enum EVENT_1760
	enum EVENT_1761
	enum EVENT_1762
	enum EVENT_1763
	enum EVENT_1764
	enum EVENT_1765
	enum EVENT_1766
	enum EVENT_1767

		enum_start 0x1768 // 0x2ED
	enum EVENT_1768
	enum EVENT_1769
	enum EVENT_176A
	enum EVENT_176B
	enum EVENT_176C
	enum EVENT_176D
	enum EVENT_176E
	enum EVENT_176F

		enum_start 0x1770 // 0x2EE
	enum EVENT_1770
	enum EVENT_1771
	enum EVENT_1772
	enum EVENT_1773
	enum EVENT_1774
	enum EVENT_1775
	enum EVENT_1776
	enum EVENT_1777

		enum_start 0x1778 // 0x2EF
	enum EVENT_1778
	enum EVENT_1779
	enum EVENT_177A
	enum EVENT_177B
	enum EVENT_177C
	enum EVENT_177D
	enum EVENT_177E
	enum EVENT_177F

		enum_start 0x1780 // 0x2F0
	enum EVENT_1780
	enum EVENT_1781
	enum EVENT_1782
	enum EVENT_1783
	enum EVENT_1784
	enum EVENT_1785
	enum EVENT_1786
	enum EVENT_1787

		enum_start 0x1788 // 0x2F1
	enum EVENT_1788
	enum EVENT_1789
	enum EVENT_178A
	enum EVENT_178B
	enum EVENT_178C
	enum EVENT_178D
	enum EVENT_178E
	enum EVENT_178F

		enum_start 0x1790 // 0x2F2
	enum EVENT_1790
	enum EVENT_1791
	enum EVENT_1792
	enum EVENT_1793
	enum EVENT_1794
	enum EVENT_1795
	enum EVENT_1796
	enum EVENT_1797

		enum_start 0x1798 // 0x2F3
	enum EVENT_1798
	enum EVENT_1799
	enum EVENT_179A
	enum EVENT_179B
	enum EVENT_179C
	enum EVENT_179D
	enum EVENT_179E
	enum EVENT_179F

		enum_start 0x17a0 // 0x2F4
	enum EVENT_17A0
	enum EVENT_17A1
	enum EVENT_17A2
	enum EVENT_17A3
	enum EVENT_17A4
	enum EVENT_17A5
	enum EVENT_17A6
	enum EVENT_17A7

		enum_start 0x17a8 // 0x2F5
	enum EVENT_17A8
	enum EVENT_17A9
	enum EVENT_17AA
	enum EVENT_17AB
	enum EVENT_17AC
	enum EVENT_17AD
	enum EVENT_17AE
	enum EVENT_17AF

		enum_start 0x17b0 // 0x2F6
	enum EVENT_17B0
	enum EVENT_17B1
	enum EVENT_17B2
	enum EVENT_17B3
	enum EVENT_17B4
	enum EVENT_17B5
	enum EVENT_17B6
	enum EVENT_17B7

		enum_start 0x17b8 // 0x2F7
	enum EVENT_17B8
	enum EVENT_17B9
	enum EVENT_17BA
	enum EVENT_17BB
	enum EVENT_17BC
	enum EVENT_17BD
	enum EVENT_17BE
	enum EVENT_17BF

		enum_start 0x17c0 // 0x2F8
	enum EVENT_17C0
	enum EVENT_17C1
	enum EVENT_17C2
	enum EVENT_17C3
	enum EVENT_17C4
	enum EVENT_17C5
	enum EVENT_17C6
	enum EVENT_17C7

		enum_start 0x17c8 // 0x2F9
	enum EVENT_17C8
	enum EVENT_17C9
	enum EVENT_17CA
	enum EVENT_17CB
	enum EVENT_17CC
	enum EVENT_17CD
	enum EVENT_17CE
	enum EVENT_17CF

		enum_start 0x17d0 // 0x2FA
	enum EVENT_17D0
	enum EVENT_17D1
	enum EVENT_17D2
	enum EVENT_17D3
	enum EVENT_17D4
	enum EVENT_17D5
	enum EVENT_17D6
	enum EVENT_17D7

		enum_start 0x17d8 // 0x2FB
	enum EVENT_17D8
	enum EVENT_17D9
	enum EVENT_17DA
	enum EVENT_17DB
	enum EVENT_17DC
	enum EVENT_17DD
	enum EVENT_17DE
	enum EVENT_17DF

		enum_start 0x17e0 // 0x2FC
	enum EVENT_17E0
	enum EVENT_17E1
	enum EVENT_17E2
	enum EVENT_17E3
	enum EVENT_17E4
	enum EVENT_17E5
	enum EVENT_17E6
	enum EVENT_17E7

		enum_start 0x17e8 // 0x2FD
	enum EVENT_17E8
	enum EVENT_17E9
	enum EVENT_17EA
	enum EVENT_17EB
	enum EVENT_17EC
	enum EVENT_17ED
	enum EVENT_17EE
	enum EVENT_17EF

		enum_start 0x17f0 // 0x2FE
	enum EVENT_17F0
	enum EVENT_17F1
	enum EVENT_17F2
	enum EVENT_17F3
	enum EVENT_17F4
	enum EVENT_17F5
	enum EVENT_17F6
	enum EVENT_17F7

		enum_start 0x17f8 // 0x2FF
	enum EVENT_17F8
	enum EVENT_17F9
	enum EVENT_17FA
	enum EVENT_17FB
	enum EVENT_17FC
	enum EVENT_17FD
	enum EVENT_17FE
	enum EVENT_17FF

		enum_start 0x1800 // 0x300
	enum EVENT_1800
	enum EVENT_1801
	enum EVENT_1802
	enum EVENT_1803
	enum EVENT_1804
	enum EVENT_1805
	enum EVENT_1806
	enum EVENT_1807

		enum_start 0x1808 // 0x301
	enum EVENT_1808
	enum EVENT_1809
	enum EVENT_180A
	enum EVENT_180B
	enum EVENT_180C
	enum EVENT_180D
	enum EVENT_180E
	enum EVENT_180F

		enum_start 0x1810 // 0x302
	enum EVENT_1810
	enum EVENT_1811
	enum EVENT_1812
	enum EVENT_1813
	enum EVENT_1814
	enum EVENT_1815
	enum EVENT_1816
	enum EVENT_1817

		enum_start 0x1818 // 0x303
	enum EVENT_1818
	enum EVENT_1819
	enum EVENT_181A
	enum EVENT_181B
	enum EVENT_181C
	enum EVENT_181D
	enum EVENT_181E
	enum EVENT_181F

		enum_start 0x1820 // 0x304
	enum EVENT_1820
	enum EVENT_1821
	enum EVENT_1822
	enum EVENT_1823
	enum EVENT_1824
	enum EVENT_1825
	enum EVENT_1826
	enum EVENT_1827

		enum_start 0x1828 // 0x305
	enum EVENT_1828
	enum EVENT_1829
	enum EVENT_182A
	enum EVENT_182B
	enum EVENT_182C
	enum EVENT_182D
	enum EVENT_182E
	enum EVENT_182F

		enum_start 0x1830 // 0x306
	enum EVENT_1830
	enum EVENT_1831
	enum EVENT_1832
	enum EVENT_1833
	enum EVENT_1834
	enum EVENT_1835
	enum EVENT_1836
	enum EVENT_1837

		enum_start 0x1838 // 0x307
	enum EVENT_1838
	enum EVENT_1839
	enum EVENT_183A
	enum EVENT_183B
	enum EVENT_183C
	enum EVENT_183D
	enum EVENT_183E
	enum EVENT_183F

		enum_start 0x1840 // 0x308
	enum EVENT_1840
	enum EVENT_1841
	enum EVENT_1842
	enum EVENT_1843
	enum EVENT_1844
	enum EVENT_1845
	enum EVENT_1846
	enum EVENT_1847

		enum_start 0x1848 // 0x309
	enum EVENT_1848
	enum EVENT_1849
	enum EVENT_184A
	enum EVENT_184B
	enum EVENT_184C
	enum EVENT_184D
	enum EVENT_184E
	enum EVENT_184F

		enum_start 0x1850 // 0x30A
	enum EVENT_1850
	enum EVENT_1851
	enum EVENT_1852
	enum EVENT_1853
	enum EVENT_1854
	enum EVENT_1855
	enum EVENT_1856
	enum EVENT_1857

		enum_start 0x1858 // 0x30B
	enum EVENT_1858
	enum EVENT_1859
	enum EVENT_185A
	enum EVENT_185B
	enum EVENT_185C
	enum EVENT_185D
	enum EVENT_185E
	enum EVENT_185F

		enum_start 0x1860 // 0x30C
	enum EVENT_1860
	enum EVENT_1861
	enum EVENT_1862
	enum EVENT_1863
	enum EVENT_1864
	enum EVENT_1865
	enum EVENT_1866
	enum EVENT_1867

		enum_start 0x1868 // 0x30D
	enum EVENT_1868
	enum EVENT_1869
	enum EVENT_186A
	enum EVENT_186B
	enum EVENT_186C
	enum EVENT_186D
	enum EVENT_186E
	enum EVENT_186F

		enum_start 0x1870 // 0x30E
	enum EVENT_1870
	enum EVENT_1871
	enum EVENT_1872
	enum EVENT_1873
	enum EVENT_1874
	enum EVENT_1875
	enum EVENT_1876
	enum EVENT_1877

		enum_start 0x1878 // 0x30F
	enum EVENT_1878
	enum EVENT_1879
	enum EVENT_187A
	enum EVENT_187B
	enum EVENT_187C
	enum EVENT_187D
	enum EVENT_187E
	enum EVENT_187F

		enum_start 0x1880 // 0x310
	enum EVENT_1880
	enum EVENT_1881
	enum EVENT_1882
	enum EVENT_1883
	enum EVENT_1884
	enum EVENT_1885
	enum EVENT_1886
	enum EVENT_1887

		enum_start 0x1888 // 0x311
	enum EVENT_1888
	enum EVENT_1889
	enum EVENT_188A
	enum EVENT_188B
	enum EVENT_188C
	enum EVENT_188D
	enum EVENT_188E
	enum EVENT_188F

		enum_start 0x1890 // 0x312
	enum EVENT_1890
	enum EVENT_1891
	enum EVENT_1892
	enum EVENT_1893
	enum EVENT_1894
	enum EVENT_1895
	enum EVENT_1896
	enum EVENT_1897

		enum_start 0x1898 // 0x313
	enum EVENT_1898
	enum EVENT_1899
	enum EVENT_189A
	enum EVENT_189B
	enum EVENT_189C
	enum EVENT_189D
	enum EVENT_189E
	enum EVENT_189F

		enum_start 0x18a0 // 0x314
	enum EVENT_18A0
	enum EVENT_18A1
	enum EVENT_18A2
	enum EVENT_18A3
	enum EVENT_18A4
	enum EVENT_18A5
	enum EVENT_18A6
	enum EVENT_18A7

		enum_start 0x18a8 // 0x315
	enum EVENT_18A8
	enum EVENT_18A9
	enum EVENT_18AA
	enum EVENT_18AB
	enum EVENT_18AC
	enum EVENT_18AD
	enum EVENT_18AE
	enum EVENT_18AF

		enum_start 0x18b0 // 0x316
	enum EVENT_18B0
	enum EVENT_18B1
	enum EVENT_18B2
	enum EVENT_18B3
	enum EVENT_18B4
	enum EVENT_18B5
	enum EVENT_18B6
	enum EVENT_18B7

		enum_start 0x18b8 // 0x317
	enum EVENT_18B8
	enum EVENT_18B9
	enum EVENT_18BA
	enum EVENT_18BB
	enum EVENT_18BC
	enum EVENT_18BD
	enum EVENT_18BE
	enum EVENT_18BF

		enum_start 0x18c0 // 0x318
	enum EVENT_18C0
	enum EVENT_18C1
	enum EVENT_18C2
	enum EVENT_18C3
	enum EVENT_18C4
	enum EVENT_18C5
	enum EVENT_18C6
	enum EVENT_18C7

		enum_start 0x18c8 // 0x319
	enum EVENT_18C8
	enum EVENT_18C9
	enum EVENT_18CA
	enum EVENT_18CB
	enum EVENT_18CC
	enum EVENT_18CD
	enum EVENT_18CE
	enum EVENT_18CF

		enum_start 0x18d0 // 0x31A
	enum EVENT_18D0
	enum EVENT_18D1
	enum EVENT_18D2
	enum EVENT_18D3
	enum EVENT_18D4
	enum EVENT_18D5
	enum EVENT_18D6
	enum EVENT_18D7

		enum_start 0x18d8 // 0x31B
	enum EVENT_18D8
	enum EVENT_18D9
	enum EVENT_18DA
	enum EVENT_18DB
	enum EVENT_18DC
	enum EVENT_18DD
	enum EVENT_18DE
	enum EVENT_18DF

		enum_start 0x18e0 // 0x31C
	enum EVENT_18E0
	enum EVENT_18E1
	enum EVENT_18E2
	enum EVENT_18E3
	enum EVENT_18E4
	enum EVENT_18E5
	enum EVENT_18E6
	enum EVENT_18E7

		enum_start 0x18e8 // 0x31D
	enum EVENT_18E8
	enum EVENT_18E9
	enum EVENT_18EA
	enum EVENT_18EB
	enum EVENT_18EC
	enum EVENT_18ED
	enum EVENT_18EE
	enum EVENT_18EF

		enum_start 0x18f0 // 0x31E
	enum EVENT_18F0
	enum EVENT_18F1
	enum EVENT_18F2
	enum EVENT_18F3
	enum EVENT_18F4
	enum EVENT_18F5
	enum EVENT_18F6
	enum EVENT_18F7

		enum_start 0x18f8 // 0x31F
	enum EVENT_18F8
	enum EVENT_18F9
	enum EVENT_18FA
	enum EVENT_18FB
	enum EVENT_18FC
	enum EVENT_18FD
	enum EVENT_18FE
	enum EVENT_18FF

		enum_start 0x1900 // 0x320
	enum EVENT_1900
	enum EVENT_1901
	enum EVENT_1902
	enum EVENT_1903
	enum EVENT_1904
	enum EVENT_1905
	enum EVENT_1906
	enum EVENT_1907

		enum_start 0x1908 // 0x321
	enum EVENT_1908
	enum EVENT_1909
	enum EVENT_190A
	enum EVENT_190B
	enum EVENT_190C
	enum EVENT_190D
	enum EVENT_190E
	enum EVENT_190F

		enum_start 0x1910 // 0x322
	enum EVENT_1910
	enum EVENT_1911
	enum EVENT_1912
	enum EVENT_1913
	enum EVENT_1914
	enum EVENT_1915
	enum EVENT_1916
	enum EVENT_1917

		enum_start 0x1918 // 0x323
	enum EVENT_1918
	enum EVENT_1919
	enum EVENT_191A
	enum EVENT_191B
	enum EVENT_191C
	enum EVENT_191D
	enum EVENT_191E
	enum EVENT_191F

		enum_start 0x1920 // 0x324
	enum EVENT_1920
	enum EVENT_1921
	enum EVENT_1922
	enum EVENT_1923
	enum EVENT_1924
	enum EVENT_1925
	enum EVENT_1926
	enum EVENT_1927

		enum_start 0x1928 // 0x325
	enum EVENT_1928
	enum EVENT_1929
	enum EVENT_192A
	enum EVENT_192B
	enum EVENT_192C
	enum EVENT_192D
	enum EVENT_192E
	enum EVENT_192F

		enum_start 0x1930 // 0x326
	enum EVENT_1930
	enum EVENT_1931
	enum EVENT_1932
	enum EVENT_1933
	enum EVENT_1934
	enum EVENT_1935
	enum EVENT_1936
	enum EVENT_1937

		enum_start 0x1938 // 0x327
	enum EVENT_1938
	enum EVENT_1939
	enum EVENT_193A
	enum EVENT_193B
	enum EVENT_193C
	enum EVENT_193D
	enum EVENT_193E
	enum EVENT_193F

		enum_start 0x1940 // 0x328
	enum EVENT_1940
	enum EVENT_1941
	enum EVENT_1942
	enum EVENT_1943
	enum EVENT_1944
	enum EVENT_1945
	enum EVENT_1946
	enum EVENT_1947

		enum_start 0x1948 // 0x329
	enum EVENT_1948
	enum EVENT_1949
	enum EVENT_194A
	enum EVENT_194B
	enum EVENT_194C
	enum EVENT_194D
	enum EVENT_194E
	enum EVENT_194F

		enum_start 0x1950 // 0x32A
	enum EVENT_1950
	enum EVENT_1951
	enum EVENT_1952
	enum EVENT_1953
	enum EVENT_1954
	enum EVENT_1955
	enum EVENT_1956
	enum EVENT_1957

		enum_start 0x1958 // 0x32B
	enum EVENT_1958
	enum EVENT_1959
	enum EVENT_195A
	enum EVENT_195B
	enum EVENT_195C
	enum EVENT_195D
	enum EVENT_195E
	enum EVENT_195F

		enum_start 0x1960 // 0x32C
	enum EVENT_1960
	enum EVENT_1961
	enum EVENT_1962
	enum EVENT_1963
	enum EVENT_1964
	enum EVENT_1965
	enum EVENT_1966
	enum EVENT_1967

		enum_start 0x1968 // 0x32D
	enum EVENT_1968
	enum EVENT_1969
	enum EVENT_196A
	enum EVENT_196B
	enum EVENT_196C
	enum EVENT_196D
	enum EVENT_196E
	enum EVENT_196F

		enum_start 0x1970 // 0x32E
	enum EVENT_1970
	enum EVENT_1971
	enum EVENT_1972
	enum EVENT_1973
	enum EVENT_1974
	enum EVENT_1975
	enum EVENT_1976
	enum EVENT_1977

		enum_start 0x1978 // 0x32F
	enum EVENT_1978
	enum EVENT_1979
	enum EVENT_197A
	enum EVENT_197B
	enum EVENT_197C
	enum EVENT_197D
	enum EVENT_197E
	enum EVENT_197F

		enum_start 0x1980 // 0x330
	enum EVENT_1980
	enum EVENT_1981
	enum EVENT_1982
	enum EVENT_1983
	enum EVENT_1984
	enum EVENT_1985
	enum EVENT_1986
	enum EVENT_1987

		enum_start 0x1988 // 0x331
	enum EVENT_1988
	enum EVENT_1989
	enum EVENT_198A
	enum EVENT_198B
	enum EVENT_198C
	enum EVENT_198D
	enum EVENT_198E
	enum EVENT_198F

		enum_start 0x1990 // 0x332
	enum EVENT_1990
	enum EVENT_1991
	enum EVENT_1992
	enum EVENT_1993
	enum EVENT_1994
	enum EVENT_1995
	enum EVENT_1996
	enum EVENT_1997

		enum_start 0x1998 // 0x333
	enum EVENT_1998
	enum EVENT_1999
	enum EVENT_199A
	enum EVENT_199B
	enum EVENT_199C
	enum EVENT_199D
	enum EVENT_199E
	enum EVENT_199F

		enum_start 0x19a0 // 0x334
	enum EVENT_19A0
	enum EVENT_19A1
	enum EVENT_19A2
	enum EVENT_19A3
	enum EVENT_19A4
	enum EVENT_19A5
	enum EVENT_19A6
	enum EVENT_19A7

		enum_start 0x19a8 // 0x335
	enum EVENT_19A8
	enum EVENT_19A9
	enum EVENT_19AA
	enum EVENT_19AB
	enum EVENT_19AC
	enum EVENT_19AD
	enum EVENT_19AE
	enum EVENT_19AF

		enum_start 0x19b0 // 0x336
	enum EVENT_19B0
	enum EVENT_19B1
	enum EVENT_19B2
	enum EVENT_19B3
	enum EVENT_19B4
	enum EVENT_19B5
	enum EVENT_19B6
	enum EVENT_19B7

		enum_start 0x19b8 // 0x337
	enum EVENT_19B8
	enum EVENT_19B9
	enum EVENT_19BA
	enum EVENT_19BB
	enum EVENT_19BC
	enum EVENT_19BD
	enum EVENT_19BE
	enum EVENT_19BF

		enum_start 0x19c0 // 0x338
	enum EVENT_19C0
	enum EVENT_19C1
	enum EVENT_19C2
	enum EVENT_19C3
	enum EVENT_19C4
	enum EVENT_19C5
	enum EVENT_19C6
	enum EVENT_19C7

		enum_start 0x19c8 // 0x339
	enum EVENT_19C8
	enum EVENT_19C9
	enum EVENT_19CA
	enum EVENT_19CB
	enum EVENT_19CC
	enum EVENT_19CD
	enum EVENT_19CE
	enum EVENT_19CF

		enum_start 0x19d0 // 0x33A
	enum EVENT_19D0
	enum EVENT_19D1
	enum EVENT_19D2
	enum EVENT_19D3
	enum EVENT_19D4
	enum EVENT_19D5
	enum EVENT_19D6
	enum EVENT_19D7

		enum_start 0x19d8 // 0x33B
	enum EVENT_19D8
	enum EVENT_19D9
	enum EVENT_19DA
	enum EVENT_19DB
	enum EVENT_19DC
	enum EVENT_19DD
	enum EVENT_19DE
	enum EVENT_19DF

		enum_start 0x19e0 // 0x33C
	enum EVENT_19E0
	enum EVENT_19E1
	enum EVENT_19E2
	enum EVENT_19E3
	enum EVENT_19E4
	enum EVENT_19E5
	enum EVENT_19E6
	enum EVENT_19E7

		enum_start 0x19e8 // 0x33D
	enum EVENT_19E8
	enum EVENT_19E9
	enum EVENT_19EA
	enum EVENT_19EB
	enum EVENT_19EC
	enum EVENT_19ED
	enum EVENT_19EE
	enum EVENT_19EF

		enum_start 0x19f0 // 0x33E
	enum EVENT_19F0
	enum EVENT_19F1
	enum EVENT_19F2
	enum EVENT_19F3
	enum EVENT_19F4
	enum EVENT_19F5
	enum EVENT_19F6
	enum EVENT_19F7

		enum_start 0x19f8 // 0x33F
	enum EVENT_19F8
	enum EVENT_19F9
	enum EVENT_19FA
	enum EVENT_19FB
	enum EVENT_19FC
	enum EVENT_19FD
	enum EVENT_19FE
	enum EVENT_19FF

		enum_start 0x1a00 // 0x340
	enum EVENT_1A00
	enum EVENT_1A01
	enum EVENT_1A02
	enum EVENT_1A03
	enum EVENT_1A04
	enum EVENT_1A05
	enum EVENT_1A06
	enum EVENT_1A07

		enum_start 0x1a08 // 0x341
	enum EVENT_1A08
	enum EVENT_1A09
	enum EVENT_1A0A
	enum EVENT_1A0B
	enum EVENT_1A0C
	enum EVENT_1A0D
	enum EVENT_1A0E
	enum EVENT_1A0F

		enum_start 0x1a10 // 0x342
	enum EVENT_1A10
	enum EVENT_1A11
	enum EVENT_1A12
	enum EVENT_1A13
	enum EVENT_1A14
	enum EVENT_1A15
	enum EVENT_1A16
	enum EVENT_1A17

		enum_start 0x1a18 // 0x343
	enum EVENT_1A18
	enum EVENT_1A19
	enum EVENT_1A1A
	enum EVENT_1A1B
	enum EVENT_1A1C
	enum EVENT_1A1D
	enum EVENT_1A1E
	enum EVENT_1A1F

		enum_start 0x1a20 // 0x344
	enum EVENT_1A20
	enum EVENT_1A21
	enum EVENT_1A22
	enum EVENT_1A23
	enum EVENT_1A24
	enum EVENT_1A25
	enum EVENT_1A26
	enum EVENT_1A27

		enum_start 0x1a28 // 0x345
	enum EVENT_1A28
	enum EVENT_1A29
	enum EVENT_1A2A
	enum EVENT_1A2B
	enum EVENT_1A2C
	enum EVENT_1A2D
	enum EVENT_1A2E
	enum EVENT_1A2F

		enum_start 0x1a30 // 0x346
	enum EVENT_1A30
	enum EVENT_1A31
	enum EVENT_1A32
	enum EVENT_1A33
	enum EVENT_1A34
	enum EVENT_1A35
	enum EVENT_1A36
	enum EVENT_1A37

		enum_start 0x1a38 // 0x347
	enum EVENT_1A38
	enum EVENT_1A39
	enum EVENT_1A3A
	enum EVENT_1A3B
	enum EVENT_1A3C
	enum EVENT_1A3D
	enum EVENT_1A3E
	enum EVENT_1A3F

		enum_start 0x1a40 // 0x348
	enum EVENT_1A40
	enum EVENT_1A41
	enum EVENT_1A42
	enum EVENT_1A43
	enum EVENT_1A44
	enum EVENT_1A45
	enum EVENT_1A46
	enum EVENT_1A47

		enum_start 0x1a48 // 0x349
	enum EVENT_1A48
	enum EVENT_1A49
	enum EVENT_1A4A
	enum EVENT_1A4B
	enum EVENT_1A4C
	enum EVENT_1A4D
	enum EVENT_1A4E
	enum EVENT_1A4F

		enum_start 0x1a50 // 0x34A
	enum EVENT_1A50
	enum EVENT_1A51
	enum EVENT_1A52
	enum EVENT_1A53
	enum EVENT_1A54
	enum EVENT_1A55
	enum EVENT_1A56
	enum EVENT_1A57

		enum_start 0x1a58 // 0x34B
	enum EVENT_1A58
	enum EVENT_1A59
	enum EVENT_1A5A
	enum EVENT_1A5B
	enum EVENT_1A5C
	enum EVENT_1A5D
	enum EVENT_1A5E
	enum EVENT_1A5F

		enum_start 0x1a60 // 0x34C
	enum EVENT_1A60
	enum EVENT_1A61
	enum EVENT_1A62
	enum EVENT_1A63
	enum EVENT_1A64
	enum EVENT_1A65
	enum EVENT_1A66
	enum EVENT_1A67

		enum_start 0x1a68 // 0x34D
	enum EVENT_1A68
	enum EVENT_1A69
	enum EVENT_1A6A
	enum EVENT_1A6B
	enum EVENT_1A6C
	enum EVENT_1A6D
	enum EVENT_1A6E
	enum EVENT_1A6F

		enum_start 0x1a70 // 0x34E
	enum EVENT_1A70
	enum EVENT_1A71
	enum EVENT_1A72
	enum EVENT_1A73
	enum EVENT_1A74
	enum EVENT_1A75
	enum EVENT_1A76
	enum EVENT_1A77

		enum_start 0x1a78 // 0x34F
	enum EVENT_1A78
	enum EVENT_1A79
	enum EVENT_1A7A
	enum EVENT_1A7B
	enum EVENT_1A7C
	enum EVENT_1A7D
	enum EVENT_1A7E
	enum EVENT_1A7F

		enum_start 0x1a80 // 0x350
	enum EVENT_1A80
	enum EVENT_1A81
	enum EVENT_1A82
	enum EVENT_1A83
	enum EVENT_1A84
	enum EVENT_1A85
	enum EVENT_1A86
	enum EVENT_1A87

		enum_start 0x1a88 // 0x351
	enum EVENT_1A88
	enum EVENT_1A89
	enum EVENT_1A8A
	enum EVENT_1A8B
	enum EVENT_1A8C
	enum EVENT_1A8D
	enum EVENT_1A8E
	enum EVENT_1A8F

		enum_start 0x1a90 // 0x352
	enum EVENT_1A90
	enum EVENT_1A91
	enum EVENT_1A92
	enum EVENT_1A93
	enum EVENT_1A94
	enum EVENT_1A95
	enum EVENT_1A96
	enum EVENT_1A97

		enum_start 0x1a98 // 0x353
	enum EVENT_1A98
	enum EVENT_1A99
	enum EVENT_1A9A
	enum EVENT_1A9B
	enum EVENT_1A9C
	enum EVENT_1A9D
	enum EVENT_1A9E
	enum EVENT_1A9F

		enum_start 0x1aa0 // 0x354
	enum EVENT_1AA0
	enum EVENT_1AA1
	enum EVENT_1AA2
	enum EVENT_1AA3
	enum EVENT_1AA4
	enum EVENT_1AA5
	enum EVENT_1AA6
	enum EVENT_1AA7

		enum_start 0x1aa8 // 0x355
	enum EVENT_1AA8
	enum EVENT_1AA9
	enum EVENT_1AAA
	enum EVENT_1AAB
	enum EVENT_1AAC
	enum EVENT_1AAD
	enum EVENT_1AAE
	enum EVENT_1AAF

		enum_start 0x1ab0 // 0x356
	enum EVENT_1AB0
	enum EVENT_1AB1
	enum EVENT_1AB2
	enum EVENT_1AB3
	enum EVENT_1AB4
	enum EVENT_1AB5
	enum EVENT_1AB6
	enum EVENT_1AB7

		enum_start 0x1ab8 // 0x357
	enum EVENT_1AB8
	enum EVENT_1AB9
	enum EVENT_1ABA
	enum EVENT_1ABB
	enum EVENT_1ABC
	enum EVENT_1ABD
	enum EVENT_1ABE
	enum EVENT_1ABF

		enum_start 0x1ac0 // 0x358
	enum EVENT_1AC0
	enum EVENT_1AC1
	enum EVENT_1AC2
	enum EVENT_1AC3
	enum EVENT_1AC4
	enum EVENT_1AC5
	enum EVENT_1AC6
	enum EVENT_1AC7

		enum_start 0x1ac8 // 0x359
	enum EVENT_1AC8
	enum EVENT_1AC9
	enum EVENT_1ACA
	enum EVENT_1ACB
	enum EVENT_1ACC
	enum EVENT_1ACD
	enum EVENT_1ACE
	enum EVENT_1ACF

		enum_start 0x1ad0 // 0x35A
	enum EVENT_1AD0
	enum EVENT_1AD1
	enum EVENT_1AD2
	enum EVENT_1AD3
	enum EVENT_1AD4
	enum EVENT_1AD5
	enum EVENT_1AD6
	enum EVENT_1AD7

		enum_start 0x1ad8 // 0x35B
	enum EVENT_1AD8
	enum EVENT_1AD9
	enum EVENT_1ADA
	enum EVENT_1ADB
	enum EVENT_1ADC
	enum EVENT_1ADD
	enum EVENT_1ADE
	enum EVENT_1ADF

		enum_start 0x1ae0 // 0x35C
	enum EVENT_1AE0
	enum EVENT_1AE1
	enum EVENT_1AE2
	enum EVENT_1AE3
	enum EVENT_1AE4
	enum EVENT_1AE5
	enum EVENT_1AE6
	enum EVENT_1AE7

		enum_start 0x1ae8 // 0x35D
	enum EVENT_1AE8
	enum EVENT_1AE9
	enum EVENT_1AEA
	enum EVENT_1AEB
	enum EVENT_1AEC
	enum EVENT_1AED
	enum EVENT_1AEE
	enum EVENT_1AEF

		enum_start 0x1af0 // 0x35E
	enum EVENT_1AF0
	enum EVENT_1AF1
	enum EVENT_1AF2
	enum EVENT_1AF3
	enum EVENT_1AF4
	enum EVENT_1AF5
	enum EVENT_1AF6
	enum EVENT_1AF7

		enum_start 0x1af8 // 0x35F
	enum EVENT_1AF8
	enum EVENT_1AF9
	enum EVENT_1AFA
	enum EVENT_1AFB
	enum EVENT_1AFC
	enum EVENT_1AFD
	enum EVENT_1AFE
	enum EVENT_1AFF

		enum_start 0x1b00 // 0x360
	enum EVENT_1B00
	enum EVENT_1B01
	enum EVENT_1B02
	enum EVENT_1B03
	enum EVENT_1B04
	enum EVENT_1B05
	enum EVENT_1B06
	enum EVENT_1B07

		enum_start 0x1b08 // 0x361
	enum EVENT_1B08
	enum EVENT_1B09
	enum EVENT_1B0A
	enum EVENT_1B0B
	enum EVENT_1B0C
	enum EVENT_1B0D
	enum EVENT_1B0E
	enum EVENT_1B0F

		enum_start 0x1b10 // 0x362
	enum EVENT_1B10
	enum EVENT_1B11
	enum EVENT_1B12
	enum EVENT_1B13
	enum EVENT_1B14
	enum EVENT_1B15
	enum EVENT_1B16
	enum EVENT_1B17

		enum_start 0x1b18 // 0x363
	enum EVENT_1B18
	enum EVENT_1B19
	enum EVENT_1B1A
	enum EVENT_1B1B
	enum EVENT_1B1C
	enum EVENT_1B1D
	enum EVENT_1B1E
	enum EVENT_1B1F

		enum_start 0x1b20 // 0x364
	enum EVENT_1B20
	enum EVENT_1B21
	enum EVENT_1B22
	enum EVENT_1B23
	enum EVENT_1B24
	enum EVENT_1B25
	enum EVENT_1B26
	enum EVENT_1B27

		enum_start 0x1b28 // 0x365
	enum EVENT_1B28
	enum EVENT_1B29
	enum EVENT_1B2A
	enum EVENT_1B2B
	enum EVENT_1B2C
	enum EVENT_1B2D
	enum EVENT_1B2E
	enum EVENT_1B2F

		enum_start 0x1b30 // 0x366
	enum EVENT_1B30
	enum EVENT_1B31
	enum EVENT_1B32
	enum EVENT_1B33
	enum EVENT_1B34
	enum EVENT_1B35
	enum EVENT_1B36
	enum EVENT_1B37

		enum_start 0x1b38 // 0x367
	enum EVENT_1B38
	enum EVENT_1B39
	enum EVENT_1B3A
	enum EVENT_1B3B
	enum EVENT_1B3C
	enum EVENT_1B3D
	enum EVENT_1B3E
	enum EVENT_1B3F

		enum_start 0x1b40 // 0x368
	enum EVENT_1B40
	enum EVENT_1B41
	enum EVENT_1B42
	enum EVENT_1B43
	enum EVENT_1B44
	enum EVENT_1B45
	enum EVENT_1B46
	enum EVENT_1B47

		enum_start 0x1b48 // 0x369
	enum EVENT_1B48
	enum EVENT_1B49
	enum EVENT_1B4A
	enum EVENT_1B4B
	enum EVENT_1B4C
	enum EVENT_1B4D
	enum EVENT_1B4E
	enum EVENT_1B4F

		enum_start 0x1b50 // 0x36A
	enum EVENT_1B50
	enum EVENT_1B51
	enum EVENT_1B52
	enum EVENT_1B53
	enum EVENT_1B54
	enum EVENT_1B55
	enum EVENT_1B56
	enum EVENT_1B57

		enum_start 0x1b58 // 0x36B
	enum EVENT_1B58
	enum EVENT_1B59
	enum EVENT_1B5A
	enum EVENT_1B5B
	enum EVENT_1B5C
	enum EVENT_1B5D
	enum EVENT_1B5E
	enum EVENT_1B5F

		enum_start 0x1b60 // 0x36C
	enum EVENT_1B60
	enum EVENT_1B61
	enum EVENT_1B62
	enum EVENT_1B63
	enum EVENT_1B64
	enum EVENT_1B65
	enum EVENT_1B66
	enum EVENT_1B67

		enum_start 0x1b68 // 0x36D
	enum EVENT_1B68
	enum EVENT_1B69
	enum EVENT_1B6A
	enum EVENT_1B6B
	enum EVENT_1B6C
	enum EVENT_1B6D
	enum EVENT_1B6E
	enum EVENT_1B6F

		enum_start 0x1b70 // 0x36E
	enum EVENT_1B70
	enum EVENT_1B71
	enum EVENT_1B72
	enum EVENT_1B73
	enum EVENT_1B74
	enum EVENT_1B75
	enum EVENT_1B76
	enum EVENT_1B77

		enum_start 0x1b78 // 0x36F
	enum EVENT_1B78
	enum EVENT_1B79
	enum EVENT_1B7A
	enum EVENT_1B7B
	enum EVENT_1B7C
	enum EVENT_1B7D
	enum EVENT_1B7E
	enum EVENT_1B7F

		enum_start 0x1b80 // 0x370
	enum EVENT_1B80
	enum EVENT_1B81
	enum EVENT_1B82
	enum EVENT_1B83
	enum EVENT_1B84
	enum EVENT_1B85
	enum EVENT_1B86
	enum EVENT_1B87

		enum_start 0x1b88 // 0x371
	enum EVENT_1B88
	enum EVENT_1B89
	enum EVENT_1B8A
	enum EVENT_1B8B
	enum EVENT_1B8C
	enum EVENT_1B8D
	enum EVENT_1B8E
	enum EVENT_1B8F

		enum_start 0x1b90 // 0x372
	enum EVENT_1B90
	enum EVENT_1B91
	enum EVENT_1B92
	enum EVENT_1B93
	enum EVENT_1B94
	enum EVENT_1B95
	enum EVENT_1B96
	enum EVENT_1B97

		enum_start 0x1b98 // 0x373
	enum EVENT_1B98
	enum EVENT_1B99
	enum EVENT_1B9A
	enum EVENT_1B9B
	enum EVENT_1B9C
	enum EVENT_1B9D
	enum EVENT_1B9E
	enum EVENT_1B9F

		enum_start 0x1ba0 // 0x374
	enum EVENT_1BA0
	enum EVENT_1BA1
	enum EVENT_1BA2
	enum EVENT_1BA3
	enum EVENT_1BA4
	enum EVENT_1BA5
	enum EVENT_1BA6
	enum EVENT_1BA7

		enum_start 0x1ba8 // 0x375
	enum EVENT_1BA8
	enum EVENT_1BA9
	enum EVENT_1BAA
	enum EVENT_1BAB
	enum EVENT_1BAC
	enum EVENT_1BAD
	enum EVENT_1BAE
	enum EVENT_1BAF

		enum_start 0x1bb0 // 0x376
	enum EVENT_1BB0
	enum EVENT_1BB1
	enum EVENT_1BB2
	enum EVENT_1BB3
	enum EVENT_1BB4
	enum EVENT_1BB5
	enum EVENT_1BB6
	enum EVENT_1BB7

		enum_start 0x1bb8 // 0x377
	enum EVENT_1BB8
	enum EVENT_1BB9
	enum EVENT_1BBA
	enum EVENT_1BBB
	enum EVENT_1BBC
	enum EVENT_1BBD
	enum EVENT_1BBE
	enum EVENT_1BBF

		enum_start 0x1bc0 // 0x378
	enum EVENT_1BC0
	enum EVENT_1BC1
	enum EVENT_1BC2
	enum EVENT_1BC3
	enum EVENT_1BC4
	enum EVENT_1BC5
	enum EVENT_1BC6
	enum EVENT_1BC7

		enum_start 0x1bc8 // 0x379
	enum EVENT_1BC8
	enum EVENT_1BC9
	enum EVENT_1BCA
	enum EVENT_1BCB
	enum EVENT_1BCC
	enum EVENT_1BCD
	enum EVENT_1BCE
	enum EVENT_1BCF

		enum_start 0x1bd0 // 0x37A
	enum EVENT_1BD0
	enum EVENT_1BD1
	enum EVENT_1BD2
	enum EVENT_1BD3
	enum EVENT_1BD4
	enum EVENT_1BD5
	enum EVENT_1BD6
	enum EVENT_1BD7

		enum_start 0x1bd8 // 0x37B
	enum EVENT_1BD8
	enum EVENT_1BD9
	enum EVENT_1BDA
	enum EVENT_1BDB
	enum EVENT_1BDC
	enum EVENT_1BDD
	enum EVENT_1BDE
	enum EVENT_1BDF

		enum_start 0x1be0 // 0x37C
	enum EVENT_1BE0
	enum EVENT_1BE1
	enum EVENT_1BE2
	enum EVENT_1BE3
	enum EVENT_1BE4
	enum EVENT_1BE5
	enum EVENT_1BE6
	enum EVENT_1BE7

		enum_start 0x1be8 // 0x37D
	enum EVENT_1BE8
	enum EVENT_1BE9
	enum EVENT_1BEA
	enum EVENT_1BEB
	enum EVENT_1BEC
	enum EVENT_1BED
	enum EVENT_1BEE
	enum EVENT_1BEF

		enum_start 0x1bf0 // 0x37E
	enum EVENT_1BF0
	enum EVENT_1BF1
	enum EVENT_1BF2
	enum EVENT_1BF3
	enum EVENT_1BF4
	enum EVENT_1BF5
	enum EVENT_1BF6
	enum EVENT_1BF7

		enum_start 0x1bf8 // 0x37F
	enum EVENT_1BF8
	enum EVENT_1BF9
	enum EVENT_1BFA
	enum EVENT_1BFB
	enum EVENT_1BFC
	enum EVENT_1BFD
	enum EVENT_1BFE
	enum EVENT_1BFF

		enum_start 0x1c00 // 0x380
	enum EVENT_1C00
	enum EVENT_1C01
	enum EVENT_1C02
	enum EVENT_1C03
	enum EVENT_1C04
	enum EVENT_1C05
	enum EVENT_1C06
	enum EVENT_1C07

		enum_start 0x1c08 // 0x381
	enum EVENT_1C08
	enum EVENT_1C09
	enum EVENT_1C0A
	enum EVENT_1C0B
	enum EVENT_1C0C
	enum EVENT_1C0D
	enum EVENT_1C0E
	enum EVENT_1C0F

		enum_start 0x1c10 // 0x382
	enum EVENT_1C10
	enum EVENT_1C11
	enum EVENT_1C12
	enum EVENT_1C13
	enum EVENT_1C14
	enum EVENT_1C15
	enum EVENT_1C16
	enum EVENT_1C17

		enum_start 0x1c18 // 0x383
	enum EVENT_1C18
	enum EVENT_1C19
	enum EVENT_1C1A
	enum EVENT_1C1B
	enum EVENT_1C1C
	enum EVENT_1C1D
	enum EVENT_1C1E
	enum EVENT_1C1F

		enum_start 0x1c20 // 0x384
	enum EVENT_1C20
	enum EVENT_1C21
	enum EVENT_1C22
	enum EVENT_1C23
	enum EVENT_1C24
	enum EVENT_1C25
	enum EVENT_1C26
	enum EVENT_1C27

		enum_start 0x1c28 // 0x385
	enum EVENT_1C28
	enum EVENT_1C29
	enum EVENT_1C2A
	enum EVENT_1C2B
	enum EVENT_1C2C
	enum EVENT_1C2D
	enum EVENT_1C2E
	enum EVENT_1C2F

		enum_start 0x1c30 // 0x386
	enum EVENT_1C30
	enum EVENT_1C31
	enum EVENT_1C32
	enum EVENT_1C33
	enum EVENT_1C34
	enum EVENT_1C35
	enum EVENT_1C36
	enum EVENT_1C37

		enum_start 0x1c38 // 0x387
	enum EVENT_1C38
	enum EVENT_1C39
	enum EVENT_1C3A
	enum EVENT_1C3B
	enum EVENT_1C3C
	enum EVENT_1C3D
	enum EVENT_1C3E
	enum EVENT_1C3F

		enum_start 0x1c40 // 0x388
	enum EVENT_1C40
	enum EVENT_1C41
	enum EVENT_1C42
	enum EVENT_1C43
	enum EVENT_1C44
	enum EVENT_1C45
	enum EVENT_1C46
	enum EVENT_1C47

		enum_start 0x1c48 // 0x389
	enum EVENT_1C48
	enum EVENT_1C49
	enum EVENT_1C4A
	enum EVENT_1C4B
	enum EVENT_1C4C
	enum EVENT_1C4D
	enum EVENT_1C4E
	enum EVENT_1C4F

		enum_start 0x1c50 // 0x38A
	enum EVENT_1C50
	enum EVENT_1C51
	enum EVENT_1C52
	enum EVENT_1C53
	enum EVENT_1C54
	enum EVENT_1C55
	enum EVENT_1C56
	enum EVENT_1C57

		enum_start 0x1c58 // 0x38B
	enum EVENT_1C58
	enum EVENT_1C59
	enum EVENT_1C5A
	enum EVENT_1C5B
	enum EVENT_1C5C
	enum EVENT_1C5D
	enum EVENT_1C5E
	enum EVENT_1C5F

		enum_start 0x1c60 // 0x38C
	enum EVENT_1C60
	enum EVENT_1C61
	enum EVENT_1C62
	enum EVENT_1C63
	enum EVENT_1C64
	enum EVENT_1C65
	enum EVENT_1C66
	enum EVENT_1C67

		enum_start 0x1c68 // 0x38D
	enum EVENT_1C68
	enum EVENT_1C69
	enum EVENT_1C6A
	enum EVENT_1C6B
	enum EVENT_1C6C
	enum EVENT_1C6D
	enum EVENT_1C6E
	enum EVENT_1C6F

		enum_start 0x1c70 // 0x38E
	enum EVENT_1C70
	enum EVENT_1C71
	enum EVENT_1C72
	enum EVENT_1C73
	enum EVENT_1C74
	enum EVENT_1C75
	enum EVENT_1C76
	enum EVENT_1C77

		enum_start 0x1c78 // 0x38F
	enum EVENT_1C78
	enum EVENT_1C79
	enum EVENT_1C7A
	enum EVENT_1C7B
	enum EVENT_1C7C
	enum EVENT_1C7D
	enum EVENT_1C7E
	enum EVENT_1C7F

		enum_start 0x1c80 // 0x390
	enum EVENT_1C80
	enum EVENT_1C81
	enum EVENT_1C82
	enum EVENT_1C83
	enum EVENT_1C84
	enum EVENT_1C85
	enum EVENT_1C86
	enum EVENT_1C87

		enum_start 0x1c88 // 0x391
	enum EVENT_1C88
	enum EVENT_1C89
	enum EVENT_1C8A
	enum EVENT_1C8B
	enum EVENT_1C8C
	enum EVENT_1C8D
	enum EVENT_1C8E
	enum EVENT_1C8F

		enum_start 0x1c90 // 0x392
	enum EVENT_1C90
	enum EVENT_1C91
	enum EVENT_1C92
	enum EVENT_1C93
	enum EVENT_1C94
	enum EVENT_1C95
	enum EVENT_1C96
	enum EVENT_1C97

		enum_start 0x1c98 // 0x393
	enum EVENT_1C98
	enum EVENT_1C99
	enum EVENT_1C9A
	enum EVENT_1C9B
	enum EVENT_1C9C
	enum EVENT_1C9D
	enum EVENT_1C9E
	enum EVENT_1C9F

		enum_start 0x1ca0 // 0x394
	enum EVENT_1CA0
	enum EVENT_1CA1
	enum EVENT_1CA2
	enum EVENT_1CA3
	enum EVENT_1CA4
	enum EVENT_1CA5
	enum EVENT_1CA6
	enum EVENT_1CA7

		enum_start 0x1ca8 // 0x395
	enum EVENT_1CA8
	enum EVENT_1CA9
	enum EVENT_1CAA
	enum EVENT_1CAB
	enum EVENT_1CAC
	enum EVENT_1CAD
	enum EVENT_1CAE
	enum EVENT_1CAF

		enum_start 0x1cb0 // 0x396
	enum EVENT_1CB0
	enum EVENT_1CB1
	enum EVENT_1CB2
	enum EVENT_1CB3
	enum EVENT_1CB4
	enum EVENT_1CB5
	enum EVENT_1CB6
	enum EVENT_1CB7

		enum_start 0x1cb8 // 0x397
	enum EVENT_1CB8
	enum EVENT_1CB9
	enum EVENT_1CBA
	enum EVENT_1CBB
	enum EVENT_1CBC
	enum EVENT_1CBD
	enum EVENT_1CBE
	enum EVENT_1CBF

		enum_start 0x1cc0 // 0x398
	enum EVENT_1CC0
	enum EVENT_1CC1
	enum EVENT_1CC2
	enum EVENT_1CC3
	enum EVENT_1CC4
	enum EVENT_1CC5
	enum EVENT_1CC6
	enum EVENT_1CC7

		enum_start 0x1cc8 // 0x399
	enum EVENT_1CC8
	enum EVENT_1CC9
	enum EVENT_1CCA
	enum EVENT_1CCB
	enum EVENT_1CCC
	enum EVENT_1CCD
	enum EVENT_1CCE
	enum EVENT_1CCF

		enum_start 0x1cd0 // 0x39A
	enum EVENT_1CD0
	enum EVENT_1CD1
	enum EVENT_1CD2
	enum EVENT_1CD3
	enum EVENT_1CD4
	enum EVENT_1CD5
	enum EVENT_1CD6
	enum EVENT_1CD7

		enum_start 0x1cd8 // 0x39B
	enum EVENT_1CD8
	enum EVENT_1CD9
	enum EVENT_1CDA
	enum EVENT_1CDB
	enum EVENT_1CDC
	enum EVENT_1CDD
	enum EVENT_1CDE
	enum EVENT_1CDF

		enum_start 0x1ce0 // 0x39C
	enum EVENT_1CE0
	enum EVENT_1CE1
	enum EVENT_1CE2
	enum EVENT_1CE3
	enum EVENT_1CE4
	enum EVENT_1CE5
	enum EVENT_1CE6
	enum EVENT_1CE7

		enum_start 0x1ce8 // 0x39D
	enum EVENT_1CE8
	enum EVENT_1CE9
	enum EVENT_1CEA
	enum EVENT_1CEB
	enum EVENT_1CEC
	enum EVENT_1CED
	enum EVENT_1CEE
	enum EVENT_1CEF

		enum_start 0x1cf0 // 0x39E
	enum EVENT_1CF0
	enum EVENT_1CF1
	enum EVENT_1CF2
	enum EVENT_1CF3
	enum EVENT_1CF4
	enum EVENT_1CF5
	enum EVENT_1CF6
	enum EVENT_1CF7

		enum_start 0x1cf8 // 0x39F
	enum EVENT_1CF8
	enum EVENT_1CF9
	enum EVENT_1CFA
	enum EVENT_1CFB
	enum EVENT_1CFC
	enum EVENT_1CFD
	enum EVENT_1CFE
	enum EVENT_1CFF

		enum_start 0x1d00 // 0x3A0
	enum EVENT_1D00
	enum EVENT_1D01
	enum EVENT_1D02
	enum EVENT_1D03
	enum EVENT_1D04
	enum EVENT_1D05
	enum EVENT_1D06
	enum EVENT_1D07

		enum_start 0x1d08 // 0x3A1
	enum EVENT_1D08
	enum EVENT_1D09
	enum EVENT_1D0A
	enum EVENT_1D0B
	enum EVENT_1D0C
	enum EVENT_1D0D
	enum EVENT_1D0E
	enum EVENT_1D0F

		enum_start 0x1d10 // 0x3A2
	enum EVENT_1D10
	enum EVENT_1D11
	enum EVENT_1D12
	enum EVENT_1D13
	enum EVENT_1D14
	enum EVENT_1D15
	enum EVENT_1D16
	enum EVENT_1D17

		enum_start 0x1d18 // 0x3A3
	enum EVENT_1D18
	enum EVENT_1D19
	enum EVENT_1D1A
	enum EVENT_1D1B
	enum EVENT_1D1C
	enum EVENT_1D1D
	enum EVENT_1D1E
	enum EVENT_1D1F

		enum_start 0x1d20 // 0x3A4
	enum EVENT_1D20
	enum EVENT_1D21
	enum EVENT_1D22
	enum EVENT_1D23
	enum EVENT_1D24
	enum EVENT_1D25
	enum EVENT_1D26
	enum EVENT_1D27

		enum_start 0x1d28 // 0x3A5
	enum EVENT_1D28
	enum EVENT_1D29
	enum EVENT_1D2A
	enum EVENT_1D2B
	enum EVENT_1D2C
	enum EVENT_1D2D
	enum EVENT_1D2E
	enum EVENT_1D2F

		enum_start 0x1d30 // 0x3A6
	enum EVENT_1D30
	enum EVENT_1D31
	enum EVENT_1D32
	enum EVENT_1D33
	enum EVENT_1D34
	enum EVENT_1D35
	enum EVENT_1D36
	enum EVENT_1D37

		enum_start 0x1d38 // 0x3A7
	enum EVENT_1D38
	enum EVENT_1D39
	enum EVENT_1D3A
	enum EVENT_1D3B
	enum EVENT_1D3C
	enum EVENT_1D3D
	enum EVENT_1D3E
	enum EVENT_1D3F

		enum_start 0x1d40 // 0x3A8
	enum EVENT_1D40
	enum EVENT_1D41
	enum EVENT_1D42
	enum EVENT_1D43
	enum EVENT_1D44
	enum EVENT_1D45
	enum EVENT_1D46
	enum EVENT_1D47

		enum_start 0x1d48 // 0x3A9
	enum EVENT_1D48
	enum EVENT_1D49
	enum EVENT_1D4A
	enum EVENT_1D4B
	enum EVENT_1D4C
	enum EVENT_1D4D
	enum EVENT_1D4E
	enum EVENT_1D4F

		enum_start 0x1d50 // 0x3AA
	enum EVENT_1D50
	enum EVENT_1D51
	enum EVENT_1D52
	enum EVENT_1D53
	enum EVENT_1D54
	enum EVENT_1D55
	enum EVENT_1D56
	enum EVENT_1D57

		enum_start 0x1d58 // 0x3AB
	enum EVENT_1D58
	enum EVENT_1D59
	enum EVENT_1D5A
	enum EVENT_1D5B
	enum EVENT_1D5C
	enum EVENT_1D5D
	enum EVENT_1D5E
	enum EVENT_1D5F

		enum_start 0x1d60 // 0x3AC
	enum EVENT_1D60
	enum EVENT_1D61
	enum EVENT_1D62
	enum EVENT_1D63
	enum EVENT_1D64
	enum EVENT_1D65
	enum EVENT_1D66
	enum EVENT_1D67

		enum_start 0x1d68 // 0x3AD
	enum EVENT_1D68
	enum EVENT_1D69
	enum EVENT_1D6A
	enum EVENT_1D6B
	enum EVENT_1D6C
	enum EVENT_1D6D
	enum EVENT_1D6E
	enum EVENT_1D6F

		enum_start 0x1d70 // 0x3AE
	enum EVENT_1D70
	enum EVENT_1D71
	enum EVENT_1D72
	enum EVENT_1D73
	enum EVENT_1D74
	enum EVENT_1D75
	enum EVENT_1D76
	enum EVENT_1D77

		enum_start 0x1d78 // 0x3AF
	enum EVENT_1D78
	enum EVENT_1D79
	enum EVENT_1D7A
	enum EVENT_1D7B
	enum EVENT_1D7C
	enum EVENT_1D7D
	enum EVENT_1D7E
	enum EVENT_1D7F

		enum_start 0x1d80 // 0x3B0
	enum EVENT_1D80
	enum EVENT_1D81
	enum EVENT_1D82
	enum EVENT_1D83
	enum EVENT_1D84
	enum EVENT_1D85
	enum EVENT_1D86
	enum EVENT_1D87

		enum_start 0x1d88 // 0x3B1
	enum EVENT_1D88
	enum EVENT_1D89
	enum EVENT_1D8A
	enum EVENT_1D8B
	enum EVENT_1D8C
	enum EVENT_1D8D
	enum EVENT_1D8E
	enum EVENT_1D8F

		enum_start 0x1d90 // 0x3B2
	enum EVENT_1D90
	enum EVENT_1D91
	enum EVENT_1D92
	enum EVENT_1D93
	enum EVENT_1D94
	enum EVENT_1D95
	enum EVENT_1D96
	enum EVENT_1D97

		enum_start 0x1d98 // 0x3B3
	enum EVENT_1D98
	enum EVENT_1D99
	enum EVENT_1D9A
	enum EVENT_1D9B
	enum EVENT_1D9C
	enum EVENT_1D9D
	enum EVENT_1D9E
	enum EVENT_1D9F

		enum_start 0x1da0 // 0x3B4
	enum EVENT_1DA0
	enum EVENT_1DA1
	enum EVENT_1DA2
	enum EVENT_1DA3
	enum EVENT_1DA4
	enum EVENT_1DA5
	enum EVENT_1DA6
	enum EVENT_1DA7

		enum_start 0x1da8 // 0x3B5
	enum EVENT_1DA8
	enum EVENT_1DA9
	enum EVENT_1DAA
	enum EVENT_1DAB
	enum EVENT_1DAC
	enum EVENT_1DAD
	enum EVENT_1DAE
	enum EVENT_1DAF

		enum_start 0x1db0 // 0x3B6
	enum EVENT_1DB0
	enum EVENT_1DB1
	enum EVENT_1DB2
	enum EVENT_1DB3
	enum EVENT_1DB4
	enum EVENT_1DB5
	enum EVENT_1DB6
	enum EVENT_1DB7

		enum_start 0x1db8 // 0x3B7
	enum EVENT_1DB8
	enum EVENT_1DB9
	enum EVENT_1DBA
	enum EVENT_1DBB
	enum EVENT_1DBC
	enum EVENT_1DBD
	enum EVENT_1DBE
	enum EVENT_1DBF

		enum_start 0x1dc0 // 0x3B8
	enum EVENT_1DC0
	enum EVENT_1DC1
	enum EVENT_1DC2
	enum EVENT_1DC3
	enum EVENT_1DC4
	enum EVENT_1DC5
	enum EVENT_1DC6
	enum EVENT_1DC7

		enum_start 0x1dc8 // 0x3B9
	enum EVENT_1DC8
	enum EVENT_1DC9
	enum EVENT_1DCA
	enum EVENT_1DCB
	enum EVENT_1DCC
	enum EVENT_1DCD
	enum EVENT_1DCE
	enum EVENT_1DCF

		enum_start 0x1dd0 // 0x3BA
	enum EVENT_1DD0
	enum EVENT_1DD1
	enum EVENT_1DD2
	enum EVENT_1DD3
	enum EVENT_1DD4
	enum EVENT_1DD5
	enum EVENT_1DD6
	enum EVENT_1DD7

		enum_start 0x1dd8 // 0x3BB
	enum EVENT_1DD8
	enum EVENT_1DD9
	enum EVENT_1DDA
	enum EVENT_1DDB
	enum EVENT_1DDC
	enum EVENT_1DDD
	enum EVENT_1DDE
	enum EVENT_1DDF

		enum_start 0x1de0 // 0x3BC
	enum EVENT_1DE0
	enum EVENT_1DE1
	enum EVENT_1DE2
	enum EVENT_1DE3
	enum EVENT_1DE4
	enum EVENT_1DE5
	enum EVENT_1DE6
	enum EVENT_1DE7

		enum_start 0x1de8 // 0x3BD
	enum EVENT_1DE8
	enum EVENT_1DE9
	enum EVENT_1DEA
	enum EVENT_1DEB
	enum EVENT_1DEC
	enum EVENT_1DED
	enum EVENT_1DEE
	enum EVENT_1DEF

		enum_start 0x1df0 // 0x3BE
	enum EVENT_1DF0
	enum EVENT_1DF1
	enum EVENT_1DF2
	enum EVENT_1DF3
	enum EVENT_1DF4
	enum EVENT_1DF5
	enum EVENT_1DF6
	enum EVENT_1DF7

		enum_start 0x1df8 // 0x3BF
	enum EVENT_1DF8
	enum EVENT_1DF9
	enum EVENT_1DFA
	enum EVENT_1DFB
	enum EVENT_1DFC
	enum EVENT_1DFD
	enum EVENT_1DFE
	enum EVENT_1DFF

		enum_start 0x1e00 // 0x3C0
	enum EVENT_1E00
	enum EVENT_1E01
	enum EVENT_1E02
	enum EVENT_1E03
	enum EVENT_1E04
	enum EVENT_1E05
	enum EVENT_1E06
	enum EVENT_1E07

		enum_start 0x1e08 // 0x3C1
	enum EVENT_1E08
	enum EVENT_1E09
	enum EVENT_1E0A
	enum EVENT_1E0B
	enum EVENT_1E0C
	enum EVENT_1E0D
	enum EVENT_1E0E
	enum EVENT_1E0F

		enum_start 0x1e10 // 0x3C2
	enum EVENT_1E10
	enum EVENT_1E11
	enum EVENT_1E12
	enum EVENT_1E13
	enum EVENT_1E14
	enum EVENT_1E15
	enum EVENT_1E16
	enum EVENT_1E17

		enum_start 0x1e18 // 0x3C3
	enum EVENT_1E18
	enum EVENT_1E19
	enum EVENT_1E1A
	enum EVENT_1E1B
	enum EVENT_1E1C
	enum EVENT_1E1D
	enum EVENT_1E1E
	enum EVENT_1E1F

		enum_start 0x1e20 // 0x3C4
	enum EVENT_1E20
	enum EVENT_1E21
	enum EVENT_1E22
	enum EVENT_1E23
	enum EVENT_1E24
	enum EVENT_1E25
	enum EVENT_1E26
	enum EVENT_1E27

		enum_start 0x1e28 // 0x3C5
	enum EVENT_1E28
	enum EVENT_1E29
	enum EVENT_1E2A
	enum EVENT_1E2B
	enum EVENT_1E2C
	enum EVENT_1E2D
	enum EVENT_1E2E
	enum EVENT_1E2F

		enum_start 0x1e30 // 0x3C6
	enum EVENT_1E30
	enum EVENT_1E31
	enum EVENT_1E32
	enum EVENT_1E33
	enum EVENT_1E34
	enum EVENT_1E35
	enum EVENT_1E36
	enum EVENT_1E37

		enum_start 0x1e38 // 0x3C7
	enum EVENT_1E38
	enum EVENT_1E39
	enum EVENT_1E3A
	enum EVENT_1E3B
	enum EVENT_1E3C
	enum EVENT_1E3D
	enum EVENT_1E3E
	enum EVENT_1E3F

		enum_start 0x1e40 // 0x3C8
	enum EVENT_1E40
	enum EVENT_1E41
	enum EVENT_1E42
	enum EVENT_1E43
	enum EVENT_1E44
	enum EVENT_1E45
	enum EVENT_1E46
	enum EVENT_1E47

		enum_start 0x1e48 // 0x3C9
	enum EVENT_1E48
	enum EVENT_1E49
	enum EVENT_1E4A
	enum EVENT_1E4B
	enum EVENT_1E4C
	enum EVENT_1E4D
	enum EVENT_1E4E
	enum EVENT_1E4F

		enum_start 0x1e50 // 0x3CA
	enum EVENT_1E50
	enum EVENT_1E51
	enum EVENT_1E52
	enum EVENT_1E53
	enum EVENT_1E54
	enum EVENT_1E55
	enum EVENT_1E56
	enum EVENT_1E57

		enum_start 0x1e58 // 0x3CB
	enum EVENT_1E58
	enum EVENT_1E59
	enum EVENT_1E5A
	enum EVENT_1E5B
	enum EVENT_1E5C
	enum EVENT_1E5D
	enum EVENT_1E5E
	enum EVENT_1E5F

		enum_start 0x1e60 // 0x3CC
	enum EVENT_1E60
	enum EVENT_1E61
	enum EVENT_1E62
	enum EVENT_1E63
	enum EVENT_1E64
	enum EVENT_1E65
	enum EVENT_1E66
	enum EVENT_1E67

		enum_start 0x1e68 // 0x3CD
	enum EVENT_1E68
	enum EVENT_1E69
	enum EVENT_1E6A
	enum EVENT_1E6B
	enum EVENT_1E6C
	enum EVENT_1E6D
	enum EVENT_1E6E
	enum EVENT_1E6F

		enum_start 0x1e70 // 0x3CE
	enum EVENT_1E70
	enum EVENT_1E71
	enum EVENT_1E72
	enum EVENT_1E73
	enum EVENT_1E74
	enum EVENT_1E75
	enum EVENT_1E76
	enum EVENT_1E77

		enum_start 0x1e78 // 0x3CF
	enum EVENT_1E78
	enum EVENT_1E79
	enum EVENT_1E7A
	enum EVENT_1E7B
	enum EVENT_1E7C
	enum EVENT_1E7D
	enum EVENT_1E7E
	enum EVENT_1E7F

		enum_start 0x1e80 // 0x3D0
	enum EVENT_1E80
	enum EVENT_1E81
	enum EVENT_1E82
	enum EVENT_1E83
	enum EVENT_1E84
	enum EVENT_1E85
	enum EVENT_1E86
	enum EVENT_1E87

		enum_start 0x1e88 // 0x3D1
	enum EVENT_1E88
	enum EVENT_1E89
	enum EVENT_1E8A
	enum EVENT_1E8B
	enum EVENT_1E8C
	enum EVENT_1E8D
	enum EVENT_1E8E
	enum EVENT_1E8F

		enum_start 0x1e90 // 0x3D2
	enum EVENT_1E90
	enum EVENT_1E91
	enum EVENT_1E92
	enum EVENT_1E93
	enum EVENT_1E94
	enum EVENT_1E95
	enum EVENT_1E96
	enum EVENT_1E97

		enum_start 0x1e98 // 0x3D3
	enum EVENT_1E98
	enum EVENT_1E99
	enum EVENT_1E9A
	enum EVENT_1E9B
	enum EVENT_1E9C
	enum EVENT_1E9D
	enum EVENT_1E9E
	enum EVENT_1E9F

		enum_start 0x1ea0 // 0x3D4
	enum EVENT_1EA0
	enum EVENT_1EA1
	enum EVENT_1EA2
	enum EVENT_1EA3
	enum EVENT_1EA4
	enum EVENT_1EA5
	enum EVENT_1EA6
	enum EVENT_1EA7

		enum_start 0x1ea8 // 0x3D5
	enum EVENT_1EA8
	enum EVENT_1EA9
	enum EVENT_1EAA
	enum EVENT_1EAB
	enum EVENT_1EAC
	enum EVENT_1EAD
	enum EVENT_1EAE
	enum EVENT_1EAF

		enum_start 0x1eb0 // 0x3D6
	enum EVENT_1EB0
	enum EVENT_1EB1
	enum EVENT_1EB2
	enum EVENT_1EB3
	enum EVENT_1EB4
	enum EVENT_1EB5
	enum EVENT_1EB6
	enum EVENT_1EB7

		enum_start 0x1eb8 // 0x3D7
	enum EVENT_1EB8
	enum EVENT_1EB9
	enum EVENT_1EBA
	enum EVENT_1EBB
	enum EVENT_1EBC
	enum EVENT_1EBD
	enum EVENT_1EBE
	enum EVENT_1EBF

		enum_start 0x1ec0 // 0x3D8
	enum EVENT_1EC0
	enum EVENT_1EC1
	enum EVENT_1EC2
	enum EVENT_1EC3
	enum EVENT_1EC4
	enum EVENT_1EC5
	enum EVENT_1EC6
	enum EVENT_1EC7

		enum_start 0x1ec8 // 0x3D9
	enum EVENT_1EC8
	enum EVENT_1EC9
	enum EVENT_1ECA
	enum EVENT_1ECB
	enum EVENT_1ECC
	enum EVENT_1ECD
	enum EVENT_1ECE
	enum EVENT_1ECF

		enum_start 0x1ed0 // 0x3DA
	enum EVENT_1ED0
	enum EVENT_1ED1
	enum EVENT_1ED2
	enum EVENT_1ED3
	enum EVENT_1ED4
	enum EVENT_1ED5
	enum EVENT_1ED6
	enum EVENT_1ED7

		enum_start 0x1ed8 // 0x3DB
	enum EVENT_1ED8
	enum EVENT_1ED9
	enum EVENT_1EDA
	enum EVENT_1EDB
	enum EVENT_1EDC
	enum EVENT_1EDD
	enum EVENT_1EDE
	enum EVENT_1EDF

		enum_start 0x1ee0 // 0x3DC
	enum EVENT_1EE0
	enum EVENT_1EE1
	enum EVENT_1EE2
	enum EVENT_1EE3
	enum EVENT_1EE4
	enum EVENT_1EE5
	enum EVENT_1EE6
	enum EVENT_1EE7

		enum_start 0x1ee8 // 0x3DD
	enum EVENT_1EE8
	enum EVENT_1EE9
	enum EVENT_1EEA
	enum EVENT_1EEB
	enum EVENT_1EEC
	enum EVENT_1EED
	enum EVENT_1EEE
	enum EVENT_1EEF

		enum_start 0x1ef0 // 0x3DE
	enum EVENT_1EF0
	enum EVENT_1EF1
	enum EVENT_1EF2
	enum EVENT_1EF3
	enum EVENT_1EF4
	enum EVENT_1EF5
	enum EVENT_1EF6
	enum EVENT_1EF7

		enum_start 0x1ef8 // 0x3DF
	enum EVENT_1EF8
	enum EVENT_1EF9
	enum EVENT_1EFA
	enum EVENT_1EFB
	enum EVENT_1EFC
	enum EVENT_1EFD
	enum EVENT_1EFE
	enum EVENT_1EFF

		enum_start 0x1f00 // 0x3E0
	enum EVENT_1F00
	enum EVENT_1F01
	enum EVENT_1F02
	enum EVENT_1F03
	enum EVENT_1F04
	enum EVENT_1F05
	enum EVENT_1F06
	enum EVENT_1F07

		enum_start 0x1f08 // 0x3E1
	enum EVENT_1F08
	enum EVENT_1F09
	enum EVENT_1F0A
	enum EVENT_1F0B
	enum EVENT_1F0C
	enum EVENT_1F0D
	enum EVENT_1F0E
	enum EVENT_1F0F

		enum_start 0x1f10 // 0x3E2
	enum EVENT_1F10
	enum EVENT_1F11
	enum EVENT_1F12
	enum EVENT_1F13
	enum EVENT_1F14
	enum EVENT_1F15
	enum EVENT_1F16
	enum EVENT_1F17

		enum_start 0x1f18 // 0x3E3
	enum EVENT_1F18
	enum EVENT_1F19
	enum EVENT_1F1A
	enum EVENT_1F1B
	enum EVENT_1F1C
	enum EVENT_1F1D
	enum EVENT_1F1E
	enum EVENT_1F1F

		enum_start 0x1f20 // 0x3E4
	enum EVENT_1F20
	enum EVENT_1F21
	enum EVENT_1F22
	enum EVENT_1F23
	enum EVENT_1F24
	enum EVENT_1F25
	enum EVENT_1F26
	enum EVENT_1F27

		enum_start 0x1f28 // 0x3E5
	enum EVENT_1F28
	enum EVENT_1F29
	enum EVENT_1F2A
	enum EVENT_1F2B
	enum EVENT_1F2C
	enum EVENT_1F2D
	enum EVENT_1F2E
	enum EVENT_1F2F

		enum_start 0x1f30 // 0x3E6
	enum EVENT_1F30
	enum EVENT_1F31
	enum EVENT_1F32
	enum EVENT_1F33
	enum EVENT_1F34
	enum EVENT_1F35
	enum EVENT_1F36
	enum EVENT_1F37

		enum_start 0x1f38 // 0x3E7
	enum EVENT_1F38
	enum EVENT_1F39
	enum EVENT_1F3A
	enum EVENT_1F3B
	enum EVENT_1F3C
	enum EVENT_1F3D
	enum EVENT_1F3E
	enum EVENT_1F3F

		enum_start 0x1f40 // 0x3E8
	enum EVENT_1F40
	enum EVENT_1F41
	enum EVENT_1F42
	enum EVENT_1F43
	enum EVENT_1F44
	enum EVENT_1F45
	enum EVENT_1F46
	enum EVENT_1F47

		enum_start 0x1f48 // 0x3E9
	enum EVENT_1F48
	enum EVENT_1F49
	enum EVENT_1F4A
	enum EVENT_1F4B
	enum EVENT_1F4C
	enum EVENT_1F4D
	enum EVENT_1F4E
	enum EVENT_1F4F

		enum_start 0x1f50 // 0x3EA
	enum EVENT_1F50
	enum EVENT_1F51
	enum EVENT_1F52
	enum EVENT_1F53
	enum EVENT_1F54
	enum EVENT_1F55
	enum EVENT_1F56
	enum EVENT_1F57

		enum_start 0x1f58 // 0x3EB
	enum EVENT_1F58
	enum EVENT_1F59
	enum EVENT_1F5A
	enum EVENT_1F5B
	enum EVENT_1F5C
	enum EVENT_1F5D
	enum EVENT_1F5E
	enum EVENT_1F5F

		enum_start 0x1f60 // 0x3EC
	enum EVENT_1F60
	enum EVENT_1F61
	enum EVENT_1F62
	enum EVENT_1F63
	enum EVENT_1F64
	enum EVENT_1F65
	enum EVENT_1F66
	enum EVENT_1F67

		enum_start 0x1f68 // 0x3ED
	enum EVENT_1F68
	enum EVENT_1F69
	enum EVENT_1F6A
	enum EVENT_1F6B
	enum EVENT_1F6C
	enum EVENT_1F6D
	enum EVENT_1F6E
	enum EVENT_1F6F

		enum_start 0x1f70 // 0x3EE
	enum EVENT_1F70
	enum EVENT_1F71
	enum EVENT_1F72
	enum EVENT_1F73
	enum EVENT_1F74
	enum EVENT_1F75
	enum EVENT_1F76
	enum EVENT_1F77

		enum_start 0x1f78 // 0x3EF
	enum EVENT_1F78
	enum EVENT_1F79
	enum EVENT_1F7A
	enum EVENT_1F7B
	enum EVENT_1F7C
	enum EVENT_1F7D
	enum EVENT_1F7E
	enum EVENT_1F7F

		enum_start 0x1f80 // 0x3F0
	enum EVENT_1F80
	enum EVENT_1F81
	enum EVENT_1F82
	enum EVENT_1F83
	enum EVENT_1F84
	enum EVENT_1F85
	enum EVENT_1F86
	enum EVENT_1F87

		enum_start 0x1f88 // 0x3F1
	enum EVENT_1F88
	enum EVENT_1F89
	enum EVENT_1F8A
	enum EVENT_1F8B
	enum EVENT_1F8C
	enum EVENT_1F8D
	enum EVENT_1F8E
	enum EVENT_1F8F

		enum_start 0x1f90 // 0x3F2
	enum EVENT_1F90
	enum EVENT_1F91
	enum EVENT_1F92
	enum EVENT_1F93
	enum EVENT_1F94
	enum EVENT_1F95
	enum EVENT_1F96
	enum EVENT_1F97

		enum_start 0x1f98 // 0x3F3
	enum EVENT_1F98
	enum EVENT_1F99
	enum EVENT_1F9A
	enum EVENT_1F9B
	enum EVENT_1F9C
	enum EVENT_1F9D
	enum EVENT_1F9E
	enum EVENT_1F9F

		enum_start 0x1fa0 // 0x3F4
	enum EVENT_1FA0
	enum EVENT_1FA1
	enum EVENT_1FA2
	enum EVENT_1FA3
	enum EVENT_1FA4
	enum EVENT_1FA5
	enum EVENT_1FA6
	enum EVENT_1FA7

		enum_start 0x1fa8 // 0x3F5
	enum EVENT_1FA8
	enum EVENT_1FA9
	enum EVENT_1FAA
	enum EVENT_1FAB
	enum EVENT_1FAC
	enum EVENT_1FAD
	enum EVENT_1FAE
	enum EVENT_1FAF

		enum_start 0x1fb0 // 0x3F6
	enum EVENT_1FB0
	enum EVENT_1FB1
	enum EVENT_1FB2
	enum EVENT_1FB3
	enum EVENT_1FB4
	enum EVENT_1FB5
	enum EVENT_1FB6
	enum EVENT_1FB7

		enum_start 0x1fb8 // 0x3F7
	enum EVENT_1FB8
	enum EVENT_1FB9
	enum EVENT_1FBA
	enum EVENT_1FBB
	enum EVENT_1FBC
	enum EVENT_1FBD
	enum EVENT_1FBE
	enum EVENT_1FBF

		enum_start 0x1fc0 // 0x3F8
	enum EVENT_1FC0
	enum EVENT_1FC1
	enum EVENT_1FC2
	enum EVENT_1FC3
	enum EVENT_1FC4
	enum EVENT_1FC5
	enum EVENT_1FC6
	enum EVENT_1FC7

		enum_start 0x1fc8 // 0x3F9
	enum EVENT_1FC8
	enum EVENT_1FC9
	enum EVENT_1FCA
	enum EVENT_1FCB
	enum EVENT_1FCC
	enum EVENT_1FCD
	enum EVENT_1FCE
	enum EVENT_1FCF

		enum_start 0x1fd0 // 0x3FA
	enum EVENT_1FD0
	enum EVENT_1FD1
	enum EVENT_1FD2
	enum EVENT_1FD3
	enum EVENT_1FD4
	enum EVENT_1FD5
	enum EVENT_1FD6
	enum EVENT_1FD7

		enum_start 0x1fd8 // 0x3FB
	enum EVENT_1FD8
	enum EVENT_1FD9
	enum EVENT_1FDA
	enum EVENT_1FDB
	enum EVENT_1FDC
	enum EVENT_1FDD
	enum EVENT_1FDE
	enum EVENT_1FDF

		enum_start 0x1fe0 // 0x3FC
	enum EVENT_1FE0
	enum EVENT_1FE1
	enum EVENT_1FE2
	enum EVENT_1FE3
	enum EVENT_1FE4
	enum EVENT_1FE5
	enum EVENT_1FE6
	enum EVENT_1FE7

		enum_start 0x1fe8 // 0x3FD
	enum EVENT_1FE8
	enum EVENT_1FE9
	enum EVENT_1FEA
	enum EVENT_1FEB
	enum EVENT_1FEC
	enum EVENT_1FED
	enum EVENT_1FEE
	enum EVENT_1FEF

		enum_start 0x1ff0 // 0x3FE
	enum EVENT_1FF0
	enum EVENT_1FF1
	enum EVENT_1FF2
	enum EVENT_1FF3
	enum EVENT_1FF4
	enum EVENT_1FF5
	enum EVENT_1FF6
	enum EVENT_1FF7

		enum_start 0x1ff8 // 0x3FF
	enum EVENT_1FF8
	enum EVENT_1FF9
	enum EVENT_1FFA
	enum EVENT_1FFB
	enum EVENT_1FFC
	enum EVENT_1FFD
	enum EVENT_1FFE
	enum EVENT_1FFF

		enum_start 0x2000 // 0x400
	enum EVENT_2000
	enum EVENT_2001
	enum EVENT_2002
	enum EVENT_2003
	enum EVENT_2004
	enum EVENT_2005
	enum EVENT_2006
	enum EVENT_2007

		enum_start 0x2008 // 0x401
	enum EVENT_2008
	enum EVENT_2009
	enum EVENT_200A
	enum EVENT_200B
	enum EVENT_200C
	enum EVENT_200D
	enum EVENT_200E
	enum EVENT_200F

		enum_start 0x2010 // 0x402
	enum EVENT_2010
	enum EVENT_2011
	enum EVENT_2012
	enum EVENT_2013
	enum EVENT_2014
	enum EVENT_2015
	enum EVENT_2016
	enum EVENT_2017

		enum_start 0x2018 // 0x403
	enum EVENT_2018
	enum EVENT_2019
	enum EVENT_201A
	enum EVENT_201B
	enum EVENT_201C
	enum EVENT_201D
	enum EVENT_201E
	enum EVENT_201F
		
        enum_start 0x2020 // 0x404
	enum EVENT_2020
	enum EVENT_2021
	enum EVENT_2022
	enum EVENT_2023
	enum EVENT_2024
	enum EVENT_2025
	enum EVENT_2026
	enum EVENT_2027
        
        enum_start 0x2028 // 0x405
	enum EVENT_2028
	enum EVENT_2029
	enum EVENT_202A
	enum EVENT_202B
	enum EVENT_202C
	enum EVENT_202D
	enum EVENT_202E
	enum EVENT_202F

// eFlags2009F38
