.ifndef INC_ASM_ASM09
.equ INC_ASM_ASM09, 0

/* Public Symbols */
.global sub_8062AB0
.global sub_8062B64
.global sub_8062BCC


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_8030AA4

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat08.inc"
// .global off_8062728
// .global byte_8062860
// .global byte_80628A0
// .global byte_80628E0
// .global byte_8062908
// .global byte_8062958
// .global byte_80629C0
// .global byte_80629F0
// .global byte_8062A30
// .global byte_8062A70

.include "data/dat09.inc"
// .global unk_8062BFC
// .global byte_8062DA4
// .global byte_8062DE4
// .global byte_8062E88
// .global byte_8062EB4
// .global byte_8062F1C
// .global off_8063008


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM09
