.ifndef INC_ASM_ASM04
.equ INC_ASM_ASM04, 0

/* Public Symbols */
.global sub_804E62C
.global sub_804E6D0
.global sub_804E720


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_8030AA4

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat03.inc"
// .global off_804E38C
// .global off_804E450
// .global off_804E478
// .global off_804E4A0
// .global byte_804E5D4
// .global byte_804E604

.include "data/dat04.inc"
// .global byte_804E74C
// .global byte_804E87C
// .global dword_804E8D0
// .global dword_804E8D4
// .global byte_804E8D8
// .global off_804E9CC


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM04
