.ifndef INC_ASM_ASM07
.equ INC_ASM_ASM07, 0

/* Public Symbols */


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global loc_8030472
// .global sub_8030AA4

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat06.inc"
// .global off_805DD24
// .global off_805DE28
// .global byte_805DE50
// .global byte_805DE78
// .global byte_805DEA8
// .global byte_805DED8

.include "data/dat07.inc"
// .global dword_805E01C
// .global dword_805E084
// .global dword_805E09C
// .global dword_805E118
// .global dword_805E158
// .global off_805E1FC


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM07
