.ifndef INC_ASM_ASM15
.equ INC_ASM_ASM15, 0

/* Public Symbols */
.global sub_807544C
.global sub_80754E2
.global sub_8075530
.global sub_80755C4
.global sub_80755EE


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global sub_80019D0
// .global nullsub_39
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_80304E8
// .global sub_8030AA4

.include "asm/asm03_1.inc"
// .global sub_8034FB8

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat14.inc"
// .global off_8074F30
// .global byte_8074FDC
// .global byte_807500C
// .global off_807505C
// .global byte_807534C
// .global byte_807537C
// .global byte_80753CC
// .global byte_80753FC

.include "data/dat15.inc"
// .global byte_8075614
// .global byte_8075708
// .global byte_807575C

.include "data/dat38_60.inc"
// .global off_8617068


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM15
