	.ifndef INC_ASM_ASM17
	.equ INC_ASM_ASM17, 0

/* Public Symbols */
	.global sub_807931C
	.global sub_807939A
	.global sub_80793E8
	.global sub_8079468
	.global sub_807948C


/* External Symbols */
	.include "asm/asm38.inc"
// .global nullsub_38

	.include "asm/asm00_0.inc"
// .global sRender_08_setRenderingState
// .global sub_8001780
// .global sub_800195C
// .global nullsub_36
// .global nullsub_39
// .global sub_8002354

	.include "asm/sprite.inc"
// .global sub_80028D4
// .global uncompSprite_8002906

	.include "asm/asm00_1.inc"
// .global SpawnObjectsFromList

	.include "asm/asm03_0.inc"
// .global camera_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_80304E8
// .global sub_8030AA4

	.include "asm/asm03_1.inc"
// .global sub_8034FB8

	.include "asm/chatbox.inc"
// .global chatbox_uncompBasedOnMap_803FD08 // () -> int

	.include "data/dat16.inc"
// .global off_80790A4
// .global off_80790EC
// .global byte_8079114
// .global byte_8079164
// .global byte_80791B4
// .global byte_8079204
// .global byte_8079254
// .global byte_80792A4
// .global byte_80792F4

	.include "data/dat17.inc"
// .global byte_80794AC
// .global byte_80794EC

	.include "data/dat18.inc"
// .global off_807C974

	.include "data/dat38_60.inc"
// .global dword_8618910
// .global dword_8618DFC
// .global byte_8618E40


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800
// .equ byte_3001960, 0x3001960

	.endif // INC_ASM_ASM17
