.ifndef INC_ASM_ASM18
.equ INC_ASM_ASM18, 0

/* Public Symbols */
.global sub_807A8E0
.global sub_807A974
.global sub_807A9CC
.global sub_807AAAC
.global sub_807AAD6


/* External Symbols */
.include "asm/asm38.inc"
// .global nullsub_38

.include "asm/asm00_0.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global sub_80019D0
// .global nullsub_39
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_80304E8
// .global sub_8030540
// .global sub_8030AA4

.include "asm/asm03_1.inc"
// .global sub_8034FB8

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat17.inc"
// .global off_8079F74
// .global off_807A080
// .global byte_807A370
// .global byte_807A3C0
// .global byte_807A410
// .global byte_807A460
// .global byte_807A4B0
// .global off_807A4E0
// .global byte_807A7D0
// .global byte_807A800
// .global byte_807A850

.include "data/dat18.inc"
// .global byte_807AAFC
// .global byte_807AC18
// .global byte_807ACA8

.include "data/dat38_60.inc"
// .global off_8617068
// .global dword_8617190
// .global dword_8618AB4
// .global dword_8618C58


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800
// .equ byte_3001960, 0x3001960

.endif // INC_ASM_ASM18
