.ifndef INC_ASM_ASM19
.equ INC_ASM_ASM19, 0

/* Public Symbols */
.global sub_807CDEC
.global sub_807CE90
.global sub_807CF24
.global sub_807CFCC
.global sub_807CFFC


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global nullsub_36
// .global nullsub_39
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global sub_8030472
// .global sub_80304E8
// .global sub_8030AA4

.include "asm/asm03_1.inc"
// .global sub_8034FB8

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat18.inc"
// .global off_807C82C
// .global off_807C94C
// .global off_807C974
// .global byte_807CA04
// .global byte_807CA54
// .global byte_807CAA4
// .global byte_807CACC
// .global byte_807CB1C
// .global byte_807CB6C
// .global byte_807CBBC
// .global byte_807CC0C
// .global byte_807CC34
// .global byte_807CC5C
// .global byte_807CCAC
// .global byte_807CCFC
// .global byte_807CD4C
// .global byte_807CD9C

.include "data/dat19.inc"
// .global dword_807D024
// .global dword_807D0B4
// .global dword_807D1A8
// .global dword_807D210

.include "data/dat38_60.inc"
// .global dword_8618DFC


/* Undeclared Symbols */
// .equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM19
