.ifndef INC_ASM_ASM34
.equ INC_ASM_ASM34, 0

/* Public Symbols */
.global sub_812D378
.global sub_812D3A8
.global sub_812D3E4
.global sub_812D4FC
.global sub_812D528
.global sub_812D5A0
.global sub_812D5D0
.global sub_812D690
.global sub_812D6F8
.global sub_812D748
.global sub_812D778
.global sub_812D78C
.global sub_812D854
.global sub_812D880
.global sub_812D8C8
.global sub_812D91C
.global loc_812D922
.global sub_812D934
.global sub_812D954
.global sub_812D99C
.global sub_812DA3C
.global sub_812DA4C
.global sub_812DA60


/* External Symbols */
.include "asm/asm38.inc"
// .global byte_30069A0

.include "asm/asm00_0.inc"
// .global sound_play // () -> void
// .global ZeroFillByEightWords // (int a1, int a2) -> void
// .global sub_800183C
// .global copyTiles // (int j, int i, int cpyOff, u16 *tileRefs) -> void
// .global sub_80018D0

.include "asm/asm00_1.inc"
// .global sub_800307C
// .global engine_setScreeneffect // (int a1, int a2) -> void
// .global sub_80062C8

.include "asm/asm03_1.inc"
// .global sub_803C754
// .global sub_803EA60
// .global sub_803EBF4

.include "asm/chatbox.inc"
// .global chatbox_8040818

.include "asm/asm03_2.inc"
// .global sub_80465A0 // (void *a1) -> void
// .global sub_8046664 // () -> void
// .global sub_80466C4

.include "asm/asm32.inc"
// .global sub_811980C
// .global sub_8119854
// .global sub_811F7EC
// .global sub_811F7F8
// .global sub_811FA22
// .global sub_811FA98
// .global sub_811FAF4
// .global sub_811FE7C
// .global sub_8120018
// .global sub_8120194
// .global sub_8120228
// .global sub_8120390
// .global sub_81203E4
// .global sub_8120458
// .global sub_81204C4
// .global sub_8120618
// .global sub_8120A88
// .global sub_8120AB8
// .global sub_8120CC8

.include "asm/asm33.inc"
// .global byte_8129178
// .global dword_8129180

.include "data/dat33.inc"
// .global byte_812C258
// .global byte_812C268
// .global byte_812C278
// .global byte_812C280
// .global byte_812C288

.include "asm/asm36.inc"
// .global sub_8132280

.include "asm/libs.inc"
// .global sub_81440D8 // static () -> void


/* Undeclared Symbols */
// .equ unk_201D620, 0x201D620
// .equ unk_201DB20, 0x201DB20
// .equ dword_201E420, 0x201E420
// .equ unk_20227A0, 0x20227A0
// .equ word_2023FA0, 0x2023FA0
// .equ unk_2023FC0, 0x2023FC0
// .equ unk_202DFA0, 0x202DFA0
// .equ unk_202DFC0, 0x202DFC0
// .equ unk_202E080, 0x202E080
// .equ unk_202E0B8, 0x202E0B8
// .equ unk_202E0F0, 0x202E0F0
// .equ byte_202E10C, 0x202E10C
// .equ byte_202E144, 0x202E144
// .equ unk_2037780, 0x2037780

.endif // INC_ASM_ASM34
