	.ifndef INC_ASM_ASM32
	.equ INC_ASM_ASM32, 0

/* Public Symbols */
	.global sub_810D970
	.global sub_810D98C
	.global sub_810D998
	.global sub_810DCCE
	.global byte_810DD10
	.global byte_810DD18
	.global byte_810DD3C
	.global off_810E120
	.global sub_810E2A6
	.global sub_810E336
	.global sub_810E340
	.global sub_810E386
	.global byte_810E3E8
	.global byte_810E3F0
	.global byte_810E414
	.global off_810E7B0
	.global sub_810E81E
	.global sub_810E854
	.global byte_810EC80
	.global byte_810EC88
	.global byte_810ECAC
	.global off_810F010
	.global sub_810F040
	.global sub_810F090
	.global byte_810F200
	.global byte_810F208
	.global byte_810F22C
	.global off_810F39C
	.global sub_810F3F8
	.global byte_810F4E4
	.global byte_810F4EC
	.global byte_810F510
	.global sub_810FA4C
	.global off_810FCE0
	.global sub_81100B0
	.global sub_81100E2
	.global sub_8110254
	.global byte_8110290
	.global byte_8110298
	.global byte_81102BC
	.global off_81104D4
	.global sub_8110546
	.global sub_811060A
	.global byte_8110628
	.global byte_8110630
	.global byte_8110654
	.global off_8110DC0
	.global sub_8110E76
	.global byte_8111130
	.global byte_8111138
	.global byte_811115C
	.global off_8111330
	.global sub_8111816
	.global sub_8111846
	.global byte_811190C
	.global byte_8111914
	.global byte_8111938
	.global off_8111DC0
	.global byte_8111FF8
	.global byte_8112000
	.global byte_8112024
	.global off_81121F0
	.global byte_81126DC
	.global byte_81126E4
	.global byte_8112708
	.global off_81129A0
	.global sub_81129EE
	.global byte_8112B94
	.global byte_8112B9C
	.global byte_8112BC0
	.global off_8113078
	.global byte_811323C
	.global byte_8113244
	.global byte_8113268
	.global off_81135CC
	.global sub_8113626
	.global byte_8113754
	.global byte_811375C
	.global byte_8113780
	.global off_8113D50
	.global byte_8113DC0
	.global sub_8114170
	.global byte_81143C8
	.global byte_81143D0
	.global byte_81143F4
	.global off_8114710
	.global sub_8114DF2
	.global sub_8114E30
	.global sub_8114F52
	.global sub_8114F6A
	.global sub_8115098
	.global byte_81150AC
	.global byte_81150B4
	.global byte_81150D8
	.global off_81154F0
	.global byte_8115704
	.global byte_811570C
	.global byte_8115730
	.global off_8115950
	.global sub_81159B0
	.global sub_81159DC
	.global sub_8115BB0
	.global byte_8115BEC
	.global byte_8115BF4
	.global byte_8115C18
	.global off_8115DE0
	.global sub_811627A
	.global sub_81162AA
	.global byte_81162F8
	.global byte_8116300
	.global off_81163F0
	.global sub_8116414
	.global sub_81165A4
	.global byte_81165BC
	.global byte_81165C4
	.global off_81166B0
	.global sub_81166D4
	.global sub_8116878
	.global sub_8116894
	.global sub_8116924
	.global sub_8116ADC
	.global sub_8116CE0
	.global sub_8116E10
	.global sub_8116FDC
	.global sub_8117084
	.global sub_8117110
	.global sub_81171D4
	.global sub_81171F4
	.global sub_8117218
	.global sub_81172B0
	.global sub_8117404
	.global sub_81175D0
	.global sub_8117690
	.global sub_8117780
	.global sub_81178D8
	.global sub_81179AE
	.global sub_8117BC8
	.global sub_8117D10
	.global sub_8117D2C
	.global sub_8117EC8
	.global sub_8118344
	.global sub_81187E8
	.global sub_8118BA4
	.global sub_8118D60
	.global sub_8118E84
	.global sub_8118F24
	.global sub_81190F8
	.global sub_8119118
	.global sub_8119364
	.global sub_811980C
	.global sub_811983C
	.global sub_8119854
	.global sub_811997C
	.global sub_8119ACC
	.global sub_8119BE8
	.global sub_8119C74
	.global sub_8119C94
	.global sub_8119D54
	.global sub_8119E40
	.global sub_811A1F4
	.global sub_811A220
	.global sub_811A338
	.global sub_811A414
	.global sub_811A610
	.global sub_811A768
	.global sub_811A78C
	.global sub_811A858
	.global sub_811A914
	.global sub_811A940
	.global sub_811A968
	.global sub_811A978
	.global sub_811AB5C
	.global sub_811AD04
	.global sub_811AD18
	.global sub_811AD38
	.global sub_811AE5C
	.global sub_811AE7C
	.global sub_811B010
	.global sub_811B1EC
	.global sub_811B314
	.global sub_811B338
	.global sub_811B3F4
	.global sub_811B46C
	.global sub_811B48C
	.global sub_811B4AC
	.global byte_811B9B5
	.global sub_811BC00
	.global sub_811BC24
	.global sub_811BC44
	.global sub_811BD64
	.global sub_811BDFC
	.global sub_811BED4
	.global sub_811C08C
	.global sub_811C11C
	.global sub_811C1AC
	.global sub_811C23C
	.global sub_811C25C
	.global sub_811C2A8
	.global sub_811C4D8
	.global sub_811C4E8
	.global sub_811C9FC
	.global sub_811CC74
	.global sub_811D634
	.global sub_811D66C
	.global sub_811D69C
	.global sub_811DBF0
	.global sub_811DC34
	.global sub_811DC88
	.global sub_811DF0C
	.global sub_811DF1C
	.global sub_811E024
	.global sub_811E0BA
	.global sub_811E168
	.global sub_811E248
	.global sub_811E360
	.global sub_811E418
	.global sub_811E57C
	.global sub_811E61C
	.global sub_811E6C0
	.global sub_811E744
	.global sub_811E7D4
	.global sub_811E858
	.global sub_811E914
	.global sub_811E9A0
	.global sub_811EBE0
	.global sub_811EBF4
	.global sub_811EC00
	.global sub_811EC10
	.global sub_811EC50
	.global ho_811ED1C // () -> void
	.global sub_811F290
	.global sub_811F6C0
	.global sub_811F6E0
	.global sub_811F708
	.global sub_811F728
	.global sub_811F758
	.global SubMenuControl // () -> void
	.global JoypadKeyPressed
	.global sub_811F7F8
	.global sub_811F91C
	.global sub_811FA0C
	.global sub_811FA22
	.global sub_811FA98
	.global sub_811FAF4
	.global sub_811FB64
	.global sub_811FB78
	.global sub_811FB84
	.global sub_811FCA4
	.global sub_811FCB8
	.global sub_811FDB8
	.global sub_811FE34
	.global sub_811FE7C
	.global sub_811FF6C
	.global sub_811FFC0 // () -> void
	.global sub_8120018
	.global sub_81200EC
	.global sub_8120194
	.global sub_8120228
	.global sub_8120280
	.global sub_81202B4
	.global sub_81202FC
	.global sub_8120348
	.global sub_8120390
	.global sub_81203E4
	.global sub_8120458
	.global sub_81204C4
	.global sub_812053C
	.global sub_8120618
	.global sub_81206C4
	.global sub_81206F8
	.global sub_8120740
	.global sub_81207C4
	.global sub_81207F8
	.global sub_8120900
	.global sub_81209DC
	.global sub_8120A38
	.global sub_8120A88
	.global sub_8120AB8
	.global sub_8120B54
	.global sub_8120BE4
	.global sub_8120C94
	.global sub_8120CC8
	.global sub_8120D10
	.global sub_8120DAC
	.global sub_8120DF0
	.global sub_8121144
	.global sub_8121154
	.global sub_8121198
	.global byte_81211B4
	.global pt_8121200


/* External Symbols */
	.include "asm/asm38.inc"
// .global sub_3006B94

	.include "asm/start.inc"
// .global 0x4000000

	.include "asm/asm00_0.inc"
// .global PlaySoundEffect
// .global ZeroFillByHalfword
// .global ZeroFillByWord // (void *memBlock, int size) -> void
// .global ZeroFillByEightWords // (int a1, int a2) -> void
// .global CopyWords // (u32 *src, u32 *dest, int size) -> void
// .global CopyByEightWords // (u32 *src, u32 *dest, int byteCount) -> void
// .global WordFill
// .global sub_8000AC4
// .global sub_8000AC8
// .global decompAndCopyData // (u32 *initRefs) -> void
// .global decomp_initGfx_8000B8E // (u32 *dataRefs) -> void
// .global sub_8000C00
// .global sub_8000C5C
// .global getPETNaviSelect // () -> u8
// .global sub_8001330
// .global sub_800139A
// .global GetRNG2 // () -> int
// .global GetPositiveSignedRNG2
// .global GetPositiveSignedRNG1
// .global sub_80015FC
// .global copyMemory_8001850
// .global CopyBackgroundTiles // (int j, int i, int cpyOff, u16 *tileIds) -> void
// .global sub_8001B1C
// .global sub_8001B84
// .global loc_8002676

	.include "asm/sprite.inc"
// .global sprite_loadAnimationData // () -> void
// .global sprite_update
// .global initGuiSprite_8002770 // (int a1, int a2) -> void
// .global loc_8002774
// .global sprite_setScaleParameters
// .global sub_8002C52
// .global sub_8002C7A
// .global sprite_setMosaicScalingParameters
// .global sub_8002CCE
// .global sprite_getMosaicScalingParameters
// .global sprite_makeScalable
// .global sprite_makeUnscalable
// .global sprite_setPalette // (int pallete) -> void
// .global sprite_setAnimation // (u8 a1) -> void

	.include "asm/asm00_1.inc"
// .global sprite_getFrameParameters
// .global sub_8002E14
// .global sprite_setColorShader
// .global sub_8002EE8
// .global loc_8002F02
// .global sub_8002F3E
// .global sprite_setFlip
// .global sprite_noShadow // () -> void
// .global sub_8002FA6
// .global sub_8002FB2
// .global sub_8002FEC
// .global sub_800304A
// .global sub_8003060
// .global sub_800306C
// .global sprite_setCoordinates
// .global sprite_addCoordinates
// .global sprite_getCoordinates
// .global sub_8005524
// .global engine_setScreeneffect // (int a1, int a2) -> void
// .global IsPaletteFadeActive // () -> zf
// .global math_sinTable
// .global math_cosTable
// .global sub_80077B4
// .global battle_isPaused
// .global battle_isTimeStop
// .global sub_800A11C
// .global battle_isBattleOver
// .global sub_800A704
// .global sub_800AAE8

	.include "asm/object.inc"
// .global object_getPanelParameters
// .global object_highlightPanel
// .global object_setPanelType
// .global object_isCurrentPanelValid
// .global object_isValidPanel
// .global object_checkPanelParameters
// .global object_isPanelSolid
// .global object_getPanelsExceptCurrentFiltered
// .global object_getPanelsFiltered
// .global object_getPanelsIgnoreColumnFiltered
// .global object_getPanelsInColumnFiltered
// .global object_getClosestPanelMatchingRowFiltered
// .global object_getFirstPanelInDirectionFiltered
// .global object_getPanelRegion
// .global sub_800D45C
// .global sub_800D5F0
// .global sub_800E258
// .global object_getCoordinatesForPanels // (int a1, int a2) -> (int n1, int n2)
// .global object_setCoordinatesFromPanels // () -> void
// .global object_setPanelsFromCoordinates
// .global object_getEnemyDirection
// .global object_getAllianceDirection
// .global object_getFrontDirection // () -> int
// .global sub_800E360
// .global object_getFlip // () -> int
// .global object_canMove
// .global sub_800E994
// .global object_setCounterTime
// .global object_getEnemyByNameRange

	.include "asm/asm00_2.inc"
// .global sub_800ED90
// .global sub_800F29C
// .global sub_800F2C6
// .global sub_800F322
// .global sub_80101C4
// .global sub_80101F8
// .global sub_80103F8
// .global sub_8010C76
// .global sub_8010CE0
// .global object_setAttack0
// .global object_exitAttackState
// .global sub_801171C
// .global sub_80126E4
// .global navicust_801379E // (int a1, int a2, int a3) -> void
// .global sub_80137B6 // (int a1, int a2) -> u8
// .global SetField16ToSelectedS20047CCStruct
// .global GetField16FromSelectedS20047CCStruct
// .global init_8013B4E // (bool a1, int a2) -> void
// .global SelectS20047CCStruct8014018 // (int idx) -> bool8
// .global sub_8015C48
// .global sub_8015C94
// .global sub_8015D80
// .global GetRandomRelativePanelFiltered
// .global sub_8016380
// .global sub_80165B8
// .global sub_80165C2
// .global sub_80166AE
// .global sub_8016934
// .global sub_8016B02
// .global sub_8016B36
// .global sub_8016B72
// .global sub_8016CE8
// .global sub_8016EC4
// .global sub_8018810
// .global PanelOffsetListsPointerTable
// .global object_updateCollisionPanels
// .global object_setCollisionPanelsToCurrent
// .global object_clearCollisionRegion // () -> void
// .global object_setCollisionRegion
// .global sub_801A082
// .global object_setFlag1 // (int a1) -> void
// .global object_clearFlag // (int bitfield) -> void
// .global object_getFlag // () -> int
// .global object_clearFlag2
// .global object_setCollisionStatusEffect1
// .global sub_801A284
// .global sub_801A29A
// .global sub_801A2B0
// .global sub_801A5E2
// .global sub_801A7F4
// .global object_reservePanel
// .global object_removePanelReserve
// .global sub_801BD3C
// .global sub_801DC36
// .global sub_801DC7C
// .global sub_801DD34
// .global sub_801DFA2

	.include "data/dat01.inc"
// .global byte_80203EA

	.include "asm/asm02.inc"
// .global getChip8021DA8 // (int chip_idx) -> ChipData*
// .global split9BitsFromBitfield_8021AE0 // (int bitfield) -> (int, int)
// .global dword_8021AEC
// .global sub_8021B2A
// .global sub_8021B92 // (int idx, int searchItem, int off) -> void*
// .global GetChipCountOfCode
// .global GetTotalChipCount
// .global chip_8021C7C // (int chip_idx, int searchItem, int off) -> void*

	.include "asm/asm03_0.inc"
// .global sub_802CDD0
// .global GetBattleMode
// .global GetBattleEffects // () -> int
// .global sub_802EF5C
// .global TestEventFlagFromImmediate // (int entryIdx, int byteFlagIdx) -> zf
// .global TestEventFlag // (u16 entryFlagBitfield) -> zf
// .global sub_802FE28 // (u32 a1, u16 a2, int notUsed, int a4) -> void

	.include "asm/asm03_1.inc"
// .global sub_8033978
// .global sub_8036F70
// .global sub_803C316
// .global sub_803CE28
// .global sub_803D06C
// .global sub_803D0F4
// .global sub_803D138
// .global sub_803D148
// .global sub_803DD60
// .global notZero_eByte200AD04
// .global sub_803F674
// .global sub_803F740

	.include "asm/chatbox.inc"
// .global chatbox_8040818
// .global chatbox_clear_eFlags2009F38 // (int a1) ->
// .global chatbox_check_eFlags2009F38

	.include "asm/asm03_2.inc"
// .global renderTextGfx_8045F8C
// .global sub_80465A0 // (void *a1) -> void
// .global sub_80465BC
// .global sub_80465F8 // () -> void
// .global sub_8046664 // () -> void
// .global sub_8046670
// .global sub_804668A
// .global getStructFrom2008450
// .global sub_80468E0
// .global sub_8047D84
// .global sub_804A24C

	.include "asm/asm23.inc"
// .global dword_8089128

	.include "asm/asm28_1.inc"
// .global sub_809F68C

	.include "asm/asm31.inc"
// .global sub_80B8786
// .global sub_80B87AC
// .global sub_80B87F0
// .global sub_80B89DC
// .global sub_80B8A0A
// .global sub_80BC998
// .global sub_80BC9BE
// .global sub_80BCB12
// .global sub_80BE6D8
// .global sub_80C0098
// .global sub_80C00C2
// .global sub_80C0136
// .global sub_80C10C8
// .global sub_80C10E8
// .global sub_80C1400
// .global sub_80C4038
// .global sub_80C4072
// .global sub_80C407C
// .global sub_80C4086
// .global sub_80C4090
// .global object_spawnCollisionRegion
// .global sub_80C579E
// .global sub_80C59F6
// .global sub_80CBAB8
// .global sub_80CBAF2
// .global sub_80D1442
// .global sub_80D1EB8
// .global sub_80D1EE8
// .global sub_80D464A
// .global sub_80D5890
// .global sub_80D6B78
// .global sub_80D8400
// .global sub_80D842E
// .global sub_80D9CA4
// .global sub_80DD25E
// .global sub_80DFAD6
// .global sub_80DFF84
// .global SpawnT4BattleObjectWithId0
// .global sub_80E060E
// .global sub_80E33FA
// .global sub_80E3CF2
// .global sub_80E5B62
// .global sub_80E5B6E
// .global sub_80E8124
// .global sub_8109630
// .global sub_8109660
// .global sub_81096BA
// .global GetAllianceDependentPanelParamArgs
// .global sub_8109708
// .global sub_810971A
// .global sub_81097B4
// .global sub_81097BA
// .global sub_81097D6
// .global sub_81097DC
// .global sub_8109804
// .global sub_8109952
// .global sub_8109974

	.include "data/dat32.inc"
// .global byte_8121270
// .global byte_812127C
// .global byte_8121288
// .global byte_812129C
// .global byte_81212B0
// .global byte_81212CC
// .global byte_81212E8
// .global byte_812130C
// .global byte_8121330
// .global byte_8121354
// .global byte_8121388
// .global byte_81213BC
// .global byte_81213F0
// .global byte_8121424
// .global byte_8121458
// .global off_812148C
// .global off_8121748
// .global off_8121A2C
// .global off_8121C40
// .global off_8121EA4
// .global off_81220F8
// .global off_8122334
// .global off_8122618
// .global off_812291C
// .global off_8122BF8
// .global off_8122EBC
// .global byte_8123199
// .global byte_81231A5
// .global byte_81231B1
// .global byte_81231BD
// .global byte_81231C9
// .global byte_81231D5
// .global byte_81231E1
// .global byte_81231E9
// .global byte_81231F1
// .global byte_81231F9
// .global byte_8123201

	.include "asm/asm33.inc"
// .global sub_8123208
// .global sub_8123360
// .global HandleChipFolderMenu8123434
// .global HandleSubChipMenu8123F5C
// .global byte_8124B1C
// .global HandleLibraryMenu8124B3C
// .global HandleMegaManStatusMenu8126B4C
// .global HandleEmailMenu81279F8
// .global HandleKeyItemMenu8128730
// .global sub_8128CBC
// .global HandleCommMenu81291E8
// .global sub_8129248

	.include "asm/asm36.inc"
// .global sub_81312F4
// .global sub_81329C8
// .global sub_8132A14
// .global sub_8132A50
// .global dword_8132A9C
// .global HandleSaveMenu8132B88
// .global sub_8133200
// .global sub_81355D8
// .global sub_81356D4
// .global sub_8136DE0
// .global sub_81376CC
// .global sub_8137718
// .global sub_81377EC
// .global sub_8137884
// .global sub_8137890
// .global sub_81378B4

	.include "asm/asm37_0.inc"
// .global sub_813B780
// .global sub_813B7A0
// .global sub_813B9B4
// .global sub_813B9FC

	.include "asm/reqBBS.inc"
// .global reqBBS_813EE58
// .global reqBBS_81406FC

	.include "asm/asm37_1.inc"
// .global sub_81418E4
// .global sub_8142190
// .global sub_81421D0
// .global sub_8143198
// .global sub_81433DA
// .global sub_8143D4C
// .global sub_8143F90
// .global sub_8144010

	.include "asm/libs.inc"
// .global sub_8144D30
// .global SWI_LZ77UnCompReadNormalWrite8bit // (void *src, void *dest) -> void

	.include "data/dat38_32.inc"
// .global sprite_837D8E0

	.include "data/dat38_33.inc"
// .global npcSpriteLan

	.include "data/dat38_36.inc"
// .global npcSpriteMegaMan

	.include "data/dat38_39.inc"
// .global sprite_849B424

	.include "data/dat38_60.inc"
// .global dword_86A5D60
// .global dword_86B7AE0
// .global byte_86C0B20
// .global byte_86C0B60
// .global byte_86C0BA0
// .global byte_86C0BE0
// .global byte_86C0C20
// .global byte_86C0C60
// .global byte_86C14A0
// .global byte_86C1520
// .global byte_86C15A0
// .global byte_86C1620
// .global byte_86C16A0
// .global byte_86C1720
// .global byte_86C18E0
// .global byte_86C1920
// .global byte_86C1960
// .global byte_86C19A0
// .global byte_86C19E0
// .global byte_86C1A60
// .global byte_86C1BA0
// .global byte_86C1C20
// .global byte_86C1CA0
// .global byte_86C1D20
// .global byte_86C1DA0
// .global byte_86C1EA0

	.include "data/dat38_67.inc"
// .global dword_86C9108

	.include "data/dat38_69.inc"
// .global dword_86C9AF4
// .global dword_86C9B14
// .global dword_86C9B34
// .global dword_86C9B54
// .global dword_86C9B94

	.include "data/dat38_70.inc"
// .global byte_86C9D8C
// .global byte_86C9DAC
// .global byte_86C9DCC
// .global dword_86CA10C
// .global PET_Gfx_tileIds
// .global TileIds_86CB21C
// .global TileIds_86CB240
// .global TileIds_86CB264
// .global TileIds_86CB288
// .global TileIds_86CB2AC
// .global TileIds_86CB2D0
// .global TileIds_86CB2F4
// .global TileIds_86CB318
// .global TileIds_86CB33C
// .global byte_86CB360
// .global sprite_86CBB7C
// .global sprite_86CC13C
// .global dword_86CD7C4
// .global dword_86CD924

	.include "data/dat38_71.inc"
// .global TextScriptFolderNames

	.include "data/dat38_78.inc"
// .global dword_86DAC40

	.include "data/dat38_80.inc"
// .global off_86DC3F8

	.include "data/dat38_85.inc"
// .global dword_86E2E98
// .global dword_86E3B9C
// .global dword_86E411C
// .global dword_86E43DC
// .global byte_86E587C
// .global TextScriptChipNames0
// .global TextScriptChipNames1
// .global TextScriptChipDescriptions0
// .global dword_86EE0CC

	.include "data/dat38_86.inc"
// .global byte_872CF94

	.include "data/dat38_87.inc"
// .global byte_873EA50


/* Undeclared Symbols */
// .equ timer_2000000, 0x2000000
// .equ unk_2000310, 0x2000310
// .equ byte_2000780, 0x2000780
// .equ byte_2001010, 0x2001010
// .equ dword_2001020, 0x2001020
// .equ dword_2001020, 0x2001020
// .equ reqBBS_eStruct2001150, 0x2001150
// .equ unk_2001186, 0x2001186
// .equ unk_200119E, 0x200119E
// .equ unk_20018EC, 0x20018EC
// .equ eReqBBSGui, 0x2005780
// .equ byte_20065C0, 0x20065C0
// .equ unk_20096E0, 0x20096E0
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ sSubmenu, 0x2009A30
// .equ unk_200BEA0, 0x200BEA0
// .equ unk_200C0E0, 0x200C0E0
// .equ unk_200C2A0, 0x200C2A0
// .equ byte_200C620, 0x200C620
// .equ byte_200C920, 0x200C920
// .equ byte_200CC20, 0x200CC20
// .equ byte_200CF20, 0x200CF20
// .equ byte_200D220, 0x200D220
// .equ word_200DCF0, 0x200DCF0
// .equ ePETMenuData, 0x200DF20
// .equ byte_200DF21, 0x200DF21
// .equ byte_200DF24, 0x200DF24
// .equ eFlags200DF25, 0x200DF25
// .equ byte_200DF28, 0x200DF28
// .equ byte_200DF29, 0x200DF29
// .equ byte_200DF2A, 0x200DF2A
// .equ byte_200DF2B, 0x200DF2B
// .equ word_200DF30, 0x200DF30
// .equ eStruct200F360, 0x200F360
// .equ unk_2010100, 0x2010100
// .equ byte_2011C10, 0x2011C10
// .equ byte_2011E40, 0x2011E40
// .equ byte_2011E42, 0x2011E42
// .equ byte_2011E46, 0x2011E46
// .equ unk_2016200, 0x2016200
// .equ unk_2016300, 0x2016300
// .equ unk_2016400, 0x2016400
// .equ byte_2016A04, 0x2016A04
// .equ byte_2017A00, 0x2017A00
// .equ unk_2017C00, 0x2017C00
// .equ unk_2017E00, 0x2017E00
// .equ unk_2018000, 0x2018000
// .equ unk_2018200, 0x2018200
// .equ unk_2018400, 0x2018400
// .equ unk_2018600, 0x2018600
// .equ unk_2018800, 0x2018800
// .equ unk_2018A00, 0x2018A00
// .equ unk_2018C00, 0x2018C00
// .equ unk_2018E00, 0x2018E00
// .equ unk_2019000, 0x2019000
// .equ unk_2019200, 0x2019200
// .equ unk_2019400, 0x2019400
// .equ unk_2019600, 0x2019600
// .equ unk_2019800, 0x2019800
// .equ byte_2019A00, 0x2019A00
// .equ unk_2019C00, 0x2019C00
// .equ unk_201A800, 0x201A800
// .equ unk_201AA00, 0x201AA00
// .equ byte_201AE00, 0x201AE00
// .equ byte_201B200, 0x201B200
// .equ byte_201B480, 0x201B480
// .equ eTextScript201BA00, 0x201BA00
// .equ unk_201BA04, 0x201BA04
// .equ eTextScript201BA20, 0x201BA20
// .equ eTextScript201BF20, 0x201BF20
// .equ unk_201C400, 0x201C400
// .equ eTextScript201D280, 0x201D280
// .equ unk_201D2F8, 0x201D2F8
// .equ unk_201D700, 0x201D700
// .equ unk_201D774, 0x201D774
// .equ unk_201D884, 0x201D884
// .equ word_201DA80, 0x201DA80
// .equ unk_201DD70, 0x201DD70
// .equ unk_201E284, 0x201E284
// .equ unk_201F294, 0x201F294
// .equ unk_201F6F0, 0x201F6F0
// .equ dword_201FC20, 0x201FC20
// .equ unk_2020484, 0x2020484
// .equ unk_2020500, 0x2020500
// .equ unk_2020C00, 0x2020C00
// .equ unk_20212F8, 0x20212F8
// .equ unk_20218F0, 0x20218F0
// .equ unk_2021FF0, 0x2021FF0
// .equ unk_20222A0, 0x20222A0
// .equ unk_20222F0, 0x20222F0
// .equ unk_20226F0, 0x20226F0
// .equ eGuiSprite2022AA0, 0x2022AA0
// .equ byte_2022C00, 0x2022C00
// .equ eGuiSprite2022FA0, 0x2022FA0
// .equ byte_20231A0, 0x20231A0
// .equ byte_2023BC0, 0x2023BC0
// .equ byte_2023BC8, 0x2023BC8
// .equ word_2023FA0, 0x2023FA0
// .equ unk_2024290, 0x2024290
// .equ unk_202458C, 0x202458C
// .equ unk_202488C, 0x202488C
// .equ unk_2024A00, 0x2024A00
// .equ unk_2024A20, 0x2024A20
// .equ unk_2024C00, 0x2024C00
// .equ unk_2024E8C, 0x2024E8C
// .equ unk_20251B0, 0x20251B0
// .equ unk_2025AE8, 0x2025AE8
// .equ unk_2026A00, 0x2026A00
// .equ unk_2026A20, 0x2026A20
// .equ unk_2026C00, 0x2026C00
// .equ unk_2027000, 0x2027000
// .equ unk_20270EC, 0x20270EC
// .equ unk_202714C, 0x202714C
// .equ byte_2027200, 0x2027200
// .equ byte_2027204, 0x2027204
// .equ byte_2027208, 0x2027208
// .equ byte_202720C, 0x202720C
// .equ byte_2027210, 0x2027210
// .equ byte_2027214, 0x2027214
// .equ byte_2027218, 0x2027218
// .equ byte_202721C, 0x202721C
// .equ unk_2028000, 0x2028000
// .equ unk_202CA00, 0x202CA00
// .equ unk_202CC00, 0x202CC00
// .equ byte_202CE00, 0x202CE00
// .equ byte_202D000, 0x202D000
// .equ byte_202D200, 0x202D200
// .equ byte_202D400, 0x202D400
// .equ byte_202D600, 0x202D600
// .equ byte_202D800, 0x202D800
// .equ byte_202DA00, 0x202DA00
// .equ byte_202DC00, 0x202DC00
// .equ unk_202DE00, 0x202DE00
// .equ byte_202E17C, 0x202E17C
// .equ byte_202F57C, 0x202F57C
// .equ byte_202FA04, 0x202FA04
// .equ byte_2030204, 0x2030204
// .equ unk_2031204, 0x2031204
// .equ unk_2031344, 0x2031344
// .equ unk_2032A04, 0x2032A04
// .equ unk_2032D00, 0x2032D00
// .equ unk_2033A00, 0x2033A00
// .equ unk_20343E0, 0x20343E0
// .equ unk_20347D8, 0x20347D8
// .equ unk_2034B6C, 0x2034B6C
// .equ unk_2034E00, 0x2034E00
// .equ unk_203526C, 0x203526C
// .equ unk_2035A04, 0x2035A04
// .equ unk_2036500, 0x2036500
// .equ unk_2037780, 0x2037780
// .equ byte_203778C, 0x203778C
// .equ word_203779E, 0x203779E
// .equ word_20377A0, 0x20377A0
// .equ word_20377A4, 0x20377A4
// .equ word_20377BC, 0x20377BC
// .equ word_20377C0, 0x20377C0
// .equ unk_2037A04, 0x2037A04
// .equ unk_3000000, 0x3000000
// .equ byte_3001550, 0x3001550
// .equ byte_30015B0, 0x30015B0
// .equ byte_30015D0, 0x30015D0
// .equ byte_30015F0, 0x30015F0
// .equ byte_3001610, 0x3001610
// .equ word_3001684, 0x3001684
// .equ byte_3001686, 0x3001686
// .equ byte_30016A8, 0x30016A8
// .equ unk_3001B20, 0x3001B20
// .equ word_3001B2C, 0x3001B2C
// .equ unk_3001B40, 0x3001B40
// .equ word_3001B56, 0x3001B56
// .equ word_3001B58, 0x3001B58
	.equ LCDControl, 0x4000000
	.equ IWRAMRoutinesROMLocation, 0x81D6000
// .global battleSpriteMegaMan
// .global virusBattleSprite_8244164
// .global virusBattleSprite_8246A24
// .global virusBattleSprite_824AC94
// .global virusBattleSprite_824B254
// .global virusBattleSprite_824EAF4
// .global sprite_82533F4
// .global sprite_8253F88
// .global sprite_825C9AC
// .global sprite_825F2C8
// .global sprite_8260F88
// .global battleSpriteSpoutMan
// .global sprite_829D818
// .global sprite_82A5AF0
// .global sprite_82B0690
// .global sprite_82BA7BC
// .global comp_82FCA14

	.endif // INC_ASM_ASM32
