.ifndef INC_ASM_ASM30_0
.equ INC_ASM_ASM30_0, 0

/* Public Symbols */
.global sub_80AED50


/* External Symbols */
.include "asm/asm00_2.inc"
// .global sub_80182B4

.include "asm/asm31.inc"
// .global byte_80F28F0
// .global byte_80F2A54
// .global byte_80F390C
// .global byte_80F47D4
// .global byte_80F5838
// .global byte_80F6394
// .global byte_80F757C
// .global byte_80F8334
// .global byte_80F8EEC
// .global byte_80F9C80
// .global byte_80FACDC
// .global byte_80FB8E0
// .global byte_80FD044
// .global byte_80FDCF0
// .global byte_80FE7D0
// .global byte_80FF7F0
// .global byte_81001E8
// .global byte_8101268
// .global byte_8101880
// .global byte_8103BB4
// .global byte_81053BC
// .global byte_8106828
// .global byte_8107B50
// .global byte_8109AA4
// .global byte_8109BFC
// .global byte_810A2EC
// .global byte_810A86C
// .global byte_810AE70
// .global byte_810B7B8
// .global byte_810BEF8

.include "data/dat31.inc"
// .global byte_810C388
// .global byte_810C8F8
// .global byte_810D034
// .global byte_810D198
// .global byte_810D724

.include "asm/asm32.inc"
// .global byte_810DD3C
// .global byte_810E414
// .global byte_810ECAC
// .global byte_810F22C
// .global byte_810F510
// .global byte_81102BC
// .global byte_8110654
// .global byte_811115C
// .global byte_8111938
// .global byte_8112024
// .global byte_8112708
// .global byte_8112BC0
// .global byte_8113268
// .global byte_8113780
// .global byte_81143F4
// .global byte_81150D8
// .global byte_8115730
// .global byte_8115C18


.endif // INC_ASM_ASM30_0
