	.ifndef INC_ASM_ASM31
	.equ INC_ASM_ASM31, 0

/* Public Symbols */
	.global sub_80B81EC
	.global sub_80B8210
	.global sub_80B84EC
	.global sub_80B85E0
	.global sub_80B8786
	.global sub_80B87AC
	.global sub_80B87F0
	.global sub_80B88D0
	.global sub_80B89DC
	.global sub_80B8A0A
	.global sub_80B8A18
	.global sub_80B8CD8
	.global sub_80B8EA0
	.global sub_80B9014
	.global sub_80B9078
	.global sub_80B921A
	.global sub_80B92B8
	.global sub_80B9432
	.global sub_80B94BC
	.global sub_80B9750
	.global sub_80B97C0
	.global sub_80B999A
	.global sub_80B99C0
	.global sub_80B9B6E
	.global sub_80B9C14
	.global sub_80B9F0E
	.global sub_80B9F44
	.global sub_80BA1B0
	.global sub_80BA364
	.global sub_80BA660
	.global sub_80BA708
	.global sub_80BA920
	.global sub_80BAA8C
	.global sub_80BAE16
	.global sub_80BAF50
	.global sub_80BB2A0
	.global sub_80BB608
	.global sub_80BB7F6
	.global sub_80BB914
	.global sub_80BBAC6
	.global sub_80BBB98
	.global sub_80BBDE8
	.global sub_80BBF0C
	.global sub_80BC0DA
	.global sub_80BC17C
	.global sub_80BC4FC
	.global sub_80BC650
	.global sub_80BC844
	.global sub_80BC87C
	.global sub_80BC998
	.global sub_80BC9BE
	.global sub_80BCA04
	.global sub_80BCB12
	.global sub_80BCB50
	.global sub_80BCD14
	.global sub_80BD388
	.global sub_80BD9A2
	.global sub_80BDBA4
	.global sub_80BE3E8
	.global sub_80BE4D8
	.global sub_80BE6D8
	.global sub_80BE798
	.global sub_80BF160
	.global sub_80BF260
	.global sub_80BF6AE
	.global sub_80BF6EC
	.global sub_80BFCD0
	.global sub_80BFDFC
	.global sub_80BFF68
	.global sub_80C0098
	.global sub_80C00C2
	.global sub_80C0136
	.global sub_80C0178
	.global sub_80C0334
	.global sub_80C04AC
	.global sub_80C065C
	.global sub_80C07BC
	.global sub_80C0DD8
	.global sub_80C0E04
	.global sub_80C0F6C
	.global sub_80C10C8
	.global sub_80C10E8
	.global sub_80C11AC
	.global sub_80C1400
	.global sub_80C1570
	.global sub_80C1A10
	.global sub_80C2138
	.global sub_80C26F0
	.global sub_80C2A4C
	.global sub_80C2A78
	.global sub_80C2F96
	.global sub_80C3000
	.global sub_80C3218
	.global sub_80C34E0
	.global sub_80C3734
	.global sub_80C3970
	.global sub_80C3B30
	.global sub_80C3CE8
	.global sub_80C3E98
	.global sub_80C3EE0
	.global sub_80C4038
	.global sub_80C4072
	.global sub_80C407C
	.global sub_80C4086
	.global sub_80C4090
	.global sub_80C40D8
	.global sub_80C41D8
	.global sub_80C4204
	.global sub_80C4348
	.global sub_80C44A8
	.global sub_80C44C8
	.global sub_80C44D2
	.global sub_80C4530
	.global sub_80C468C
	.global sub_80C46B0
	.global sub_80C46B6
	.global sub_80C46C0
	.global sub_80C46FC
	.global sub_80C4828
	.global sub_80C4B18
	.global sub_80C4C12
	.global sub_80C4C3A
	.global sub_80C4E58
	.global sub_80C4FFE
	.global sub_80C50B8
	.global sub_80C51AC
	.global sub_80C52B0
	.global object_spawnCollisionRegion
	.global sub_80C53A6
	.global sub_80C53C0
	.global sub_80C5578
	.global sub_80C55B0
	.global sub_80C579E
	.global sub_80C57C0
	.global sub_80C59F6
	.global sub_80C5A34
	.global sub_80C5B76
	.global sub_80C5BB0
	.global sub_80C5DDC
	.global sub_80C5F60
	.global sub_80C60A8
	.global sub_80C6280
	.global sub_80C6414
	.global sub_80C6580
	.global sub_80C67F8
	.global sub_80C6946
	.global sub_80C6B40
	.global sub_80C6DCC
	.global sub_80C7074
	.global sub_80C71A4
	.global sub_80C740C
	.global sub_80C793C
	.global sub_80C7C18
	.global sub_80C7D78
	.global sub_80C7F20
	.global sub_80C7F40
	.global sub_80C8098
	.global sub_80C81CC
	.global sub_80C8388
	.global sub_80C853C
	.global loc_80C86D8
	.global sub_80C882C
	.global sub_80C8AA4
	.global sub_80C8C74
	.global sub_80C8E08
	.global sub_80C8FFC
	.global sub_80C91A0
	.global sub_80C93CC
	.global sub_80C96A0
	.global nullsub_101
	.global nullsub_102
	.global nullsub_94
	.global nullsub_95
	.global sub_80C9824
	.global sub_80C9BC4
	.global sub_80C9D00
	.global sub_80C9F78
	.global sub_80CA2A8
	.global sub_80CA544
	.global sub_80CA6B8
	.global sub_80CA938
	.global sub_80CAB68
	.global sub_80CAD28
	.global sub_80CAEF0
	.global sub_80CB0DC
	.global sub_80CB284
	.global sub_80CB49C
	.global sub_80CB6F8
	.global sub_80CB8DE
	.global sub_80CB900
	.global sub_80CBAB8
	.global sub_80CBAF2
	.global sub_80CBB44
	.global sub_80CC044
	.global sub_80CC0B2
	.global sub_80CC0E8
	.global sub_80CC4C4
	.global sub_80CC5A8
	.global sub_80CC76C
	.global sub_80CC944
	.global sub_80CCA40
	.global sub_80CCC48
	.global sub_80CCD70
	.global sub_80CCFDC
	.global sub_80CD2EC
	.global sub_80CD4EC
	.global sub_80CD8EC
	.global sub_80CDD44
	.global sub_80CDF84
	.global sub_80CE118
	.global sub_80CE24C
	.global sub_80CE530
	.global sub_80CE70C
	.global sub_80CE81C
	.global sub_80CEB00
	.global sub_80CEE78
	.global sub_80CF0D0
	.global sub_80CF3BE
	.global sub_80CF5C8
	.global sub_80CF7F0
	.global sub_80CF954
	.global sub_80CFBC4
	.global sub_80CFC08
	.global sub_80CFCF8
	.global sub_80CFEC4
	.global sub_80D00A0
	.global sub_80D0268
	.global sub_80D0394
	.global sub_80D0500
	.global sub_80D0610
	.global sub_80D07CC
	.global sub_80D0AA8
	.global sub_80D0D7C
	.global sub_80D0F8C
	.global sub_80D1218
	.global sub_80D1442
	.global sub_80D1514
	.global sub_80D17A4
	.global sub_80D18D8
	.global sub_80D1A08
	.global sub_80D1B48
	.global sub_80D1C20
	.global sub_80D1EB8
	.global sub_80D1EE8
	.global sub_80D2034
	.global sub_80D2290
	.global sub_80D2430
	.global sub_80D2460
	.global sub_80D25D4
	.global sub_80D2A94
	.global sub_80D2BDC
	.global sub_80D2EBC
	.global sub_80D30D0
	.global sub_80D34CC
	.global sub_80D385C
	.global sub_80D39BC
	.global sub_80D4088
	.global sub_80D4440
	.global sub_80D464A
	.global sub_80D46B8
	.global sub_80D4A28
	.global sub_80D4B68
	.global sub_80D4C84
	.global sub_80D4FA6
	.global sub_80D5028
	.global sub_80D5138
	.global sub_80D535C
	.global sub_80D5580
	.global sub_80D5740
	.global sub_80D5890
	.global sub_80D58B4
	.global sub_80D5ABC
	.global sub_80D5C48
	.global sub_80D5D54
	.global sub_80D5F08
	.global sub_80D622C
	.global sub_80D655C
	.global sub_80D67EC
	.global sub_80D6924
	.global sub_80D6A20
	.global sub_80D6B78
	.global sub_80D6BD4
	.global sub_80D6D80
	.global sub_80D6EE0
	.global sub_80D7068
	.global sub_80D7278
	.global sub_80D7400
	.global sub_80D75FC
	.global sub_80D7ACC
	.global sub_80D7DE4
	.global sub_80D807C
	.global sub_80D825C
	.global sub_80D8400
	.global sub_80D842E
	.global sub_80D8444
	.global sub_80D85F0
	.global sub_80D8620
	.global sub_80D879C
	.global sub_80D88E0
	.global sub_80D8C5C
	.global sub_80D8D5A
	.global sub_80D8E10
	.global sub_80D8FC4
	.global sub_80D9154
	.global sub_80D9350
	.global sub_80D954C
	.global sub_80D96A4
	.global sub_80D984C
	.global sub_80D99EC
	.global sub_80D9A50
	.global sub_80D9CA4
	.global sub_80D9D4C
	.global sub_80DA050
	.global sub_80DA470
	.global sub_80DA5FC
	.global sub_80DA80C
	.global sub_80DA9DC
	.global sub_80DA9FE
	.global sub_80DAA28
	.global sub_80DACE4
	.global sub_80DAE94
	.global sub_80DB0E4
	.global sub_80DB304
	.global sub_80DB570
	.global sub_80DB6A4
	.global sub_80DB8CC
	.global sub_80DB994
	.global sub_80DBB40
	.global sub_80DBCEC
	.global sub_80DBEE6
	.global sub_80DC0E8
	.global sub_80DC260
	.global sub_80DC3F8
	.global sub_80DC4FC
	.global sub_80DC5F8
	.global sub_80DC70C
	.global sub_80DCB1C
	.global sub_80DCCD4
	.global sub_80DCE38
	.global sub_80DCEF4
	.global sub_80DD0AC
	.global sub_80DD25E
	.global sub_80DD34C
	.global sub_80DD764
	.global sub_80DD940
	.global sub_80DDA84
	.global sub_80DDC10
	.global sub_80DDDF0
	.global sub_80DE000
	.global sub_80DE13C
	.global sub_80DE404
	.global sub_80DE7F4
	.global sub_80DEA7C
	.global sub_80DEE60
	.global sub_80DF0A4
	.global sub_80DF188
	.global sub_80DF328
	.global sub_80DF4FC
	.global sub_80DF90C
	.global sub_80DFAD6
	.global sub_80DFC38
	.global sub_80DFE40
	.global sub_80DFF84
	.global sub_80DFFB8
	.global off_80E0408
	.global loc_80E0548
	.global SpawnT4BattleObjectWithId0
	.global sub_80E060E
	.global sub_80E0638
	.global sub_80E06F8
	.global sub_80E0710
	.global sub_80E07E0
	.global byte_80E083F
	.global sub_80E0844
	.global sub_80E08C4
	.global nullsub_99
	.global sub_80E08FC
	.global sub_80E09EE
	.global sub_80E0AD4
	.global sub_80E0D98
	.global sub_80E0DF0
	.global sub_80E0F02
	.global sub_80E0FA0
	.global sub_80E10A4
	.global sub_80E11E0
	.global sub_80E11FC
	.global sub_80E1520
	.global sub_80E1620
	.global sub_80E164A
	.global sub_80E1662
	.global sub_80E17E8
	.global sub_80E192C
	.global sub_80E19BC
	.global sub_80E1A6A
	.global sub_80E1A86
	.global sub_80E1A90
	.global sub_80E1B48
	.global sub_80E1CF8
	.global sub_80E1D7A
	.global sub_80E1D88
	.global sub_80E1E4C
	.global sub_80E2080
	.global sub_80E21D8
	.global sub_80E225C
	.global sub_80E23A4
	.global sub_80E24B8
	.global sub_80E24E4
	.global sub_80E2566
	.global sub_80E25D0
	.global sub_80E28A8
	.global sub_80E2AE8
	.global sub_80E2B5A
	.global sub_80E2B7C
	.global sub_80E2CA4
	.global sub_80E2D76
	.global sub_80E2E34
	.global sub_80E2F24
	.global sub_80E2F56
	.global sub_80E309C
	.global sub_80E3128
	.global sub_80E3150
	.global sub_80E31D8
	.global sub_80E3242
	.global sub_80E32B8
	.global sub_80E33FA
	.global sub_80E342C
	.global sub_80E349E
	.global sub_80E34C0
	.global sub_80E353E
	.global sub_80E35A4
	.global sub_80E3728
	.global sub_80E37D2
	.global sub_80E37F4
	.global sub_80E39A0
	.global sub_80E3AB8
	.global sub_80E3B50
	.global sub_80E3B70
	.global sub_80E3CF2
	.global sub_80E3D68
	.global sub_80E3FD0
	.global sub_80E40EC
	.global sub_80E4164
	.global sub_80E4188
	.global sub_80E4288
	.global sub_80E4344
	.global sub_80E440C
	.global sub_80E4634
	.global sub_80E46B6
	.global sub_80E46D8
	.global sub_80E47B4
	.global sub_80E4848
	.global sub_80E4910
	.global sub_80E49A2
	.global sub_80E4A1C
	.global sub_80E4B34
	.global sub_80E4CB8
	.global sub_80E4D8A
	.global sub_80E4DA2
	.global sub_80E4DB0
	.global sub_80E50C4
	.global sub_80E5244
	.global sub_80E532C
	.global sub_80E5368
	.global sub_80E5410
	.global sub_80E544C
	.global sub_80E5470
	.global sub_80E55C0
	.global sub_80E5710
	.global sub_80E5944
	.global sub_80E59C6
	.global sub_80E59E8
	.global locret_80E5B60
	.global sub_80E5B62
	.global sub_80E5B6E
	.global sub_80E5C2C
	.global sub_80E5D44
	.global sub_80E5E00
	.global sub_80E5EA8
	.global sub_80E5ECC
	.global sub_80E5F78
	.global sub_80E5F9C
	.global sub_80E5FBC
	.global sub_80E6088
	.global sub_80E6254
	.global sub_80E6480
	.global sub_80E64E8
	.global sub_80E655C
	.global sub_80E6758
	.global sub_80E67E6
	.global sub_80E680C
	.global sub_80E689C
	.global sub_80E6A90
	.global sub_80E6BDC
	.global sub_80E6E44
	.global sub_80E6F88
	.global sub_80E7008
	.global sub_80E702C
	.global sub_80E70A6
	.global sub_80E70C8
	.global sub_80E71C4
	.global sub_80E723E
	.global sub_80E7260
	.global sub_80E7464
	.global sub_80E7486
	.global sub_80E74D4
	.global sub_80E7546
	.global sub_80E7568
	.global sub_80E7600
	.global sub_80E7624
	.global sub_80E76D4
	.global sub_80E76F8
	.global sub_80E7788
	.global sub_80E78BC
	.global sub_80E795C
	.global sub_80E7ACC
	.global sub_80E7BFC
	.global sub_80E7CA8
	.global sub_80E7CCC
	.global sub_80E7DC4
	.global sub_80E7E9C
	.global sub_80E7F16
	.global sub_80E7F38
	.global sub_80E7FBA
	.global sub_80E7FDC
	.global sub_80E8058
	.global sub_80E807C
	.global sub_80E8124
	.global sub_80E8138
	.global sub_80E81B4
	.global sub_80E81D8
	.global sub_80E8268
	.global sub_80E83B8
	.global sub_80E857C
	.global sub_80E8688
	.global sub_80E8794
	.global sub_80E88A0
	.global sub_80E8938
	.global sub_80E8A60
	.global sub_80E8ADC
	.global sub_80E8B00
	.global sub_80E8BC0
	.global sub_80E8DF0
	.global sub_80E8EE0
	.global sub_80E8FE0
	.global sub_80E90FE
	.global sub_80E9120
	.global sub_80E91B8
	.global sub_80E91E4
	.global sub_80E92EE
	.global sub_80E9310
	.global sub_80E943E
	.global sub_80E9460
	.global sub_80E9570
	.global sub_80E979C
	.global sub_80E97F0
	.global byte_80E98C0
	.global sub_80E996E
	.global sub_80E9994
	.global sub_80E9AF0
	.global sub_80E9BDC
	.global sub_80E9C88
	.global sub_80E9DF0
	.global sub_80EA010
	.global sub_80EA11C
	.global sub_80EA14C
	.global sub_80EA258
	.global sub_80EA364
	.global sub_80EA438
	.global off_80EA814
	.global off_80EA8D8
	.global off_80EA9A0
	.global off_80EAA04
	.global off_80EAA68
	.global off_80EAACC
	.global off_80EAB30
	.global off_80EAB94
	.global off_80EABF8
	.global JumpTable80EAC60
	.global sub_80EAD9C
	.global sub_80EB04C
	.global sub_80EB234
	.global sub_80EE90C
	.global sub_80EEA3C
	.global sub_80EED56
	.global off_80F24D8
	.global off_80F253C
	.global off_80F2604
	.global off_80F2668
	.global off_80F26CC
	.global off_80F2730
	.global off_80F2794
	.global off_80F27F8
	.global off_80F285C
	.global byte_80F28F0
	.global byte_80F2A54
	.global byte_80F390C
	.global byte_80F47D4
	.global byte_80F5838
	.global byte_80F6394
	.global byte_80F757C
	.global byte_80F8334
	.global byte_80F8EEC
	.global byte_80F9C80
	.global byte_80FACDC
	.global byte_80FB8E0
	.global byte_80FD044
	.global byte_80FDCF0
	.global byte_80FE7D0
	.global sub_80FF668
	.global byte_80FF7F0
	.global byte_81001E8
	.global loc_8100314
	.global byte_8101268
	.global byte_8101880
	.global byte_8103BB4
	.global byte_81053BC
	.global byte_8106828
	.global byte_8107B50
	.global off_81090D0
	.global off_8109150
	.global off_8109250
	.global off_81092D0
	.global off_8109350
	.global off_81093D0
	.global off_8109450
	.global off_81094D0
	.global off_8109550
	.global sub_8109630
	.global sub_8109660
	.global sub_81096BA
	.global GetAllianceDependentPanelParamArgs
	.global sub_8109708
	.global sub_810971A
	.global sub_81097B4
	.global sub_81097BA
	.global sub_81097D6
	.global sub_81097DC
	.global sub_8109804
	.global sub_8109952
	.global sub_8109974
	.global byte_8109AA4
	.global byte_8109BFC
	.global byte_810A2EC
	.global byte_810A86C
	.global byte_810AE70
	.global byte_810B7B8
	.global byte_810BEF8


/* External Symbols */
	.include "asm/start.inc"
// .global 0x4000000

	.include "asm/asm00_0.inc"
// .global PlaySoundEffect
// .global ZeroFillByHalfword
// .global ZeroFillByWord // (void *memBlock, int size) -> void
// .global CopyBytes // (u8 *src, u8 *dest, int byteCount) -> void
// .global QueueEightWordAlignedGFXTransfer
// .global sub_8000C72
// .global sub_8000DE0
// .global calcAngle_800117C
// .global sub_80011A0
// .global sub_800120E
// .global sub_8001330
// .global sub_8001382
// .global sub_800139A
// .global GetRNG2 // () -> int
// .global GetPositiveSignedRNG2
// .global sub_8002378
// .global sub_800239A

	.include "asm/sprite.inc"
// .global sprite_loadAnimationData // () -> void
// .global sprite_update
// .global sprite_load // (int a1, int a2, int a3) ->
// .global sprite_decompress
// .global sub_8002C7A
// .global sprite_setMosaicScalingParameters
// .global sub_8002CCE
// .global sprite_getMosaicScalingParameters
// .global sprite_setPalette // (int pallete) -> void
// .global sprite_getPalette
// .global sprite_setAnimation // (u8 a1) -> void
// .global sprite_forceWhitePalette
// .global sprite_setFinalPalette

	.include "asm/asm00_1.inc"
// .global sprite_getFinalPalette
// .global sprite_clearFinalPalette
// .global sprite_getFrameParameters
// .global sub_8002E14
// .global sprite_hasShadow
// .global sub_8002E52
// .global sub_8002EAC
// .global sprite_setColorShader
// .global sprite_getColorShader
// .global sub_8002EE8
// .global loc_8002F02
// .global sub_8002F3E
// .global sprite_setFlip
// .global sprite_getFlip
// .global sprite_noShadow // () -> void
// .global sub_8002FA6
// .global sub_8003006
// .global sub_800302A
// .global sub_80030BA
// .global object_spawnType1
// .global object_spawnType3
// .global sub_8003374
// .global object_spawnType4
// .global sub_80033E4
// .global object_freeMemory
// .global sub_800362C
// .global SetScreenFade // (int a1, int a2) -> void
// .global IsScreenFadeActive // () -> zf
// .global math_sinTable
// .global math_cosTable
// .global battle_isPaused
// .global battle_isTimeStop
// .global sub_800A152
// .global battle_isBattleOver
// .global battle_setFlags
// .global battle_clearFlags
// .global battle_getFlags
// .global sub_800A704
// .global sub_800A772
// .global sub_800A8F8
// .global battle_networkInvert
// .global sub_800AA06
// .global sub_800AA1A
// .global sub_800AA40
// .global sub_800AA92
// .global sub_800AB3A
// .global sub_800AB46
// .global sub_800ABC6
// .global sub_800AE54
// .global sub_800AE90
// .global sub_800AF34
// .global object_timefreezeBegin
// .global object_dimScreen
// .global sub_800B97E
// .global object_drawChipName
// .global sub_800BA8A
// .global sub_800BBA8
// .global object_undimScreen
// .global sub_800BCC0

	.include "asm/object.inc"
// .global object_timefreezeEnd
// .global sub_800BDB2
// .global sub_800BF16
// .global sub_800BF5C
// .global object_getPanelParameters
// .global object_getPanelDataOffset
// .global object_crackPanel
// .global object_crackPanelDup1
// .global object_breakPanel
// .global object_breakPanel_dup1
// .global object_breakPanel_dup2
// .global object_breakPanel_dup3
// .global object_breakPanelLoud
// .global object_panel_setPoison
// .global object_highlightPanel
// .global object_setPanelType
// .global object_setPanelAlliance
// .global object_setPanelAllianceTimerLong
// .global object_setPanelAllianceTimerShort
// .global object_setPanelTypeBlink
// .global object_isCurrentPanelValid
// .global object_isValidPanel
// .global object_checkPanelParameters
// .global object_isCurrentPanelSolid
// .global object_isPanelSolid
// .global object_highlightCurrentCollisionPanels
// .global object_highlightPanelRegion
// .global object_highlightPanelRegionBlue
// .global object_hidePanel
// .global object_getPanelsExceptCurrentFiltered
// .global object_getPanelsFiltered
// .global object_getPanelsInColumnIgnoreRowFiltered
// .global object_getPanelsInRowIgnoreColumnFiltered
// .global object_getPanelsIgnoreRowFiltered
// .global object_getPanelsIgnoreColumnFiltered
// .global object_getPanelsInColumnFiltered
// .global object_getPanelsInRowFiltered
// .global object_getEnemyPlayerPanels
// .global object_getClosestPanelMatchingRowFiltered
// .global object_getFirstPanelInDirectionFiltered
// .global sub_800D120
// .global object_getPanelRegion
// .global object_getEdgePanelMatchingRow
// .global sub_800D4D0
// .global sub_800D58C
// .global sub_800D5F0
// .global sub_800D618
// .global sub_800D668
// .global sub_800E24C
// .global sub_800E258
// .global object_getCoordinatesForPanels // (int a1, int a2) -> (int n1, int n2)
// .global object_setCoordinatesFromPanels // () -> void
// .global object_setPanelsFromCoordinates
// .global object_getEnemyDirection
// .global object_getAllianceDirection
// .global object_getFrontDirection // () -> int
// .global object_getFlipDirection // (int a1, int a2) -> int
// .global object_subtractHP
// .global object_addHP
// .global sub_800E2FC
// .global sub_800E3BE
// .global object_getFlip // () -> int
// .global object_canMove
// .global sub_800E5FC
// .global sub_800E6E8
// .global sub_800E708
// .global object_setCounterTime
// .global sub_800EA22
// .global sub_800EA90
// .global sub_800EABA
// .global sub_800EAC4
// .global sub_800EADA
// .global object_setInvulnerableTime
// .global sub_800EB08
// .global sub_800EB6C
// .global object_getEnemyByNameRange
// .global sub_800EC48

	.include "asm/asm00_2.inc"
// .global sub_800ED90
// .global enemy_getStruct1
// .global enemy_getStruct2
// .global sub_800F26C
// .global sub_800F29C
// .global sub_800F2AA
// .global object_setAnimation
// .global sub_800F2C6
// .global sub_800F2FC
// .global sub_800F322
// .global sub_800F46C
// .global sub_800F486
// .global sub_800F49E
// .global setFieldBattleObject_800F614
// .global sub_800F656
// .global sub_800F672
// .global sub_800F884
// .global sub_800F898
// .global sub_800F8B0
// .global sub_800F8CE
// .global sub_800F90E
// .global sub_800F964
// .global sub_800F998
// .global sub_800FA20
// .global sub_800FA54
// .global sub_800FAAC
// .global sub_800FAF6
// .global sub_800FB54
// .global sub_800FC30
// .global sub_800FC7C
// .global sub_800FC9E
// .global sub_800FCFC
// .global object_setDefaultCounterTime
// .global sub_800FE12
// .global sub_800FE28
// .global sub_800FE36
// .global sub_800FE52
// .global SetAIData_Unk_44_Flag
// .global ClearAIData_Unk_44_Flag
// .global GetAIData_Unk_44_Flag
// .global sub_8010004
// .global sub_8010018
// .global sub_801002C
// .global sub_80100EC
// .global sub_801011A
// .global sub_80101AE
// .global sub_80101C4
// .global sub_80101D4
// .global sub_8010300
// .global sub_8010312
// .global sub_801031C
// .global sub_801032C
// .global sub_8010332
// .global sub_80103A8
// .global sub_80103BC
// .global sub_80103F8
// .global sub_8010474
// .global sub_8010488
// .global sub_80104E0
// .global sub_801050C
// .global sub_801056A
// .global sub_80105F2
// .global sub_8010660
// .global sub_80106C0
// .global sub_8010740
// .global sub_80107C0
// .global sub_80107D4
// .global sub_8010820
// .global sub_8010DD0
// .global sub_8010DF6
// .global sub_8011020
// .global sub_8011044
// .global sub_8011420
// .global sub_8011450
// .global sub_8011504
// .global sub_801155A
// .global sub_801156A
// .global object_applyDamage
// .global sub_801164C
// .global object_setAttack0
// .global object_setAttack1
// .global object_setAttack2
// .global object_setAttack3
// .global object_setAttack4
// .global sub_80116AE
// .global sub_80116D8
// .global object_exitAttackState
// .global sub_801171C
// .global sub_8011764
// .global sub_801177A
// .global sub_8011790
// .global sub_80117A4
// .global sub_801265A
// .global sub_80126E4
// .global sub_8012792
// .global sub_8012956
// .global sub_801299C
// .global sub_8012E74
// .global sub_8012EA8
// .global GetPlayerBattleVarsAddr // (int idx) -> void*
// .global GetPlayerBattleVarByte
// .global SetPlayerBattleVarByte_AllianceFromBattleObject
// .global SetPlayerBattleVarHword_AllianceFromBattleObject
// .global GetPlayerBattleVarByte_AllianceFromBattleObject
// .global sub_80139C4
// .global sub_8013CC4
// .global sub_8013DA0
// .global sub_8013FAE
// .global sub_80142C2
// .global sub_801443C
// .global sub_8014446
// .global sub_80144C0
// .global sub_8015AA6
// .global sub_8015B00
// .global sub_8015B54
// .global sub_8015BEC
// .global sub_8015C48
// .global sub_8015C94
// .global sub_8015D80
// .global GetRandomRelativePanelFiltered
// .global sub_8016004
// .global sub_8016218
// .global sub_801632C
// .global sub_8016380
// .global sub_80165B8
// .global sub_80165C2
// .global sub_80166AE
// .global sub_80169BE
// .global sub_8016B02
// .global sub_8016B36
// .global sub_8016B72
// .global sub_8016C4E
// .global object_genericDestroy
// .global sub_8016C9C
// .global sub_8016CE8
// .global sub_8016E64
// .global sub_8016F56
// .global sub_80170C4
// .global sub_80171A6
// .global sub_80172F0
// .global sub_80173F4
// .global sub_80174FE
// .global sub_80175B8
// .global sub_8017688
// .global sub_8017768
// .global sub_8017888
// .global sub_80178B6
// .global sub_8017CC0
// .global sub_8017E26
// .global sub_80182B4
// .global sub_8018810
// .global sub_8018842
// .global object_createCollisionData
// .global sub_80198CE
// .global byte_80198F4
// .global byte_80198F4
// .global byte_80199B6
// .global byte_80199B6
// .global byte_80199F5
// .global byte_80199F5
// .global PanelOffsetListsPointerTable
// .global off_8019BE0
// .global byte_8019C34
// .global sub_8019F86
// .global sub_8019F8C
// .global object_setupCollisionData
// .global object_removeCollisionData
// .global object_presentCollisionData
// .global object_updateCollisionPanels
// .global object_setCollisionPanelsToCurrent
// .global object_clearCollisionRegion // () -> void
// .global object_setCollisionRegion
// .global sub_801A082
// .global object_spawnCollisionEffect
// .global sub_801A100
// .global object_setCollisionHitEffect
// .global sub_801A146
// .global object_setFlag1 // (int a1) -> void
// .global object_clearFlag // (int bitfield) -> void
// .global object_getFlag // () -> int
// .global object_setFlag2
// .global object_clearFlag2
// .global object_getFlag2
// .global object_setCollisionStatusEffect1
// .global sub_801A264
// .global sub_801A4D0
// .global sub_801A4DC
// .global sub_801A66C
// .global sub_801A67E
// .global sub_801A7CC
// .global sub_801A9B8
// .global sub_801AA48
// .global sub_801AAC0
// .global sub_801AB40
// .global sub_801ABB8
// .global sub_801AC6C
// .global sub_801AD12
// .global sub_801AD6A
// .global sub_801AD9E
// .global sub_801ADFA
// .global sub_801AF44
// .global sub_801B1C4
// .global sub_801B394
// .global sub_801B4D4
// .global sub_801B610
// .global sub_801B750
// .global sub_801B878
// .global object_reservePanel
// .global object_removePanelReserve
// .global object_updateSprite
// .global object_updateSpriteTimestop
// .global sub_801BC24
// .global sub_801BC64
// .global object_updateSpritePaused
// .global sub_801BCD0
// .global sub_801BCF4
// .global sub_801BD3C
// .global AddRandomVarianceToTwoCoords
// .global sub_801BE04
// .global nullsub_10
// .global sub_801BE2A
// .global sub_801BED6
// .global sub_801DA48
// .global sub_801DACC
// .global sub_801DBD4
// .global sub_801DC7C
// .global sub_801DCCC
// .global sub_801DD34
// .global sub_801DF8C
// .global sub_801E658
// .global sub_801EB18

	.include "data/dat01.inc"
// .global byte_80203EA
// .global byte_8020600
// .global byte_80211A0
// .global byte_8021300
// .global byte_802136D

	.include "asm/asm02.inc"
// .global getChip8021DA8 // (int chip_idx) -> ChipData*

	.include "asm/asm03_0.inc"
// .global ho_8026554
// .global sub_802B6EC
// .global sub_802B734
// .global off_802CCB4
// .global off_802CD5C
// .global sub_802CDE6
// .global sub_802CE30
// .global sub_802CE78
// .global sub_802CE8A
// .global sub_802CEA6
// .global GetBattleMode
// .global GetBattleEffects // () -> int
// .global GetBattlePanelColumnPattern
// .global sub_802D322
// .global sub_802D4C6
// .global sub_802DD2A
// .global sub_802E032
// .global sub_802E04E
// .global sub_802E070
// .global sub_802E1BE
// .global sub_802E4B8
// .global sub_802E4E4
// .global sub_802EF5C
// .global sub_802F068
// .global sub_80302A8
// .global loc_8030604

	.include "asm/chatbox.inc"
// .global chatbox_runScript // (void *scripts, u8 scriptOffIdx) -> void
// .global chatbox_check_eFlags2009F38

	.include "asm/asm03_2.inc"
// .global sub_80465BC
// .global sub_80465F8 // () -> void
// .global sub_8046664 // () -> void
// .global sub_8046670

	.include "data/dat07.inc"
// .global byte_805FF01

	.include "data/dat13.inc"
// .global byte_8070605

	.include "data/dat20.inc"
// .global byte_8080404
// .global byte_8080C0C

	.include "asm/asm21.inc"
// .global dword_8081010

	.include "data/dat28.inc"
// .global byte_80A0C10
// .global byte_80A0C12

	.include "data/dat31.inc"
// .global byte_810C35C
// .global byte_810C364
// .global off_810C6F0
// .global byte_810C8CC
// .global byte_810C8D4
// .global off_810CD60
// .global byte_810D008
// .global byte_810D010
// .global off_810D0F4
// .global byte_810D16C
// .global byte_810D174
// .global off_810D554
// .global byte_810D6F8
// .global byte_810D700
// .global off_810D910
// .global sub_810D940

	.include "asm/asm32.inc"
// .global sub_810D98C
// .global byte_810DD10
// .global byte_810DD18
// .global off_810E120
// .global sub_810E2A6
// .global sub_810E336
// .global sub_810E340
// .global sub_810E386
// .global byte_810E3E8
// .global byte_810E3F0
// .global off_810E7B0
// .global sub_810E81E
// .global sub_810E854
// .global byte_810EC80
// .global byte_810EC88
// .global off_810F010
// .global sub_810F040
// .global sub_810F090
// .global byte_810F200
// .global byte_810F208
// .global off_810F39C
// .global sub_810F3F8
// .global byte_810F4E4
// .global byte_810F4EC
// .global sub_810FA4C
// .global off_810FCE0
// .global sub_81100B0
// .global sub_81100E2
// .global sub_8110254
// .global byte_8110290
// .global byte_8110298
// .global off_81104D4
// .global sub_8110546
// .global sub_811060A
// .global byte_8110628
// .global byte_8110630
// .global off_8110DC0
// .global sub_8110E76
// .global byte_8111130
// .global byte_8111138
// .global off_8111330
// .global sub_8111816
// .global sub_8111846
// .global byte_811190C
// .global byte_8111914
// .global off_8111DC0
// .global byte_8111FF8
// .global byte_8112000
// .global off_81121F0
// .global byte_81126DC
// .global byte_81126E4
// .global off_81129A0
// .global sub_81129EE
// .global byte_8112B94
// .global byte_8112B9C
// .global off_8113078
// .global byte_811323C
// .global byte_8113244
// .global off_81135CC
// .global sub_8113626
// .global byte_8113754
// .global byte_811375C
// .global off_8113D50
// .global byte_8113DC0
// .global sub_8114170
// .global byte_81143C8
// .global byte_81143D0
// .global off_8114710
// .global sub_8114DF2
// .global sub_8114E30
// .global sub_8114F52
// .global sub_8114F6A
// .global sub_8115098
// .global byte_81150AC
// .global byte_81150B4
// .global off_81154F0
// .global byte_8115704
// .global byte_811570C
// .global off_8115950
// .global sub_81159B0
// .global sub_81159DC
// .global sub_8115BB0
// .global byte_8115BEC
// .global byte_8115BF4
// .global off_8115DE0
// .global sub_811627A
// .global sub_81162AA
// .global byte_81162F8
// .global byte_8116300
// .global off_81163F0
// .global sub_8116414
// .global sub_81165A4
// .global byte_81165BC
// .global byte_81165C4
// .global off_81166B0
// .global sub_81166D4
// .global sub_8116878

	.include "data/dat38_85.inc"
// .global dword_86E55FC
// .global byte_86E56FC

	.include "data/dat38_86.inc"
// .global byte_8736D74


/* Undeclared Symbols */
// .equ timer_2000000, 0x2000000
// .equ unk_200150C, 0x200150C
// .equ eBattleObjectsLinkedListStart, 0x2009380
// .equ dword_2009384, 0x2009384
// .equ eBattleObjectsLinkedListSentinel, 0x2009AB0
// .equ unk_2010000, 0x2010000
// .equ unk_2010108, 0x2010108
// .equ unk_2010208, 0x2010208
// .equ unk_2010308, 0x2010308
// .equ byte_2010408, 0x2010408
// .equ off_2010508, 0x2010508
// .equ off_2010608, 0x2010608
// .equ off_2010708, 0x2010708
// .equ off_2010808, 0x2010808
// .equ off_2010908, 0x2010908
// .equ off_2010A08, 0x2010A08
// .equ off_2010B08, 0x2010B08
// .equ 0x202070C, 0x202070C
// .equ byte_2030204, 0x2030204
// .equ byte_2030405, 0x2030405
// .equ byte_2036740, 0x2036740
// .equ byte_203C960, 0x203C960
// .equ byte_203C961, 0x203C961
// .equ word_203C962, 0x203C962
// .equ dword_203C964, 0x203C964
// .equ byte_203C968, 0x203C968
// .equ dword_203CFB0, 0x203CFB0
// .equ dword_203CFB4, 0x203CFB4
// .equ dword_203CFB8, 0x203CFB8
// .equ dword_203CFBC, 0x203CFBC
// .equ dword_203CFC0, 0x203CFC0
// .equ byte_203CFC4, 0x203CFC4
// .equ iPallete3001750, 0x3001750
// .equ iPallete3001B60, 0x3001B60
// .equ 0x3003D0C, 0x3003D0C
	.equ LCDControl, 0x4000000
	.equ BG2Rotation_ScalingParameterA_dx_, 0x4000020

	.endif // INC_ASM_ASM31
