.ifndef INC_ASM_ASM31
.equ INC_ASM_ASM31, 0

/* Public Symbols */
.global sub_80B81EC
.global sub_80B8210
.global sub_80B84EC
.global sub_80B85E0
.global sub_80B88D0
.global sub_80B8A0A
.global sub_80B8A18
.global sub_80B8CD8
.global sub_80B8EA0
.global sub_80B9014
.global loc_80B9078
.global sub_80B921A
.global loc_80B92B8
.global sub_80B9432
.global loc_80B94BC
.global sub_80B9750
.global loc_80B97C0
.global sub_80B999A
.global loc_80B99C0
.global sub_80B9B6E
.global loc_80B9C14
.global sub_80B9F0E
.global loc_80B9F44
.global sub_80BA1B0
.global sub_80BA364
.global sub_80BA660
.global loc_80BA708
.global sub_80BA920
.global sub_80BAA8C
.global sub_80BAE16
.global sub_80BAF50
.global sub_80BB2A0
.global loc_80BB608
.global sub_80BB7F6
.global loc_80BB914
.global sub_80BBAC6
.global loc_80BBB98
.global sub_80BBDE8
.global loc_80BBF0C
.global sub_80BC0DA
.global loc_80BC17C
.global loc_80BC4FC
.global loc_80BC650
.global sub_80BC844
.global loc_80BC87C
.global sub_80BC998
.global sub_80BC9BE
.global loc_80BCA04
.global sub_80BCB12
.global loc_80BCB50
.global loc_80BCD14
.global loc_80BD388
.global sub_80BD9A2
.global loc_80BDBA4
.global sub_80BE3E8
.global loc_80BE4D8
.global sub_80BE6D8
.global loc_80BE798
.global sub_80BF160
.global loc_80BF260
.global sub_80BF6AE
.global loc_80BF6EC
.global sub_80BFCD0
.global loc_80BFDFC
.global loc_80BFF68
.global loc_80C0178
.global loc_80C0334
.global loc_80C04AC
.global loc_80C065C
.global loc_80C07BC
.global loc_80C0B0E
.global sub_80C0DD8
.global loc_80C0E04
.global loc_80C0F6C
.global loc_80C1008
.global sub_80C10E8
.global loc_80C11AC
.global sub_80C1570
.global sub_80C1A10
.global loc_80C2138
.global loc_80C26F0
.global sub_80C2A4C
.global loc_80C2A78
.global sub_80C2F96
.global loc_80C3000
.global loc_80C3218
.global loc_80C34E0
.global loc_80C3734
.global loc_80C3970
.global sub_80C3B30
.global loc_80C3CE8
.global sub_80C3E98
.global loc_80C3EE0
.global sub_80C4038
.global sub_80C4072
.global loc_80C40D8
.global sub_80C41D8
.global sub_80C4204
.global loc_80C4348
.global sub_80C44A8
.global sub_80C44C8
.global sub_80C44D2
.global loc_80C4530
.global sub_80C468C
.global sub_80C46B0
.global sub_80C46B6
.global sub_80C46C0
.global loc_80C46FC
.global loc_80C4828
.global loc_80C4B18
.global sub_80C4C12
.global sub_80C4C3A
.global loc_80C4E58
.global sub_80C4FFE
.global loc_80C50B8
.global loc_80C51AC
.global loc_80C52B0
.global sub_80C536A
.global sub_80C53A6
.global loc_80C53C0
.global loc_80C55B0
.global sub_80C579E
.global sub_80C57C0
.global sub_80C59F6
.global loc_80C5A34
.global sub_80C5B76
.global loc_80C5BB0
.global loc_80C5DDC
.global loc_80C5F60
.global loc_80C60A8
.global loc_80C6280
.global loc_80C6414
.global loc_80C6580
.global loc_80C67F8
.global loc_80C6946
.global loc_80C6B40
.global loc_80C6DCC
.global loc_80C7074
.global loc_80C71A4
.global loc_80C740C
.global loc_80C793C
.global loc_80C7C18
.global loc_80C7D78
.global sub_80C7F20
.global loc_80C7F40
.global loc_80C8098
.global loc_80C81CC
.global loc_80C8388
.global loc_80C853C
.global loc_80C86D8
.global loc_80C882C
.global loc_80C8AA4
.global loc_80C8C74
.global loc_80C8E08
.global loc_80C8FFC
.global loc_80C91A0
.global loc_80C93CC
.global sub_80C96A0
.global locret_80C980C
.global locret_80C9814
.global loc_80C9824
.global loc_80C9BC4
.global loc_80C9D00
.global loc_80C9F78
.global loc_80CA2A8
.global loc_80CA544
.global loc_80CA6B8
.global loc_80CA938
.global loc_80CAB68
.global loc_80CAD28
.global loc_80CAEF0
.global loc_80CB0DC
.global loc_80CB284
.global sub_80CB49C
.global loc_80CB6F8
.global loc_80CB900
.global loc_80CBB44
.global loc_80CC044
.global sub_80CC0B2
.global sub_80CC0E8
.global loc_80CC4C4
.global loc_80CC5A8
.global loc_80CC76C
.global loc_80CC944
.global loc_80CCA40
.global loc_80CCC48
.global loc_80CCD70
.global sub_80CCFDC
.global loc_80CD2EC
.global loc_80CD4EC
.global sub_80CD8EC
.global loc_80CDD44
.global loc_80CDF84
.global loc_80CE118
.global loc_80CE24C
.global sub_80CE530
.global loc_80CE70C
.global loc_80CE81C
.global loc_80CEB00
.global sub_80CEE78
.global sub_80CF0D0
.global sub_80CF3BE
.global loc_80CF5C8
.global loc_80CF7F0
.global loc_80CF954
.global sub_80CFBC4
.global loc_80CFC08
.global loc_80CFCF8
.global loc_80CFEC4
.global loc_80D00A0
.global loc_80D0268
.global loc_80D0394
.global loc_80D0500
.global loc_80D0610
.global loc_80D07CC
.global loc_80D0AA8
.global loc_80D0D7C
.global loc_80D0F8C
.global loc_80D1218
.global loc_80D1514
.global loc_80D17A4
.global loc_80D18D8
.global loc_80D1A08
.global loc_80D1B48
.global loc_80D1C20
.global sub_80D1EE8
.global sub_80D2034
.global sub_80D2290
.global sub_80D2430
.global sub_80D2460
.global sub_80D25D4
.global loc_80D2A94
.global loc_80D2BDC
.global loc_80D2EBC
.global loc_80D30D0
.global sub_80D34CC
.global loc_80D385C
.global sub_80D39BC
.global loc_80D4088
.global loc_80D4440
.global sub_80D464A
.global loc_80D46B8
.global loc_80D4A28
.global loc_80D4B68
.global loc_80D4C84
.global sub_80D4FA6
.global loc_80D5028
.global loc_80D5138
.global loc_80D535C
.global loc_80D5580
.global loc_80D5740
.global loc_80D58B4
.global loc_80D5ABC
.global loc_80D5C48
.global loc_80D5D54
.global loc_80D5F08
.global loc_80D622C
.global loc_80D655C
.global loc_80D67EC
.global loc_80D6924
.global loc_80D6A20
.global sub_80D6B78
.global loc_80D6BD4
.global loc_80D6D80
.global sub_80D6EE0
.global loc_80D7068
.global loc_80D7278
.global loc_80D7400
.global loc_80D75FC
.global loc_80D7ACC
.global loc_80D7DE4
.global loc_80D807C
.global loc_80D825C
.global sub_80D8400
.global sub_80D842E
.global loc_80D8444
.global sub_80D85F0
.global loc_80D8620
.global loc_80D879C
.global loc_80D88E0
.global loc_80D8C5C
.global sub_80D8D5A
.global loc_80D8E10
.global loc_80D8FC4
.global loc_80D9154
.global loc_80D9350
.global loc_80D954C
.global loc_80D96A4
.global loc_80D984C
.global sub_80D99EC
.global loc_80D9A50
.global loc_80D9D4C
.global loc_80DA050
.global loc_80DA470
.global loc_80DA5FC
.global loc_80DA80C
.global sub_80DA9DC
.global sub_80DA9FE
.global loc_80DAA28
.global loc_80DACE4
.global loc_80DAE94
.global loc_80DB0E4
.global loc_80DB304
.global sub_80DB570
.global sub_80DB6A4
.global loc_80DB8CC
.global loc_80DB994
.global loc_80DBB40
.global loc_80DBCEC
.global sub_80DBEE6
.global loc_80DC0E8
.global loc_80DC260
.global loc_80DC3F8
.global loc_80DC4FC
.global loc_80DC5F8
.global loc_80DC70C
.global loc_80DCB1C
.global loc_80DCCD4
.global loc_80DCE38
.global loc_80DCEF4
.global loc_80DD0AC
.global loc_80DD34C
.global loc_80DD764
.global loc_80DD940
.global loc_80DDA84
.global loc_80DDC10
.global loc_80DDDF0
.global loc_80DE000
.global loc_80DE13C
.global loc_80DE404
.global loc_80DE7F4
.global loc_80DEA7C
.global loc_80DEE60
.global loc_80DF0A4
.global loc_80DF188
.global loc_80DF328
.global loc_80DF4FC
.global loc_80DF90C
.global sub_80DFAD6
.global loc_80DFC38
.global loc_80DFE40
.global sub_80DFF84
.global loc_80DFFB8
.global off_80E0408
.global loc_80E0548
.global sub_80E05F6
.global loc_80E0638
.global sub_80E06F8
.global loc_80E0710
.global sub_80E07E0
.global byte_80E083F
.global loc_80E0844
.global sub_80E08C4
.global locret_80E08E0
.global loc_80E08FC
.global sub_80E09EE
.global loc_80E0AD4
.global sub_80E0D98
.global loc_80E0DF0
.global sub_80E0F02
.global loc_80E0FA0
.global loc_80E10A4
.global sub_80E11E0
.global loc_80E11FC
.global loc_80E1520
.global sub_80E1620
.global sub_80E164A
.global sub_80E1662
.global loc_80E17E8
.global sub_80E192C
.global loc_80E19BC
.global sub_80E1A6A
.global sub_80E1A86
.global loc_80E1A90
.global loc_80E1B48
.global loc_80E1CF8
.global sub_80E1D7A
.global loc_80E1D88
.global loc_80E1E4C
.global loc_80E2080
.global loc_80E21D8
.global loc_80E225C
.global loc_80E23A4
.global sub_80E24B8
.global loc_80E24E4
.global sub_80E2566
.global loc_80E25D0
.global loc_80E28A8
.global loc_80E2AE8
.global sub_80E2B5A
.global loc_80E2B7C
.global loc_80E2CA4
.global sub_80E2D76
.global loc_80E2E34
.global sub_80E2F24
.global sub_80E2F56
.global loc_80E309C
.global sub_80E3128
.global loc_80E3150
.global loc_80E31D8
.global sub_80E3242
.global loc_80E32B8
.global loc_80E342C
.global sub_80E349E
.global loc_80E34C0
.global sub_80E353E
.global loc_80E35A4
.global loc_80E3728
.global sub_80E37D2
.global loc_80E37F4
.global loc_80E39A0
.global loc_80E3AB8
.global sub_80E3B50
.global loc_80E3B70
.global loc_80E3D68
.global loc_80E3FD0
.global loc_80E40EC
.global sub_80E4164
.global loc_80E4188
.global sub_80E4288
.global sub_80E4344
.global loc_80E440C
.global loc_80E4634
.global sub_80E46B6
.global loc_80E46D8
.global loc_80E47B4
.global loc_80E4848
.global loc_80E4910
.global sub_80E49A2
.global loc_80E4A1C
.global sub_80E4B34
.global loc_80E4CB8
.global sub_80E4D8A
.global sub_80E4DA2
.global loc_80E4DB0
.global loc_80E50C4
.global loc_80E5244
.global sub_80E5368
.global sub_80E5410
.global sub_80E544C
.global loc_80E5470
.global loc_80E55C0
.global loc_80E5710
.global loc_80E5944
.global sub_80E59C6
.global loc_80E59E8
.global locret_80E5B60
.global sub_80E5B62
.global sub_80E5C2C
.global loc_80E5D44
.global loc_80E5E00
.global sub_80E5EA8
.global loc_80E5ECC
.global sub_80E5F78
.global loc_80E5F9C
.global sub_80E5FBC
.global loc_80E6088
.global loc_80E6254
.global loc_80E6480
.global sub_80E64E8
.global loc_80E655C
.global loc_80E6758
.global sub_80E67E6
.global loc_80E680C
.global loc_80E689C
.global loc_80E6A90
.global loc_80E6BDC
.global loc_80E6E44
.global loc_80E6F88
.global sub_80E7008
.global loc_80E702C
.global sub_80E70A6
.global loc_80E70C8
.global loc_80E71C4
.global sub_80E723E
.global loc_80E7260
.global sub_80E7464
.global sub_80E7486
.global loc_80E74D4
.global sub_80E7546
.global loc_80E7568
.global sub_80E7600
.global loc_80E7624
.global sub_80E76D4
.global loc_80E76F8
.global loc_80E7788
.global loc_80E78BC
.global loc_80E795C
.global loc_80E7ACC
.global loc_80E7BFC
.global sub_80E7CA8
.global loc_80E7CCC
.global loc_80E7DC4
.global loc_80E7E9C
.global sub_80E7F16
.global loc_80E7F38
.global sub_80E7FBA
.global loc_80E7FDC
.global sub_80E8058
.global loc_80E807C
.global sub_80E8124
.global loc_80E8138
.global sub_80E81B4
.global loc_80E81D8
.global loc_80E8268
.global loc_80E83B8
.global loc_80E857C
.global loc_80E8688
.global loc_80E8794
.global loc_80E88A0
.global loc_80E8938
.global loc_80E8A60
.global sub_80E8ADC
.global loc_80E8B00
.global sub_80E8BC0
.global loc_80E8DF0
.global loc_80E8EE0
.global loc_80E8FE0
.global sub_80E90FE
.global loc_80E9120
.global sub_80E91B8
.global loc_80E91E4
.global sub_80E92EE
.global loc_80E9310
.global sub_80E943E
.global loc_80E9460
.global loc_80E9570
.global sub_80E979C
.global loc_80E97F0
.global dword_80E98C0
.global sub_80E996E
.global loc_80E9994
.global loc_80E9AF0
.global sub_80E9BDC
.global loc_80E9C88
.global loc_80E9DF0
.global loc_80EA010
.global sub_80EA11C
.global loc_80EA14C
.global loc_80EA258
.global loc_80EA364
.global sub_80EA438
.global off_80EA814
.global loc_80EA8D8
.global loc_80EA9A0
.global loc_80EAA04
.global loc_80EAA68
.global loc_80EAACC
.global loc_80EAB30
.global loc_80EAB94
.global loc_80EABF8
.global off_80EAC60
.global loc_80EAD9C
.global loc_80EB04C
.global loc_80EB234
.global loc_80EE90C
.global loc_80EEA3C
.global loc_80EED56
.global off_80F24D8
.global off_80F253C
.global off_80F2604
.global off_80F2668
.global off_80F26CC
.global off_80F2730
.global off_80F2794
.global off_80F27F8
.global byte_80F285C
.global dword_80F28F0
.global dword_80F2A54
.global dword_80F390C
.global dword_80F47D4
.global dword_80F5838
.global dword_80F6394
.global dword_80F757C
.global dword_80F8334
.global dword_80F8EEC
.global dword_80F9C80
.global dword_80FACDC
.global dword_80FB8E0
.global dword_80FD044
.global dword_80FDCF0
.global dword_80FE7D0
.global sub_80FF668
.global byte_8100315
.global off_81090D0
.global off_8109150
.global byte_8109250
.global byte_81092D0
.global byte_8109350
.global byte_81093D0
.global byte_8109450
.global byte_81094D0
.global byte_8109550
.global sub_8109630
.global sub_8109660
.global sub_81096FA
.global sub_8109708
.global sub_810971A
.global sub_81097B4
.global sub_81097BA
.global loc_81097D6
.global sub_81097DC
.global sub_8109804
.global sub_8109952
.global loc_8109974
.global dword_8109AA4
.global dword_8109BFC
.global dword_810A2EC
.global dword_810A86C
.global dword_810AE70
.global byte_810B7B8
.global dword_810BEF8


/* External Symbols */
.include "asm/start.inc"
// .global start_
// .global off_80001F4

.include "asm/asm00_0.inc"
// .global sound_play // () -> void
// .global CpuSet_ZeroFillHalfword
// .global CpuSet_ZeroFillWord // (void *memBlock, int size) -> void
// .global copyBytes // (u8 *src, u8 *dest, int byteCount) -> void
// .global loc_8000AC8
// .global sub_8000C72
// .global sub_8000DE0
// .global calcAngle_800117C
// .global sub_80011A0
// .global sub_800120E
// .global sub_8001330
// .global sub_8001382
// .global sub_800139A
// .global change_20013F0_800151C // () -> int
// .global sub_8001532
// .global sub_8002378
// .global sub_800239A

.include "asm/sprite.inc"
// .global sprite_loadAnimationData // () -> void
// .global sprite_update
// .global sprite_load // (int a1, int a2, int a3) ->
// .global sprite_decompress
// .global sub_8002C7A
// .global sprite_setMosaicScalingParameters
// .global sub_8002CCE
// .global sprite_getMosaicScalingParameters
// .global sprite_setPallete // (int pallete) -> void
// .global sprite_getPallete
// .global sprite_setAnimation // (u8 a1) -> void
// .global sprite_forceWhitePallete
// .global loc_8002DB4

.include "asm/asm00_1.inc"
// .global sub_8002DC8
// .global sub_8002DD8
// .global sub_8002DEA
// .global sub_8002E14
// .global sub_8002E3C
// .global sub_8002E52
// .global sub_8002EAC
// .global sub_8002ED0
// .global sub_8002EDC
// .global sub_8002EE8
// .global loc_8002F02
// .global sub_8002F3E
// .global sub_8002F5C
// .global sub_8002F7E
// .global sub_8002F90 // () -> void
// .global sub_8002FA6
// .global sub_8003006
// .global sub_800302A
// .global sub_80030BA
// .global object_spawnType1
// .global object_spawnType3
// .global sub_8003374
// .global object_spawnType4
// .global sub_80033E4
// .global object_freeMemory
// .global sub_800362C
// .global engine_setScreeneffect // (int a1, int a2) -> void
// .global engine_isScreeneffectAnimating // () -> zf
// .global byte_80065E0
// .global byte_8006660
// .global battle_isPaused
// .global battle_isTimeStop
// .global sub_800A152
// .global battle_isBattleOver
// .global battle_setFlags
// .global battle_clearFlags
// .global battle_getFlags
// .global sub_800A704
// .global sub_800A772
// .global sub_800A8F8
// .global battle_networkInvert
// .global sub_800AA92
// .global sub_800AB3A
// .global sub_800AB46
// .global sub_800ABC6
// .global sub_800AE54
// .global sub_800AE90
// .global sub_800AF34
// .global sub_800B916
// .global sub_800B94C
// .global sub_800B97E
// .global sub_800B9B0
// .global sub_800BA8A
// .global sub_800BBA8
// .global sub_800BC88
// .global sub_800BCC0

.include "asm/object.inc"
// .global object_timefreezeEnd
// .global sub_800BDB2
// .global sub_800BF16
// .global sub_800BF5C
// .global object_getPanelParameters
// .global sub_800C90A
// .global object_crackPanel
// .global object_crackPanelDup1
// .global object_breakPanel
// .global object_breakPanel_dup1
// .global object_breakPanel_dup2
// .global object_breakPanel_dup3
// .global object_breakPanelLoud
// .global object_panel_setPoison
// .global object_highlightPanel
// .global object_setPanelType
// .global object_setPanelAlliance
// .global object_setPanelAllianceTimerLong
// .global object_setPanelAllianceTimerShort
// .global object_setPanelTypeBlink
// .global object_isCurrentPanelValid
// .global object_isValidPanel
// .global object_checkPanelParameters
// .global object_isCurrentPanelSolid
// .global object_isPanelSolid
// .global object_highlightCurrentCollisionPanels
// .global object_highlightPanelRegion
// .global object_highlightPanelRegionBlue
// .global object_hidePanel
// .global object_getPanelsExceptCurrentFilterred
// .global sub_800CEA0
// .global sub_800CF14
// .global sub_800CF42
// .global sub_800CF70
// .global sub_800CFA6
// .global sub_800CFDC
// .global sub_800D012
// .global sub_800D06A
// .global sub_800D086
// .global sub_800D0BC
// .global sub_800D120
// .global sub_800D3FE
// .global sub_800D4C2
// .global sub_800D4D0
// .global sub_800D58C
// .global sub_800D5F0
// .global sub_800D618
// .global sub_800D668
// .global sub_800E24C
// .global sub_800E258
// .global sub_800E276 // (int a1, int a2) -> (int n1, int n2)
// .global sub_800E29C // () -> void
// .global sub_800E2AC
// .global sub_800E2C0
// .global sub_800E2C2
// .global object_getFlipDirection_800E2CA // () -> int
// .global object_getFlipDirection // (int a1, int a2) -> int
// .global object_subtractHP
// .global object_addHP
// .global sub_800E2FC
// .global sub_800E3BE
// .global sub_800E456 // () -> int
// .global object_canMove
// .global sub_800E5FC
// .global sub_800E6E8
// .global sub_800E708
// .global object_setCounterTime
// .global sub_800EA22
// .global sub_800EA90
// .global sub_800EABA
// .global sub_800EAC4
// .global sub_800EADA
// .global object_setInvulnerableTime
// .global sub_800EB08
// .global sub_800EB6C
// .global object_getEnemyByNameRange
// .global sub_800EC48

.include "asm/asm00_2.inc"
// .global sub_800ED90
// .global sub_800F214
// .global sub_800F23C
// .global sub_800F26C
// .global sub_800F29C
// .global sub_800F2AA
// .global sub_800F2B6
// .global sub_800F2C6
// .global sub_800F2FC
// .global sub_800F322
// .global sub_800F46C
// .global sub_800F486
// .global sub_800F49E
// .global sub_800F614
// .global sub_800F656
// .global sub_800F672
// .global sub_800F884
// .global sub_800F898
// .global sub_800F8B0
// .global sub_800F8CE
// .global sub_800F90E
// .global sub_800F964
// .global sub_800F998
// .global sub_800FA20
// .global sub_800FA54
// .global sub_800FAAC
// .global sub_800FAF6
// .global sub_800FB54
// .global sub_800FC30
// .global sub_800FC7C
// .global sub_800FC9E
// .global sub_800FCFC
// .global sub_800FDB6
// .global sub_800FE12
// .global sub_800FE28
// .global sub_800FE36
// .global sub_800FE52
// .global sub_800FFE4
// .global sub_800FFEE
// .global sub_800FFFE
// .global sub_8010004
// .global sub_8010018
// .global sub_801002C
// .global sub_80100EC
// .global sub_801011A
// .global sub_80101AE
// .global sub_80101C4
// .global sub_80101D4
// .global sub_8010300
// .global sub_8010312
// .global sub_801031C
// .global sub_801032C
// .global sub_8010332
// .global sub_80103A8
// .global sub_80103BC
// .global sub_80103F8
// .global sub_8010474
// .global sub_8010488
// .global sub_80104E0
// .global sub_801050C
// .global sub_801056A
// .global sub_80105F2
// .global sub_8010660
// .global sub_80106C0
// .global sub_8010740
// .global sub_80107C0
// .global sub_80107D4
// .global sub_8010820
// .global sub_8010DD0
// .global sub_8010DF6
// .global sub_8011020
// .global loc_8011044
// .global sub_8011420
// .global sub_8011450
// .global sub_8011504
// .global sub_801155A
// .global sub_801156A
// .global sub_801162A
// .global sub_801164C
// .global sub_8011680
// .global sub_8011684
// .global sub_8011688
// .global loc_801168C
// .global loc_8011690
// .global sub_80116AE
// .global sub_80116D8
// .global sub_8011714
// .global loc_801171C
// .global sub_8011764
// .global sub_801177A
// .global sub_8011790
// .global loc_80117A4
// .global sub_801265A
// .global sub_80126E4
// .global sub_8012792
// .global sub_8012956
// .global sub_801299C
// .global sub_8012E74
// .global sub_8012EA8
// .global sub_8013682 // (int idx) -> void*
// .global sub_80136CC
// .global sub_8013754
// .global sub_8013764
// .global sub_8013774
// .global sub_80139C4
// .global sub_8013CC4
// .global sub_8013DA0
// .global sub_8013FAE
// .global sub_80142C2
// .global sub_801443C
// .global sub_8014446
// .global sub_80144C0
// .global sub_8015AA6
// .global sub_8015B00
// .global sub_8015B54
// .global sub_8015BEC
// .global sub_8015C48
// .global sub_8015D80
// .global sub_8015E46
// .global sub_8016004
// .global sub_8016218
// .global sub_801632C
// .global sub_8016380
// .global sub_80165B8
// .global sub_80165C2
// .global sub_80166AE
// .global sub_80169BE
// .global sub_8016B02
// .global sub_8016B36
// .global sub_8016B72
// .global sub_8016C4E
// .global sub_8016C8A
// .global sub_8016C9C
// .global sub_8016CE8
// .global sub_8016E64
// .global sub_8016F56
// .global sub_80170C4
// .global sub_80172F0
// .global sub_80173F4
// .global sub_80174FE
// .global sub_80175B8
// .global sub_8017688
// .global sub_8017768
// .global sub_8017888
// .global sub_80178B6
// .global sub_8017CC0
// .global loc_8017E26
// .global sub_80182B4
// .global sub_8018810
// .global sub_8018842
// .global sub_8019892
// .global sub_80198CE
// .global byte_80198F4
// .global byte_80198F4
// .global byte_80199B6
// .global byte_80199B6
// .global byte_80199F5
// .global byte_80199F5
// .global off_8019B78
// .global off_8019BE0
// .global dword_8019C34
// .global sub_8019F86
// .global sub_8019F8C
// .global sub_8019FB4
// .global sub_801A00E
// .global sub_801A018
// .global sub_801A04C
// .global sub_801A066
// .global sub_801A074 // () -> void
// .global sub_801A07C
// .global sub_801A082
// .global sub_801A0D4
// .global sub_801A100
// .global sub_801A140
// .global sub_801A146
// .global object_setFlag // (int a1) -> void
// .global object_clearFlag // (int bitfield) -> void
// .global object_getFlag // () -> int
// .global sub_801A16C
// .global sub_801A176
// .global sub_801A180
// .global sub_801A258
// .global sub_801A264
// .global sub_801A4D0
// .global sub_801A4DC
// .global sub_801A66C
// .global sub_801A67E
// .global sub_801A7CC
// .global sub_801A9B8
// .global sub_801AA48
// .global sub_801AAC0
// .global sub_801AB40
// .global sub_801ABB8
// .global sub_801AC6C
// .global sub_801AD12
// .global sub_801AD6A
// .global sub_801AD9E
// .global sub_801ADFA
// .global sub_801AF44
// .global sub_801B1C4
// .global sub_801B394
// .global sub_801B4D4
// .global sub_801B610
// .global loc_801B750
// .global loc_801B878
// .global sub_801BB1C
// .global sub_801BB46
// .global sub_801BBAC
// .global sub_801BBF4
// .global sub_801BC24
// .global sub_801BC64
// .global sub_801BCA6
// .global sub_801BCD0
// .global sub_801BCF4
// .global sub_801BD3C
// .global sub_801BDDE
// .global sub_801BE04
// .global nullsub_10
// .global sub_801BE2A
// .global sub_801BED6
// .global sub_801DA48
// .global sub_801DACC
// .global sub_801DBD4
// .global sub_801DC7C
// .global sub_801DCCC
// .global sub_801DD34
// .global sub_801DF8C
// .global sub_801E658
// .global sub_801EB18

.include "data/dat01.inc"
// .global byte_8020600
// .global byte_80211A0
// .global byte_8021300
// .global byte_802136D

.include "asm/asm02.inc"
// .global getChip_8021DA8 // (int chip_idx) -> ChipData*

.include "asm/asm03_0.inc"
// .global ho_8026554
// .global sub_802B6EC
// .global loc_802B734
// .global off_802CCB4
// .global off_802CD5C
// .global sub_802CDE6
// .global sub_802CE30
// .global sub_802CE78
// .global sub_802CE8A
// .global sub_802CEA6
// .global sub_802D234
// .global get_802D246 // () -> int
// .global sub_802D26A
// .global sub_802D322
// .global loc_802D4C6
// .global sub_802DD2A
// .global sub_802E032
// .global sub_802E04E
// .global sub_802E070
// .global sub_802E1BE
// .global sub_802E4B8
// .global sub_802E4E4
// .global sub_802EF5C
// .global sub_802F068
// .global sub_80302A8

.include "asm/chatbox.inc"
// .global chatbox_runScript // (void *scripts, u8 scriptOffIdx) -> void
// .global chatbox_8045F3C

.include "asm/asm03_2.inc"
// .global sub_80465BC
// .global sub_80465F8 // () -> void
// .global sub_8046664 // () -> void
// .global sub_8046670

.include "data/dat20.inc"
// .global dword_8080AC4

.include "asm/asm21.inc"
// .global aSa

.include "data/dat28.inc"
// .global byte_80A0C10

.include "data/dat31.inc"
// .global dword_810C35C
// .global dword_810C35C
// .global dword_810C388
// .global dword_810C388
// .global dword_810CFE8
// .global dword_810CFE8
// .global dword_810D034
// .global dword_810D034
// .global dword_810D198
// .global dword_810D198

.include "asm/asm32.inc"
// .global dword_810DD10
// .global dword_810DD10
// .global sub_810E2A6
// .global sub_810E336
// .global sub_810E340
// .global dword_810E3E8
// .global dword_810E3E8
// .global sub_810E854
// .global dword_810EC80
// .global dword_810EC80
// .global sub_810F090
// .global dword_810F200
// .global dword_810F200
// .global dword_810F22C
// .global dword_810F22C
// .global sub_810FA4C
// .global sub_81100E2
// .global dword_811028C
// .global dword_811028C
// .global sub_811060A
// .global dword_8110610
// .global dword_8110610
// .global dword_8111130
// .global dword_8111130
// .global sub_8111846
// .global dword_811190C
// .global dword_811190C
// .global dword_8111FF8
// .global dword_8111FF8
// .global dword_81126DC
// .global dword_81126DC
// .global sub_81129EE
// .global dword_8112B94
// .global dword_8112B94
// .global dword_8112F2C
// .global dword_8112F2C
// .global dword_8113754
// .global dword_8113754
// .global dword_8113DC0
// .global dword_81143C0
// .global dword_81143C0
// .global sub_8114F52
// .global sub_8114F6A
// .global sub_8115098
// .global dword_81150AC
// .global dword_81150AC
// .global dword_8115704
// .global dword_8115704
// .global sub_81159DC
// .global sub_8115BB0
// .global dword_8115BEC
// .global dword_8115BEC
// .global sub_81162AA
// .global dword_81162F8
// .global dword_81162F8
// .global dword_81165BC
// .global dword_81165BC
// .global sub_8116878

.include "data/dat38_86.inc"
// .global aTuDhr


/* Undeclared Symbols */
// .equ timer_2000000, 0x2000000
// .equ unk_200150C, 0x200150C
// .equ dword_2009380, 0x2009380
// .equ dword_2009384, 0x2009384
// .equ dword_2009AB0, 0x2009AB0
// .equ unk_2010000, 0x2010000
// .equ unk_2010108, 0x2010108
// .equ unk_2010208, 0x2010208
// .equ unk_2010308, 0x2010308
// .equ byte_2010408, 0x2010408
// .equ unk_2010508, 0x2010508
// .equ unk_2010608, 0x2010608
// .equ unk_2010708, 0x2010708
// .equ unk_2010808, 0x2010808
// .equ unk_2010908, 0x2010908
// .equ unk_2010A08, 0x2010A08
// .equ unk_2010B08, 0x2010B08
// .equ unk_202070C, 0x202070C
// .equ byte_2030204, 0x2030204
// .equ byte_2030405, 0x2030405
// .equ byte_2036740, 0x2036740
// .equ byte_203C960, 0x203C960
// .equ byte_203C961, 0x203C961
// .equ word_203C962, 0x203C962
// .equ dword_203C964, 0x203C964
// .equ byte_203C968, 0x203C968
// .equ dword_203CFB0, 0x203CFB0
// .equ dword_203CFB4, 0x203CFB4
// .equ dword_203CFB8, 0x203CFB8
// .equ dword_203CFBC, 0x203CFBC
// .equ dword_203CFC0, 0x203CFC0
// .equ byte_203CFC4, 0x203CFC4
// .equ byte_3001750, 0x3001750
// .equ unk_3001B60, 0x3001B60
// .equ unk_3003D0C, 0x3003D0C
.equ LCDControl, 0x4000000
.equ BG2Rotation_ScalingParameterA_dx_, 0x4000020

.endif // INC_ASM_ASM31
