.ifndef INC_ASM15
.equ INC_ASM15, 0

/* Public Symbols */


/* External Symbols */
.include "asm03_0.inc"
// .global sub_802FF4C // (int a1, int a2) ->
// .global sub_803037C
// .global loc_8030472
// .global sub_80304E8
// .global sub_8030AA4
// .global sub_8034FB8

.include "chatbox.inc"
// .global chatbox_decomp_currMap_gameProgress_803FD08 // () -> int

.include "asm00.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global loc_80019D0
// .global locret_8001AB4
// .global sub_8002354
// .global sub_80028D4
// .global decomp_8002906 // (int a1) -> bool
// .global loc_8003570


/* Undeclared Symbols */
.equ unk_2037800, 0x2037800
.equ off_8074F30, 0x8074F30
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8074FCC, 0x8074FCC
.equ dword_8075614, 0x8075614
.equ dword_8075708, 0x8075708
.equ dword_807575C, 0x807575C
.equ off_8617068, 0x8617068

.endif // INC_ASM15
