.ifndef INC_ASM20
.equ INC_ASM20, 0

/* Public Symbols */


/* External Symbols */
.include "asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global loc_8030472
// .global sub_80304E8
// .global sub_8030AA4
// .global sub_8034FB8

.include "chatbox.inc"
// .global chatbox_uncomp_803FD08

.include "asm00.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global loc_8001A46
// .global locret_8001AB4
// .global sub_8002354
// .global sub_80028D4
// .global sub_8002906
// .global loc_8003570


/* Undeclared Symbols */
.equ unk_2037800, 0x2037800
.equ off_807EA6C, 0x807EA6C
.equ off_807EB18, 0x807EB18
.equ dword_807EEB8, 0x807EEB8
.equ dword_807EFD4, 0x807EFD4
.equ dword_807F1E0, 0x807F1E0
.equ off_8619174, 0x8619174

.endif // INC_ASM20
