.ifndef INC_ASM20
.equ INC_ASM20, 0

/* Public Symbols */


/* External Symbols */
.include "asm03.inc"
// .extern sub_802FF4C
// .extern sub_803037C
// .extern loc_8030472
// .extern sub_80304E8
// .extern sub_8030AA4
// .extern sub_8034FB8
// .extern sub_803FD08

.include "asm00.inc"
// .extern sub_8001778
// .extern sub_8001780
// .extern sub_800195C
// .extern loc_8001A46
// .extern locret_8001AB4
// .extern sub_8002354
// .extern sub_80028D4
// .extern sub_8002906
// .extern loc_8003570


/* Undeclared Symbols */
.equ unk_2037800, 0x2037800
.equ off_807EA6C, 0x807EA6C
.equ off_807EB18, 0x807EB18
.equ dword_807EEB8, 0x807EEB8
.equ dword_807EFD4, 0x807EFD4
.equ dword_807F1E0, 0x807F1E0
.equ off_8619174, 0x8619174

.endif // INC_ASM20
