.ifndef INC_ASM23
.equ INC_ASM23, 0

/* Public Symbols */
.extern dword_8089128


/* External Symbols */
.include "asm03.inc"
// .extern sub_802F110
// .extern sub_802F12C
// .extern sub_802F130
// .extern sub_802F164
// .extern sub_802FE28
// .extern sub_8035408
// .extern sub_8036E44
// .extern sub_8036E78
// .extern sub_8036F98
// .extern sub_8036FAA
// .extern chatbox_runScript
// .extern sub_8045EDC
// .extern sub_8045F3C
// .extern sub_8045F4C
// .extern sub_80468C6
// .extern sub_80468EC

.include "asm37.inc"
// .extern sub_8140A0C
// .extern sub_814216E
// .extern sub_8142190
// .extern sub_814219C
// .extern sub_81421B2
// .extern sub_81421C8
// .extern sub_81421D0
// .extern sub_8142224
// .extern sub_814223E
// .extern sub_81422B4
// .extern sub_81426CE
// .extern sub_81427CE
// .extern sub_8142896
// .extern sub_81428D4
// .extern sub_8142990
// .extern sub_81429CA
// .extern sub_8142A84
// .extern sub_8142ADA
// .extern sub_8142B58
// .extern sub_8142BB6
// .extern sub_8142BF4
// .extern sub_8142BFA
// .extern sub_8142C20
// .extern sub_8142C46

.include "asm28.inc"
// .extern sub_809E13C
// .extern sub_809E2AE
// .extern sub_809E2B8

.include "asm00.inc"
// .extern sound_play
// .extern getPETNaviSelect
// .extern sub_80010D4
// .extern sub_8001158
// .extern off_8001800
// .extern sub_8004822
// .extern sub_80048B2
// .extern sub_8005D88
// .extern engine_setScreeneffect
// .extern engine_isScreeneffectAnimating


/* Undeclared Symbols */
.equ unk_30016F0, 0x30016F0
.equ dword_87DE44C, 0x87DE44C

.endif // INC_ASM23
