.ifndef INC_ASM24
.equ INC_ASM24, 0

/* Public Symbols */


/* External Symbols */
.include "asm03.inc"
// .extern sub_802F110
// .extern sub_802F114
// .extern sub_802F12C
// .extern sub_802F164
// .extern sub_802F168
// .extern loc_802F1AC
// .extern loc_802F200
// .extern sub_80302A8
// .extern sub_8036E90
// .extern sub_8048F88

.include "asm32.inc"
// .extern sub_811EBE0

.include "asm28.inc"
// .extern sub_809E13C
// .extern sub_809E188
// .extern sub_809E1AE
// .extern sub_809E2AE
// .extern sub_809E2B8

.include "asm37.inc"
// .extern sub_81409E4
// .extern sub_8140A00
// .extern sub_8142C94
// .extern sub_8142CB0
// .extern sub_8142CC8
// .extern sub_8142D4C
// .extern sub_8143294

.include "asm00.inc"
// .extern sound_play
// .extern sub_8000672
// .extern CpuSet_ZeroFillWord
// .extern sub_8001172
// .extern sub_800151C
// .extern sub_80047E0
// .extern sub_8005D88


/* Undeclared Symbols */
.equ byte_2000B43, 0x2000B43
.equ byte_2000B44, 0x2000B44
.equ byte_2000B45, 0x2000B45
.equ word_2000B46, 0x2000B46
.equ byte_2000B48, 0x2000B48
.equ byte_2000B49, 0x2000B49
.equ byte_2000B4C, 0x2000B4C
.equ word_2000B52, 0x2000B52
.equ word_2000B54, 0x2000B54
.equ word_2000B5A, 0x2000B5A
.equ word_2000B5C, 0x2000B5C

.endif // INC_ASM24
