.ifndef INC_ASM31
.equ INC_ASM31, 0

/* Public Symbols */
.extern sub_80B8A0A
.extern sub_80BC844
.extern sub_80BC998
.extern sub_80BC9BE
.extern sub_80BCB12
.extern sub_80BE6D8
.extern loc_80C1008
.extern sub_80C10E8
.extern sub_80C4038
.extern sub_80C4072
.extern sub_80C41D8
.extern sub_80C4204
.extern sub_80C44A8
.extern sub_80C44C8
.extern sub_80C468C
.extern sub_80C46B0
.extern sub_80C46C0
.extern sub_80C4C12
.extern sub_80C4C3A
.extern sub_80C4FFE
.extern sub_80C536A
.extern sub_80C53A6
.extern sub_80C579E
.extern sub_80C59F6
.extern sub_80C5B76
.extern sub_80C7F20
.extern sub_80CC0B2
.extern sub_80CFBC4
.extern sub_80D1EE8
.extern sub_80D464A
.extern sub_80D6B78
.extern sub_80D8400
.extern sub_80D842E
.extern sub_80D99EC
.extern sub_80DFAD6
.extern sub_80DFF84
.extern off_80E0408
.extern sub_80E05F6
.extern sub_80E06F8
.extern sub_80E08C4
.extern sub_80E09EE
.extern sub_80E0D98
.extern sub_80E0F02
.extern sub_80E11E0
.extern sub_80E1620
.extern sub_80E164A
.extern sub_80E1662
.extern sub_80E192C
.extern sub_80E1A6A
.extern sub_80E1A86
.extern sub_80E1D7A
.extern sub_80E37D2
.extern sub_80E4B34
.extern sub_80E4D8A
.extern sub_80E4DA2
.extern sub_80E5410
.extern sub_80E544C
.extern sub_80E5B62
.extern sub_80E7486
.extern sub_80E8124
.extern sub_80E90FE
.extern dword_80E98C0
.extern sub_80E996E
.extern sub_80E9BDC
.extern sub_80EA438
.extern off_80EA814
.extern loc_80EA8D8
.extern off_80EAC60
.extern loc_80EAD9C
.extern loc_80EB04C
.extern loc_80EB234
.extern loc_80EE90C
.extern loc_80EEA3C
.extern loc_80EED56
.extern loc_80F0804
.extern off_80F24D8
.extern off_80F253C
.extern dword_80F28F0
.extern dword_80F2A54
.extern dword_80F390C
.extern dword_80F47D4
.extern dword_80F5838
.extern dword_80F6394
.extern dword_80F757C
.extern dword_80F8334
.extern dword_80F8EEC
.extern dword_80F9C80
.extern dword_80FACDC
.extern dword_80FB8E0
.extern dword_80FD044
.extern dword_80FDCF0
.extern dword_80FE7D0
.extern off_81090D0
.extern off_8109150
.extern sub_8109630
.extern sub_8109660
.extern sub_81096FA
.extern sub_8109708
.extern sub_810971A
.extern sub_81097B4
.extern sub_8109804
.extern sub_8109952
.extern loc_8109974
.extern dword_8109AA4
.extern dword_8109BFC
.extern dword_810A2EC
.extern dword_810A86C
.extern dword_810AE70
.extern unk_810B7B8
.extern dword_810BEF8


/* External Symbols */
.include "asm03.inc"
// .extern ho_8026554
// .extern sub_802B6EC
// .extern loc_802B734
// .extern off_802CCB4
// .extern off_802CD5C
// .extern sub_802CDE6
// .extern sub_802CE30
// .extern sub_802CE78
// .extern sub_802CE8A
// .extern sub_802CEA6
// .extern sub_802D234
// .extern sub_802D246
// .extern sub_802D26A
// .extern loc_802D322
// .extern loc_802D4C6
// .extern sub_802DD2A
// .extern sub_802E032
// .extern sub_802E04E
// .extern sub_802E070
// .extern sub_802E1BE
// .extern sub_802E4B8
// .extern sub_802E4E4
// .extern sub_802EF5C
// .extern sub_802F068
// .extern sub_80302A8
// .extern chatbox_runScript
// .extern sub_8045F3C
// .extern sub_80465BC
// .extern sub_80465F8
// .extern sub_8046664
// .extern sub_8046670

.include "start.inc"
// .extern start_
// .extern dword_8000004
// .extern dword_80001F4

.include "asm02.inc"
// .extern sub_8021AA4

.include "asm21.inc"
// .extern aSa

.include "asm32.inc"
// .extern dword_810DD10
// .extern dword_810DD10
// .extern sub_810E2A6
// .extern sub_810E336
// .extern sub_810E340
// .extern dword_810E3E8
// .extern dword_810E3E8
// .extern sub_810E854
// .extern dword_810EC80
// .extern dword_810EC80
// .extern sub_810F090
// .extern dword_810F200
// .extern dword_810F200
// .extern dword_810F22C
// .extern dword_810F22C
// .extern sub_810FA4C
// .extern sub_81100E2
// .extern dword_811028C
// .extern dword_811028C
// .extern sub_811060A
// .extern dword_8110610
// .extern dword_8110610
// .extern dword_8111130
// .extern dword_8111130
// .extern sub_8111846
// .extern dword_811190C
// .extern dword_811190C
// .extern dword_8111FF8
// .extern dword_8111FF8
// .extern dword_81126DC
// .extern dword_81126DC
// .extern sub_81129EE
// .extern dword_8112B94
// .extern dword_8112B94
// .extern dword_8112F2C
// .extern dword_8112F2C
// .extern dword_8113754
// .extern dword_8113754
// .extern dword_8113DC0
// .extern dword_81143C0
// .extern dword_81143C0
// .extern sub_8114F52
// .extern sub_8114F6A
// .extern sub_8115098
// .extern dword_81150AC
// .extern dword_81150AC
// .extern dword_8115704
// .extern dword_8115704
// .extern sub_81159DC
// .extern sub_8115BB0
// .extern dword_8115BEC
// .extern dword_8115BEC
// .extern sub_81162AA
// .extern dword_81162F8
// .extern dword_81162F8
// .extern dword_81165BC
// .extern dword_81165BC
// .extern sub_8116878

.include "asm00.inc"
// .extern sound_play
// .extern sub_80008C0
// .extern CpuSet_ZeroFillWord
// .extern sub_8000920
// .extern loc_8000AC8
// .extern sub_8000C72
// .extern sub_8000DE0
// .extern calcAngle_800117C
// .extern sub_80011A0
// .extern sub_800120E
// .extern sub_8001330
// .extern sub_8001382
// .extern sub_800139A
// .extern sub_800151C
// .extern sub_8001532
// .extern sub_8002378
// .extern sub_800239A
// .extern sprite_loadAnimationData_80026A4
// .extern anim_80026C4
// .extern sub_80026E4
// .extern sub_8002B30
// .extern sub_8002C7A
// .extern loc_8002C7E
// .extern sub_8002CCE
// .extern sub_8002CE0
// .extern sprite_setPallete
// .extern sub_8002D8C
// .extern sprite_setAnimation
// .extern sub_8002DB0
// .extern loc_8002DB4
// .extern sub_8002DC8
// .extern sub_8002DD8
// .extern sub_8002DEA
// .extern sub_8002E14
// .extern sub_8002E3C
// .extern sub_8002E52
// .extern sub_8002EAC
// .extern sub_8002ED0
// .extern sub_8002EDC
// .extern sub_8002EE8
// .extern loc_8002F02
// .extern sub_8002F3E
// .extern sub_8002F5C
// .extern sub_8002F7E
// .extern sub_8002F90
// .extern sub_8002FA6
// .extern sub_8003006
// .extern sub_800302A
// .extern sub_80030BA
// .extern object_spawnType1
// .extern object_spawnType3
// .extern sub_8003374
// .extern object_spawnType4
// .extern sub_80033E4
// .extern object_freeMemory
// .extern sub_800362C
// .extern engine_setScreeneffect
// .extern engine_isScreeneffectAnimating
// .extern dword_80065D0
// .extern dword_8006660
// .extern battle_isPaused
// .extern battle_isTimeStop
// .extern sub_800A152
// .extern battle_isBattleOver
// .extern battle_setFlags
// .extern battle_clearFlags
// .extern battle_getFlags
// .extern sub_800A704
// .extern sub_800A772
// .extern sub_800A8F8
// .extern battle_networkInvert
// .extern sub_800AA92
// .extern sub_800AB3A
// .extern sub_800AB46
// .extern sub_800ABC6
// .extern sub_800AE54
// .extern sub_800AE90
// .extern sub_800AF34
// .extern sub_800B916
// .extern sub_800B94C
// .extern sub_800B97E
// .extern sub_800B9B0
// .extern sub_800BA8A
// .extern sub_800BBA8
// .extern sub_800BC88
// .extern sub_800BCC0
// .extern object_timefreezeEnd
// .extern loc_800BDB2
// .extern sub_800BF16
// .extern sub_800BF5C
// .extern object_getPanelParameters
// .extern sub_800C90A
// .extern object_crackPanel
// .extern object_crackPanelDup1
// .extern object_breakPanel
// .extern object_breakPanel_dup1
// .extern object_breakPanel_dup2
// .extern object_breakPanel_dup3
// .extern object_breakPanelLoud
// .extern object_panel_setPoison
// .extern object_highlightPanel
// .extern object_setPanelType
// .extern object_setPanelAlliance
// .extern object_setPanelAllianceTimerLong
// .extern object_setPanelAllianceTimerShort
// .extern object_setPanelTypeBlink
// .extern object_isCurrentPanelValid
// .extern object_isValidPanel
// .extern object_checkPanelParameters
// .extern object_isCurrentPanelSolid
// .extern object_isPanelSolid
// .extern object_highlightCurrentCollisionPanels
// .extern object_highlightPanelRegion
// .extern object_highlightPanelRegionBlue
// .extern object_hidePanel
// .extern object_getPanelsExceptCurrentFilterred
// .extern sub_800CEA0
// .extern sub_800CF14
// .extern sub_800CF42
// .extern sub_800CF70
// .extern sub_800CFA6
// .extern sub_800CFDC
// .extern sub_800D012
// .extern sub_800D06A
// .extern sub_800D086
// .extern sub_800D0BC
// .extern sub_800D120
// .extern sub_800D3FE
// .extern sub_800D4C2
// .extern sub_800D4D0
// .extern sub_800D58C
// .extern sub_800D5F0
// .extern sub_800D618
// .extern sub_800D668
// .extern sub_800E24C
// .extern sub_800E258
// .extern sub_800E276
// .extern sub_800E29C
// .extern sub_800E2AC
// .extern sub_800E2C0
// .extern sub_800E2C2
// .extern sub_800E2CA
// .extern object_getFlipDirection
// .extern object_subtractHP
// .extern object_addHP
// .extern sub_800E2FC
// .extern sub_800E3BE
// .extern sub_800E456
// .extern object_canMove
// .extern sub_800E5FC
// .extern sub_800E6E8
// .extern sub_800E708
// .extern object_setCounterTime
// .extern sub_800EA22
// .extern sub_800EA90
// .extern sub_800EABA
// .extern sub_800EAC4
// .extern sub_800EADA
// .extern object_setInvulnerableTime
// .extern sub_800EB08
// .extern sub_800EB6C
// .extern object_getEnemyByNameRange
// .extern sub_800EC48
// .extern sub_800ED90
// .extern sub_800F214
// .extern sub_800F23C
// .extern sub_800F26C
// .extern sub_800F29C
// .extern sub_800F2AA
// .extern sub_800F2B6
// .extern sub_800F2C6
// .extern sub_800F2FC
// .extern sub_800F322
// .extern sub_800F46C
// .extern sub_800F486
// .extern sub_800F49E
// .extern sub_800F614
// .extern sub_800F656
// .extern sub_800F672
// .extern sub_800F884
// .extern sub_800F898
// .extern sub_800F8B0
// .extern sub_800F8CE
// .extern sub_800F90E
// .extern sub_800F964
// .extern sub_800F998
// .extern sub_800FA20
// .extern sub_800FA54
// .extern sub_800FAAC
// .extern sub_800FAF6
// .extern sub_800FB54
// .extern sub_800FC30
// .extern sub_800FC7C
// .extern sub_800FC9E
// .extern sub_800FCFC
// .extern sub_800FDB6
// .extern sub_800FE12
// .extern sub_800FE28
// .extern sub_800FE36
// .extern sub_800FE52
// .extern sub_800FFE4
// .extern sub_800FFEE
// .extern sub_800FFFE
// .extern sub_8010004
// .extern sub_8010018
// .extern sub_801002C
// .extern sub_80100EC
// .extern sub_801011A
// .extern sub_80101AE
// .extern sub_80101C4
// .extern sub_80101D4
// .extern sub_8010300
// .extern sub_8010312
// .extern sub_801031C
// .extern sub_801032C
// .extern sub_8010332
// .extern sub_80103A8
// .extern sub_80103BC
// .extern sub_80103F8
// .extern sub_8010474
// .extern sub_8010488
// .extern sub_80104E0
// .extern sub_801050C
// .extern sub_801056A
// .extern sub_80105F2
// .extern sub_8010660
// .extern sub_80106C0
// .extern sub_8010740
// .extern sub_80107C0
// .extern sub_80107D4
// .extern sub_8010820
// .extern sub_8010DD0
// .extern loc_8010DF6
// .extern sub_8011020
// .extern loc_8011044
// .extern sub_8011420
// .extern sub_8011450
// .extern sub_8011504
// .extern sub_801155A
// .extern sub_801156A
// .extern sub_801162A
// .extern sub_801164C
// .extern sub_8011680
// .extern sub_8011684
// .extern sub_8011688
// .extern loc_801168C
// .extern loc_8011690
// .extern sub_80116AE
// .extern sub_80116D8
// .extern sub_8011714
// .extern loc_801171C
// .extern sub_8011764
// .extern sub_801177A
// .extern sub_8011790
// .extern loc_80117A4
// .extern sub_801265A
// .extern sub_80126E4
// .extern sub_8012792
// .extern sub_8012956
// .extern sub_801299C
// .extern sub_8012E74
// .extern sub_8012EA8
// .extern sub_8013682
// .extern sub_80136CC
// .extern sub_8013754
// .extern sub_8013764
// .extern sub_8013774
// .extern sub_80139C4
// .extern sub_8013CC4
// .extern sub_8013DA0
// .extern sub_8013FAE
// .extern sub_80142C2
// .extern sub_801443C
// .extern sub_8014446
// .extern sub_80144C0
// .extern sub_8015AA6
// .extern sub_8015B00
// .extern sub_8015B54
// .extern sub_8015BEC
// .extern sub_8015C48
// .extern sub_8015D80
// .extern sub_8015E46
// .extern sub_8016004
// .extern sub_8016218
// .extern sub_801632C
// .extern sub_8016380
// .extern sub_80165B8
// .extern sub_80165C2
// .extern sub_80166AE
// .extern sub_80169BE
// .extern byte_8016B02
// .extern byte_8016B03
// .extern sub_8016B36
// .extern sub_8016B72
// .extern sub_8016C4E
// .extern sub_8016C8A
// .extern sub_8016C9C
// .extern loc_8016CE8
// .extern sub_8016E64
// .extern sub_8016F56
// .extern sub_80170C4
// .extern sub_80172F0
// .extern sub_80173F4
// .extern sub_80174FE
// .extern sub_80175B8
// .extern sub_8017688
// .extern sub_8017768
// .extern sub_8017888
// .extern loc_80178B6
// .extern sub_8017CC0
// .extern loc_8017E26
// .extern sub_80182B4
// .extern sub_8018810
// .extern sub_8018842
// .extern sub_8019892
// .extern sub_80198CE
// .extern dword_80198E8
// .extern dword_80198E8
// .extern dword_80198E8
// .extern dword_80198E8
// .extern dword_80198E8
// .extern dword_80198E8
// .extern off_8019B78
// .extern dword_8019B84
// .extern dword_8019C34
// .extern sub_8019F86
// .extern sub_8019F8C
// .extern sub_8019FB4
// .extern sub_801A00E
// .extern sub_801A018
// .extern sub_801A04C
// .extern sub_801A066
// .extern sub_801A074
// .extern sub_801A07C
// .extern sub_801A082
// .extern sub_801A0D4
// .extern sub_801A100
// .extern sub_801A140
// .extern sub_801A146
// .extern object_setFlag
// .extern object_clearFlag
// .extern object_getFlag
// .extern sub_801A16C
// .extern sub_801A176
// .extern sub_801A180
// .extern sub_801A258
// .extern sub_801A264
// .extern sub_801A4D0
// .extern sub_801A4DC
// .extern sub_801A66C
// .extern sub_801A67E
// .extern sub_801A7CC
// .extern sub_801A9B8
// .extern sub_801AA48
// .extern sub_801AAC0
// .extern sub_801AB40
// .extern sub_801ABB8
// .extern sub_801AC6C
// .extern sub_801AD12
// .extern sub_801AD6A
// .extern sub_801AD9E
// .extern sub_801ADFA
// .extern sub_801AF44
// .extern sub_801B1C4
// .extern sub_801B394
// .extern sub_801B4D4
// .extern sub_801B610
// .extern loc_801B750
// .extern loc_801B878
// .extern sub_801BB1C
// .extern sub_801BB46
// .extern sub_801BBAC
// .extern sub_801BBF4
// .extern sub_801BC24
// .extern sub_801BC64
// .extern sub_801BCA6
// .extern sub_801BCD0
// .extern sub_801BCF4
// .extern sub_801BD3C
// .extern sub_801BDDE
// .extern sub_801BE04
// .extern nullsub_10
// .extern sub_801BE2A
// .extern sub_801BED6
// .extern sub_801DA48
// .extern sub_801DACC
// .extern sub_801DBD4
// .extern sub_801DC7C
// .extern sub_801DCCC
// .extern sub_801DD34
// .extern sub_801DF8C
// .extern sub_801E658
// .extern sub_801EB18


/* Undeclared Symbols */
.equ timer_2000000, 0x2000000
.equ unk_200150C, 0x200150C
.equ dword_2009380, 0x2009380
.equ dword_2009384, 0x2009384
.equ dword_2009AB0, 0x2009AB0
.equ unk_2010000, 0x2010000
.equ unk_2010108, 0x2010108
.equ unk_2010208, 0x2010208
.equ unk_2010308, 0x2010308
.equ byte_2010408, 0x2010408
.equ unk_2010508, 0x2010508
.equ unk_2010608, 0x2010608
.equ unk_2010708, 0x2010708
.equ unk_2010808, 0x2010808
.equ unk_2010908, 0x2010908
.equ unk_2010A08, 0x2010A08
.equ unk_2010B08, 0x2010B08
.equ unk_202070C, 0x202070C
.equ unk_2030204, 0x2030204
.equ byte_2036740, 0x2036740
.equ byte_203C960, 0x203C960
.equ byte_203C961, 0x203C961
.equ word_203C962, 0x203C962
.equ dword_203C964, 0x203C964
.equ dword_203C968, 0x203C968
.equ dword_203CFB0, 0x203CFB0
.equ dword_203CFB4, 0x203CFB4
.equ dword_203CFB8, 0x203CFB8
.equ dword_203CFBC, 0x203CFBC
.equ dword_203CFC0, 0x203CFC0
.equ dword_203CFC4, 0x203CFC4
.equ unk_3001750, 0x3001750
.equ unk_3001B60, 0x3001B60
.equ unk_3003D0C, 0x3003D0C
.equ LCDControl, 0x4000000
.equ BG2Rotation_ScalingParameterA_dx_, 0x4000020
.equ dword_80205F8, 0x80205F8
.equ dword_8021300, 0x8021300
.equ byte_802136D, 0x802136D
.equ dword_8080AC4, 0x8080AC4
.equ dword_80A0BE0, 0x80A0BE0
.equ dword_810C35C, 0x810C35C
.equ dword_810C35C, 0x810C35C
.equ dword_810C388, 0x810C388
.equ dword_810C388, 0x810C388
.equ dword_810CFE8, 0x810CFE8
.equ dword_810CFE8, 0x810CFE8
.equ dword_810D034, 0x810D034
.equ dword_810D034, 0x810D034
.equ dword_810D198, 0x810D198
.equ dword_810D198, 0x810D198
.equ aTuDhr, 0x8736D74

.endif // INC_ASM31
