.ifndef INC_ASM30
.equ INC_ASM30, 0

/* Public Symbols */
.extern sub_80AED50
.extern battleSettingsList0


/* External Symbols */
.include "asm32.inc"
// .extern dword_810DD3C
// .extern dword_810E414
// .extern dword_810ECAC
// .extern dword_810F22C
// .extern dword_810F510
// .extern dword_81102BC
// .extern unk_8110654
// .extern dword_811115C
// .extern dword_8111938
// .extern dword_8112024
// .extern dword_8112708
// .extern dword_8112BC0
// .extern dword_8113268
// .extern dword_8113780
// .extern dword_81143F4
// .extern dword_81150D8
// .extern dword_8115730
// .extern dword_8115C18

.include "asm31.inc"
// .extern dword_80F28F0
// .extern dword_80F2A54
// .extern dword_80F390C
// .extern dword_80F47D4
// .extern dword_80F5838
// .extern dword_80F6394
// .extern dword_80F757C
// .extern dword_80F8334
// .extern dword_80F8EEC
// .extern dword_80F9C80
// .extern dword_80FACDC
// .extern dword_80FB8E0
// .extern dword_80FD044
// .extern dword_80FDCF0
// .extern dword_80FE7D0
// .extern dword_8109AA4
// .extern dword_8109BFC
// .extern dword_810A2EC
// .extern dword_810A86C
// .extern dword_810AE70
// .extern unk_810B7B8
// .extern dword_810BEF8

.include "asm00.inc"
// .extern sub_80182B4


/* Undeclared Symbols */
.equ dword_810C388, 0x810C388
.equ dword_810C8F8, 0x810C8F8
.equ dword_810D034, 0x810D034
.equ dword_810D198, 0x810D198
.equ dword_810D724, 0x810D724

.endif // INC_ASM30
