.ifndef INC_ASM30
.equ INC_ASM30, 0

/* Public Symbols */
.global sub_80AED50
.global battleSettingsList0


/* External Symbols */
.include "asm32.inc"
// .global dword_810DD3C
// .global dword_810E414
// .global dword_810ECAC
// .global dword_810F22C
// .global dword_810F510
// .global dword_81102BC
// .global unk_8110654
// .global dword_811115C
// .global dword_8111938
// .global dword_8112024
// .global dword_8112708
// .global dword_8112BC0
// .global dword_8113268
// .global dword_8113780
// .global dword_81143F4
// .global dword_81150D8
// .global dword_8115730
// .global dword_8115C18

.include "asm31.inc"
// .global dword_80F28F0
// .global dword_80F2A54
// .global dword_80F390C
// .global dword_80F47D4
// .global dword_80F5838
// .global dword_80F6394
// .global dword_80F757C
// .global dword_80F8334
// .global dword_80F8EEC
// .global dword_80F9C80
// .global dword_80FACDC
// .global dword_80FB8E0
// .global dword_80FD044
// .global dword_80FDCF0
// .global dword_80FE7D0
// .global dword_8109AA4
// .global dword_8109BFC
// .global dword_810A2EC
// .global dword_810A86C
// .global dword_810AE70
// .global unk_810B7B8
// .global dword_810BEF8

.include "asm00.inc"
// .global sub_80182B4


/* Undeclared Symbols */
.equ dword_810C388, 0x810C388
.equ dword_810C8F8, 0x810C8F8
.equ dword_810D034, 0x810D034
.equ dword_810D198, 0x810D198
.equ dword_810D724, 0x810D724

.endif // INC_ASM30
