.ifndef INC_DATA_DAT07
.equ INC_DATA_DAT07, 0

/* Public Symbols */
.global dword_805E01C
.global dword_805E084
.global dword_805E09C
.global dword_805E118
.global dword_805E158
.global off_805E15C
.global off_805E170
.global off_805E184
.global off_805E198
.global off_805E1FC
.global off_8060184
.global unk_806020A
.global off_8060284
.global unk_80602A4
.global unk_80602CC
.global unk_80602FC
.global unk_806032C


/* External Symbols */
.include "asm/asm31.inc"
// .global off_80E0408


/* Undeclared Symbols */
.equ unk_3001A20, 0x3001A20

.endif // INC_DATA_DAT07
