.ifndef INC_DATA_DAT01
.equ INC_DATA_DAT01, 0

/* Public Symbols */
.global byte_8020354
.global byte_80203EA
.global byte_8020404
.global byte_8020600
.global byte_802083F
.global dword_80209CC
.global off_80209EC
.global byte_8020B2C
.global byte_8020B8C
.global dword_8020B9C
.global dword_8020C5C
.global dword_8020CE4
.global dword_8020E54
.global byte_8020FE0
.global byte_80210DD
.global byte_80211A0
.global byte_8021220
.global byte_80212BB
.global dword_80212D4
.global byte_8021300
.global byte_8021369
.global byte_802136A
.global byte_802136B
.global byte_802136C
.global byte_802136D
.global dword_802137C
.global byte_80213AC
.global byte_802158C
.global byte_80215C8
.global byte_8021604
.global byte_8021640
.global byte_802167C
.global byte_80216B8
.global byte_80216F4
.global byte_8021730
.global byte_802176C
.global byte_80217A8
.global byte_80217E4
.global byte_8021820
.global byte_802185C
.global byte_8021898
.global byte_80218D4
.global byte_8021910
.global byte_802194C
.global byte_8021988


/* External Symbols */

.endif // INC_DATA_DAT01
