.ifndef INC_DATA_DAT06
.equ INC_DATA_DAT06, 0

/* Public Symbols */
.global dword_80596F4
.global dword_805975C
.global dword_8059A58
.global dword_8059C00
.global dword_8059D30
.global off_8059D48
.global dword_8059D5C
.global off_8059D70
.global off_8059D84
.global off_8059DE8
.global off_805DD24
.global off_805DE28


/* External Symbols */

/* Undeclared Symbols */
.equ unk_3001AA0, 0x3001AA0

.endif // INC_DATA_DAT06
