.ifndef INC_DATA_DAT03
.equ INC_DATA_DAT03, 0

/* Public Symbols */
.global dword_804CFBC
.global dword_804CFD4
.global dword_804D08C
.global dword_804D090
.global dword_804D094
.global dword_804D098
.global dword_804D09C
.global dword_804D0A0
.global off_804D0A4
.global off_804D0AC
.global off_804D0B4
.global off_804D0BC
.global off_804D0E4
.global byte_804D0FC
.global byte_804D0FE
.global byte_804D100
.global off_804E38C
.global off_804E450
.global off_804E478
.global off_804E4A0
.global dword_804E5D4
.global unk_804E604


/* External Symbols */
.include "data/dat38_41.inc"
// .global dword_850D034


/* Undeclared Symbols */
.equ unk_3000001, 0x3000001
.equ unk_3001A60, 0x3001A60
.equ unk_3001A80, 0x3001A80

.endif // INC_DATA_DAT03
