.ifndef INC_DATA_DAT04
.equ INC_DATA_DAT04, 0

/* Public Symbols */
.global dword_804E74C
.global dword_804E87C
.global dword_804E8D0
.global dword_804E8D4
.global dword_804E8D8
.global off_804E92C
.global dword_804E940
.global off_804E954
.global off_804E968
.global off_804E9CC
.global byte_804EA08
.global byte_804EA0D
.global byte_804EA12
.global byte_804EA1C
.global unk_8050202
.global off_8052244
.global off_8052480
.global off_80524C0
.global byte_80524E8
.global byte_8052510
.global unk_8052538
.global dword_80525C0
.global dword_80525DC


/* External Symbols */

/* Undeclared Symbols */
.equ word_3001960, 0x3001960
.equ unk_3001AA0, 0x3001AA0

.endif // INC_DATA_DAT04
