.ifndef INC_DATA_DAT01
.equ INC_DATA_DAT01, 0

/* Public Symbols */
.global dword_8020354
.global dword_8020404
.global dword_80209CC
.global off_80209EC
.global dword_8020B2C
.global dword_8020B8C
.global dword_8020B9C
.global dword_8020C5C
.global dword_8020CE4
.global dword_8020E54
.global dword_8020FE0
.global dword_8021220
.global dword_80212D4
.global dword_8021300
.global byte_8021369
.global byte_802136A
.global byte_802136B
.global byte_802136C
.global byte_802136D
.global dword_802137C
.global dword_80213AC


/* External Symbols */

/* Undeclared Symbols */
.equ timer_2000000, 0x2000000

.endif // INC_DATA_DAT01
