.ifndef INC_DATA_DAT09
.equ INC_DATA_DAT09, 0

/* Public Symbols */
.global dword_8062BFC
.global dword_8062DA4
.global dword_8062DE4
.global dword_8062E88
.global dword_8062EB4
.global dword_8062F1C
.global off_8062F48
.global off_8062F60
.global off_8062F78
.global off_8062F90
.global off_8063008
.global unk_8063050
.global byte_8063056
.global off_8066020
.global off_8066048
.global unk_80662B8
.global unk_80662E8
.global unk_8066328
.global unk_8066368
.global unk_80663A8


/* External Symbols */
.include "data/dat38_42.inc"
// .global dword_8610F08


.endif // INC_DATA_DAT09
