.ifndef INC_DATA_DAT05
.equ INC_DATA_DAT05, 0

/* Public Symbols */
.global dword_8052834
.global dword_80529B4
.global dword_8052A6C
.global dword_8052B24
.global dword_8052BDC
.global dword_8052BE0
.global dword_8052BE4
.global dword_8052C10
.global dword_8052D54
.global dword_8052D80
.global dword_8052D84
.global off_8052D88
.global dword_8052DB4
.global off_8052DE0
.global off_8052E0C
.global off_8052EE8
.global byte_8052F6C
.global byte_8052F77
.global byte_8052F82
.global off_8059294
.global off_8059378
.global byte_80593B8
.global byte_80593F8
.global byte_8059438
.global byte_8059468
.global byte_80594A8
.global byte_80594E8
.global byte_8059528
.global byte_8059558
.global byte_8059588


/* External Symbols */
.include "asm/asm28_1.inc"
// .global byte_809F6CC


/* Undeclared Symbols */
.equ unk_3001A80, 0x3001A80

.endif // INC_DATA_DAT05
