.ifndef INC_DATA_DAT00
.equ INC_DATA_DAT00, 0

/* Public Symbols */
.global off_801ECB4
.global word_801ED6C
.global word_801EDB4
.global dword_801EDFC
.global word_801EE14
.global word_801EE58
.global dword_801EE78
.global dword_801EE98
.global dword_801EF10
.global off_801EF30
.global off_801EF4C
.global off_801EF68
.global pt_801EF84
.global pt_801EFD4
.global word_801F374
.global byte_801F376
.global word_801F554
.global byte_801F556
.global off_801FD64
.global off_801FD90
.global dword_801FDC0


/* External Symbols */
.include "data/dat38_2.inc"
// .global dword_86B7AC0

.include "data/dat38_25.inc"
// .global dword_86E1938
// .global dword_86E1978
// .global dword_86E19B8
// .global dword_86E19F8
// .global dword_86E1A38
// .global dword_86E1A78
// .global dword_86E1AB8
// .global dword_86E1AF8
// .global dword_86E1B38
// .global dword_86E1B78
// .global dword_86E1BF8
// .global dword_86F1340
// .global dword_86F1380
// .global dword_86F1440
// .global dword_86F1600
// .global dword_86F1780
// .global dword_86F17C0
// .global dword_86F1800
// .global dword_86F19C0
// .global dword_86F1A00
// .global dword_86F1A40
// .global dword_86F1A80
// .global dword_86F1DC0
// .global dword_86F1E00
// .global dword_86F1E40
// .global dword_86F1E80
// .global dword_86F1EC0
// .global dword_86F1F00
// .global dword_86F1F40
// .global dword_86F1F80
// .global dword_86F1FC0
// .global dword_86F2000
// .global dword_86F2040
// .global dword_86F2240
// .global dword_86F26C0


/* Undeclared Symbols */
.equ unk_3001710, 0x3001710

.endif // INC_DATA_DAT00
