.ifndef INC_DATA_DAT08
.equ INC_DATA_DAT08, 0

/* Public Symbols */
.global dword_8060474
.global dword_80604A0
.global dword_80605E4
.global dword_80605E8
.global off_806063C
.global off_806064C
.global off_806065C
.global off_806066C
.global off_80606BC
.global unk_80606EC
.global byte_80606F0
.global byte_80606F4
.global byte_8060C02
.global unk_8061416
.global unk_8061622
.global off_8062728
.global unk_8062860
.global unk_80628A0
.global unk_80628E0
.global unk_8062908
.global unk_8062958
.global unk_80629C0
.global unk_80629F0
.global unk_8062A30
.global unk_8062A70


/* External Symbols */

.endif // INC_DATA_DAT08
