.ifndef INC_DATA_DAT10
.equ INC_DATA_DAT10, 0

/* Public Symbols */
.global dword_8067DF8
.global dword_8067E08
.global unk_8067E18
.global byte_8067E28
.global unk_8067E2C
.global unk_8067E8D
.global dword_8067F24
.global unk_8067F4F
.global dword_8067F74
.global unk_8067FDF
.global off_8068044
.global off_8068400
.global off_8068734
.global off_8068CCC
.global off_8068D18
.global dword_8068E48
.global off_8068E88
.global off_8068ED0
.global off_8068EF0
.global off_8068F30
.global dword_8068FA0
.global off_8069010


/* External Symbols */
.include "asm/asm00_2.inc"
// .global loc_801083E

.include "data/dat20.inc"
// .global unk_8080684
// .global unk_8080685
// .global unk_8080686
// .global unk_8080687
// .global unk_8080689
// .global unk_808068A
// .global unk_808068B

.include "data/dat21.inc"
// .global unk_8083C05
// .global unk_80865AC

.include "asm/asm28_1.inc"
// .global unk_809F6CC

.include "data/dat38_14.inc"
// .global unk_83C0510
// .global unk_83F010F
// .global unk_83F0208
// .global unk_83F0408
// .global unk_83F0708
// .global unk_83F0716
// .global unk_83F1916
// .global unk_83F2C16

.include "data/dat38_18.inc"
// .global unk_8451508

.include "data/dat38_42.inc"
// .global unk_85AB89C
// .global unk_85AB8BC
// .global unk_85AB8DC
// .global unk_85AB900
// .global unk_85AB920
// .global unk_85AB940
// .global unk_85AB960
// .global unk_85AB984
// .global unk_85AB9A4
// .global unk_85AB9C4
// .global unk_85AB9E4
// .global unk_85ABA04
// .global unk_85ABA24
// .global unk_85ABA44
// .global unk_85ABA68
// .global unk_85ABA88
// .global unk_85ABAAC
// .global unk_85ABACC
// .global unk_85ABAEC
// .global unk_85ABB0C
// .global unk_85ABB30
// .global unk_85ABB50
// .global unk_85ABB70
// .global unk_85ABB90
// .global unk_85ABBB0
// .global unk_85ABBD0
// .global unk_85ABBF0
// .global unk_85ABC10
// .global unk_85ABC30
// .global unk_85ABC50
// .global unk_85ABC70
// .global unk_85ABC90
// .global unk_85ABCB4
// .global unk_85ABCD4
// .global unk_85ABCF4
// .global unk_85ABD14
// .global unk_85ABD34
// .global unk_85ABD54
// .global unk_85ABD74
// .global unk_85ABD94
// .global unk_85ABDB4
// .global unk_85ABDD4
// .global unk_85ABDF4
// .global unk_85ABE14
// .global unk_85CD026
// .global dword_8613028

.include "data/dat38_68.inc"
// .global unk_86DF925


/* Undeclared Symbols */
.equ unk_3001A20, 0x3001A20
.equ unk_3001A60, 0x3001A60
.equ unk_3001A80, 0x3001A80
.equ unk_3001AA0, 0x3001AA0
.equ unk_3001AC0, 0x3001AC0

.endif // INC_DATA_DAT10
