.ifndef INC_DATA_DAT10
.equ INC_DATA_DAT10, 0

/* Public Symbols */
.global dword_8067DF8
.global dword_8067E08
.global byte_8067E18
.global byte_8067E28
.global byte_8067E2C
.global byte_8067E8D
.global dword_8067F24
.global unk_8067F4F
.global dword_8067F74
.global unk_8067FDF
.global off_8068044
.global off_8068400
.global off_8068734
.global off_8068CCC
.global off_8068D18
.global dword_8068E48
.global off_8068E88
.global off_8068ED0
.global off_8068EF0
.global off_8068F30
.global dword_8068FA0
.global off_8069010


/* External Symbols */
.include "asm/asm00_2.inc"
// .global loc_801083E

.include "data/dat20.inc"
// .global byte_8080684
// .global byte_8080685
// .global byte_8080686
// .global byte_8080687
// .global byte_8080689
// .global byte_808068A
// .global byte_808068B

.include "data/dat21.inc"
// .global byte_8083C05
// .global unk_80865AC

.include "asm/asm28_1.inc"
// .global byte_809F6CC

.include "data/dat38_33.inc"
// .global byte_83F010F
// .global byte_83F0208
// .global byte_83F0408
// .global byte_83F0708
// .global byte_83F0716
// .global byte_83F1916
// .global byte_83F2C16

.include "data/dat38_37.inc"
// .global byte_8451508

.include "data/dat38_60.inc"
// .global byte_85AB89C
// .global byte_85AB8BC
// .global byte_85AB8DC
// .global byte_85AB900
// .global byte_85AB920
// .global byte_85AB940
// .global byte_85AB960
// .global byte_85AB984
// .global byte_85AB9A4
// .global byte_85AB9C4
// .global byte_85AB9E4
// .global byte_85ABA04
// .global byte_85ABA24
// .global byte_85ABA44
// .global byte_85ABA68
// .global byte_85ABA88
// .global byte_85ABAAC
// .global byte_85ABACC
// .global byte_85ABAEC
// .global byte_85ABB0C
// .global byte_85ABB30
// .global byte_85ABB50
// .global byte_85ABB70
// .global byte_85ABB90
// .global byte_85ABBB0
// .global byte_85ABBD0
// .global byte_85ABBF0
// .global byte_85ABC10
// .global byte_85ABC30
// .global byte_85ABC50
// .global byte_85ABC70
// .global byte_85ABC90
// .global byte_85ABCB4
// .global byte_85ABCD4
// .global byte_85ABCF4
// .global byte_85ABD14
// .global byte_85ABD34
// .global byte_85ABD54
// .global byte_85ABD74
// .global byte_85ABD94
// .global byte_85ABDB4
// .global byte_85ABDD4
// .global byte_85ABDF4
// .global byte_85ABE14
// .global unk_85CD026
// .global dword_8613028

.include "data/dat38_85.inc"
// .global byte_86DF925


/* Undeclared Symbols */
.equ unk_3001A20, 0x3001A20
.equ unk_3001A60, 0x3001A60
.equ unk_3001A80, 0x3001A80
.equ unk_3001AA0, 0x3001AA0
.equ unk_3001AC0, 0x3001AC0

.endif // INC_DATA_DAT10
