.ifndef INC_DATA_DAT10
.equ INC_DATA_DAT10, 0

/* Public Symbols */
.global dword_8067DF8
.global dword_8067E08
.global dword_8067E18
.global dword_8067E2C
.global dword_8067F24
.global dword_8067F74
.global off_8068044
.global off_8068400
.global off_8068734
.global off_8068CCC
.global off_8068D18


/* External Symbols */
.include "data/dat38_2.inc"
// .global dword_8613028


.endif // INC_DATA_DAT10
