.ifndef INC_DATA_DAT13
.equ INC_DATA_DAT13, 0

/* Public Symbols */
.global byte_8070034
.global dword_8070074
.global dword_80700B4
.global dword_80700CC
.global dword_80700E4
.global byte_80700FC
.global byte_8070102
.global dword_8070114
.global dword_807012C
.global dword_8070144
.global dword_8070184
.global dword_807019C
.global dword_80701B4
.global dword_80701CC
.global dword_80701E4
.global byte_80701FC
.global byte_8070202
.global dword_8070214
.global off_807022C
.global dword_807026C
.global off_80702AC
.global off_80702EC
.global byte_807042C
.global byte_8070605
.global byte_807083F
.global byte_8070A02
.global byte_8071503
.global byte_807150F
.global off_8071584


/* External Symbols */
.include "asm/asm03_0.inc"
// .global sub_8030808


/* Undeclared Symbols */
.equ unk_3000190, 0x3000190

.endif // INC_DATA_DAT13
