.ifndef INC_DATA_DAT11
.equ INC_DATA_DAT11, 0

/* Public Symbols */
.global dword_806C5D0
.global dword_806C638
.global dword_806C68C
.global dword_806C6E0
.global dword_806C748
.global off_806C7B0
.global off_806C7CC
.global off_806C7E8
.global off_806C804
.global byte_806C870
.global off_806D6B0
.global byte_806D820


/* External Symbols */
.include "asm/asm03_0.inc"
// .global sub_8030808
// .global loc_80315CC

.include "data/dat13.inc"
// .global byte_807083F

.include "data/dat20.inc"
// .global byte_80809F6

.include "data/dat21.inc"
// .global byte_8083F04

.include "asm/asm28_1.inc"
// .global byte_809F6CC
// .global byte_809F889
// .global byte_809F8B3
// .global byte_809F8CA

.include "data/dat38_33.inc"
// .global unk_83C0116
// .global unk_83C09C0
// .global unk_83C1A16
// .global unk_83F0016
// .global unk_83F0116
// .global unk_83F0208
// .global unk_83F0608
// .global unk_83F0907
// .global unk_83F0E08
// .global unk_83F1916
// .global unk_83F3D16

.include "data/dat38_60.inc"
// .global unk_863FF05


.endif // INC_DATA_DAT11
