.ifndef INC_DATA_DAT18
.equ INC_DATA_DAT18, 0

/* Public Symbols */
.global dword_807AAFC
.global dword_807AC18
.global dword_807ACA8
.global off_807ADEC
.global dword_807ADF8
.global off_807AE04
.global off_807AE10
.global off_807C82C
.global off_807C94C
.global off_807C974


/* External Symbols */
.include "asm/asm28_1.inc"
// .global dword_809F6CC


/* Undeclared Symbols */
.equ unk_8605FD8, 0x8605FD8
.equ dword_86190F4, 0x86190F4

.endif // INC_DATA_DAT18
