.ifndef INC_DATA_DAT15
.equ INC_DATA_DAT15, 0

/* Public Symbols */
.global dword_8075614
.global dword_8075708
.global dword_807575C
.global off_80758A0
.global off_80758AC
.global off_80758B8
.global off_80758C4
.global byte_8075900
.global byte_8075903
.global off_8077618
.global off_8077720


/* External Symbols */
.include "asm/asm03_0.inc"
// .global loc_8030308

.include "data/dat38_60.inc"
// .global dword_8617488


.endif // INC_DATA_DAT15
