.ifndef INC_DATA_DAT27
.equ INC_DATA_DAT27, 0

/* Public Symbols */
.global dword_80984C8
.global dword_8098824
.global dword_80988E4
.global dword_809895C
.global dword_8098A78
.global dword_8098B1C


/* External Symbols */
.include "asm/asm00_1.inc"
// .global off_8008000


/* Undeclared Symbols */
.equ LCDControl, 0x4000000
.equ unk_400020C, 0x400020C
.equ dword_8FF0000, 0x8FF0000

.endif // INC_DATA_DAT27
