.ifndef INC_DATA_DAT20
.equ INC_DATA_DAT20, 0

/* Public Symbols */
.global dword_807EEB8
.global dword_807EFD4
.global dword_807F1E0
.global dword_807F1F8
.global dword_807F204
.global dword_807F210
.global off_807F21C
.global off_807FAC0
.global unk_8080598
.global unk_80805C0
.global unk_8080684
.global unk_8080685
.global unk_8080686
.global unk_8080687
.global unk_8080689
.global unk_808068A
.global unk_808068B
.global unk_80806B3
.global unk_8080808
.global unk_80808B0
.global unk_80808D8
.global unk_80809F6
.global unk_8080AA0


/* External Symbols */
.include "data/dat38_42.inc"
// .global dword_8616904


.endif // INC_DATA_DAT20
