.ifndef INC_DATA_DAT27
.equ INC_DATA_DAT27, 0

/* Public Symbols */
.global unk_8095434
.global unk_8095CD8
.global unk_8097A48
.global unk_8098358
.global unk_8098384
.global dword_80984C8
.global dword_8098824
.global dword_80988E4
.global dword_809895C
.global unk_8098A02
.global unk_8098A2E
.global dword_8098A78
.global dword_8098B1C
.global unk_8098BB8


/* External Symbols */
.include "asm/asm00_1.inc"
// .global off_8008000


/* Undeclared Symbols */
.equ LCDControl, 0x4000000
.equ unk_400020C, 0x400020C
.equ dword_8FF0000, 0x8FF0000

.endif // INC_DATA_DAT27
