.ifndef INC_DATA_DAT20
.equ INC_DATA_DAT20, 0

/* Public Symbols */
.global dword_807EEB8
.global dword_807EFD4
.global dword_807F1E0
.global dword_807F1F8
.global dword_807F204
.global dword_807F210
.global off_807F21C
.global byte_807F268
.global off_807FAC0
.global byte_807FB98
.global byte_807FE88
.global byte_8080115
.global byte_8080315
.global byte_8080501
.global byte_808054A
.global byte_808054F
.global byte_808058D
.global byte_8080598
.global byte_80805C0
.global byte_808060A
.global byte_8080684
.global byte_8080685
.global byte_8080686
.global byte_8080687
.global byte_8080689
.global byte_808068A
.global byte_808068B
.global byte_80806B3
.global unk_8080715
.global byte_80808B0
.global byte_80808D8
.global byte_80809F6
.global byte_80809F8
.global byte_8080A06
.global byte_8080AA0


/* External Symbols */
.include "data/dat38_60.inc"
// .global dword_8616904


.endif // INC_DATA_DAT20
