.ifndef INC_DATA_DAT21
.equ INC_DATA_DAT21, 0

/* Public Symbols */
.global dword_80813F8
.global dword_80813FC
.global dword_8081400
.global dword_8081404
.global dword_8081408
.global dword_8081410
.global dword_8081418
.global dword_8081428
.global dword_8081438
.global dword_808143C
.global dword_8081440
.global dword_8081444
.global dword_8081448
.global dword_808144C
.global dword_8081450
.global unk_8083C05
.global unk_8083C09
.global unk_8083F04
.global unk_8083F07
.global unk_80865AC
.global dword_8086D5C
.global unk_8086D74


/* External Symbols */
.include "data/dat37.inc"
// .global dword_81D4314


/* Undeclared Symbols */
.equ unk_2010800, 0x2010800
.equ unk_3001750, 0x3001750
.equ unk_3001B60, 0x3001B60

.endif // INC_DATA_DAT21
