.ifndef INC_DATA_DAT38_82
.equ INC_DATA_DAT38_82, 0

/* Public Symbols */
.global unk_87F40F4
.global unk_87F4194


/* External Symbols */
.include "data/dat37.inc"
// .global unk_81A081B
// .global unk_81D081E

.include "data/dat38_10.inc"
// .global unk_8320833

.include "data/dat38_13.inc"
// .global unk_8370817

.include "data/dat38_26.inc"
// .global dword_84B07F8

.include "data/dat38_34.inc"
// .global dword_84C0C24

.include "data/dat38_41.inc"
// .global unk_84F0C30


/* Undeclared Symbols */
// .global comp_82E0114
// .global comp_84D014C

.endif // INC_DATA_DAT38_82
