.ifndef INC_DATA_DAT38_14
.equ INC_DATA_DAT38_14, 0

/* Public Symbols */
.global byte_838B930
.global byte_838C3C8
.global byte_838C864
.global byte_838E194
.global byte_838E74C
.global byte_838EC00
.global dword_83908A4
.global byte_8390F44
.global byte_8390FC4
.global byte_8391E40
.global byte_839247C
.global byte_83930E0
.global byte_8395034
.global dword_8395660
.global byte_8396650
.global byte_83971C0
.global byte_8398048
.global byte_8399578
.global byte_839AAB8
.global off_839B9C0
.global byte_839CCDC
.global byte_83A000C
.global byte_83A0DA8
.global byte_83A5E30
.global byte_83A67AC
.global byte_83A9190
.global byte_83AC1A8
.global byte_83AC430
.global byte_83ACF48
.global byte_83AD870
.global byte_83AE2B4
.global byte_83AF658
.global byte_83B00F8
.global byte_83B0A90
.global byte_83B2494
.global byte_83B3BF4
.global byte_83B440C
.global byte_83B4AE4
.global byte_83B5F44
.global byte_83B92B4
.global byte_83BA940
.global byte_83BB440
.global byte_83BC3B0
.global byte_83BCC70
.global byte_83BD228
.global byte_83BE6B0
.global byte_83BFD0C
.global byte_83C0116
.global byte_83C0510
.global byte_83C0716
.global byte_83C0806
.global byte_83C09C0
.global unk_83C0A10
.global unk_83C1916
.global unk_83C1A16
.global unk_83CC02A
.global byte_83CD574
.global byte_83CFF28
.global byte_83D0426
.global unk_83D0801
.global byte_83D346C
.global byte_83D604C
.global byte_83D91C0
.global byte_83DC525
.global byte_83DD0A8
.global unk_83DF125
.global byte_83E0108
.global byte_83E1EEC
.global byte_83E2B48
.global byte_83E55F8
.global byte_83E7F4C
.global dword_83EB980
.global byte_83EEF14
.global byte_83F0000
.global byte_83F000F
.global byte_83F0016
.global byte_83F010F
.global unk_83F0116
.global byte_83F0208
.global unk_83F020F
.global unk_83F0308
.global byte_83F0408
.global unk_83F0416
.global byte_83F0508
.global byte_83F0516
.global unk_83F0608
.global byte_83F0708
.global unk_83F0716
.global byte_83F0907
.global dword_83F0908
.global unk_83F0E08
.global unk_83F1408
.global unk_83F1916
.global unk_83F1B16
.global unk_83F1D16
.global byte_83F2916
.global byte_83F2C16
.global byte_83F37C4
.global byte_83F3D16
.global unk_83F3F16
.global byte_83F6824
.global unk_83F8108
.global byte_83FA130


/* External Symbols */
.include "asm/start.inc"
// .global start_

.include "data/dat38_17.inc"
// .global byte_8420000


/* Undeclared Symbols */
.equ timer_2000000, 0x2000000
.equ unk_2010010, 0x2010010
.equ unk_3000000, 0x3000000
.equ LCDControl, 0x4000000
.equ dword_8800000, 0x8800000
.equ dword_8900000, 0x8900000

.endif // INC_DATA_DAT38_14
