.ifndef INC_DATA_DAT38_84
.equ INC_DATA_DAT38_84, 0

/* Public Symbols */
.global byte_87F8EB0
.global byte_87F93B4
.global byte_87F93D4
.global byte_87F93F4
.global byte_87F9414
.global byte_87F9434
.global byte_87F9454
.global byte_87F9474
.global byte_87F9494
.global byte_87F94B4
.global byte_87F94D4
.global byte_87F94F4
.global byte_87F9514
.global byte_87F9534
.global byte_87F9554
.global byte_87F9574
.global byte_87F9594
.global byte_87F95B4
.global byte_87F95D4
.global byte_87F95F4
.global byte_87F9614
.global byte_87F96D4
.global byte_87F96F4
.global byte_87F9714
.global byte_87F9734
.global byte_87F9754
.global byte_87F9774
.global byte_87F9794
.global byte_87F97B4
.global byte_87F97D4
.global byte_87F97F4
.global dword_87FF8A0


/* External Symbols */

.endif // INC_DATA_DAT38_84
