.ifndef INC_DATA_DAT38_32
.equ INC_DATA_DAT38_32, 0

/* Public Symbols */
.global dword_87E74F4
.global dword_87E7514
.global dword_87E7534
.global dword_87E7554
.global dword_87E7574
.global dword_87E76B8
.global dword_87E771C
.global dword_87E7780
.global dword_87E77E4
.global dword_87E7848
.global dword_87EE1AC
.global dword_87EE2F0
.global dword_87EE5B0
.global dword_87EF5A4
.global dword_87EFBA4
.global reqBBS_textualShades
.global unk_87EFE14


/* External Symbols */

.endif // INC_DATA_DAT38_32
