.ifndef INC_DATA_DAT38_31
.equ INC_DATA_DAT38_31, 0

/* Public Symbols */
.global sprite_8338F18
.global sprite_833BE68
.global sprite_833F3A0
.global byte_8340031
.global byte_8340901
.global sprite_8342AC4
.global sprite_8345C50
.global sprite_8348E80
.global sprite_83497CC
.global sprite_834A108
.global sprite_834A580
.global sprite_834AE94
.global sprite_834B2D0
.global sprite_834B6A4
.global sprite_834BBF0
.global sprite_834BEB8
.global sprite_834C6F0


/* External Symbols */

.endif // INC_DATA_DAT38_31
