.ifndef INC_DATA_DAT38_37
.equ INC_DATA_DAT38_37, 0

/* Public Symbols */
.global npcSpriteProtoMan
.global npcSpriteProgman
.global npcSpriteGreenNavi
.global npcSpriteEvilNavi
.global unk_8451508
.global npcSpriteGirlNavi
.global npcSpriteSpoutMan
.global npcSpriteHawkMan
.global unk_8468940
.global npcSpriteDrillMan
.global unk_8477574
.global unk_8481548
.global unk_848334C
.global npcSpriteColonel
.global unk_848FCEC


/* External Symbols */

.endif // INC_DATA_DAT38_37
