.ifndef INC_DATA_DAT38_12
.equ INC_DATA_DAT38_12, 0

/* Public Symbols */
.global byte_8338F18
.global byte_833BE68
.global dword_833F3A0
.global byte_8342AC4
.global byte_8345C50
.global byte_834C6F0


/* External Symbols */
.include "asm/start.inc"
// .global start_

.include "data/dat20.inc"
// .global dword_807FAC4

.include "data/dat22.inc"
// .global dword_8087F90

.include "data/dat38_70.inc"
// .global dword_8778780
// .global unk_8787680
// .global dword_8787800


/* Undeclared Symbols */
.equ unk_3000000, 0x3000000
.equ dword_8800000, 0x8800000
.equ dword_8808800, 0x8808800
.equ dword_8886668, 0x8886668
.equ dword_888BB00, 0x888BB00

.endif // INC_DATA_DAT38_12
