.ifndef INC_ASM_ASM15
.equ INC_ASM_ASM15, 0

/* Public Symbols */


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global sub_80019D0
// .global locret_8001AB4
// .global sub_8002354

.include "asm/sprite.inc"
// .global sub_80028D4
// .global sub_8002906

.include "asm/asm00_1.inc"
// .global sub_8003570

.include "asm/asm03_0.inc"
// .global sub_802FF4C
// .global sub_803037C
// .global loc_8030472
// .global sub_80304E8
// .global sub_8030AA4

.include "asm/asm03_1.inc"
// .global sub_8034FB8

.include "asm/chatbox.inc"
// .global chatbox_uncomp_803FD08 // () -> int

.include "data/dat14.inc"
// .global off_8074F30
// .global dword_8074FCC
// .global dword_8074FCC
// .global dword_8074FCC
// .global dword_8074FCC
// .global dword_8074FCC
// .global dword_8074FCC
// .global dword_8074FCC

.include "data/dat15.inc"
// .global dword_8075614
// .global dword_8075708
// .global dword_807575C

.include "data/dat38_42.inc"
// .global off_8617068


/* Undeclared Symbols */
.equ unk_2037800, 0x2037800

.endif // INC_ASM_ASM15
