.ifndef INC_ASM_ASM21
.equ INC_ASM_ASM21, 0

/* Public Symbols */
.global sub_8080D90
.global sub_8080DA0


/* External Symbols */
.include "asm/asm00_0.inc"
// .global sub_80008B4
// .global sub_8001778
// .global sub_8001780
// .global sub_800195C
// .global locret_80019B0
// .global loc_80019B4
// .global loc_80019EC
// .global loc_8001A10
// .global loc_8001A34
// .global loc_8001A58
// .global locret_8001AB4
// .global sub_8002354

.include "asm/asm03_0.inc"
// .global sub_802D234
// .global isActiveFlag_2001C88_bitfield // (u16 entryFlagBitfield) -> zf
// .global sub_80304E8
// .global sub_803537C
// .global sub_8035424

.include "asm/asm11.inc"
// .global dword_806992C
// .global dword_806992C
// .global off_806A810
// .global dword_806C1E0

.include "data/dat19.inc"
// .global off_807EB18

.include "data/dat20.inc"
// .global dword_807F604
// .global dword_807F868
// .global off_807FAC0
// .global dword_807FAC4
// .global dword_807FAC4
// .global dword_807FAC4
// .global dword_807FAC4
// .global dword_80802C4
// .global dword_80802C4
// .global dword_80802C4
// .global dword_80802C4
// .global dword_80802C4

.include "data/dat21.inc"
// .global dword_80813F8
// .global dword_80813FC
// .global dword_8081400
// .global dword_8081404
// .global dword_8081408
// .global dword_8081410
// .global dword_8081418
// .global dword_8081428
// .global dword_8081438
// .global dword_808143C
// .global dword_8081440
// .global dword_8081444
// .global dword_8081448
// .global dword_808144C
// .global dword_8081450


/* Undeclared Symbols */
.equ dword_2009690, 0x2009690
.equ off_8610B04, 0x8610B04
.equ off_86116C8, 0x86116C8
.equ dword_8612CF0, 0x8612CF0
.equ dword_8613AAC, 0x8613AAC
.equ dword_8614A0C, 0x8614A0C
.equ off_8614DE0, 0x8614DE0
.equ dword_86154A8, 0x86154A8
.equ off_861578C, 0x861578C
.equ off_8615BA4, 0x8615BA4
.equ dword_8616264, 0x8616264
.equ off_8616598, 0x8616598
.equ dword_8617190, 0x8617190
.equ dword_8618DFC, 0x8618DFC
.equ off_8619174, 0x8619174
.equ dword_8619474, 0x8619474

.endif // INC_ASM_ASM21
